### ISSUE TITLE
Feature: Add hover tooltip to reactions on highlights

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/app#1092]
### Type of feature

🍕 Feature

### Current behavior

When a user hover's on a highlight reaction, it shows no information about users that reacted

<img width="694" alt="image" src="https://user-images.githubusercontent.com/62995161/231591410-6b9bc538-e685-45f8-9fa7-702e9a8bb8e6.png">

### Suggested solution

Let's add a tooltip similar to GitHub's for reactions with the name of the first user and a `+${restUsers.length}`

<img width="457" alt="image" src="https://user-images.githubusercontent.com/62995161/231591818-61587df6-a957-4a7e-b8a0-dc46183695d9.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by OgDev-01** [comment]
@brandonroberts @0-vortex This might need API updates... The users that reacted should be included in the highlights reaction response object.

**Comment by brandonroberts** [comment]
Yep, this will need to be added

**Comment by OgDev-01** [comment]
Opened a ticket for it in the backend 👍 https://github.com/open-sauced/ops-backend/issues/48

**Comment by 0-vortex** [comment]
under no circumstances. stop trying to do what github can’t, it should be a first red flag something is not possible at scale.
this is not the only thing happening on hover that can’t/won’t scale …

**Comment by a0m0rajab** [comment]
There might a way to do this, we can have something like what facebook and twitter is doing: 

Twitter example: 
they have a button for reactions and when you click it, it opens the information about reactions:
![image](https://github.com/open-sauced/insights/assets/18273833/33d377b9-8e60-47c1-a6ff-3ffbadfbcf53)

![image](https://github.com/open-sauced/insights/assets/18273833/3ed50ef1-9dd9-4ada-8d38-9392944faeab)


Instagram has something similar: 
when you click on likes it show a new tab for that: 
![image](https://github.com/open-sauced/insights/assets/18273833/bfe8cc58-ca3d-44e0-a60b-295a67c0a7fc)

Facebook is showing up to 20 on hover: 
![image](https://github.com/open-sauced/insights/assets/18273833/256b524c-2a69-49d5-8147-b47c7860a8db)


GitHub is showing 3-4 people on hover, 
I think we can allow the user to click the text that we show on hover to open the full reaction list. 

something like: ogdev-01 and others reacted with thumb, see full list
Or even add a place like twitter saying: {count} reactions 
where it would be clickable and have a tab showing reactions.

**Comment by diivi** [comment]
@brandonroberts was this done in the backend or should I work on that first?
