### ISSUE TITLE
Feature: add number of open prs to non-backfilled insight repos creation flow

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/app#1138]
### Type of feature

🍕 Feature

### Current behavior

In the insight page creation process, trying to add a repo we have not backfilled will return the information from GitHub REST API 

As reported by @getaheaddev

![Issue - Forks](https://user-images.githubusercontent.com/237133/235892232-a79bd0ed-39b6-4c6f-b741-92b1a929125b.png)

### Suggested solution

Switch from GitHub REST to GraphQL and attach open pull requests information to the repos

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
This is being handled in the API by an initial backfill on demand
