### ISSUE TITLE
Feature: Ability to create highlights using query params

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#1143]
### Type of feature

🍕 Feature

### Current behavior

We have a new feature in the extension to create a highlight from the extension while on GitHub. It uses query params to pass context, but no way to receive that data. 

https://github.com/open-sauced/browser-extensions/pull/64

### Suggested solution

1. Add the ability to use query params to create a highlight

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by diivi** [comment]
Already kind of implemented with #1079. We just need to accept other query params as needed.

**Comment by a0m0rajab** [comment]
Hi @bdougie and @brandonroberts, is not this issue resolved with this url: `https://app.opensauced.pizza/feed?new=true`? 
This is related to this issue: https://github.com/open-sauced/ai/issues/256
