### ISSUE TITLE
Bug: unable to edit date on editing a highlight (Safari Only)

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/app#1144]
### Describe the bug

https://user-images.githubusercontent.com/237133/236319313-b8c3746d-077d-471c-9ca4-5be5068ec2b1.mov

### Steps to reproduce

1. Add a new highlight without date
1. Edit highlight and try to set date

### Affected services

insights.opensauced.pizza

### Environment

Production, Development, Testing

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
@OgDev-01 Knowing you have worked on implementing the date picker, do you happen to know if this bug is a duplicate of any existing issue? 😅

**Comment by OgDev-01** [comment]
So I tried to replicate this issue from my end...
https://www.loom.com/share/2f39f0bd7d15456ea64f3bbc0898c4c9

It works as expected on other browsers except Safari... I'll look into this for a possible fix 👍

**Comment by diivi** [comment]
I'm on ubuntu and almost all alternatives I tried to safari ended up being either too old or ruining other elements of the website too:
![image](https://github.com/open-sauced/insights/assets/41837037/4f3723f2-e731-4ce2-a02d-230c2dcd5f49)

If someone knows how to run safari on Linux, I can work on this.

**Comment by 0-vortex** [comment]
> If someone knows how to run safari on Linux, I can work on this.

Most online tutorials will use wine to install safari version 5 (2010) on linux - in my humble opinion, that is a waste of time and would not recommend trying 🍕

**Comment by RitaDee** [comment]
.take

**Comment by nickytonline** [comment]
I did a quick test in Safari and if you click quickly multiple times, you'll see it open very briefly and close. I tried recording it, but for some reason it didn't get picked up.

There's also no errors in the console on Safari. The fact that it opens and closes so quickly leads me to believe the state of a hook is somehow triggering in invalid ways.
