### ISSUE TITLE
Feature: Structured reporting CSVs

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#1151]
### Type of feature

🍕 Feature

### Current behavior

Today a user can only pull CSV data from superlative filters. But superlatives only work on top level topics. 

![Screen Shot 2023-05-08 at 3 20 10 PM](https://user-images.githubusercontent.com/5713670/236950402-9ea2f4bd-5ef9-4bb1-a7a8-e91c71fd32b2.png)

### Suggested solution

Structure the report to list contributions by date.

Open to interpretation, but here is the thought

_list all contributions by date_
date|contributor|title|contribution 
-|-|-|-
x|x|x|x

_list all contributions by grouped by count_
date|contributor|lastcommit date |count 
-|-|-|-
x|x|x|x

_list all new contributors by date (first PR flag is true on GitHub)_
date|contributor|title|contribution 
-|-|-|-
x|x|x|x

What else? Probably a flag for org member true/false

### Additional context

https://github.com/open-sauced/ops-backend/issues/6#issuecomment-1526535067

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by a0m0rajab** [comment]
The new link: https://github.com/open-sauced/api.opensauced.pizza//issues/6#issuecomment-1526535067

**Comment by bdougie** [comment]
> The new link: https://github.com/open-sauced/api.opensauced.pizza//issues/6#issuecomment-1526535067
> 
> commented on the API repo to connect both issues in case if names changed again in the future. 

That link is not correct. The recency score is actually we identify trending repositories and contributors.

However we can leverage this to create a structured report.

**Comment by a0m0rajab** [comment]
Did not the ops-backend repo changed to api.opensauced? I was referring to the link in the description of the issue since it's dead right now.

**Comment by bdougie** [comment]
The ops-backend repo is intentionally private. Private shows as 404 for those without access.

**Comment by brandonroberts** [comment]
We're going to revisit reporting overall, but it has been removed for now
