### ISSUE TITLE
Feature: Lists Tracking Issue

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#1152]
### Type of feature

🍕 Feature

### Current behavior

[Figma](https://www.figma.com/file/768ifqOGWrsRN29Igkc4ip/User-Flows?node-id=205-1661)

## User Stories

As a user, I would like to find engineers who participate in react projects and are located in UTC-7 so that I can invite them my event. 

As a hiring manager, I would like to find AI experts based on their contributions and location so that I can collaborate faster.

As a maintainer of an enterprise, I would like to see contributors not employed at my company and connect (collaborate) with them so that I can ship faster. 

### Suggested solution

- [x] #1153
- [x] #1154
- [x] #1155
- [x] #1156
- [x] #1157

### Additional context

[Kickoff Doc](https://app.clickup.com/20553800/v/dc/kk828-5380/kk828-8820)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by OgDev-01** [comment]
Closing this as all tracking issue has been completed ⚡️
