### ISSUE TITLE
Feature: Suggested highlights in dropdown

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#1179]
### Type of feature

🍕 Feature

### Current behavior

If the auth'd user has a PR in the repo that has not been highlighted, we should suggest them to highlight.

### Suggested solution

We have a figma with a design in the insights app. 

[[Figma File](https://www.figma.com/file/768ifqOGWrsRN29Igkc4ip/User-Flows?node-id=301%3A1597&t=IggKgB5nBNUMShqz-1)]

### Additional context

https://github.com/open-sauced/insights/issues/943

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by Lucif3r-in** [comment]
@bdougie The figma link is broken!

**Comment by bdougie** [comment]
Yes. I think a new issue was created when the design was done.
