### ISSUE TITLE
Feature: add keyboard bind in highlight

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/app#1196]
### Type of feature

🍕 Feature

### Current behavior

When you write a highlight pressing enter will create a new line, pressing CTRL+ENTER does nothing. 

### Suggested solution

WE can use CTRL+ENTER to post the post or shift enter

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by NsdHSO** [comment]
@a0m0rajab  I tested this and If I pressed `shift+enter` I got a new line. I think it is good `shift+enter` like every application e.g ( Github, Teams, Discord )

**Comment by 289Volts** [comment]
.take

**Comment by RitaDee** [comment]
I will .take this.
