### ISSUE TITLE
Feature: refactor user profile tabs routing implementation

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/app#1229]
### Type of feature

🍕 Feature

### Current behavior

We are currently appending the tabs to the url path 

### Exp:
- highlights -> `/user/{username}/highlights`
- contributions -> `/user/{username}/contributions`

This solution works... But if we are to put SEO into consideration, A better solution is using [URL parameters](https://www.botify.com/learn/basics/what-are-url-parameters)

### Exp:

- highlights -> `/user/{username}?tab=highlights`
- contributions -> `/user/{username}?tab=contributions`

### What are the benefits of this approach?

- **SEO and shareability**: URL parameters are more search engine friendly and shareable. Search engines can index individual tab URLs, and users can easily copy and share specific tab URLs.
- **Browser history**: URL parameters modify the URL itself, creating a new entry in the browser history. This allows users to bookmark or navigate back to specific tab URLs.
- **Server-side rendering**:  URL parameters are easier to handle as they can be processed on the server and the appropriate tab can be rendered accordingly.

### Suggested solution

Change the current path implementation to urlParams to handle all tabs in the user profile page

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by a0m0rajab** [comment]
Side note: clicking on tabs does not change the URL right now if you are on the profile page. 

Just asking: why the query parameter is better than path parameters? From my understanding query is being used to filter rather than show a specific page.

**Comment by takanome-dev** [comment]
> Side note: clicking on tabs does not change the URL right now if you are on the profile page.
> 
That's most likely a bug

> Just asking: why the query parameter is better than path parameters? From my understanding query is being used to filter rather than show a specific page.
>
Yeah, query parameters are typically used to filter or sort data.

What about SEO?
> **Note** From copilot

> In terms of SEO, there is no significant difference between using query parameters or path parameters. Search engines can crawl and index both types of parameters.
>
>However, it's important to note that search engines prefer URLs that are easy to read and understand. Using path parameters can make your URLs more descriptive and easier to read, which can be beneficial for SEO.

I think using `?tab=` notation is better in this case and more descriptive since both pages are the same

**Comment by bdougie** [comment]
@OgDev-01 can you pick this one up.

**Comment by OgDev-01** [comment]
> ![MeButtersStotchGIF](https://github.com/open-sauced/app/assets/27003616/cfaa0a33-89dd-44d4-a8e7-c4838ac95e11)
> 

You can give it a shot if you want😊😊
