### ISSUE TITLE
Bug: Share button copies the url but adds undefined instead of the username 

### ISSUE THREAD

**Issue by yhoungdev** [open-sauced/app#1243]
### Describe the bug

Share button copies the url but adds undefined instead of the username. when a user is not logged in yet. 

When i am not login and i click on share button, i get this 

![image](https://github.com/open-sauced/insights/assets/54102389/3c4e745c-34c5-4632-be89-995ea2d2fdbf)

But it works normal when am logged in. when i am logged in i get this 
![image](https://github.com/open-sauced/insights/assets/54102389/9b425c60-af08-460f-a9ad-252e91c14fdc)

### Steps to reproduce

* If you are not authenticated, go to profile and click the share button. 
![image](https://github.com/open-sauced/insights/assets/54102389/09f9c2b2-e183-4c40-929a-f8c4e456de3c)

It copies successfully, but does not copy the user name 

### Additional context (Is this in dev or production?)

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by a0m0rajab** [comment]
@yhoungdev Thank you for your first contribution to open sauced! 🙌 

I could reproduce this. Here is the related code block: 

To reproduce this, you need to be on a profile page, for example: 
https://insights.opensauced.pizza/user/a0m0rajab/contributions

https://github.com/open-sauced/insights/blob/9456876bad1ab0466a60bffd8d25cbd92d6876a5/components/molecules/ContributorProfileHeader/contributor-profile-header.tsx#L93-L102

To solve this we need to understand the user variable and why it's not being used or even empty. 
Then we might find a solution for that, as a simple solution would using `windows.location.href`

If you want to work on this issue, feel free to take it --> https://docs.opensauced.pizza/contributing/introduction-to-contributing/#issues

**Comment by yhoungdev** [comment]
Yea sure i will love to work on it. 
  i already thought about the solution before i raise the issue.

**Comment by a0m0rajab** [comment]
Awesome, feel free to self-assign yourself (explained in the docs) and open a PR 👍

**Comment by yhoungdev** [comment]
I cant find a way to assign it to my self

**Comment by bdougie** [comment]
Checking in to see if this still an issue and/or being worked on @yhoungdev

**Comment by yhoungdev** [comment]
currently working on it at the moment

**Comment by yhoungdev** [comment]
Sure.

   How do I mark as draft, havnt used the feature before

**Comment by takanome-dev** [comment]
I couldn't reproduce this issue. @yhoungdev can you confirm that this behaviour is still present?

**Comment by yhoungdev** [comment]
> I couldn't reproduce this issue. @yhoungdev can you confirm that this behaviour is still present?

No. Tested this abouyt 2 days ago, and it have been resolved. 

so i will be closing the issue now.
