### ISSUE TITLE
Feature: Collaboration Metrics

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#1244]
### Type of feature

🍕 Feature

### Current behavior

As a user, I should see user collaboration metrics or ratings. 

If a user has a high number of ignored collaborations, we should not recommend them. If a user has a high number of acceptance

### Suggested solution

Display collaboration insights for the user. The api collects all the needed information:

https://api.opensauced.pizza/#/User%20Collaborations%20service/findAllUserCollaborations

I don't have a location for this, but imagine this is information paid users should be able to see of others and something that the individual user can see their own data. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
The connections feature will be revisited
