### ISSUE TITLE
design: Add a list of repos to an insight page

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#1249]
## What is needed?
The user needs to be able to multiple repositories at a time, perhaps in a comma separate or input that allows + to add more. 

![Image](https://user-images.githubusercontent.com/5713670/243548538-efa5994c-2034-4573-b71e-f716343107c9.png)

## Additional Context

https://opensauced.rewatch.com/series/19929/zedh2aylb8rz8i1e

## Add another ENV variables example
Sort of related. This is also painful when deploy devops tools. Vercel allows you to add another item. 

![Image](https://user-images.githubusercontent.com/5713670/243549004-a980367b-9d52-4ba9-96fa-a0099593c233.png)

![Image](https://user-images.githubusercontent.com/5713670/243549014-027ca972-0f4d-4293-b963-fbb759d9c6b7.png)

**Comment by OgDev-01** [comment]
Hey @isabensusan, following up on this to know when the designs are ready

**Comment by brandonroberts** [comment]
We have copy/past available for workspace repos and GitHub Org Import available
