### ISSUE TITLE
Bug: filters odd design on md screens (surface pro 7)

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/app#1264]
### Describe the bug

When you change filters on medium screens (surface pro 7 as example) it will give an odd design with each filter. 

### Steps to reproduce

1. go to highlights
2. change the view to surface pro 7 mode
3. try to change the filters
4. you will find the odd change 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by babblebey** [comment]
Hi @a0m0rajab 

Could you share a screenshot?

**Comment by a0m0rajab** [comment]
Here you can see that the filters are changing the feed sizes, there is no fixed width. 

https://github.com/open-sauced/insights/assets/18273833/ee28f3fb-de95-4f9f-86a1-7f6c3b1247b0

Plus, when I click on a filter again to remove it, it stays selected.

**Comment by babblebey** [comment]
Very well @a0m0rajab 

I believe the width issue will be fixed with the release of the anticipated new highlights page #1298 unless you still think it should be fixed even in this current release.

I couldn't recreate the filter active click one, as it seem to be working just fine on my end.

**Comment by diivi** [comment]
Can reproduce this with the resolution set to "Surface Pro 7"

**Comment by a0m0rajab** [comment]
With the new UI we have a new issue + the old one, the new issue is that the 3 columns does not fit the screen, the top bar is off. 

![image](https://github.com/open-sauced/insights/assets/18273833/a19e42bd-1456-4324-8779-86bf6f436bfc)

**Comment by takanome-dev** [comment]
I think this has been fixed. Can you confirm @a0m0rajab?

**Comment by a0m0rajab** [comment]
@takanome-dev yes, the menu itself got deleted! closing this issue now.
