### ISSUE TITLE
Feature: Include reviewed prs in user's contributions

### ISSUE THREAD

**Issue by takanome-dev** [open-sauced/app#1272]
https://api.opensauced.pizza/v1/users/BaseMax/prs?limit=15&range=90

Seems working, So it should be okay.
It seems this route only returns a list of PRs made by yourself. It's not about reviewing but I think it's not a good solution to show because most maintainers do not work on other projects.

Cheers

_Originally posted by @BaseMax in https://github.com/open-sauced/insights/issues/865#issuecomment-1585490604_

**Comment by takanome-dev** [comment]
cc @brandonroberts

**Comment by isabensusan** [comment]
@brandonroberts  is this ok to close?

**Comment by brandonroberts** [comment]
Yes, we have a separate issue for identifying pr reviewers
