### ISSUE TITLE
Bug: repo/contributors table needs an empty state design

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/app#1280]
### Describe the bug

The repositories and contributors table doesn't have an empty state component
![hello](https://github.com/open-sauced/insights/assets/62995161/c0280a51-827d-420e-9acb-84969251dfa4)

We might need design help for this @is

### Steps to reproduce

1. Visit the repo or contributors page and filter by 7days

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by babblebey** [comment]
Hi @OgDev-01, please help me understand the "needs-design" issue label.

Does it mean, issues with this label needs contribution from a UX/UI/Product Designer!?

**Comment by OgDev-01** [comment]
Yes @babblebey

**Comment by babblebey** [comment]
> Yes @babblebey

Great!

Thank you || Danke || O ṣeun

**Comment by babblebey** [comment]
Another question @OgDev-01 

Kindly confirm the steps to make this design-related contribution...

- Grab the Figma file
- Make the Changes
- Submit the new updated figma file (how?)

?????????

**Comment by bdougie** [comment]
> Kindly confirm the steps to make this design-related contribution...

There is no precedent for this. Your suggestions are welcomed, but wireframes are preferred if the design is net new. For fixes like this, my suggestion is designing over screenshot for now. 

Our figma is paid and cost $$$ every-time we add a new editor. So allowing access to the figma files are not possible, unless there is another way someone can suggest.

cc @isabensusan for 👀

**Comment by brandonroberts** [comment]
We have empty states that will do for now
