### ISSUE TITLE
Tracking: Page speed

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#1284]
We need to run an audit page and data load speeds. The goal is just running an audit, no need to act on information just yet. 

Open to suggestions using tools like New Relic. A quick audit can be run using Lighthouse to get overall numbers.

**Comment by bdougie** [comment]
Just discovered that Netlify provides a high level insight for this. 

https://app.netlify.com/sites/oss-insights/analytics/rum

<img width="1014" alt="Screen Shot 2023-06-28 at 9 31 43 PM" src="https://github.com/open-sauced/insights/assets/5713670/5ef6fa15-dcae-4f59-b908-67dcdc181728">

**Comment by brandonroberts** [comment]
Track page load speed through OKRs here https://github.com/open-sauced/engineering/issues/292
