### ISSUE TITLE
enhancement: show `requests` tab for user's who have at least one collaboration request

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/app#1310]
With this feature, We should keep the `requests` tab for users who have at least one request in their inbox.

![image](https://github.com/open-sauced/insights/assets/62995161/4386b23a-b4ea-43c2-a2b1-ce4c3c83f727)

### Currently
The `request` tab is hidden if a user turns off collaboration requests from their profile. 

### limitations
While this approach is valid, we also need to put into consideration use cases where a user who has the collaboration request turned on and has received a collaboration that is still pending acceptance. If this user turns this feature off at this point in their profile settings, they don't get to see those requests that are pending.

With the intro of [1305](https://github.com/open-sauced/insights/issues/1305), we need to also include a check to see if a user has at least one collaboration request and show the `requests` tab.

_Originally posted by @OgDev-01 in https://github.com/open-sauced/insights/issues/1305#issuecomment-1610820096_

**Comment by babblebey** [comment]
I'll .take this one @OgDev-01 

Kindly confirm this small talk

> User with at least 1 Collab Request && Collab Turned On => Display Request Tab

> User with Collab Turned Off => DISABLE Request Tab (Regardless of  Collab Request Count???)

**Comment by brandonroberts** [comment]
I think the requests tab should always be shown if enabled, regardless of number of requests, and it should be hidden if disabled even if they're are requests. The user can't receive collaboration requests if they don't enable it

**Comment by babblebey** [comment]
> I think the requests tab should always be shown if enabled, regardless of number of requests, and it should be hidden if disabled even if they're are requests. The user can't receive collaboration requests if they don't enable it 

I second this @brandonroberts

I have Collab turned on, but no difference, my "Request" tab is not displayed.

So...

> **Display Request Tab** => When Collab is turned on, regardless of requests count, we will handle zero requests state with the current empty message available.

> **Hide Request Tab** => When Collab is turned off, regardless of requests count. Request can still be seen deep at `/user/[username]/request` regardless.

Shall I Proceed?

**Comment by babblebey** [comment]
> I think the requests tab should always be shown if enabled, regardless of number of requests, and it should be hidden if disabled even if they're are requests. The user can't receive collaboration requests if they don't enable it

@brandonroberts 

This in fact turns out to be the what the current setup is.

If we are to keep this set-up, then I suggest this issue is closed.

**Comment by OgDev-01** [comment]
Let's analyse this use case:

### Instance:
1. I am a user that has access to collaborations
2. I turn on my collaboration switch from my profile settings
3. I get up to like 3 requests from users to collaborate
4. Then i decide to turn the collaboration switch off without accepting or declining the requests i had while collaborations switch was active


Is it ideal to hide those pending requests when the user turns off the collaboration switch? cc: @brandonroberts @bdougie 

IMO, As a user, I want to see what pending requests I have in my inbox even when I turned off the feature. I can have multiple reasons for turning off the collab switch which might include me wanting to attend to pending requests before accepting new requests.

**Comment by babblebey** [comment]
I see your point @OgDev-01

I can honestly relate to this use case. So I think it's going to be a great option to have the Request Tab displayed regardless of Collab status.

Then there can be a `div`, at the top part of the Request Tab Content that actively displays the users Collab Status with a message for `true` or `false` cases.

Case: Collab Status is `false` i.e. `!receive_collaboration`

```You are not accepting Collaboration Requests```

Case: Collab Status is `true` i.e. `receive_collaboration`

```You are currently accepting Collaboration Requests```

Also, with either a quick link to the settings area to change Collab Status or better still a toggle component right there in the `div` to set Collab Status `true` or `false` instantly.

I think this will be a good one.

**Comment by babblebey** [comment]
I've got a Blocker trying to implement the `ToggleSwitch` component to set `receive_collaboration` `true` or `false`.

I cannot seem to be able to persist/update the value of `receive_collaboration` via the `updateEmailPreferences` hook.

Here's what I'm experiencing

![screencast-localhost_3000-2023 07 10-20_36_24](https://github.com/open-sauced/insights/assets/25631971/96306d25-6996-4506-8361-908f841be4c3)

The Intention is to have the `ToggleSwitch` component's `handleToggle` prop to update the `receive_collaboration` via the `updateEmailPreferences` and Here's what I have.

```javascript
// components\organism\CollaborationRequestWrapper\collaboration-request-wrapper.tsx

import { useState } from "react";
import { useToast } from "lib/hooks/useToast";
import { useFetchUser } from "lib/hooks/useFetchUser";
import { updateEmailPreferences } from "lib/hooks/updateEmailPreference";
import ToggleSwitch from "components/atoms/ToggleSwitch/toggle-switch";

const CollaborationRequestsWrapper = ({ user }: CollaborationRequestsWrapperProps) => {
  const { toast } = useToast();
  // Getting DBUser
  const { data: insightsUser } = useFetchUser(user?.user_metadata.user_name, {
    revalidateOnFocus: false
  });

  // Setting Initial State of emailPreference from DBUser data
  const [emailPreference, setEmailPreference] = useState<EmailPreferenceType>({
    display_email: insightsUser?.display_email,
    receive_collaboration: insightsUser?.receive_collaboration
  });

  // Toggle switch handler function
  const handleUpdateReceiveCollab = () => {
    // Update `receive_collaboration` value
    setEmailPreference((prev) => ({
      ...prev, 
      receive_collaboration: !prev.receive_collaboration
    }));
    
    // invoke `updateEmailPreferences`
    handleUpdateEmailPreference();
  };

  // Update Email Handler invoking `updateEmailPreferences`
  const handleUpdateEmailPreference = async () => {
    const data = await updateEmailPreferences({ ...emailPreference });
    if (data) {
      toast({ description: "Updated successfully", variant: "success" });
    } else {
      toast({ description: "An error occurred!", variant: "danger" });
    }
  };

  return (
    <div>
      <DashContainer className="flex-col gap-6 md:gap-8 text-light-slate-9">
        <p>
          Collaboration Status: { emailPreference.receive_collaboration ? "ACTIVE" : "INACTIVE" }
        </p>

        <ToggleSwitch
          name="receive_collaboration"
          checked={emailPreference.receive_collaboration as boolean} 
          handleToggle={handleUpdateReceiveCollab}       
        />
      </DashContainer>
    </div>
  );
};
```

Cc: @OgDev-01

**Comment by OgDev-01** [comment]
Hey @babblebey, you might want to place a `useEffect` to set the `emailPreference` state when the `insightUser` data is available.

Remember the `useFetchUser` hook is an async action(`Promise`) that might take some time to resolve. At initial render, the data is `null` and that is what is captured in the `useState`. We need to update the state using a `useEffect` when the data is available for the changes from the API to reflect when you leave the component.

```javascript

useEffect(() => {
  if(insightsUser){
    // Set you email preference state here
  }
},[insightUser])
```

Let me know if this helps 👍

**Comment by babblebey** [comment]
My Apologies, I did left out that part yea.

I did exactly that though, I resulted to not putting it here exactly because I thought to keep the code short.

But, I did that as I see it was implemented in this way on the `UserSetting` area too.

Same thing!

I will experiment further for sure.

Just so you know too, I have tried passing static value as arguments to the `updateEmailPreferences` hook.

**Comment by babblebey** [comment]
My Apologies, I did left out that part yea.

I did exactly that though, I resulted to not putting it here exactly because I thought to keep the code short.

But, I did that as I see it was implemented in that way on the `UserSetting` area too.

Same thing!

I will experiment further for sure.

Just so you know too, I have tried passing static value as arguments to the `updateEmailPreferences` hook.

**Comment by OgDev-01** [comment]
One Question: When you log your state to the console, do you get the updated value?

**Comment by babblebey** [comment]
> One Question: When you log your state to the console, do you get the updated value?

@OgDev-01 

Ofcourse not exactly updated when logged to the console and that seem very usual though (since state updates are kinda asynchronous), the logged state is always one step behind. See screencast below.

![screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023 07 11-10_21_15](https://github.com/open-sauced/insights/assets/25631971/4f841b6a-4e33-40c8-9021-9687b9c1dd2b)

**Comment by babblebey** [comment]
Oh, that's it! 

`useEffect` I can have the callback to run the `updateEmailPreferences` depend on changes in `emailPreference`.

How did I not think about that? That should obviously work. 

I'll revert shortly.

**Comment by babblebey** [comment]
@OgDev-01 

So I found a solution, the task was to ensure the `emailPreference.receive_collaboration` state property value changes (actually inverses) before using it in a call to the `/auth/profile/email` endpoint, I decided to use the already available `insightsUser` data instead of the `emailPreference` state in the data.

This way I was able to leave `emailPreference` to managing the `ToggleSwitch` component and allow the response `insightsUser`  data deal in the call to the `/auth/profile/email` endpoint

```javascript
const handleUpdateReceiveCollaboration = async () => {
  // this handles `ToggleSwitch` component state
  setEmailPreference((prev) => ({
    ...prev, 
    receive_collaboration: !prev.receive_collaboration
  }));

  // using `insightsUser` in data passed to the endpoint 
  const data = await updateEmailPreferences({ 
    display_email: insightsUser?.display_email,
    receive_collaboration: !insightsUser?.receive_collaboration // <- inversing the initial `receive_collaboration` value
  });

  if (data) {
    toast({ description: "Updated successfully", variant: "success" });
  } else {
    toast({ description: "An error occurred!", variant: "danger" });
  };

  return;
};
```

Phew!

**Comment by brandonroberts** [comment]
Thanks @babblebey. I saw you opened a PR for this, but for some feature requests we need a design review first to make sure it fits for the feature. Collaborations is still in progress.

**Comment by babblebey** [comment]
Well noted @brandonroberts ✌🏾

**Comment by brandonroberts** [comment]
We're going to revisit the connections feature in the future. Closing this one for now
