### ISSUE TITLE
Bug: General Responsiveness of the Highlights Page

### ISSUE THREAD

**Issue by babblebey** [open-sauced/app#1336]
### Describe the bug

General Responsiveness on the Highlights Page Isn't Crisp, some content goes out of the viewport and certain width size and some overflow on the x-axis is scrolled at some point too

![screencast-insights opensauced pizza-2023 07 07-00_18_44](https://github.com/open-sauced/insights/assets/25631971/30d94cb9-3fd9-492c-a77b-420f28aa79fd)

### Steps to reproduce

1. Go to https://insights.opensauced.pizza/feed
2. Restore you browser and reduce the width size to the smallest possible
3. Pay attention to how the viewport treats the content

### Browsers

Chrome

### Additional context (Is this in dev or production?)

Dev and Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bharathkalyans** [comment]
Hiding the left and right sections in that viewpoint would solve this bug!
Or we can reduce the width of the middle section so that we can fit the 3 sections accordingly!

**Comment by jpmcb** [comment]
I also ran into this today

https://github.com/open-sauced/insights/assets/23109390/040e6507-a769-4ec1-8541-e2857cd4f93b

This video I took on Firefox so looks like it's across all browsers. But looks like #1340 will address this.

**Comment by NsdHSO** [comment]
Hi folks, In this issue I want to add some more info about the issue, or some docs. I remembered when I worked first time on responsiveness, "What is this how can cover the entire screen area".
[BrowserStack](https://www.browserstack.com/guide/responsive-design-breakpoints)
[Ideal-scrren](https://www.browserstack.com/guide/ideal-screen-sizes-for-responsive-design)
[Tailwind](https://tailwindcss.com/docs/responsive-design#targeting-a-breakpoint-range)

**Comment by jpmcb** [comment]
Looks like this behavior with the left side shifting beyond the left viewport isn't fixed. Here's a screenshot from just now on `beta.insights.opensauced.pizza`:

<img width="1403" alt="Screenshot 2023-08-08 at 8 20 08 PM" src="https://github.com/open-sauced/insights/assets/23109390/fa3d849a-ab35-443a-b7e4-e884cfe52eb7">

And this was raised recently again in #1530

**Comment by bdougie** [comment]
I did notice on stream today. Not sure if the changes were overwritten.

**Comment by babblebey** [comment]
The PR #1538 should fix this. 🍕

**Comment by babblebey** [comment]
Issue has been resolved in https://github.com/open-sauced/app/pull/1553
