### ISSUE TITLE
Bug: tables don't always resize with browser windows

### ISSUE THREAD

**Issue by LauraLangdon** [open-sauced/app#1344]
### Describe the bug

On a wide monitor with a browser window sized to half the screen, the table displaying "Respositories" doesn't scale with the browser window, and the "Add to insights page" button is only accessible by scrolling right.

This only seems to occur on wide monitors when the browser window width is between approx. 40%-50% of the screen size. All good otherwise!

### Steps to reproduce

1. On a wide monitor (in this case 5k 27"), set a browser window to 50% of the screen width
2. Open a user's dashboard
3. Click "Explore"
4. Click "Repositories"
5. Tick a box to select a repository:

![CleanShot 2023-07-11 at 10 06 46@2x](https://github.com/open-sauced/insights/assets/48335772/70835237-6f65-4678-8882-37097a92d2ae)

6. The "Add to insights" button only appears after scrolling to the right:

![CleanShot 2023-07-11 at 10 14 26@2x](https://github.com/open-sauced/insights/assets/48335772/c647f5f5-8598-4fe0-8a4d-f4b27fd20033)

### Browsers

Other (add additional context)

### Additional context (Is this in dev or production?)

Arc browser (Chromium-based)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
Confirmed that this is not a present issue in app.
