### ISSUE TITLE
Feature: creating a highlight should have a "Close" button to collapse form

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#1363]
### Type of feature

🍕 Feature

### Current behavior

I found the UI / UX to be abit confusing for creating a highlight:

https://github.com/open-sauced/insights/assets/23109390/5f03086c-28bd-48dd-b348-f2027586502a

Seems like to close the popup, you must click the "Title" again which wasn't immediately obvious to me and resulting on some "click and find out" behavior.

### Suggested solution

Maybe this deserves it's own "Close" button? Or maybe something else to make the UI / UX alittle more obvious. This sort of felt similar to how GitHub forms are designed where clicking onto another field collapses the current field.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by MartiinWalsh** [comment]
Hey @jpmcb, I agree that the addition of a "Close" button could enhance the user experience and make the functionality more intuitive.

I've quickly implemented a solution that utilizes the 'outline' variant of our existing custom Button component. I also added a handler to clear the form data when the form is closed.

Here's a brief video showcasing that change:

https://github.com/open-sauced/insights/assets/74657328/6f4325ec-eea9-44fc-a487-32af5c02b40f

I believe this implementation addresses the current issue, but I'm open to feedback. Do you think this solution is worth creating a PR for? Or should we leave this issue open for further design discussions?

**Comment by MartiinWalsh** [comment]
@bdougie this might be a question for you too?

**Comment by isabensusan** [comment]
hey @MartiinWalsh ! Thank you for this :)

I think the "Close" secondary button works, but it does feel like it overpowers the "Post" button at times.

Alternatively, I think a close icon button works better design wise. Something we could also add to make this interaction more intuitive: when the user clicks outside the new highlight box, collapse it.

<img width="765" alt="image" src="https://github.com/open-sauced/insights/assets/27322879/d9590ae5-7eee-4f16-b498-7ceeb1ee75aa">

**Comment by babblebey** [comment]
Quick Addition in suggestion to @isabensusan's comment.

Click outside the Input Form should Collapse only when there's no content in the Form fields, that way on mistake click outside the form, the data stays tact.

...and another to confirm @MartiinWalsh's intro of the inputs resets

> I also added a handler to clear the form data when the form is closed.

Now, onClick close! Then I think the data can be cleared, you might want to add a confirmation Alert to for UX to authorize that then.

Now maybe the Alert might require some design now, is this something we can do isabensusan?

We can look at the [RadixUI Alert Primitive](https://www.radix-ui.com/docs/primitives/components/alert-dialog)

**Comment by takanome-dev** [comment]
The new highlight form now opens up in a modal and can be closed by clicking the close button or outside of the modal
