### ISSUE TITLE
Feature: Add more option to list of interests

### ISSUE THREAD

**Issue by Olaleye-Blessing** [open-sauced/app#1366]
### Type of feature

🍕 Feature

### Current behavior

The number of options in the interests section is limited to 14. A dev that has interest in (Vue/Elixir/Clojurescript/Next.js and others) currently has no way to choose an interest.
The same problem occurred when I was setting up my profile.
![Screenshot (774)](https://github.com/open-sauced/insights/assets/70102539/5fd1320d-1962-4057-b9ca-ec5fd66f218e)

### Suggested solution

Add more options to the list of interests.
A better solution will be to provide "a add more" button. This button when clicked, will provide an input text that users can fill. These options provided by a user should be verified and given a consensus name by "open-sauced".
For example: JavaScript could be written as Javascript, JavaScript, Js. The consensus name for this could be JavaScript.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Olaleye-Blessing** [comment]
I will like to work on this. Is there a design I should follow for this?

**Comment by takanome-dev** [comment]
cc @bdougie :eyes:

**Comment by bdougie** [comment]
> I will like to work on this. Is there a design I should follow for this?

What is your suggestion? Adding Vue to the list is a trivial change and has already been done.

https://insights.opensauced.pizza/vue/dashboard/filter/recent

Can you provide more thought on what you are looking for?

**Comment by Olaleye-Blessing** [comment]
> > I will like to work on this. Is there a design I should follow for this?
> 
> What is your suggestion? Adding Vue to the list is a trivial change and has already been done.
> 
> https://insights.opensauced.pizza/vue/dashboard/filter/recent
> 
> Can you provide more thought on what you are looking for?

I didn't know the link in your comment is connected to the interests section in my screenshot.

Assuming the link in your reply is not connected to the interests section, then what I'm about to say would be fine. 

So what I was saying is the limited list of languages prevents users from adding/choosing all of their languages.
For example, Vue was added because you thought some users have an interest in Vue. What about if I have an interest in Elixir, Erlang, or C++? Then, There is no way to choose any of these because it hasn't been added to the list. 

This is why I provided a suggested solution in my first comment. This prevent users from waiting for open-sauced to add an interest they really want.
> A better solution will be to provide "a add more" button. This button when clicked, will provide an input text that users can fill.

Just think of it as:
- I came to the interests section, [https://insights.opensauced.pizza/user/settings](https://insights.opensauced.pizza/user/settings).
- I checked the list of interests hoping to find `Elixir`, `Go`, `CSS` and maybe `C++`.
- Found no option for any of these.
- Fine, I can click the `add language` button.
- An input element pops up to collect my language and the language is added to the list after pressing enter.(x4 for each language)
- Then I click on the `Update Interest` button and my interests get updated.

Instead of what we have at the moment:
- I came to the interests section, [https://insights.opensauced.pizza/user/settings](https://insights.opensauced.pizza/user/settings).
- I checked the list of interests hoping to find `Elixir`, `Go`, `CSS` and maybe `C++`.
- Found no option for any of these.
- Then leave the page hoping the languages will be added at some point in the future.

**Comment by brandonroberts** [comment]
We're going to revisit this feature in the future. Closing this one for now
