### ISSUE TITLE
Feature: Load more repos on the insights page

### ISSUE THREAD

**Issue by Olaleye-Blessing** [open-sauced/app#1373]
### Type of feature

🍕 Feature

### Current behavior

Since this page is only accessible to authenticated users, it will be nice to load their Github repos as suggested repos. E.g 50 repos

![Screenshot (780)](https://github.com/open-sauced/insights/assets/70102539/2baf413f-2aa3-45c7-939e-9721935d9440)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by aryanas159** [comment]
.take

**Comment by babblebey** [comment]
Great stuff @Olaleye-Blessing, 

Thanks for picking this one out yea, I think it'll be good! 

The `InsightPage` component used on this route/page seem to actually have the current Suggested Repositories List data statically added for now, I guess for some reason best known to the core team.

```javascript
// components\organisms\InsightPage\InsightPage.tsx

<SuggestedRepositoriesList
  reposData={staticSuggestedRepos} // <- Static Suggested Repos Data
  onAddRepo={(repo) => {
    loadAndAddRepo(repo);
  }}
/>
```

So @aryanas159, I think you should hold-on with working on this for now and lets hear a `triage-team` decision on the issue.

Cc @bdougie @brandonroberts @OgDev-01

**Comment by brandonroberts** [comment]
Thanks @Olaleye-Blessing. We've discussed this previously, and while loading your personal repos is an option, its not the usually path for finding repos you want to track or to look for contribution opportunities. We are looking at ways to surface more suggested repositories for contributions similar to the recommendations page.

**Comment by a0m0rajab** [comment]
@brandonroberts, from your last comment do we understand that this might need an API update to connect with the recommendation system and use it here? if that's the case we might have a weekly thread (different page) something similar to the one @BekahHW is doing on `Dev.to` where contributors can add their projects and we can use that for this. 

Another option, would be adding a flag to repositories that's looking for contributors and show them here after filtering them based on the programming languages.

Anyway, whatever solution will be applied here it will need an API update.
