### ISSUE TITLE
Feature: refetch following count after following a user

### ISSUE THREAD

**Issue by takanome-dev** [open-sauced/app#1418]
### Type of feature

🍕 Feature

### Current behavior

https://github.com/open-sauced/insights/assets/79809121/ba7cc627-33f0-476b-90fb-0b5cd0b7df27

### Suggested solution

Refetch the following count each time a new user is followed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by ThePromiseBenard** [comment]
.take

**Comment by aryanas159** [comment]
@ThePromiseBenard  are you still working on the issue?

**Comment by OgDev-01** [comment]
hey @aryanas159, would you like to take this on?

**Comment by aryanas159** [comment]
> hey @aryanas159, would you like to take this on?

@OgDev-01 Sure, I'll look into it.
