### ISSUE TITLE
Feature: Flow for creating and updating insights pages could be more intuitive

### ISSUE THREAD

**Issue by dominicduffin1** [open-sauced/app#1425]
### Type of feature

🍕 Feature

### Current behavior

When creating or updating an insights page the flow could be more intuitive. It is easy to navigate away from the flow without realizing you haven't saved the page / page updates and the buttons to click on don't stand out too well if you're not familiar with how it works.

![2023-07-25 19 09 31 insights opensauced pizza 8419953f597e](https://github.com/open-sauced/insights/assets/26224873/68363d09-2aa1-45e8-a944-c9a8feb19ec4)

### Suggested solution

I don't have a definite solution but some ideas include:

- Duplicating the "Update Page" / "Create Page" button within the flow on the left / center of the page (I didn't see it over on the right the first time I tried to create a page and wasn't sure why my page wasn't being created)
- Either make the "Add Repository" button change to draw attention to itself when the user has selected a repository in the Repository Full Name field, or have the repository be added automatically when the user selects it from the dropdown
- If a user navigated away without clicking on "Update Page" / "Create Page", warn that they have not saved their changes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by a0m0rajab** [comment]
I think this is a more of a design decision right now, I kep the needs triage label and added needs design. 

@isabensusan can you provide your input when you can?

**Comment by bdougie** [comment]
I removed the "needs design," I am not convinced based on the data people are creating insights pages. 

> If a user navigated away without clicking on "Update Page" / "Create Page", warn that they have not saved their changes

I'd suggest adding a warning and we keep discussing solutions and sharing ideas. @a0m0rajab please be mindful when triaging issues. I'd get more context from the issue opener prior to pulling in the team with an @ mention. 

@open-sauced/triage can help with context as well. 

At the moment we cannot prioritize the design of this page just yet. We are working on shipping the lists feature first.

**Comment by a0m0rajab** [comment]
@bdougie Thank you for the information, I had faced a similar issue before which made me feel it's clear though. I added some repos and went forward without saving it as well. I would need to go without mentions then. 

As for the need design,  I did this due to this comment: https://github.com/open-sauced/insights/issues/1445#issuecomment-1658428693 

> Anything that changes the user experience (either in the appearance or user flow of something) should in theory have a design signoff. You'd be surprised how these small changes can really add up to drastically change the feel and experience of using something.

**Comment by diivi** [comment]
an alert/[confirm](https://www.w3schools.com/jsref/met_win_confirm.asp) before [unload](https://www.w3schools.com/jsref/event_onbeforeunload.asp) when the page isn't saved would be a good solution imo.

**Comment by dominicduffin1** [comment]
@jpmcb My focus was on the flow at the left side of the screen, I didn't realize there was anything else I had to do so I didn't take in what was over on the right until I realized it hadn't saved and I looked around more on the second try.

**Comment by a0m0rajab** [comment]
I just did a quick check mockup for the designs, besides your issues I think since the create page button is not showing before adding repos, it would confuse the users. 

I am not sure what is the best for those designs.

| Option 1 | Option 2|
|--------|--------|
| ![Option 1](https://github.com/open-sauced/insights/assets/18273833/c3c3fa11-97d8-4b00-a7a2-1c58eb9463f8) | ![Option 2](https://user-images.githubusercontent.com/18273833/257544207-b99ff344-20ac-42b2-872c-f860db6d835c.png) |

**Comment by a0m0rajab** [comment]
.take

**Comment by bdougie** [comment]
Linking to https://github.com/open-sauced/insights/pull/1500 as it expands on the conversation here.

**Comment by brandonroberts** [comment]
Closing as resolved with move to workspaces
