### ISSUE TITLE
Feature: Setup Next.js App router and convert one route

### ISSUE THREAD

**Issue by foxyblocks** [open-sauced/app#1439]
### Type of feature

🍕 Feature

### Current behavior

The next.js App directory and router is now stable. The goal of this issue is to turn it on and setup whatever infrastructure is necessary to convert a single route to use the new directory structure and react server components. Also create issues for followup work such as getting server side supabase helpers working.

Good candidates for an initial route include:
- [pages/404](https://github.com/open-sauced/insights/blob/beta/pages/404.tsx)
  - Has few dependencies and no login requirements
- [card page](https://github.com/open-sauced/insights/blob/beta/pages/user/%5Busername%5D/card.tsx)
  - Would require testing auth

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
Will revisit app router migration in the future. We did some initial testing with just upgrading to Next 14 and saw some breakages
