### ISSUE TITLE
Bug: AI generation of highlight form body throws 401 on getting commits from github

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#1440]
### Describe the bug

When attempting to create an Ai generated text body for my highlight, the icon spins indefinitely and never generates the text:

![Screenshot 2023-07-26 at 6 02 35 PM](https://github.com/open-sauced/insights/assets/23109390/4bfe0f1b-45d0-45d1-a1c5-ef24ae5dbdfd)

I do see in the console that a `GET` https://api.github.com/repos/open-sauced/api/pulls/223/commits (for this specific highlight) throws a 401, not authorized:

```json
{
	"message": "Bad credentials",
	"documentation_url": "https://docs.github.com/rest"
}
```

Very weird that this would send a 401 since I can curl this on my own machine just fine without having to provide any auth:
```sh
❯ curl https://api.github.com/repos/open-sauced/api/pulls/223/commits
[
  {
    "sha": "9a0b8bd59c5ffb1d60ef5f1277329b9217d00af3",
     ...
   }
]
```

### Steps to reproduce

1. Go to highlights
2. Attempt to input a PR and generate text
3. Open dev console and see response to `api.github.com` for that pull request

### Browsers

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by aryanas159** [comment]
.take

**Comment by aryanas159** [comment]
@jpmcb It's working fine when I removed the authentication header from the request, is that an appropriate fix?

**Comment by jpmcb** [comment]
@aryanas159 - I don't think so: without the auth header with the github token, users will get rate limited pretty quickly.

Here's the code that's adding that auth header:

https://github.com/open-sauced/insights/blob/8b01158f0c0300cf487f01b89bbf315f762e39bd/lib/utils/github.ts#L71-L78

Drilling abit further into the actual request, there is a problem where the auth header is being set to `null`:

```
Authorization
	token null
```

@OgDev-01 - any thoughts on this?

**Comment by OgDev-01** [comment]
> there is a problem where the auth header is being set to null


This should be a superbase-related issue where the provider's tokens are sometimes inconsistent or `null`. This is something we should closely investigate moving on. cc: @brandonroberts

**Comment by bdougie** [comment]
I'm just bumping this on the notifications and sharing that I could not summarize a highlight yesterday. I think we might want to prioritize this in the coming weeks or make a decision to flag this feature until it is fixed.
