### ISSUE TITLE
Feature: improving the create insight page

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/app#1463]
### Type of feature

🍕 Feature

### Current behavior

The page right now does not have a title for the added repositories neither showing the create page from first look, which could be confusing:
![image](https://github.com/open-sauced/insights/assets/18273833/8a6d8929-220e-44f4-a4a3-a9db535ed1a9)

https://insights.opensauced.pizza/hub/insights/new

### Suggested solution

It would be great to: 

- have a title for the repos
- have the create page button visible always 

![image](https://github.com/open-sauced/insights/assets/18273833/b99ff344-20ac-42b2-872c-f860db6d835c)

### Additional context

I got this when I tried to understand the UX from this issue: Related to: https://github.com/open-sauced/insights/issues/1425

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by a0m0rajab** [comment]
if we go with quick fix we can do the next: 

When no repo is added (with suggestions): 
![image](https://github.com/open-sauced/insights/assets/18273833/963d662e-5033-475a-8b3a-a319c30781e1)

When no repo is add (without suggestions): 
![image](https://github.com/open-sauced/insights/assets/18273833/ec61a652-f234-426c-b9b2-186b1f0e6a60)

**Comment by a0m0rajab** [comment]
.take

**Comment by brandonroberts** [comment]
Closing as resolved
