### ISSUE TITLE
Feature: hovering "Following" button should indicate unfollow action

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#1468]
### Type of feature

🍕 Feature

### Current behavior

Currently, when clicking or hovering over the "Following" button on someone's profile, it's not clear what the action will be when clicking it:

![Screenshot 2023-08-02 at 9 34 03 AM](https://github.com/open-sauced/insights/assets/23109390/dc91d50a-065f-4fb0-8f0c-fa7f0614dae9)

Further, this pop up closes immediately on clicking the "Following" button so it's confusing what action was taken. Did clicking that simply cause the menu to collapse? 

![Screenshot 2023-08-02 at 9 49 03 AM](https://github.com/open-sauced/insights/assets/23109390/5fb1e0e5-b3c6-4fd0-857b-b9b971828f84)

Re-opening the menu shows that I've unfollowed the person.

![Screenshot 2023-08-02 at 9 49 06 AM](https://github.com/open-sauced/insights/assets/23109390/3d0eaf94-f22a-4b33-ad6c-f659b208a5ce)

### Suggested solution

I think Twitter/X has a few good, clear solutions for this: 

A) On desktop, when hovering over the following button, it turns red and changes to "Unfollow":

![Screenshot 2023-08-02 at 9 43 26 AM](https://github.com/open-sauced/insights/assets/23109390/10652060-cffc-410e-be8c-03be9dfcbc95)

B) on mobile, clicking "Following" pops open a secondary button for unfollowing someone which is also very clear.

![IMG_4BF96DD6F6DE-1](https://github.com/open-sauced/insights/assets/23109390/0891f58a-6005-49a1-b5d4-f3634d7e9a9e)

---

I'm curious to hear what others prefer in this user flow? I could see either solution above working or coming up with a novel solution. Either way, the UX around unfollowing someone is abit confusing.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by deepakrudrapaul** [comment]
.take

**Comment by deepakrudrapaul** [comment]
Your solution is outstanding. Perhaps we could consider implementing it in this manner. (Please see the gif) 
Let's gather feedback from others to see what they think about the proposed approach.
 
![CPT2308022210-518x241](https://github.com/open-sauced/insights/assets/25549935/9625bd0d-b286-45ea-83cc-c00571b48b53)

**Comment by a0m0rajab** [comment]
I think we can have the button outside the menu, since there is no indicator if you are following someone in the profile page:

![image](https://github.com/open-sauced/insights/assets/18273833/d055420d-faaa-47eb-8506-66b060bdbfef)

**Comment by a0m0rajab** [comment]
The menu button was removed :) 
![image](https://github.com/open-sauced/insights/assets/18273833/5e667df5-3ac5-4de8-a54d-57386d9fb7ae)

Design-wise, I think having GitHub unfollow style would be more meaningful: 
![image](https://github.com/open-sauced/insights/assets/18273833/271b30fa-3dbe-4b5c-a295-00cc57668332)

**Comment by ThePiyushAggarwal** [comment]
May I please work on this issue?

What I understand I have to do.
- I will be changing the text "Following" to "Unfollow" with some danger color referencing to Figma.
- I need to change the dropdown to stay open for the time the API to unfollow is in progress. I can only do this if the component supports this already. Otherwise, I might need to create another issue for giving this dropdown this feature.

**Comment by ThePiyushAggarwal** [comment]
[opensauced-follow-unfollow-button.webm](https://github.com/open-sauced/app/assets/27003616/2abb26f4-f495-405c-9f48-ed0577878915)

I am able to do this. Shall I raise a PR? Do you have any suggestions?

I wasn't able to implement my suggestions.

**Comment by takanome-dev** [comment]
> I am able to do this. Shall I raise a PR? Do you have any suggestions?

@ThePiyushAggarwal yes, open a pr
