### ISSUE TITLE
Bug: repos table in small screens does not show select.

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/app#1477]
### Describe the bug

Bug: repos table in small screens does not show select.
![image](https://github.com/open-sauced/insights/assets/18273833/0e7bf655-24d3-4ef2-9f92-4674f006d201)

### Steps to reproduce

1. https://insights.opensauced.pizza/javascript/repositories/filter/recent
2. make screen small
3. see that we have no select 

I am expecting to see the select:
![image](https://github.com/open-sauced/insights/assets/18273833/dd27f19c-1f52-4500-a302-55a5ce17d34b)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by RitaDee** [comment]
I will fix this.

.take
