### ISSUE TITLE
Feature: add languages filters for the user profile

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/app#1498]
### Type of feature

🍕 Feature

### Current behavior

Thinking from a recruiter point of view, how can I know what did this person do with JS code or react code? 

Right now, the highlights does not show a filter or language tag in the user profile or the highlight itself, I think it would be great to add that. 

https://insights.opensauced.pizza/user/a0m0rajab/highlights

### Suggested solution

We can get the langauges written from the Github project and ask the user about that, so they can add it, plus we can add some additional soft skills related topics like: technical writing,  documentation etc. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
Lol when you said languages @a0m0rajab, I thought you meant having a translation feature for non-English-speaking users.

**Comment by CBID2** [comment]
When you said languages @a0m0rajab, I thought you meant having a translation feature for non-English-speaking users.

**Comment by brandonroberts** [comment]
Closing as not planned currently
