### ISSUE TITLE
Bug: flicking behavior on update insight page 

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/app#1504]
### Describe the bug

When you open update insights the added repositories will be hidden then shown, sometimes it will show the added repositories then hide them, then show them.

I think having a placeholder would be better than this behaviour. 

https://github.com/open-sauced/insights/assets/18273833/73ae0215-5092-45e5-b717-eb6967562cb3

### Steps to reproduce

1. go to insights
2. click on update an insight
3. you will see this behaviour on added repositories 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by sital002** [comment]
.take[](url)
