### ISSUE TITLE
Bug: odd emoji style on highlights on small screens

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/app#1509]
### Describe the bug

While browsing the site, I found this as odd behavior, the emojis at the bottom of the card is not aligned. 

![image](https://github.com/open-sauced/insights/assets/18273833/77395917-1756-4315-a611-66efaa77d67d)

### Steps to reproduce

1. go to highlights feed
2. go to a card with 4-5 emoji reactions
3. you will see the issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
@a0m0rajab which browser did you noticed this?

Tested in Brave Browser and looks good

![emojis-alignments](https://github.com/open-sauced/insights/assets/79809121/8f623914-5d7b-4b30-b7ac-3cd300c36baf)

**Comment by a0m0rajab** [comment]
Chrome, a thing that I forgot to write, this is happening on small screens: 
![image](https://github.com/open-sauced/insights/assets/18273833/ebd93d6c-5eaf-4033-87b7-95ec877790c2)

**Comment by Satoshi-Sh** [comment]
On it. .take

**Comment by Satoshi-Sh** [comment]
I spent lots of time on this.

The problem is the Emoji component has a hardcoded style inside.  We cannot override it.

```
<span style="width: 1em; height: 1em; margin: 0px 0.05em 0px 0.1em; vertical-align: -0.1em;">👀</span>
``` 
Here is the related discussion.
https://github.com/tommoor/react-emoji-render/issues/48#issuecomment-580934376

We might need to take another approach or make a pull request on the library. I will unassign myself for now.

**Comment by a0m0rajab** [comment]
@brandonroberts FYI: the emojis is still not aligned with the number

![image](https://github.com/open-sauced/app/assets/18273833/e52f7cee-c7e9-459d-98fa-bc5c5702cb1a)

it will be even weirder when you have double digits: 

![image](https://github.com/open-sauced/app/assets/18273833/32008ecd-de99-4be6-a03d-205f919e04f7)
