### ISSUE TITLE
bug: Long names in top contributors mess up spacing on small screens.

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#1518]
bug: Long names in top contributors mess up spacing on small screens.

I noticed a weird side effect. I did see this get reported elsewhere. OK to have it addressed on another PR

My suggestion is to add truncation when the width is adjusted.

![Screen Shot 2023-08-07 at 4 46 56 PM](https://github.com/open-sauced/insights/assets/5713670/5f9a7059-e03d-4086-b015-20e2d03e674d)

_Originally posted by @bdougie in https://github.com/open-sauced/insights/issues/1516#issuecomment-1668759551_

**Comment by babblebey** [comment]
Hey @RitaDee, the issue has been raised here.

We discovered this during our pair session yesterday remember!? 🤓

**Comment by RitaDee** [comment]
Hello @babblebey, yes, we did notice that yesterday.

@bdougie, is it okay if I make the changes on this branch?
