### ISSUE TITLE
refactor: remove anti-pattern from the repo

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/app#1522]
We spent a lot of time rewiring the hot repo after leaning into hardcoding pixels in tailwind. We may want to avoid this anti-pattern 

https://github.com/open-sauced/hot/pull/337

_Originally posted by @bdougie in https://github.com/open-sauced/insights/pull/1500#discussion_r1287280902_

**Comment by a0m0rajab** [comment]
to search this technical debt in VsCode, you need to enable the RegEx search and use the next regex: `^.*?-\[[^\d]*(\d+)[^\d]*\].*$` This will make it easier to find them, right now we have 60 files.  I think it would be better to fix each file in isolation from others and have a different PR for it. Otherwise, we might break the design. 

![image](https://github.com/open-sauced/insights/assets/18273833/16a73283-da4e-454d-8f91-4f74311a4ac4)

**Comment by RitaDee** [comment]
I would like to work on this.

.take

**Comment by a0m0rajab** [comment]
Just a quick suggestion for this, there is a lot of files effected by this, you can go slowly with small PRs and have this as tracker this way it would make the tests easier and more stable. (instead of changing 60 files at once, try to go with logic based files)

**Comment by RitaDee** [comment]
Noted @a0m0rajab
