### ISSUE TITLE
Feature: add snapshot testing

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/app#1527]
### Type of feature

🍕 Feature

### Current behavior

right now the tests we have are for functions (I hope) and we have nothing to test the desing itself, some minor changes in the tailwind can break the whole site. 

### Suggested solution

I am suggesting to use: Snapshot Testing
so that we can ensure that the design does not break with minor things. Relying on human behavior's is not working always.

https://jestjs.io/docs/snapshot-testing

### Additional context

Related https://github.com/open-sauced/insights/issues/1526
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
We switched to Vitest but will revisit this
