### ISSUE TITLE
Bug: Calendar cut off when adding highlight, moving up and down when editing highlight

### ISSUE THREAD

**Issue by adiati98** [open-sauced/app#1528]
#### Select date on calendar when adding highlight

I wanted to select a back date when I added a highlight but the calendar is cut off. So I couldn't select the target date (see gif attached).

![select date open sauced](https://github.com/open-sauced/insights/assets/45172775/7acad6d0-1ef2-4a17-851c-6e9fe24c874f)

#### Select date on calendar when editing highlight

However, the calendar doesn't cut off when I edited the date of an existing highlight. Although the position of the calendar is moving up and down whenever I click the previous button (see gif attached).

![edit date open sauced](https://github.com/open-sauced/insights/assets/45172775/9e5df76b-fe97-4429-8fe8-ab69f426e841)

#### Select date on calendar when adding highlight

1. Go to Highlights tab.
2. Click the input "Post a highlight to show your work!".
3. Click the calendar icon.
4. Click back arrow to go to previous month. 
5. The calendar cut off.

#### Select date on calendar when editing highlight

1. Click the three dots icon and select the edit.
2. Click the calendar icon.
3. Click back arrow t go to previous months.
4. The calendar moving up and down depending on the number of rows in the month. 

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
cc @adiati98, it seems like this has been fixed. Can you confirm please?

**Comment by adiati98** [comment]
@takanome-dev I've checked it just now. It has been fixed! 😄
I'll close this issue. Thank you!
