### ISSUE TITLE
design: [pricing page] add context on future features

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#1548]
Idea: 
Make users that are thinking about signing up excited about new features. 

Right now our pricing doesn't match our value add, so until we get there we need to get people excited about what's coming.

**Comment by gcho91** [comment]
What about a dedicated feature list for the different plans, or just a page specifically for "Upcoming Features"? The way that pricing 3-col CTA is right now, it looks like it's optimizing for clicks to the get started page

**Comment by bdougie** [comment]
> What about a dedicated feature list for the different plans, or just a page specifically for "Upcoming Features"? The way that pricing 3-col CTA is right now, it looks like it's optimizing for clicks to the get started page

@gcho91 do you have any examples of this somewhere?

**Comment by a0m0rajab** [comment]
I think an opt-in for a specific features can help, where you can get the users to opt in for what features they would like to be notified with and they will enter a waitlist to get an update about that feature. This might help to prioritize features based on the numbers of people who opted in to it.

**Comment by gcho91** [comment]
Here are some examples of how "upcoming features" are listed on website:
![image](https://github.com/open-sauced/app/assets/19658964/ef6b134b-497d-4f88-baef-9aebf23f6582)
![image](https://github.com/open-sauced/app/assets/19658964/ffb1ac74-3263-426a-aaca-fcf2f301e34c)
![image](https://github.com/open-sauced/app/assets/19658964/d31723e5-6a15-46d3-802f-35f2c07c77fd)
![image](https://github.com/open-sauced/app/assets/19658964/ca2267e8-7c8c-4ef2-82e4-ca52de9df313)

**Comment by brandonroberts** [comment]
We will open a new issue here when actionable
