### ISSUE TITLE
Fix: remove extra spaces on mobile in the hub pages 

### ISSUE THREAD

**Issue by takanome-dev** [open-sauced/app#1573]
### Type of feature

📦 Chore

### Current behavior

| | |
| ------ | ------ |
| ![explore-extra-space](https://github.com/open-sauced/insights/assets/79809121/546be8e5-e748-4571-9941-46493d60321d) | ![insights-extra-space](https://github.com/open-sauced/insights/assets/79809121/13e78ac4-851a-4da2-959a-8443ebf9b335) |
| ![new-insights-extra-space](https://github.com/open-sauced/insights/assets/79809121/eda15726-196b-4c2b-b209-e44211c3ec14) | ![accept-extra-space](https://github.com/open-sauced/insights/assets/79809121/1073e496-bcc8-4821-baba-7ab5995d9a3f)

### Suggested solution

Remove extra spaces on mobile.

## Affected pages
- `/hub/insights`
- `/hub/insights/new`
- `/hub/insights/[insightId]/edit`
- `/hub/insights/[insightId]/accept`

All of those pages are wrapped by `HubLayout`. Which means that the changes should only be made in the `HubLayout.tsx` 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by RitaDee** [comment]
.take

**Comment by RitaDee** [comment]
Hello @takanome-dev, I tried reproducing this on my machine, but it appears good. Can you please confirm again?

<img width="470" alt="image" src="https://github.com/open-sauced/app/assets/106407013/983c8f62-1221-4a0a-a4cf-c0a79edfe213">

**Comment by takanome-dev** [comment]
Hey @RitaDee, sorry for the late response. I can see that it looks good on beta. Thanks for taking the time to try it out
