### ISSUE TITLE
Bug: overflows in insights page on md screen size

### ISSUE THREAD

**Issue by takanome-dev** [open-sauced/app#1574]
### Describe the bug

![insights-page-responsive](https://github.com/open-sauced/insights/assets/79809121/67dc6c0c-06c6-4e29-9251-5cee64e9327c)

### Steps to reproduce

1. Visit your insights page
2. Switch to tablet view (768px)

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by himanshumalviya15** [comment]
What should be the design of the page @takanome-dev , where should I placed edit button, go to insight page

![image](https://github.com/open-sauced/insights/assets/76220055/98cd7e51-e38f-436b-85fc-9cf07995350a)

**Comment by takanome-dev** [comment]
Honestly I don't know :sweat_smile: I would try out different layout to see what looks good. Feel free to play with it and propose a solution.

**Comment by OpherM** [comment]
Is this issue still open? if it is, can I work on it?

**Comment by dev-phantom** [comment]
> Is this issue still open? if it is, can I work on it?

yea feel free to use the `.take` to auto assign your self to this

**Comment by RitaDee** [comment]
.take

**Comment by RitaDee** [comment]
I will be taking this on.

.take
