### ISSUE TITLE
Bug: Non stop flickering on Highlights page after using filters

### ISSUE THREAD

**Issue by ThePiyushAggarwal** [open-sauced/app#1576]
### Describe the bug

Endless flickering issue on highlights page

[highlights-issue.webm](https://github.com/open-sauced/insights/assets/27003616/aea650fc-0de3-4723-a012-dabb8732ab99)

### Steps to reproduce

1. This happens only when you are following zero people.
1. Go to Highlights/Feed page.
1. Click on a Repository filter on the right hand side.
1. Click on Following tab.
1. Go back to the Home tab.
1. Now you should be able to see endless flickering screen.

### Browsers

Chrome

### Additional context (Is this in dev or production?)

dev and production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by ThePiyushAggarwal** [comment]
May I please work on this issue?

**Comment by bdougie** [comment]
Please review the [CONTIBUTING.md](https://github.com/open-sauced/.github/blob/HEAD/CONTRIBUTING.md) for info on how to assign yourself to the issue.

**Comment by ThePiyushAggarwal** [comment]
.take
