### ISSUE TITLE
Feature: Show top contributors that I am not following

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#1593]
### Type of feature

🍕 Feature

### Current behavior

This top contributors feature shows the same contributors every time. I'd love to make the list more dynamic and encourage the logged-in user to follow new users. Until the active users increase, we should attempt some of my suggestions below.

![Screen Shot 2023-08-22 at 4 29 58 PM](https://github.com/open-sauced/app/assets/5713670/e6b1b42b-9b51-46a4-b061-a82e128b6127)

### Suggested solution

1. Check the logged-in user's following and remove individuals they are already following.
2. OpenSauced employees dominate the list. We need to exclude those folks as well.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by OgDev-01** [comment]
I totally agree with the first suggestion. Solving the first also means solving the second, you can't follow a user twice unless you unfollow them. So my proposal here is we exclude followed users from the API before sending them to the front-end. It would be fairer to approach this feature from the API side of things.

**Comment by OgDev-01** [comment]
Update: We will have to update the fetch call to include the logged-in user-id once https://github.com/open-sauced/api/pull/275 is merged
