### ISSUE TITLE
Feature: "Most Active Contributors" horizontally stacked bar chart prototype

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#1599]
### Type of feature

🍕 Feature

### Current behavior

-

### Suggested solution

Create a prototype component of the following bar chart, with no real data yet, just dummy data.

[Link to Figma frame](https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/Design-Lab?type=design&node-id=9982-48438&mode=design&t=u3Hs2tJqicSJzGQI-4)

<img src="https://github.com/open-sauced/app/assets/27322879/a63db07c-cc4a-4e6c-aa6b-3b7faa87bb67" width="60%" height="auto">

### Filter values

**Time range filter**
- last 7 days
- last 30 days
- last 3 months

**Contributors filter**
- All contributors
- Active contributors
- New contributors
- Churned contributors

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by foxyblocks** [comment]
@isabensusan what are the options going to be for the sorting dropdown on the right, other than "Most Active"
