### ISSUE TITLE
Feature: "Contributions by type of contributor" line chart prototype

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#1601]
### Type of feature

🍕 Feature

### Current behavior

N/A

### Suggested solution

Create a prototype component of the following line chart, with no real data yet, just dummy data.

### [Figma Frame](https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/Design-Lab?type=design&node-id=10093-3518&mode=design&t=u3Hs2tJqicSJzGQI-4)

<img src="https://github.com/open-sauced/app/assets/27322879/d2a91d87-c750-4f0a-ae65-cf0314dbcb63" width="60%" />

### Filter values

**Time range filter**
- last 7 days
- last 30 days
- last 3 months

**Contributors filter**
- All contributors
- Active contributors
- New contributors
- Churned contributors

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by isabensusan** [comment]
@nickytonline Tagging you to see if we can get this chart going using the endpoints from this PR https://github.com/open-sauced/api/pull/320

**Comment by nickytonline** [comment]
@isabensusan, is the contributor dropdown necessary? We're showing all types in the graph.
