### ISSUE TITLE
Feature: "Most used languages" prototype chart

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#1602]
### Type of feature

🍕 Feature

### Current behavior

N/A

### Suggested solution

Create a prototype component of the following bar chart, with no real data yet, just dummy data.

### [Figma frame](https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/Design-Lab?type=design&node-id=9663-24630&mode=design&t=u3Hs2tJqicSJzGQI-4)

<img width="60%" src="https://github.com/open-sauced/app/assets/27322879/a51fec4b-f76d-40da-ab8b-576ec52c4c2c" />

### Filter values

**Time range filter**
- last 7 days
- last 30 days
- last 3 months

**Contributors filter**
- All contributors
- Active contributors
- New contributors
- Churned contributors

### Context 
This chart will be part of the "Contributor Profile" tab in the Lists feature dashboards. 
<img width="60%" src="https://github.com/open-sauced/app/assets/27322879/a9f1f4cf-1f27-4fb0-8dc4-632f76203c1c" />

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by isabensusan** [comment]
@nickytonline re-starting conversation for this chart too, can you take a look?

**Comment by nickytonline** [comment]
Is this still going under the Contributor Profile page (non-existent page atm) @isabensusan or should it go under the Activity page for now?

**Comment by isabensusan** [comment]
let's add it to the Activity page for now. When you get a PR preview we can take a look at the tab's layout to make sure we get it to look good :)

**Comment by nickytonline** [comment]
Looks like there is no API endpoint for this yet @isabensusan. I'll create it, but just wondering if this component only shows top 5 languages?

**Comment by nickytonline** [comment]
The component is built, so going to go ahead and close this as that's what the issue initially asked for. Next up is adding it to the list activity page.
