### ISSUE TITLE
Bug: Profile page - Hidden link to feed out of nowhere

### ISSUE THREAD

**Issue by ThePiyushAggarwal** [open-sauced/app#1618]
### Describe the bug

Checkout the highlighted area in the image.

![profile-issue](https://github.com/open-sauced/app/assets/27003616/c3e2f75c-7dd8-43d2-8713-2fc399fa5b4c)

If I click there, I am taken to the feed page with the highlight opening in a modal.

![image](https://github.com/open-sauced/app/assets/27003616/03901a87-8649-40dd-9068-34c472b345d1)

### Steps to reproduce

1. Go to Profile page
1. Click on the highlighted area in the first image given in the issue.
1. You will be redirected to /feed/[highlight-id]

### Browsers

Chrome

### Additional context (Is this in dev or production?)

dev and production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by ThePiyushAggarwal** [comment]
I can take up this issue. I just need confirmation if this was intended to be a link to somewhere? It just got some messed up CSS?

**Comment by bdougie** [comment]
This area is not meant to be a link. Feel free to open a pr and fix.

**Comment by ThePiyushAggarwal** [comment]
.take

**Comment by ThePiyushAggarwal** [comment]
I see that the link is actually attached to the time elapsed above. Shall I remove that as well? I can keep the link and fix the issue as well.

**Comment by bdougie** [comment]
For now, that is the expected behavior. Linking to the highlight, which is the solution while there is no highlights page.
