### ISSUE TITLE
Feature: refactor `date-utils.ts` function `calcDistanceFromToday` 

### ISSUE THREAD

**Issue by ThePiyushAggarwal** [open-sauced/app#1619]
### Type of feature

🧑‍💻 Refactor

### Current behavior

I think this particular function should be refactored. It has checks for two cases but it is actually doing the same thing at the end.

```ts
export const calcDistanceFromToday = (endDate: Date) => {
  const daysFromNow = calcDaysFromToday(endDate);

  if (daysFromNow >= 365) {
    return `${getRelativeDays(calcDaysFromToday(endDate))}`;
  }

  if (daysFromNow > 30 && daysFromNow < 365) {
    return `${getRelativeDays(calcDaysFromToday(endDate))}`;
  }

  return `${getRelativeDays(daysFromNow)}`;
};
```

### Suggested solution

```ts
export const calcDistanceFromToday = (endDate: Date) => {
  const daysFromNow = calcDaysFromToday(endDate);

  return `${getRelativeDays(daysFromNow)}`;
};
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by ThePiyushAggarwal** [comment]
I would like to take this if approved.

**Comment by babblebey** [comment]
Look true to me 🤔

I'd suggest a refactor too, but kindly ensure the tests written against this function passes.

Also, you do a code search to find all the components that integrates this function to ensure that they don't regress after your operation.

**Comment by a0m0rajab** [comment]
@ThePiyushAggarwal feel free to open a PR and move the discussion to it, the PR review will be the approve (it will save time as well from going back and forth in the issue) imo

**Comment by ThePiyushAggarwal** [comment]
.take
