### ISSUE TITLE
Bug: Create insights - PR showing as zero for all added insights in form

### ISSUE THREAD

**Issue by ThePiyushAggarwal** [open-sauced/app#1620]
### Describe the bug

Number of PRs for any given repository is shown as zero in the selected repo area in Create Insights page.

[create-insights-pr-zero-issue.webm](https://github.com/open-sauced/app/assets/27003616/579f38a0-8073-45e4-9018-cae068e2b05f)

## Create Insights page
1. Go https://insights.opensauced.pizza/hub/insights/new
1. Click on "Add to Page" buttons
1. On the right hand side, the repo is added but the PR number does not match. (matches if 0)

## Edit Insights page
1. Edit any insight
1. Remove an existing insight which has a number of PRs
1. The removed Repo goes to the list below but does not have the right amount of PRs anymore.

### Browsers

Chrome

### Additional context (Is this in dev or production?)

dev and production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by ThePiyushAggarwal** [comment]
.take

**Comment by ThePiyushAggarwal** [comment]
Shall I work on this issue?

**Comment by takanome-dev** [comment]
Please do :slightly_smiling_face:

**Comment by ThePiyushAggarwal** [comment]
I am going to be busy for a week or two. I have unassigned myself for now. Will pick it up when I am able to.

**Comment by RitaDee** [comment]
I will .take this.

**Comment by jpmcb** [comment]
Hmmm yes, something's not right with the `prs/insights` endpoint or our data. For example, using spf13/cobra (where I know several prs have been opened within the last few weeks):

```sh
curl -X 'GET' \
  'https://api.opensauced.pizza/v1/prs/insights?page=1&limit=10&range=30&repo=spf13%2Fcobra' \
  -H 'accept: application/json'
```

I get:
```json
[
  {
    "day": "2023-08-01",
    "interval": 30,
    "all_prs": 0,
    "accepted_prs": 0,
    "spam_prs": 0
  },
  {
    "day": "2023-07-02",
    "interval": 60,
    "all_prs": 0,
    "accepted_prs": 0,
    "spam_prs": 0
  }
]
```

This will require we look deeply at what's going on with our backfill services and API to ensure data quality.

**Comment by bdougie** [comment]
This was fixed in a change to our ETL service, please confirm @ThePiyushAggarwal 

https://github.com/open-sauced/etl/pull/80
