### ISSUE TITLE
Feat: signIn issue on codespace 

### ISSUE THREAD

**Issue by dev-phantom** [open-sauced/app#1624]
> You are welcome! Thank you for your time to work on it!

please i am having this issue anytime i am on github codespace and in try to signIn locally i get redirected to https://beta.insights.opensauced.pizza/hub/insights and any change i make locally wont be affected in the https://beta.insights.opensauced.pizza/hub/insights
how do i resolve this?

https://github.com/open-sauced/app/assets/72051159/1d68e945-e107-4e55-ac42-ecbe7e67fc5f

_Originally posted by @dev-phantom in https://github.com/open-sauced/app/issues/1505#issuecomment-1694408353_

**Comment by bdougie** [comment]
> please i am having this issue anytime i am on github codespace and in try to signIn locally i get redirected to

This is because the Codespaces dev domain is not allow listed. 

You will need to set up your own auth using the example in the open-sauced/api repo and run that and this repo locally.

**Comment by AyoMoses1** [comment]
I will love to .take this

**Comment by nickytonline** [comment]
> You will need to set up your own auth using the example in the open-sauced/api repo and run that and this repo locally.

Closing as this is not something we'll implement.

**Comment by dev-phantom** [comment]
> > You will need to set up your own auth using the example in the open-sauced/api repo and run that and this repo locally.
> 
> Closing as this is not something we'll implement.
@nickytonline 
I think this should have been closed as "not planned" instead of "completed" as this issue was not completed

**Comment by dev-phantom** [comment]
> @dev-phantom any tips on how to run it on local? I still can't manage to run the `api` codebase on local!

None

Ask @bdougie
