### ISSUE TITLE
Bug: font size on the Highlights page navigation tabs is too big

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#1629]
### Describe the bug

The font size on the "Home" and "Following" tabs in the Highlights page is too big.

<img width="703" alt="image" src="https://github.com/open-sauced/app/assets/27322879/d70f8da4-28de-45f4-a12a-c896cb2248e4">

&nbsp;

<img width="703" alt="image" src="https://github.com/open-sauced/app/assets/27322879/11c94ddb-b59e-4014-bcb5-7aa2871e5629">
&nbsp;

&nbsp;

### Can we make the sizing match the tabs in the insight pages?

&nbsp;
<img width="703" alt="image" src="https://github.com/open-sauced/app/assets/27322879/c895fc92-e0e0-4a4f-a4f3-fc4921b9be43">

### Steps to reproduce

1. Go to "Highlights"
2. Tabs are right there

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
This was fixed for the user's profile here: https://github.com/open-sauced/app/pull/1413

and looks to also need fixing in the highlights page cc @OgDev-01

**Comment by RitaDee** [comment]
.take
