### ISSUE TITLE
design: no error warning or message indicating collaboration req min

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#1634]
### Describe the bug

When you create a collaboration request, you can submit at any point. However, if you submit in under 20 characters, you get an error message. 

My suggestion, is a message in the collaboration box that indicates the minimum length and potentially disabling submit until you hit the min.

![image](https://github.com/open-sauced/app/assets/34313413/7f4c08e9-22c2-4ef7-9af6-bfe1410b0268)

### Steps to reproduce

1.  Go to https://insights.opensauced.pizza/user/nickytonline/
2. Hit collaborate option. 
3. type "hey"
4. Submit and see the error

### Browsers

Chrome

### Additional context (Is this in dev or production?)

production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by babblebey** [comment]
I will .take and work on this.

**Comment by NsdHSO** [comment]
@babblebey  @BekahHW  Wouldn't it be more effective to show him how many characters he entered?? and not to display the text directly in red??? because the user did nothing wrong. He just started writing. Only if it focuses out. Then it should be red.

**Comment by babblebey** [comment]
> Wouldn't it be more effective to show him how many characters he entered?? and not to display the text directly in red??? because the user did nothing wrong. He just started writing. Only if it focuses out. Then it should be red.

I agree, I'll look into this ✌🏾
