### ISSUE TITLE
Test: update `OpenUserProfile` e2e test 

### ISSUE THREAD

**Issue by babblebey** [open-sauced/app#1641]
I will leave this comment here as a note to update the e2e test once the PR (#1631) merges. 

https://github.com/open-sauced/app/blob/64aa404e30b0cdbe832136f3044f4e7126386b81/e2e-tests/OpenUserProfile.spec.ts

_Originally posted by @babblebey in https://github.com/open-sauced/app/pull/1631#pullrequestreview-1601063551_

**Comment by babblebey** [comment]
.take

**Comment by brandonroberts** [comment]
We are going to revisit and do some new e2e tests
