### ISSUE TITLE
Bug: User profile page throws Application error (cannot read property of undefined: reading map)

### ISSUE THREAD

**Issue by diivi** [open-sauced/app#1644]
### Describe the bug

![image](https://github.com/open-sauced/app/assets/41837037/45df9dfc-a8c0-4685-bba1-dd300df4ae46)

### Steps to reproduce

1. Go to  https://insights.opensauced.pizza/user/diivi

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
I'm not seeing the issue even in an incognito browser. Can you hard refresh and see if the issue is still there?

**Comment by jpmcb** [comment]
<img width="1421" alt="Screenshot 2023-08-31 at 2 26 04 PM" src="https://github.com/open-sauced/app/assets/23109390/3e341e70-1cae-4737-9bbb-aad600423be3">

I just saw this throw for me in Chrome. But it works fine in Firefox.

**Comment by jpmcb** [comment]
I do see this 401 being thrown ... is it trying to read off this user insight PRs but since it's unauthenticated, it throws the error not being able to read the data?

<img width="1418" alt="Screenshot 2023-08-31 at 2 27 43 PM" src="https://github.com/open-sauced/app/assets/23109390/1249402b-fdbc-4fc1-b405-bf7933f27a12">

**Comment by nickytonline** [comment]
If I open @bdougie's profile while I'm logged in, I get an undefined array that throws the error.

![CleanShot 2023-08-31 at 22 34 38](https://github.com/open-sauced/app/assets/833231/769cce3b-e7b6-4232-a7e8-c0edf599f72e)

In prod, I traced it to a toast messages array being undefined. 

![image](https://github.com/open-sauced/app/assets/833231/e5ab4be0-f05e-427b-a2ef-f5c13d131666)

If I open an incognito window though, the page loads fine but there are errors including the 401 error @jpmcb mentions.

![CleanShot 2023-08-31 at 22 35 53](https://github.com/open-sauced/app/assets/833231/7afdb223-663b-46ad-834f-ddbd7eb72e9a)

I think in the logged out scenario, the 401 error masks the error (a hunch), and when logged in that particular array is undefined and we get the error.

This is potentially a few issues to hash out.
