### ISSUE TITLE
Suggestion: "insights" tab should indicate onboarding needs to be done

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#1645]
### Describe the bug

When I go to `beta.insights.opensauced.pizza` I notice that the "Insights" tab is missing:

<img width="620" alt="Screenshot 2023-08-31 at 2 07 40 PM" src="https://github.com/open-sauced/app/assets/23109390/d914d0c8-dd78-4111-b8d9-0d2b0ba1df4e">

Same thing on Chrome.

I even tried checking out `v1.62.0` and `v1.61.0` and running it locally to see if it's a recent release that broke. But those are both fine locally.

But it looks totally fine in prod 🤔 

 
<img width="647" alt="Screenshot 2023-08-31 at 2 22 36 PM" src="https://github.com/open-sauced/app/assets/23109390/b599bb44-94c8-4a70-8e77-4b1e331f1172">

I'm not seeing anything obvious in the console logs that would point me to what's going on.

### Steps to reproduce

? ? ?

### Browsers

Chrome, Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
Seems that after completing the onboarding experience, I get the insights tab in beta:

Before the onboarding is complete

![Screenshot 2023-09-05 at 11 59 03 AM](https://github.com/open-sauced/app/assets/23109390/f99abc3c-e56c-4318-bdd9-57120d7ff725)

After the onboarding is complete

![Screenshot 2023-09-05 at 11 59 25 AM](https://github.com/open-sauced/app/assets/23109390/87910d35-f662-42f7-a0d4-c7edb42a9614)

---

Seems abit bizarre that we'd block the entire user experience of looking at insights without the onboarding being done. Is this the expected behavior?

**Comment by bdougie** [comment]
> Seems abit bizarre that we'd block the entire user experience of looking at insights without the onboarding being done. Is this the expected behavior?

Agreed. I think the original thought was if we did not have basic information like interests then we could not recommend repos for insights, but we never realized that path. 

With this issue https://github.com/open-sauced/app/issues/1673 in the works, I'd suggest all features should be viewable but force a login if the insight page needs to be added. 

cc for context: @isabensusan & @open-sauced/engineering

**Comment by jpmcb** [comment]
+1 - my suggestion would be that a user can "see" the insights page, but there should be some clear indication that if they want to fully take advantage of it, they need to complete onboarding. if that's too many clicks to go from zero to hero (in the product scene) then maybe we drop that requirement like Brian mentioned.

**Comment by bdougie** [comment]
I am moving this to high priority. Any new user will not be able to see the List feature without completing onboarding.

We should remove that flag and show this feature. 

<img width="1728" alt="Screen Shot 2023-09-16 at 8 05 44 AM" src="https://github.com/open-sauced/app/assets/5713670/357aee03-a316-4f2a-9c9a-2871fec4b3bf">

**Comment by jpmcb** [comment]
This has seemed to degrade:

<img width="1509" alt="Screenshot 2023-10-05 at 9 21 58 AM" src="https://github.com/open-sauced/app/assets/23109390/fc015695-6cb3-4c6a-ac83-05acc4b494c7">

With my test user (who has not done the onboarding), on beta, I now cannot see the insights page tab. Did we recently hide this or change this flow?

**Comment by OgDev-01** [comment]
Hmm 🤔. I'll check

**Comment by bdougie** [comment]
We should really moving away hiding links all together and start leveraging the pricing and login elements @isabensusan 

Hiding the insights link was a solution to a short term problem.
