### ISSUE TITLE
Feature: User searchbar

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#1647]
### Type of feature

🍕 Feature

### Current behavior

N/A

### Context
This is a searchbar to allow users to find users on the platform. This is a first iteration of what we want to build into a command palette, the idea is to start with only the ability to search users and in the future add repo and insights/lists page search, highlights and more.

### [Figma Design Link](https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/Design-Lab?type=design&node-id=10369-17266&mode=design&t=oE7SBjhBJB8ttP6D-4)
**Design Lab** file > **Design: Search** page

## Functional requirements
Users will be able to type a username and get results for other users on OpenSauced
- Results should contain users that have connected and haven't connected their Github accounts. If they are in our database they should appear
- Max amount of results displayed is 3. The logic behind this is that as we turn it into a command palette we will add more features like searching for repos, so we want to keep the amount of results of each search category to a low number as to not clutter the ui.
- Users can press both the ⌘K command and the  /  key to trigger the searchbar (both are standard patterns for searchbars)
- Users can navigate the searchbar results using only the up/down arrows and the enter key to select a user profile.

### Default state
Show the search bar in the nav bar, next to the user avatar.

<img width="1126" alt="image" src="https://github.com/open-sauced/app/assets/27322879/860415e4-a9bf-4663-8032-5920a010a4ea">

### Active state
When active, a new component will show up on top of the UI and the background will be slightly blurred.
- If the user hasn't typed anything, then show a "Type 3 characters or more to start searching" message at the bottom. Message will be displayed until the user types 3 minimum characters.
<img width="1133" alt="image" src="https://github.com/open-sauced/app/assets/27322879/1cfcd5d7-a5bc-4afa-b74e-63837d6d2899">

### Exact Match
If user inputs a string that exactly matches a username, only show that username

<img width="849" alt="image" src="https://github.com/open-sauced/app/assets/27322879/9a5c11a2-fd62-4f2b-9d2b-345243ff7d77">

### Partial Match
If user inputs a string that partially matches multiple usernames, show up to 3 results that match the search (if there's only 2 results that match, show only 2 of course). 

<img width="793" alt="image" src="https://github.com/open-sauced/app/assets/27322879/06bab2be-f78c-42d2-b206-8661776d04fb">

### Exact + Partial Matches
If the user types a username and there’s an exact match, but there’s also partial matches:
Show exact match on the top and then up to 2 partial match results --> 3 results total

<img width="786" alt="image" src="https://github.com/open-sauced/app/assets/27322879/e45716e7-a48a-4d49-ad95-18fa9ec1f2e4">

### No match
<img width="589" alt="image" src="https://github.com/open-sauced/app/assets/27322879/54d76e51-27d6-42b1-9a41-a9be02c2fd69">

## Component

The searchbar component that will go on the nav bar is a slight variation of the existing Search component [link](https://design-insights.netlify.app/?path=/docs/design-system-atoms-search--docs) with an added badge showing the shortcut to trigger the searchbar (⌘K). 

The active searchbar component is meant to have the same look, but bigger.

<img width="1071" alt="image" src="https://github.com/open-sauced/app/assets/27322879/b4ab0862-5faf-44a8-b48b-9911c335c7d0">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
I think this is great and would love to see the initial components added to the design system. You did a great job matching our existing design system. 

## future 
Search in general is not great in our app today and I see repository search being an easy addition. I also think we can add more complex searching in a future iteration. Perhaps similar to github, we could miro github's search keywords i.e. `user: ~bdo language: typescript`for users with bdo in the username and have typescript in their contributions. 

## technical approach

Today our search for repos uses github and not our data. @brandonroberts @foxyblocks or @OgDev-01 any thoughts how to approach this technically?

Algolia is expensive, but easily implemented, however we do have [qdrant](https://qdrant.tech/) in  the https://github.com/open-sauced/repo-query and can use that for more advance semantic or keyword searching.

**Comment by jpmcb** [comment]
> Today our search for repos uses github and not our data. @brandonroberts @jpmcb @foxyblocks @OgDev-01 any thoughts how to approach this technically?

We don't currently have a `/v1/users/search` endpoint in the API. But it would be pretty easy to implement with the "ilike" operator. This would probably end up being some `findUsersWithFilters` on the user's service in the API:

For example
```sql
select login from users
where login ilike '%nick%'
limit 3;
```
would result in something like:
```
nick
mrnick
examplenickles
```

We get this out of the box today and does pretty basic matching.

Going any deeper and doing anything more "intelligent" would require some vector tables to be setup.

Thankfully, it looks like the `pgvector` extension is already supported in Digital Ocean: https://docs.digitalocean.com/products/databases/postgresql/details/supported-extensions/ and the installation would be really really simple. Granted, we'd want to explore and research how it works before going too deep with that as the solution, but my gut is that we shouldn't fracture the data too much (since it all already lives in postgres). Qdrant is great, but we get alot of velocity from having things in one stop shops. Creating some sort of ACID system that takes data from our postgres db, enters it into qdrant, sets the vectors up correctly, and surfaces it for semantic search is alot of software to build/maintain/lease for something we might just get out of the box with our current setup.

**Comment by babblebey** [comment]
Great stuff @isabensusan 

This is an important step in the right direction for the request in the discussion here - https://github.com/orgs/open-sauced/discussions/18

> I think this is great and would love to see the initial components added to the design system. You did a great job matching our existing design system.

@bdougie, can I patch a PR for this?

**Comment by bdougie** [comment]
Yes go for it

**Comment by babblebey** [comment]
.take
