### ISSUE TITLE
Bug: overlay of buttons on other items

### ISSUE THREAD

**Issue by dev-phantom** [open-sauced/app#1654]
### Describe the bug

Currently the chatbot button and the new highlight button are displaying over some items like the footer link and the discord icon in the footer
![Screenshot_20230901-222539](https://github.com/open-sauced/app/assets/72051159/8b181975-90a2-43d9-a778-4ed9ef929996)

### Steps to reproduce

1. Go to your user profile on opensauced
2. Scroll to the bottom where the footer is 
3. See error 

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by himanshumalviya15** [comment]
.take

**Comment by himanshumalviya15** [comment]
@dev-phantom where should I placed those two buttons can we have a design for mobile

**Comment by dev-phantom** [comment]
I think the approach used here
https://github.com/open-sauced/app/pull/1420
Was better try moving the links and the icon to the left
