### ISSUE TITLE
Bug: Persistent Yellow Circle on Notification Bell After Viewing Notifications on OpenSauced

### ISSUE THREAD

**Issue by dev-phantom** [open-sauced/app#1655]
### Describe the bug

When using OpenSauced, I've noticed that a yellow circle appears on the notification bell to indicate new notifications. However, after I view these notifications, the yellow circle remains there, which can be confusing and misleading for users.

**Expected Behavior:**
The yellow circle should disappear from the notification bell icon once the user has viewed their notifications. This behavior is essential for a clear and intuitive user experience.

**Actual Behavior:**
The yellow circle persists even after viewing the notifications, causing confusion and making it difficult for users to know if they have new notifications or not.

**Additional Information:**
This issue affects the overall user experience on OpenSauced and could lead to missed notifications. It is recommended to resolve this issue to improve the platform's usability

![Screenshot_20230901-222539_1](https://github.com/open-sauced/app/assets/72051159/48815cd0-e54c-420c-9f7e-de4f30325c90)

### Steps to reproduce

1. Log in to your OpenSauced account.
2. Click on the notification bell icon or access the notifications.
3. Observe that a yellow circle appears to indicate new notifications.
4. Click on the notifications to view them.
5. After viewing the notifications, the yellow circle remains on the notification bell icon.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by himanshumalviya15** [comment]
@dev-phantom I wanted to resolve this, but how can I reproduce this I dont have any notifications

**Comment by dev-phantom** [comment]
> @dev-phantom I wanted to resolve this, but how can I reproduce this I dont have any notifications

Try to follow bdougie or Rita on opensauced when they post an highlight you'll get a new notification

**Comment by dev-phantom** [comment]
> @dev-phantom I wanted to resolve this, but how can I reproduce this I dont have any notifications

I just followed you 
You should have a new notification now

**Comment by dev-phantom** [comment]
Looks like this issue has been fixed
I can't reproduce this on my end 
closing this now

**Comment by dev-phantom** [comment]
Noticed this issue still persist

**Comment by RitaDee** [comment]
I will .take this.
