### ISSUE TITLE
Feature: Allow users to post blogs from (RSS) multiple platforms 

### ISSUE THREAD

**Issue by CBID2** [open-sauced/app#1656]
### Type of feature

🍕 Feature

### Current behavior

I tried posting my Hashnode blog post as a highlight but I received this message:
![A screenshot of the result after I tried to post my article from Hashnode](https://github.com/open-sauced/app/assets/105683440/96c2719f-5ef1-474e-83e8-0d44e938cf50)
This can be a turn-off for people who either don't use Dev.to or use other platforms alongside with it. 

### Suggested solution

Create some sort of code to allow blog posts from all platforms to be shared as highlights.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
A lot of the context around the decision to only allow did not make it here, but my solution is leveraging RSS directly and bing platform agnostic. This would require us build a social card fetcher that is DEV agnostic.

## current implementation

https://github.com/open-sauced/app/blob/172c61e24601fb5739f7711e6e7142864f662b92/components/molecules/DevToSocialImage/dev-to-social-img.tsx#L19

## I have a thing I made

I have some code that fetches social cards using the og lib 

https://github.com/bdougie/social-carding/blob/main/pages/api/fetchMeta.js#L1

**Comment by CBID2** [comment]
Ok that could work @bdougie

**Comment by bdougie** [comment]
> When the endpoint is ready, I will take this.

To be clear, I don't believe a new endpoint is needed. All changes can be add in this repo's lib folder.

The fetching just needs to be non DEV specific.

**Comment by CBID2** [comment]
Go ahead @RitaDee

**Comment by RitaDee** [comment]
Hello @bdougie, 

https://github.com/bdougie/social-carding/blob/main/pages/api/fetchMeta.js

Looking at the implementation, it seems as though the `open-graph` package works only on the server side. Is this correct?

I thought to implement the og lib in the Api route but the folder 'page/api" is not there.

**Comment by RitaDee** [comment]
Here is an update on my progress regarding this issue @bdougie:

I've been working on this task and have made significant progress on several fronts. I encountered some challenges when attempting to access the endpoints for Medium and Hashnode just like @diivi did with the dev.to platform. Despite my efforts, I have not been able to find a resolution. So, I will unassign myself 😞.

**Comment by babblebey** [comment]
I will .take this from here now dear @RitaDee 🤗

**Comment by RitaDee** [comment]
> I will .take this from here now dear @RitaDee 🤗

Go Ola! 🙌🏽

**Comment by aboli55558** [comment]
Oooo
