### ISSUE TITLE
Feature: Remove title from highlights

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#1657]
### Type of feature

🍕 Feature

### Current behavior

Can we remove the title?

The design intentionally remove it because of the complexity and confusion the title causes

![image](https://github.com/open-sauced/app/assets/5713670/a9f7d5e2-fac0-40ad-8dd5-95b6616bd0fe)

1. Title is not used in social cards
2. Title is not included in the character limit for posts, but has a hidden char limit
3. Title does not add value and only confusion for submissions

### Suggested solution

1. Remove the ability to add titles in the highlights form
2. Remove the title from being displayed in all highlight components.  

### Additional context

related https://github.com/open-sauced/app/pull/1646

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by RitaDee** [comment]
.take
