### ISSUE TITLE
Refactor: Move explore tabs into dedicated pages

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/app#1664]
### Type of feature

🍕 Feature

### Current behavior

Currently, on the explore page, we have four tabs/pages

- Dashboard
- Reports
- Repositories
- Contributors

These pages are all driven by dynamic routes. While this is flexible, all the code for these pages is bundled together for each page, increasing the bundle size, which causes longer load times. This also makes our routing very brittle in terms of handling actual 404 routes because the dynamic routes capture URLs that should be 404s.

### Suggested solution

- Refactor each tab into its on page in the pages folder under [filterName]
- Update/remove occurrences of `[toolName]` with page name (dashboard, reports, repositories, contributors, etc)

This allows for better bundle splitting and more specific route matching. It will allow use to reuse the structure in future features also, such as the Lists feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by RitaDee** [comment]
I will .take this on.

**Comment by brandonroberts** [comment]
Closing as resolved with the move to workspaces
