### ISSUE TITLE
Chatbot Accepts Empty Inputs Without Error

### ISSUE THREAD

**Issue by SoundaryaKoutharapu** [open-sauced/app#1676]
### Describe the bug

When using the chatbot, I've observed that it allows users to submit empty inputs without displaying an error message. 
However, if I input just a space and click the send button, it correctly shows an error message. This inconsistency in behavior can be confusing for users.

The chatbot should consistently handle empty inputs, whether they are truly empty or contain only whitespace. 
It should display an error message in both cases, providing a clear indication to the user that the input is invalid.

[6894785e-7d7b-4b99-8d4d-0124918fc410.webm](https://github.com/open-sauced/app/assets/71914071/de75b50c-0e60-4228-9d4a-7490b4b332d8)

### Steps to reproduce

1. Start the chatbot.
2. Attempt to send an empty input (e.g., just press the send button).
3. Notice that the chatbot accepts the empty input without showing an error message.
4. Now, input just a space and click the send button.
5. Observe that the chatbot correctly displays an error message.

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
The chat it is powered by https://sitegpt.ai.

It is meant to be a low effort to unblock users. I see you assigned your self to an the issues but could describe an approach to this before opening a PR?

**Comment by SoundaryaKoutharapu** [comment]
I assumed it would be a input validation. so, I assigned the issue to myself. 
apologizing for my mistake
I understand that we do not have direct access to the codebase that drives the chatbot's behavior.

**Comment by 786-aquib** [comment]
!assign

**Comment by nickytonline** [comment]
Closing because of #1971
