### ISSUE TITLE
Bug: Repository contributor data seems incorrect

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#1689]
### Describe the bug

<img width="1396" alt="Screen Shot 2023-09-07 at 4 13 37 PM" src="https://github.com/open-sauced/app/assets/5713670/91c8364d-7e42-4ac5-b364-13c07a07d773">

Looking at this new public [insight](https://insights.opensauced.pizza/pages/jossse69/619/repositories) page from @jossse69 and there seems to be some extra contributors listed. 

### Steps to reproduce

It seems like contributions list includes data from the wrong repo. 

This is the 30 day chart. 

<img width="1360" alt="Screen Shot 2023-09-07 at 4 18 39 PM" src="https://github.com/open-sauced/app/assets/5713670/4845c485-dbf8-437e-a775-ca5dba8dcd8e">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by jossse69** [comment]
oh crap

**Comment by bdougie** [comment]
These are contributors from two different golang projects.

![image](https://github.com/open-sauced/app/assets/5713670/cebbde94-fd6c-43a4-b7c1-a65542c56b22)
