### ISSUE TITLE
Example Ticket: Feature Name or User Story

### ISSUE THREAD

**Issue by justindowney** [open-sauced/app#1695]
As a "User" I want too "feature or change" so I can "what the user  is hoping to achieve"

Acceptance Criteria (AC)

- Ability to add or delete accounts
- Etc
- Etc

QA Plan

1. Launch browser
2. Login
3. Logout 
4. etc
5. etc

Version: 1.4.2 

*Any assets needed to complete the ticket are linked or attached to the ticket

**Comment by brandonroberts** [comment]
We are revising our product engineering process. Closing this for now
