### ISSUE TITLE
Bug: opening someone's profile menu locks scrollbar and "shifts" header css

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#1696]
### Describe the bug

https://github.com/open-sauced/app/assets/23109390/2e7a7deb-a973-4758-8563-72bca964e656

2 things with this bug:
1. Clicking the drop down menu (right now used only for following and unfollowing) causes the header CSS to shift over.
2. After investigating abit further, it seems that this "locks" the scrollbar (notice in the video above the scrollbar on the right disappears) and prevents any scrolling

Clicking the dropdown menu should not cause the scrollbar to disappear (or lock scrolling) and shouldn't shift the CSS where it's visible by the user.

This behavior is the same on Chrome and Firefox.

### Steps to reproduce

1. Go to someone's profile: https://insights.opensauced.pizza/user/jpmcb
2. Click the (...) dropdown menu
3. Notice the shift in CSS and lack of being able to scroll

### Browsers

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
This has to do with [radix dropdown](https://www.radix-ui.com/primitives/docs/components/dropdown-menu). This will probably need a deep dive to find out how to prevent that shift from happening

[Screencast from 09-12-2023 05:35:52 PM.webm](https://github.com/open-sauced/app/assets/79809121/0cc4abb5-f73d-4773-80f2-9e9bd9940804)

**Comment by RitaDee** [comment]
Hello @jpmcb, I cannot reproduce this on my device

https://github.com/open-sauced/app/assets/106407013/a5a4ab71-47c8-4bd9-970e-b4c7ad77ce40

**Comment by RitaDee** [comment]
It seems this is unique to a large screen monitor as regarding the shift in the header CSS.

**Comment by jpmcb** [comment]
> It seems this is unique to a large screen monitor

I don't think so: I can replicate it on a small screen in Firefox.

The CSS shifting seems to only happen on Firefox but on both Chrome and Firefox it looks like the scroll bar gets removed when that menu is opened (which I hypothesize is why the shift happens in Firefox). My anticipated userflow would be that you can still scroll even when that menu is open (Like on Twitter)

<img width="1202" alt="Screenshot 2023-09-15 at 8 21 31 AM" src="https://github.com/open-sauced/app/assets/23109390/26a06788-b913-440b-857d-4c2ea39cf5b3">

and hopefully that would fix what's going on with the CSS

**Comment by RitaDee** [comment]
> > It seems this is unique to a large screen monitor
> 
> I don't think so: I can replicate it on a small screen in Firefox.
> 
> The CSS shifting seems to only happen on Firefox but on both Chrome and Firefox it looks like the scroll bar gets removed when that menu is opened (which I hypothesize is why the shift happens in Firefox). My anticipated userflow would be that you can still scroll even when that menu is open (Like on Twitter)
> 
> <img alt="Screenshot 2023-09-15 at 8 21 31 AM" width="1202" src="https://user-images.githubusercontent.com/23109390/268278252-26a06788-b913-440b-857d-4c2ea39cf5b3.png">
> and hopefully that would fix what's going on with the CSS

I get it.

**Comment by RitaDee** [comment]
I went through the Radix doc, and the behaviour of the dropdown does disable the scroll. I will suggest we use the radix  [popover componet](https://www.radix-ui.com/primitives/docs/components/popover) to maintain the scroll onclick. If this is approved I would love to do the fix.

**Comment by OgDev-01** [comment]
> I went through the Radix doc, and the behaviour of the dropdown does disable the scroll. I will suggest we use the radix [popover componet](https://www.radix-ui.com/primitives/docs/components/popover) to maintain the scroll onclick. If this is approved I would love to do the fix.

+1 on switching to radix `Popover` component. This behaviour is also noticed in the contributors highlight card component.
https://github.com/open-sauced/app/blob/8527dc13e200fb8c8d61f981bedffa20a67342f5/components/molecules/ContributorHighlight/contributor-highlight-card.tsx#L442

But we can start by replacing the dropdown with the popover component here
https://github.com/open-sauced/app/blob/8527dc13e200fb8c8d61f981bedffa20a67342f5/components/molecules/Popover/popover.tsx#L5-L6

**Comment by RitaDee** [comment]
I will .take this.
