### ISSUE TITLE
Bug: "This Function Has Crashed" Error on User Profile Links

### ISSUE THREAD

**Issue by dev-phantom** [open-sauced/app#1699]
### Describe the bug

When attempting to access user profile links like `https://insights.opensauced.pizza/user/dev-phantom/card` or `https://insights.opensauced.pizza/user/jpmcb`, users are encountering a "This Function Has Crashed" error. This issue is causing inconvenience to users trying to access these profiles and needs to be addressed.

**Expected Behavior:**

Users should be able to access the user profiles without encountering any errors, and the content should be displayed as intended.

**Actual Behavior:**

The "This Function Has Crashed" error message appears when trying to access the mentioned user profiles.

**Additional Information:**

- Browser: chrome 
- Operating System: Android OS

**Screenshots/Logs:**
![Screenshot_20230912-071235](https://github.com/open-sauced/app/assets/72051159/59911333-b657-4112-8ac7-01ca4e96f711)

### Steps to reproduce

1. Open a web browser.
2. Navigate to the following links:
   - https://insights.opensauced.pizza/user/dev-phantom/card
   - https://insights.opensauced.pizza/user/jpmcb
3. Observe the "This Function Has Crashed" error message.

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
Edge functions have 50ms of CPU execution time which is why the function is crashing. Note that that time does not include network calls, i.e. `fetch`.

For reference, see https://docs.netlify.com/edge-functions/limits/#operation-limits

We should investigate if we can speed up the time it takes to generate a card. As well, it's be good to cache the generated cards for a period of time as well.

**Comment by dev-phantom** [comment]
I feel this issue should be tagged with an high priority fix label

**Comment by nickytonline** [comment]
This has been resolved by . I tested my own card and things are working great again.

![image](https://github.com/open-sauced/app/assets/833231/5d477d25-1f65-408f-bf04-da7fef7ddeb6)
