### ISSUE TITLE
Bug: Scrollbar Locks when the Dropdown Menu is Clicked

### ISSUE THREAD

**Issue by RitaDee** [open-sauced/app#1705]
### Describe the bug

https://github.com/open-sauced/app/assets/106407013/e948141b-8f45-4b9f-8cd9-e0bea77f4335

When a user interacts with the dropdown menu, it results in the scrollbar becoming disabled or locked. This behaviour prevents users from scrolling the page as expected.

Clicking on the dropdown menu should not interfere with the ability to scroll the page. The scrollbar should remain functional.

### Steps to reproduce

1. Go to "https://insights.opensauced.pizza/feed"
2. Click on the (...) dropdown menu after the Twitter icon
3. Observe that the scrollbar becomes locked or disabled.

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by RitaDee** [comment]
This is similar to issue #1696. Switching to the Radix Popover component is the fix. If approved,  I would love to work on this.

**Comment by OgDev-01** [comment]
Have at it 💯

**Comment by RitaDee** [comment]
I will .take this.
