### ISSUE TITLE
Feature: Add overview page for a list

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/app#1708]
### Type of feature

🍕 Feature

### Current behavior

This builds the overview tab for the lists feature with:

- Insight Cards for contributors from the list
- Contributor Distribution Chart for contributors from the list based on pull requests

![image](https://github.com/open-sauced/app/assets/42211/e3abcca4-5da4-49d8-967f-8b120b8517ba)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by AyoMoses1** [comment]
I will .take this

**Comment by brandonroberts** [comment]
Thanks @AyoMoses1. I already have someone who will be assigned to this. Assigning myself for now
