### ISSUE TITLE
Feature: Add activity page for a list

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/app#1709]
### Type of feature

🍕 Feature

### Current behavior

When a user visits an individual list and clicks on the activity tab, we want to display the activity based on the list contributors.

Initial charts:
- Most active contributors
- Contributions by project

![image](https://github.com/open-sauced/app/assets/42211/0f364dd3-489d-456e-967a-8e84db3cb970)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
Check out https://github.com/open-sauced/app/pull/1594 for the graphs.
