### ISSUE TITLE
Bug: search bar `X` icon cause the bar to jump

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/app#1717]
- When text is entered into the search bar, the "X" button causes the bar to "jump". Preferably, this would be smooth. For example, on Twitter when searching, the "X" button just appears within the search bar on the right without resizing the search bar itself

https://github.com/open-sauced/app/assets/23109390/a0fafbc0-4ddd-42dd-92fb-634a4f2ddc1b

_Originally posted by @jpmcb in https://github.com/open-sauced/app/pull/1698#pullrequestreview-1632017645_

**Comment by sdolmo** [comment]
Hi @OgDev-01, is this issue available for me to take?

**Comment by OgDev-01** [comment]
> Hi @OgDev-01, is this issue available for me to take?

Yes @sdolmo, you can also take a quick read at our [contribution guide](https://docs.opensauced.pizza/contributing/introduction-to-contributing/) 👍

**Comment by sdolmo** [comment]
Great to know! Thank you @jpmcb

**Comment by OgDev-01** [comment]
Closing this as completed from https://github.com/open-sauced/app/pull/1735

**Comment by sdolmo** [comment]
Hey @OgDev-01,
I'm looking at the [Insights repository](https://insights.opensauced.pizza/javascript/repositories/filter/recent) page and wondering if this change took effect on the search input element. I cleared the cache in my browser and tested the change on a different browser. It looks like the site is still referencing the old styles. Will this change be released later?

**Comment by sdolmo** [comment]
> @sdolmo - #1735 has not landed on the production deployment yet. We do frequent releases and you'll see a comment in the PR from our bot informing you the change has landed.
> 
> New changes on the `beta` branch should always land in beta and looks like your change is working there: https://beta.insights.opensauced.pizza/javascript/repositories

Got it, thank you!
