### ISSUE TITLE
bug: Adding repos to insight page crashes application

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#1724]
As I remember while I was working on this, this issue is there in the frontend as well.

And I just tested it now, the "Add to Page" button seems to crash the application on both Edit and Add Insights page. At least this is what is happening with me.
On the edit page, the PR count still comes out to be zero when we remove it and add it back.

[pr-count-zero-insight-forms.webm](https://github.com/open-sauced/app/assets/27003616/aafd5859-3144-4943-aef1-d8f4864ecf97)

_Originally posted by @ThePiyushAggarwal in https://github.com/open-sauced/app/issues/1620#issuecomment-1726013738_

**Comment by jpmcb** [comment]
![Screenshot 2023-09-20 at 10 09 51 AM](https://github.com/open-sauced/app/assets/23109390/baa04023-e06b-4856-a910-83560dad889b)

I am seeing the same crash with the above flow. The console throws:

```
index.js:103 TypeError: Cannot read properties of undefined (reading 'full_name')
    at 962-84cdac9af7cc3a7c.js:1:37475
    at Array.map (<anonymous>)
    at es (962-84cdac9af7cc3a7c.js:1:37443)
    at ab (framework-aec4381329cec0e4.js:9:60911)
    at ud (framework-aec4381329cec0e4.js:9:72797)
    at i (framework-aec4381329cec0e4.js:9:120352)
    at oO (framework-aec4381329cec0e4.js:9:99104)
    at framework-aec4381329cec0e4.js:9:98971
    at oF (framework-aec4381329cec0e4.js:9:98978)
    at ox (framework-aec4381329cec0e4.js:9:95730)
```

**Comment by jpmcb** [comment]
Some more info here: it looks to only happen if you click the "Add to page" on the default repos _before_ the suggested repos has hot reloaded. Here's a demonstration:

1. Login (after clearing all session cached data)
2. Go to edit page
3. Quickly click the default repo
4. Crash!
5. Go back, edit insight page again
6. Wait for hot refresh of suggested pages
7. Works ok!


https://github.com/open-sauced/app/assets/23109390/ef3182e9-873f-41a9-9ea8-8843016659fe

**Comment by bdougie** [comment]
@brandonroberts is this was done in production. Is there a way to get these errors in Sentry as well?
