### ISSUE TITLE
Feature: Improve Visibility of the Follow CTA on User Profiles

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#1727]
### Type of feature

🧑‍💻 Refactor

### Current behavior

Currently you have to click on the three dots menu to see the Follow/Unfollow CTA. This was not obvious when I went to follow a new user on the platform.

![image](https://github.com/open-sauced/app/assets/833231/920a1b11-5a03-4740-a7a5-ff8acaa32b83)

### Suggested solution

Have the Follow button placed beside the Share button.

### Additional context

Slack Discussion: https://opensaucedworkspace.slack.com/archives/C035RQ8ANBW/p1695223459466669

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by shavidze** [comment]
Can I get this issue? @nickytonline

**Comment by shavidze** [comment]
[__Related PL__](https://github.com/open-sauced/app/pull/1739)

**Comment by shamimbinnur** [comment]
.take
