### ISSUE TITLE
Feature: Add Insights Page button shows while you are adding an insights page.

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#1728]
### Type of feature

🍕 Feature

### Current behavior

<img width="1449" alt="Screen Shot 2023-09-20 at 2 07 11 PM" src="https://github.com/open-sauced/app/assets/5713670/95b7aecc-2de0-4ecb-ac00-ccbaee499d9c">

### Suggested solution

Remove the button from the subheader section when already on the page. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by OgDev-01** [comment]
This has been resolved here https://github.com/open-sauced/app/pull/1722
