### ISSUE TITLE
Bug: "Subscribe" spills out of div

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#1729]
### Describe the bug

<img width="1510" alt="Screenshot 2023-09-20 at 9 10 26 PM" src="https://github.com/open-sauced/app/assets/23109390/a71cecf9-5aff-4a87-bb2e-b7902b83b6c3">

Notice how the "Subscribe" button on the highlights page spills over out of the div on Firefox. This looks fine on Chrome:

<img width="1505" alt="Screenshot 2023-09-20 at 9 12 38 PM" src="https://github.com/open-sauced/app/assets/23109390/5fea9946-bca0-4e68-ad26-7470921f0820">

But, again, is busted on Firefox

### Steps to reproduce

1. Use firefox
2. Go to https://insights.opensauced.pizza/feed
3. Notice the "Subscribe" button is spilling over to the right

### Browsers

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by RitaDee** [comment]
I will .take this.

**Comment by jpmcb** [comment]
This is still broken.

On firefox:
![Screenshot 2023-10-02 at 11 43 27 AM](https://github.com/open-sauced/app/assets/23109390/8cdc52c2-d9ba-463f-84f8-fe2bb1b6051f)

On Chrome:

![Screenshot 2023-10-02 at 11 43 38 AM](https://github.com/open-sauced/app/assets/23109390/2f12a10c-965f-4803-bf59-2214cbdaaf7d)

**Comment by RitaDee** [comment]
> This is still broken and looks like it has degraded on both FireFox and Chrome.
> 
> On firefox:
> 
> ![Screenshot 2023-10-02 at 11 43 27 AM](https://user-images.githubusercontent.com/23109390/272045065-8cdc52c2-d9ba-463f-84f8-fe2bb1b6051f.png)
> 
> On Chrome:
> 
> ![Screenshot 2023-10-02 at 11 43 38 AM](https://user-images.githubusercontent.com/23109390/272045091-2f12a10c-965f-4803-bf59-2214cbdaaf7d.png)

I will check it out and work the fix.

**Comment by nickytonline** [comment]
@RitaDee, consider adding `flex-wrap` to the container element holding the input and Subscribe button so that the UI is more fluid and can adjust to the different screen sizes. And you'll probably need to add the Tailwind class `self-start` to the input for the email address.

**Comment by RitaDee** [comment]
> @RitaDee, consider adding `flex-wrap` to the container element holding the input and Subscribe button so that the UI is more fluid and can adjust to the different screen sizes. And you'll probably need to add the Tailwind class `self-start` to the input for the email address.

Thank you @nickytonline. This is kind of weird to me I just pulled beta into my forked repo and noticed the changes merged for this issue aren't reflecting. Do you have an idea why?

**Comment by nickytonline** [comment]
@RitaDee, hmm not sure. How are you pulling the latest from beta into your fork? Are you using the GitHub user interface, the command line or another tool?

**Comment by RitaDee** [comment]
> @RitaDee, hmm not sure. How are you pulling the latest from beta into your fork? Are you using the GitHub user interface, the command line or another tool?

I primarily use the GitHub user interface and do a pull on my IDE. I suspect someone might have encountered some conflicts and in the process tempered with the changes. I might be wrong though.

**Comment by RitaDee** [comment]
> self-start

Going with the above fix alters the design:
<img width="1430" alt="image" src="https://github.com/open-sauced/app/assets/106407013/33dd0716-f0b1-4703-832b-9e1a30019de9">

So, I went with the former fix I made. The PR is now ready for a review.

**Comment by nickytonline** [comment]
Yeah, the button would have to go full width then which we may or may not want as the screen shrinks. With you current suggestion, it works but the text field for the email gets pretty small.

In smaller screens if we went flex-col with the buttons taking the full width, it might be better.

Do you have a preference here style wise @isabensusan?

**Current Suggestion**

![CleanShot 2023-10-02 at 17 55 34](https://github.com/open-sauced/app/assets/833231/af3ed97d-cbe6-445f-852e-a591b44b3f60)

**Alternate Suggestion**

![CleanShot 2023-10-02 at 17 52 57](https://github.com/open-sauced/app/assets/833231/b11f7da4-67a7-4927-8292-cc7a6b4dff90)

**Comment by RitaDee** [comment]
> Yeah, the button would have to go full width then which we may or may not want as the screen shrinks. With you current suggestion, it works but the text field for the email gets pretty small.
> 
> In smaller screens if we went flex-col with the buttons taking the full width, it might be better.
> 
> Do you have a preference here style wise @isabensusan?
> 
> **Current Suggestion**
> 
> ![CleanShot 2023-10-02 at 17 55 34](https://user-images.githubusercontent.com/833231/272097740-af3ed97d-cbe6-445f-852e-a591b44b3f60.gif) [ ![CleanShot 2023-10-02 at 17 55 34](https://user-images.githubusercontent.com/833231/272097740-af3ed97d-cbe6-445f-852e-a591b44b3f60.gif) ](https://user-images.githubusercontent.com/833231/272097740-af3ed97d-cbe6-445f-852e-a591b44b3f60.gif) [ ](https://user-images.githubusercontent.com/833231/272097740-af3ed97d-cbe6-445f-852e-a591b44b3f60.gif)
> 
> **Alternate Suggestion**
> 
> ![CleanShot 2023-10-02 at 17 52 57](https://user-images.githubusercontent.com/833231/272097060-b11f7da4-67a7-4927-8292-cc7a6b4dff90.png)

The alternate suggestion looks good. I will wait for the meantime until a decision is made.

**Comment by chhristopher** [comment]
<img width="366" alt="Screenshot 2023-10-16 at 1 58 49 PM" src="https://github.com/open-sauced/app/assets/48575398/e19a0df6-da83-491a-870a-2130c7110c04">


Also on Chrome

**Comment by jpmcb** [comment]
@chhristopher - looks like this fix hasn't landed on production yet: this should be fixed once it lands but can be viewed in beta: https://beta.app.opensauced.pizza/feed
