### ISSUE TITLE
feat: add `Delete` feature to list

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/app#1731]
Will it be out of scope if I add a `Delete` flow for the list?

https://github.com/open-sauced/app/assets/62995161/76b049ed-d2b0-4676-a427-c0cf8826c412

Similar to what was done with insights pages

_Originally posted by @OgDev-01 in https://github.com/open-sauced/app/issues/1698#issuecomment-1728578103_

**Comment by Jyotipal29** [comment]
.take
