### ISSUE TITLE
Feature: "Learn More" button hidden during scroll down

### ISSUE THREAD

**Issue by EthenThinkful** [open-sauced/app#1733]
### Type of feature

🍕 Feature

### Current behavior

The "Learn More" button on the left side of the insights page is hidden until a user scrolls down to the bottom of their page. This seems like a hinderance in the UI and I think it makes more sense to have the left content interactable and viewable without having to scroll to the bottom of the page. 
![unnaturalsticky](https://github.com/open-sauced/app/assets/104235709/407441c6-4570-4b50-9d90-1d4a7f576b99)

https://github.com/open-sauced/app/assets/104235709/f3d1c6d2-56da-43b6-9dd2-8f94692fedd5

### Suggested solution

Make left content "unsticky"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by himanshumalviya15** [comment]
.take

**Comment by diivi** [comment]
This is happening for the "Subscribe to Our Newsletter" div for me:
![image](https://github.com/open-sauced/app/assets/41837037/5eb59dc9-79f8-459c-8c4d-77f650262353)

**Comment by Dun-sin** [comment]
@BekahHW looks like this page no longer exists?

**Comment by nickytonline** [comment]
Yeah these pages were brought into workspaces, so this issue can be closed.
