### ISSUE TITLE
Bug: magnifier glass icon in search CSS not consistent

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#1744]
### Describe the bug

 The magnifier glass icon in beta has some CSS that's not consistent and causes the icon to shift when typing:

https://github.com/open-sauced/app/assets/23109390/e96f44c3-9cc5-4f05-80a6-81947284166a

### Steps to reproduce

1. Go to https://beta.insights.opensauced.pizza/javascript/repositories
2. Start typing in the search bar and notice the icon moves

### Browsers

Firefox & Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
The problem appears to be the insertion of the `X` SVG icon when you start to type. It must be resizing the container causing the search icon to change ever so slightly.

You can see this happen if I set X icon's `display` to `none`.

![CleanShot 2023-09-25 at 14 39 03](https://github.com/open-sauced/app/assets/833231/422c24be-c393-4ca9-8bdf-fef211ac2204)

**Comment by jpmcb** [comment]
Related to https://github.com/open-sauced/app/pull/1735

**Comment by RitaDee** [comment]
I will .take this.
