### ISSUE TITLE
Feature: modify "Add Insight Page" experience when creating an insight page? 

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#1749]
### Type of feature

🍕 Feature

### Current behavior

Just had a sad experience where i spent 5 minutes selecting repos for a new page only to select "Add Insight Page" _instinctively_ (thinking the top right button would be the finalizer) and have all my work disappear.

![Screenshot 2023-09-26 at 10 30 19 AM](https://github.com/open-sauced/app/assets/23109390/15af2986-7d90-49c4-a0e6-bfc748368e46)

### Suggested solution

A few thoughts:

- Create a confirmation popup that asks if you _really_ want to leave the current page you're working on.
- Remove the "Add Insight Page" button all together. Or maybe move it so it's not in the top right. Maybe it's just me, but given the distinction between the "Create" button in the middle of the screen vs the one in the top right, I gravitate towards the one in the top right.

CC @isabensusan for thoughts.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
This only compounds when you have a large list and the actual "Create page" button gets pushed all the way off the screen.

![Screenshot 2023-09-26 at 10 40 52 AM](https://github.com/open-sauced/app/assets/23109390/a5fb2b6e-b306-4117-b7e7-3c97d36d791a)

**Comment by heysagnik** [comment]
I think the issue has been fixed 
![image](https://github.com/open-sauced/app/assets/70798495/5c852de8-8607-421b-b3a5-586719f64135)
