### ISSUE TITLE
Bug: Repos with long names get cut off

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#1750]
### Describe the bug

Repos with longer names get cut off when viewing an insight page:

![Screenshot 2023-09-26 at 11 59 01 AM](https://github.com/open-sauced/app/assets/23109390/3ba1551a-e42b-4b9f-aa9d-50b2b66f24c7)

This makes for a tricky user experience: I'm really not sure _exactly_ which repos are which.

### Steps to reproduce

1. Create an insight page with repo names that are long
2. See the insight page and notice the names getting cut off 

CC @isabensusan - more feedback 😅 nothing urgent, just a sharp edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
Thanks @nickytonline 🙈

**Comment by aryanas159** [comment]
I am not really sure what could be a possible solution for this, maybe wrapping the text?

**Comment by nickytonline** [comment]
This issue relates to #1763. We can also look at the size of the repository name and see if we can let that input grow without overlapping other UI and use that in conjunction with ellipsis mentioned in #1763. cc: @OgDev-01

**Comment by aryanas159** [comment]
@nickytonline can you please review the changes I have made. I think it fixes the issue.
Also, for some reason my previously merged commits are also being shown in the pull request, is that an issue ?

**Comment by nickytonline** [comment]
@aryanas159, we get notified for reviewing things in GitHub, but it doesn't mean we review everything immediately.

Thanks again for contributing to the project!
