### ISSUE TITLE
Bug: Insights page more than 10 repos obscured when editing page

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#1751]
### Describe the bug

I have a page of 30 repos:

![Screenshot 2023-09-26 at 1 30 37 PM](https://github.com/open-sauced/app/assets/23109390/07ab7e0c-14a3-400e-b8c3-5c16374a9a76)

But when I go to edit the insight page, I only see the first 10

![Screenshot 2023-09-26 at 1 31 02 PM](https://github.com/open-sauced/app/assets/23109390/ba559fa0-68bc-4d53-8a6b-9af900de5d3b)

My initial reaction was that something went wrong and one of my previous edits to this page didn't go through correctly. I ended up going back to the main overview page to confirm that this wasn't the case: it had in fact correctly updated the page. It just wasn't displaying all the repos.

### Steps to reproduce

1. Go to an insights page with over 10 repos
2. Note the number of repos in the overview page
3. Edit the page
4. Note that only 10 are displayed

cc @isabensusan - more feedback: I'm not sure what the intent might be here for editing pages since new pages get dynamically added to the list during creation.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by ARodriguezHacks** [comment]
I recently started using OpenSauce, and when I created my first Insight Page and began adding repos, I found that I could only add up to 10. I'm not sure if this is intentional or not, but glad I looked up an existing issue before creating a new one.

**Comment by OgDev-01** [comment]
>  I found that I could only add up to 10. I'm not sure if this is intentional or not, but glad I looked up an existing issue before creating a new one.

Yes @ARodriguezHacks, you can add up to 10 repos as a freemium user for now.

**Comment by OgDev-01** [comment]
I checked the source of the repos coming from the API, and it turns out we have a default limit set to 10 and that resulted in the 10 repos you se whenever you try to edit a page that has more than 10 repos.

We might need some design help here, @isabensusan; maybe a way to account for more repos on the cart. Having them all display without limit can lead to quite a long cart when we have up to 20+ repos in it.

**Comment by a0m0rajab** [comment]
Just quick thought: having a fixed height and scroll for that could solve this till we have a design.
