### ISSUE TITLE
Bug: Date Selector not working on Highlight Creation/Editing Dialogs

### ISSUE THREAD

**Issue by babblebey** [open-sauced/app#1756]
### Describe the bug

While attempting to create a new highlight on OpenSauced Insights today, I encountered an issue with the date selector. I found that I am unable to use the date selector in both the highlight creation and editing dialogs. Here are my observations:

1. Clicking on a part of the date selector popup within the parent dialog body results in the date selector closing without selecting a date.
2. Clicking on a part of the date selector popup that extends outside of the parent dialog body (i.e., the dialog background overlay that closes the dialog when clicked) causes the entire highlight creation/editing dialog to close without selecting the date.

### My Analysis

Based on the above observations, I believe the issue is related to the position of the date selector on the z-axis, specifically its `z-index` or `position` property. It appears that the popup element visually sits on top of the dialog but is not actively responsive to user interactions.

### Proposed Solutions:

In such cases, an element exhibiting this behavior, like the date selector popup, may require a simple adjustment in its `position` property (e.g., setting it to `relative`, `absolute`, etc.). This adjustment can complement the existing `z-index` value, ensuring that the date selector is not only visually on top but also fully interactive. To resolve this issue, I suggest investigating and adjusting the `position` property as a potential solution. Some CSS debugging may be needed to fine-tune this behavior.

#### Highlight Creation

[screencast-insights.opensauced.pizza-2023.09.27-09_03_54 (1).webm](https://github.com/open-sauced/app/assets/25631971/d51916af-86d6-4a6b-ba5d-9b5dfffb15e4)

#### Highlight Editing

[screencast-insights.opensauced.pizza-2023.09.27-09_03_54.webm](https://github.com/open-sauced/app/assets/25631971/97998421-1f66-42d4-95d8-8e405ee3bf85)

### Browsers

Chrome

### Additional context (Is this in dev or production?)

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
@babblebey, I checked this and it does look like a regression. If you're up for it, feel free to tackle this one.

**Comment by aryanas159** [comment]
.take

**Comment by babblebey** [comment]
> babblebey, I checked this and it does look like a regression. If you're up for it, feel free to tackle this one.

Haha, and @aryanas159 swooped right in for the steal 🤓🤣😂

Great stuff @nickytonline, I wasn't up for it! Pretty occupied at the time 🥲
