### ISSUE TITLE
Bug: Text overflowing in time zone dropdown field

### ISSUE THREAD

**Issue by Hiperultimate** [open-sauced/app#1757]
### Describe the bug

**Current Behavior**
When a new user logs in they are treated with this page. 
![image](https://github.com/open-sauced/app/assets/32923170/a9175878-cf31-46ab-989a-4d54489ea4a1)

As you can see in the Time Zone dropdown field the selected field in the dropdown is overflowing. 
![image](https://github.com/open-sauced/app/assets/32923170/d7b060c8-4cda-467d-bc26-5e97f8dcd86e)

**Suggested Solution**
The dropdown field should expand accordingly.

If possible, I would love to be assigned to work on this task.

### Steps to reproduce

1. Connect with Github from a new account
![image](https://github.com/open-sauced/app/assets/32923170/5e9d544b-186e-4f8d-b5df-9429fc73877a)

2. Click on **Complete the onboarding** 
![image](https://github.com/open-sauced/app/assets/32923170/6f87b55f-2be5-4c57-a687-1be0a6e647b9)

3. Authenticate with Github

4. Choose interests

After following those steps you should be able to reach to this page
![image](https://github.com/open-sauced/app/assets/32923170/72126a76-3724-4209-a64a-0358033076bf)

### Browsers

Edge

### Additional context (Is this in dev or production?)

Dev

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Hiperultimate** [comment]
If possible, can I get this task assigned to me? I would love to work on this.

**Comment by takanome-dev** [comment]
Hey @Hiperultimate, feel free to assign yourself, check the docs [here](https://docs.opensauced.pizza/contributing/introduction-to-contributing/#issues) on how to do so

**Comment by Hiperultimate** [comment]
.take

**Comment by Hiperultimate** [comment]
@takanome-dev and fellow maintainers.
Here is the output video of the change I am able to make. 

https://github.com/open-sauced/app/assets/32923170/50cb5215-0582-40ab-895b-1c3bed025ade

As Select is a global component I tried to keep the dimensions similar as before but I made it reactive by removing hardcoded height and adding extra padding.

As the height of the select field is changing, it is causing this jump in height of the entire modal.
Should I make some extra changes or is this behavior fine? and should I create PR so maintainers can check the code?

Please let me know if I am doing something wrong.
