### ISSUE TITLE
Bug: User search shortcut shown in UI is macOS specific

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#1758]
### Describe the bug

The user search shortcut shown in the UI is macOS specific. CMD + K. The command key does not exist on other operating systems (OSes).

https://github.com/open-sauced/app/blob/e895f621df683e29ed0864ce18fb9dd42828a93e/components/organisms/SearchDialog/search-dialog.tsx#L96-L98

https://github.com/open-sauced/app/blob/e895f621df683e29ed0864ce18fb9dd42828a93e/components/organisms/SearchDialog/search-dialog.tsx#L140-L142

### Steps to reproduce

If you go to https://beta.insights.opensauced.pizza/hub/insights and search for a user, you can use CMD + K (macOS) or CTRL + K (other OSes). This works well, but the shortcut shown in the UI is only for macOS.

The shortcut should show CTRL + K or whatever we deem a shorter hand of CTRL + K.

![CleanShot 2023-09-27 at 11 17 47](https://github.com/open-sauced/app/assets/833231/74e7aff8-fa06-425a-bd47-e0c034858295)

### Additional context (Is this in dev or production?)

dev (feature hasn't rolled out to production yet)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
A suggested approach to fixing this is to check the user agent and set the text accordingly.

```javascript
if (
  navigator.userAgent.indexOf("Macintosh") === -1 &&
  navigator.userAgent.indexOf("Mac OS") === -1
) {
  // The web page is running on an operating system other than macOS
} else {
  // The web page is running on macOS
}
```

**Comment by nickytonline** [comment]
Do we have a shorter representation for <kbd>CTRL</kbd> + <kbd>K</kbd> @isabensusan?

**Comment by 289Volts** [comment]
Can i handle this task?

**Comment by nickytonline** [comment]
@289Volts, @FrancoLab has been working on this. Franco, just type in `.take` in a comment here to assign it to yourself.

**Comment by FrancoLab** [comment]
.take
