### ISSUE TITLE
Bug: Highlight Card Overflow On Small Screen

### ISSUE THREAD

**Issue by adiati98** [open-sauced/app#1764]
### Describe the bug

When I click a link to a highlight on X or open it in a browser on mobile phone, the highlight card overflow as screenshot below:

**Highlight card on X on mobile phone**

![opensauced insights on twitter on mobile phone](https://github.com/open-sauced/app/assets/45172775/de20d2df-c27d-4c8c-b150-818c58527723)

**Highlight card on browser on mobile phone**

![opensauced insights on twitter on mobile phone](https://github.com/open-sauced/app/assets/45172775/b4fde418-c346-4f80-ad68-f03e2e0f846e)

### Steps to reproduce

1. Open the X app on your phone. 
2. Click the highlight link in a post. [Here](https://x.com/BekahHW/status/1707150470807245110?s=20) is an example of a post with a highlight link.
3. You will see that the card overflows. 

### Browsers

Chrome
Others

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by aryanas159** [comment]
.take

**Comment by aryanas159** [comment]
It seems to be working fine on the beta branch.
![image](https://github.com/open-sauced/app/assets/114330931/bafe78e7-614b-4c22-bf2c-0c210599ede4)

**Comment by adiati98** [comment]
I wonder if it has anything to do with if we open the link right from X app on mobile phone?
Because if I open it on X from desktop's browser and shrink the page, it doesn't caused any error like this.

Additional information, I'm using Android version 13 (Samsung Galaxy S22).

**Comment by takanome-dev** [comment]
Hey @adiati98, this has been fixed, but the changes are not deployed to prod yet (they are in beta). 
You can visit [beta.insights.opensauced.pizza](https://beta.insights.opensauced.pizza) and try reproducing this issue.

**Comment by adiati98** [comment]
> Hey @adiati98, this has been fixed, but the changes are not deployed to prod yet (they are in beta). 
> You can visit [beta.insights.opensauced.pizza](https://beta.insights.opensauced.pizza) and try reproducing this issue.

Ah, thanks @takanome-dev 😊 🙏

**Comment by takanome-dev** [comment]
@adiati98 let us know if it's still present. Otherwise, feel free to close this issue

**Comment by adiati98** [comment]
@takanome-dev can you guide me to reproduce the modal for the card in beta? I have no idea how to do this 😅

**Comment by takanome-dev** [comment]
You can vis

**Comment by takanome-dev** [comment]
1. Head over to https://beta.insights.opensauced.pizza/feed
2. Click on one highlight post
3. See if there is an overflow of the card
4. Test it on both desktop and mobile

**Comment by adiati98** [comment]
@takanome-dev 

Clicking anywhere in the post didn't do anything both on desktop and mobile. And clicking the link will take me to the repo.

Below is the screenrecoding of the desktop:
 
![opensauced beta highlights](https://github.com/open-sauced/app/assets/45172775/e4ea33b2-a52e-4881-90bb-ad2d902f3350)

**Comment by takanome-dev** [comment]
@adiati98, try clicking on the date

https://github.com/open-sauced/app/assets/79809121/72c65d1c-5e60-4d1e-8e82-dcf187d65356

**Comment by adiati98** [comment]
Hi @takanome-dev,
Thank you for walking through it for me! 😄

I've checked both on desktop and mobile, and they aren't overflowing.
So, I'm closing this issue 😊
