### ISSUE TITLE
Bug: Hacktoberfest icon is missing in user settings

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/app#1770]
### Describe the bug

![image](https://github.com/open-sauced/app/assets/42211/73bca8d6-a208-4d24-aa84-ddd8c075f2f1)

### Steps to reproduce

Add mission svg

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by heysagnik** [comment]
I want to work on this issue .

**Comment by OgDev-01** [comment]
I'll remove my assignment and assign @heysagnik since he already has a pr up for this in #1775

**Comment by brandonroberts** [comment]
Closed via #1775
