### ISSUE TITLE
Bug: Highlights "Home" and "Following" CSS not consistent 

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#1778]
### Describe the bug

https://github.com/open-sauced/app/assets/23109390/8c486770-0c8e-4fe2-9034-fde0bada0b48

Notice how, as I switch between the "Home" and "Following" tab in the highlights page how the CSS for each card is not consistent. These should be the same between both (just like it would be between posts on Twitter between tweets in "For You" and "Following": https://twitter.com/home)

### Steps to reproduce

1. Go to https://insights.opensauced.pizza/feed
2. Flip between "Home" and "Following"
3. Notice the CSS inconsistency between cards

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 5hraddha** [comment]
The Contributor Highlight Card seems to be wrapped in different CSS in Following and Home tabs, giving extra padding in the Following tab:
In Home tab:
```js
              <div className="p-4 border bg-light-slate-1 md:px-6 lg:px-9 lg:py-5 sm:py-3 xs:py-2 rounded-xl">
                <ContributorHighlightCard
                    ...
                />
              </div>
```
where as in Following tab:
```js
              <div className="p-4 py-6 border bg-light-slate-1 md:px-6 lg:px-12 rounded-xl">
                <ContributorHighlightCard
                    ...
                />
              </div>
```

**Comment by nickytonline** [comment]
Thanks @5hraddha! If you'd like to work on it you can use the `.take` command.

**Comment by 5hraddha** [comment]
.take
