### ISSUE TITLE
Bug: urls is cut off when full url is added to insight page

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#1784]
### Describe the bug

![Screen Shot 2023-10-02 at 3 10 20 PM](https://github.com/open-sauced/app/assets/5713670/ac63cff2-f3ba-460f-bf9b-8ac354027c2e)

### Steps to reproduce

1. View insight page
2. https://github.com/open-sauced/app
3. not it is cut off

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by RitaDee** [comment]
I will love to work on this.
