### ISSUE TITLE
Feature: Fetch list of organization's repos

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#1786]
### Type of feature

🍕 Feature

### Current behavior

When working on a demo for stripe, I noticed a few issues. https://github.com/open-sauced/app/issues/1785

I needed to manually add 49 repositories. It would be nice to add an organization. 

cc @open-sauced/design adding this to the backlog. No rush, just tracking it. 

### Suggested solution

Maybe an optional modal to add an org name. My expectation would be grab the top 10 or latest 10. Perhaps in the future have options for how to grab or alert the user a max amount can be fetched. 

The amount is 49 for pro users. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
Copy/paste of repos exist for workspaces and GitHub org for repository insights
