### ISSUE TITLE
Feature: Default repository insights to be filtered by activity

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#1788]
### Type of feature

🍕 Feature

### Current behavior

While testing the insights pages, I noticed not all repositories have activity and I see nothing on page 2, but do on page 3

https://insights.opensauced.pizza/pages/bdougie/23/repositories

Page 2
![Screen Shot 2023-10-02 at 3 40 03 PM](https://github.com/open-sauced/app/assets/5713670/6e0f1f41-c65b-495e-90ae-01b7f34b7b2d)

Page 3

![Screen Shot 2023-10-02 at 3 39 31 PM](https://github.com/open-sauced/app/assets/5713670/e61e40ea-41b9-4d25-8e02-3167575ddd3d)

### Suggested solution

I am not confident, but I think the current list is filtered by stars. We should sort by activity by default. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
I think it's ordered by `updated_at`

https://github.com/open-sauced/api/blob/10a174a9ad6a9ad8d10cf974a390eddf2fb5991a/src/pull-requests/pull-request.service.ts#L203-L206

cc @brandonroberts

**Comment by brandonroberts** [comment]
Noting that we've updated this to sort by last push date for the repo, which pushes higher activity repos to the top and low activity repos to the bottom.
