### ISSUE TITLE
Bug: create highlight view not responsive to small or large screens

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#1790]
### Describe the bug

The github cards / highlights creation view does not seem to be appropriately responsive and creates some poor user experiences with small / mobile screens and large screens

### Normal screen 👍🏼 

![Screenshot 2023-10-02 at 6 17 26 PM](https://github.com/open-sauced/app/assets/23109390/f6373fc8-6ed7-405b-b791-1eca16d0de9a)

### Smaller screen 🙈 

![Screenshot 2023-10-02 at 6 18 17 PM](https://github.com/open-sauced/app/assets/23109390/6bc180a2-88cb-4d3c-9ab7-8490f2dedf40)

### Larger screen 😰

![Screenshot 2023-10-02 at 6 18 34 PM](https://github.com/open-sauced/app/assets/23109390/4e63c276-1aaf-4249-baac-bc139afc58e7)

On a much larger screen, the github image / card seems to get blown up quite alot which seems to force the entire highlight view to expand and push suggested highlights down. Notice the scrollbar that appears within the create highlight view. 

I'd imagine the best case here would be to:
- Have a design / idea for a small mobile screen (the second image)
- Keep the same size for much larger screens and not expand the image once the size of the screen reaches a certain width

Happy to start the discussion and hear any / all ideas.

### Steps to reproduce

1. Go to https://insights.opensauced.pizza/feed
2. Click "Post a highlight to show your work"
3. Enter a PR / Issue to generate the card
4. Expand the screen to be very large. Also make it really small.

### Browsers

Chrome, Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Tushar2930** [comment]
Assign this issue to me

**Comment by nickytonline** [comment]
@Tushar2930 this is still being triaged and the team needs to discuss the redesign of the mobile view for this.

**Comment by brandonroberts** [comment]
Closing as resolved

![image](https://github.com/user-attachments/assets/66c6f1ce-0493-4475-9f78-8a96f583951a)
