### ISSUE TITLE
Feature: Add postHog .identify snippet to code

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#1794]
### Type of feature

🍕 Feature

### Current behavior

N/A

### Suggested solution

To get better tracking and be able to create cohorts, we need to setup PostHog in a way that allows us to get more context on a user.

Right now, PostHog is logging sessions anonymously, assigning a random id to users as they navigate the platform.  We can use the `posthog.identify()` method to bring more data into posthog.

What we want is to identify users to add more context to the sessions and get:
- user login (we only want their usernames, not their emails, to avoid falling into GDPR infringements) 
- whether they are a maintainer or not
- whether they are pro / free users

### Resources
From PostHog docs: 
- [Identifying users](https://posthog.com/docs/product-analytics/identify)
- [PostHog + Next.js](https://posthog.com/docs/libraries/next-js#pages-router-1)
- [PostHog + Next.js + Supabase](https://posthog.com/tutorials/nextjs-supabase-signup-funnel): this is a tutorial for a related but different thing, but the examples they use might be helpful to sort out how the three technologies work together. Getting the signup funnel created would be very helpful though, and a great extra to have if possible

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
I'm not sure if we're aloud to identify them by their user login because then we'd know literally who they are, which is why an anonymous ID is used, but the rest of the info should be fine. At least that's what I remember from years ago when we did some custom stuff with Google Analytics. It was a while ago, so maybe that no longer holds in the new digital age. 😅

**Comment by isabensusan** [comment]
It's a good point, user logins are a bit of a gray area bc on their own they are not enough to successfully identify a person, but if a user uses the same user login for other platforms with public facing profiles it might be an issue. 

To be 100% safe and compliant we could use the user id from the `id` field on our `user` db instead

**Comment by nickytonline** [comment]
@brandonroberts @jpmcb, are we OK with exposing the internal `ID` from the `User` table from the insights API to be used for the unique identifier for `posthog.identify()`?

**Comment by brandonroberts** [comment]
Yes, it's already available in the user session data also under `user?.user_metadata.sub`
