### ISSUE TITLE
Feature: Can we add the follow button to non-connected accounts

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#1795]
### Type of feature

🍕 Feature

### Current behavior

![Screen Shot 2023-10-03 at 1 54 23 PM](https://github.com/open-sauced/app/assets/5713670/f167f002-93c3-4171-8118-b14c28adee46)

Reasoning:

If we see a trend of folks following users not on the platform, OpenSauced can respectively reach out to get them to join. 

### Suggested solution

Add the follow button and filter the user's followers based on connected and not connected. Show an invited button next to "followed" non-connected folks after they have followed. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by isabensusan** [comment]
So in this issue #1675 I touch on  CTA's for non-connected accounts. The intention was to have an "invite to OpenSauced" cta. 

I feel like there still a use case where someone wants to follow someone else, but isn't necessarily acquainted to them and don't want to send an invite. ie. If I want to follow Theo on OpenSauced, but I don't really know the guy, I can't send an invite but I can follow him and wait until he joins the platform.

Here's what that interaction could look like -- add a button for "follow" and on for "Invite to OpenSauced":
 
![image](https://github.com/open-sauced/app/assets/27322879/fa5b1e15-19b5-4218-ae57-30f8af674c2c)

And when a user hovers over the "follow" button we can show a tooltip clarifying that they are not OpenSauced members yet:
<img width="1022" alt="image" src="https://github.com/open-sauced/app/assets/27322879/ff201921-1d07-4bc3-9013-63f06d2e49d7">


The other side to the experience would be on the user's "following" list -> if they follow someone who isn't signed up we can show non-connected users with a "not yet on OpenSauced" type of label and an "invite to OpenSauced" CTA.
At the moment we don't have a "following" list live in the site but when we create one this should be part of that flow (I'm opening up an issue for it but it's not that urgent yet anyways).

**Comment by bdougie** [comment]
This was completed in a recent PR
