### ISSUE TITLE
Bug: OpenSauced hates me... or just doesn't show my contributions. 😄 

### ISSUE THREAD

**Issue by michaeljolley** [open-sauced/app#1800]
### Describe the bug

When looking at my profile, my contributions never load.

![image](https://github.com/open-sauced/app/assets/1228996/d8a09a25-401b-4ff8-8b95-d2a218bdcf1a)

### Steps to reproduce

1. Go to the [contributions tab of my profile](https://insights.opensauced.pizza/user/michaeljolley?tab=contributions)
2. See no contributions are shown.
3. Look at my [GitHub profile](https://github.com/michaeljolley) and see there are contributions to publicly available repositories.

### Browsers

Edge

### Additional context (Is this in dev or production?)

production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by OgDev-01** [comment]
haha😄, that's a funny title to this issue 😅. We don't hate you equally. When last did you make a pr contribution to an open source project?

**Comment by BekahHW** [comment]
@michaeljolley also can you let us know what the repo was?

**Comment by michaeljolley** [comment]
A collection of more recent (last month or so) of merged PRs.

https://github.com/expressots/expresso-site-doc/pull/24
https://github.com/michaeljolley/baldbeardedbuilder.com/pull/6
https://github.com/expressots/expresso-site-doc/pull/18
https://github.com/michaeljolley/baldbeardedbuilder.com/pull/5
https://github.com/EclipseFdn/open-vsx.org/issues/2104
https://github.com/michaeljolley/baldbeardedbuilder.com/pull/4
https://github.com/expressots/expresso-site-doc/pull/19
https://github.com/withastro/docs/pull/2862

**Comment by brandonroberts** [comment]
To provide some context here, we proactively gather information on repositories that people follow when they add them to an insight page. So if you add those repositories, we will started getting more data for them. I added `octokit/octokit.net` to one of my insight pages, so its pull requests get updated, and now it data is reflected on your profile. 

![image](https://github.com/open-sauced/app/assets/42211/0dbb5dba-7d2a-499e-a6ee-9d10def12959)

We have a larger set of repositories that are updated but less often. Will take a further look into why more aren't showing up though.

**Comment by jpmcb** [comment]
Taking a deeper look, as Brandon mentioned, into our data and backfill services to uncover this abit more

**Comment by michaeljolley** [comment]
@brandonroberts, just to confirm, my best shot of making sure my PRs show up is to add that repo to an Insight page?

**Comment by brandonroberts** [comment]
@michaeljolley Yes
