### ISSUE TITLE
Bug: when a new Insight page is created user gets redirected to Hub instead of page

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#1802]
### Describe the bug

Essentially the title. If I create a new inisght page, instead of getting redirected to the new page, I get redirected to the Insights hub.

Redirecting users to the page the've just created would be a much better experience.

Here's a screencap of the current flow:
![Rewatch GIF Recording - 2023-10-04 at 5 51 49 PM](https://github.com/open-sauced/app/assets/27322879/63a646c9-2c7a-45ed-8495-c388b0f4f901)

### Steps to reproduce

1. Go to the Insights Hub
2. Click on "Add Insight Page"
3. Fill out name + add repos
4. Click on "Create Page"
5. Get redirected to Hub instead of new page

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by OgDev-01** [comment]
I'll reassign this to myself to help with bandwidth here
