### ISSUE TITLE
Bug: remove confusing header on "Edit Insight Page" page

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#1804]
### Describe the bug

When I go edit an existing user page, the top component looks confusing/out of place

Can we remove this component? (highlighted in red)
<img width="1171" alt="image" src="https://github.com/open-sauced/app/assets/27322879/8f843c72-9d4b-4afe-9da4-b94b067c5b38">

In contrast, this is what the "New Insight Page" page looks like. We should make them look the same:
<img width="1522" alt="image" src="https://github.com/open-sauced/app/assets/27322879/b8a387a9-3c4c-41ba-bb17-dd0ded723a45">

### Steps to reproduce

1. Go to the Insights Hub
2. Click on an Insight Page
3. Click on "Edit Page"
4. You will see the component at the top of the page

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Tushar2930** [comment]
Hi assign this issue to me

**Comment by jpmcb** [comment]
Hi @Tushar2930 - looks like @OgDev-01 already has a PR up for this. Assigning him.
