### ISSUE TITLE
Feature: Onboarding helper "toasts"

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#1805]
### Type of feature

🍕 Feature

### Current behavior

When users sign up today they kind of just get thrown into the platform with little to no context. I think it'd be benefitial to offer some guidance.

### Suggested solution

To guide users through the app the first time that they signup we could create some helper toasts to explain what's going on. Kind of like a light-weight user feature onboarding. I figure it could look something like this:

<img width="1229" alt="image" src="https://github.com/open-sauced/app/assets/27322879/e100adda-1b3e-4389-b816-fa9de637e024">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
Is this blocked on copy @isabensusan? Perhaps we can see this get added to Papercuts this week. This would be helpful for our users.

**Comment by nickytonline** [comment]
Just following up on this @isabensusan.

**Comment by brandonroberts** [comment]
Will need to revisit this with public workspaces
