### ISSUE TITLE
Bug: user search only surfaces OpenSauced users

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#1810]
### Describe the bug

Using the search for users who we don't have in our `users` database table results in no results:

<img width="704" alt="Screenshot 2023-10-05 at 8 39 29 AM" src="https://github.com/open-sauced/app/assets/23109390/62e37fe1-73d5-4ceb-a879-338999c957e3">

Even though those users do show up on our platform:

https://insights.opensauced.pizza/user/rafiramadhana

This is due to some of our backfilling services that don't pick up users even if we have indexed pull requests or other contributions from them.

### Steps to reproduce

1. Go to https://insights.opensauced.pizza/user/rafiramadhana
2. Notice that the call `GET | https://api.opensauced.pizza/v1/users/rafiramadhana` results in 404 Not Found (this user isn't in our users database)
3. But we _have_ indexed PRs that are associated with this `author_login` resulting in some contributions showing up.

### Browsers

Chrome, Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
It would also be nice to make search more aware of who you follow and fuzzier. When searching Bekah, she appears last and I have noticed this multiple times when attempting to find folks. They either don't show or show last. 

<img width="1450" alt="Screen Shot 2023-11-10 at 6 03 19 PM" src="https://github.com/open-sauced/app/assets/5713670/abd16f89-a891-4d92-8470-81124f1355f5">
