### ISSUE TITLE
Feature: Insights/Lists - move date filter from individual charts to header

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#1815]
### Type of feature

🍕 Feature

### Current behavior

Right now, on Insight Pages there is no global date filter. The only filterable component is the repositories and contributors table, making it a bit confusing.

For the initial design of the list feature we wanted to do individual filters for each chart, but realized a global one would be better.

## Goal
Implement global date filter on Lists and Insight Pages.
- Add the date filter to the header on every tab of the List and Insight pages
- It should be usable on every tab (we can disable it on the reports tab until we figure out what we want to do with reports)
- The state should persist as the user navigates the tabs. ie. If I'm on the Dashboard Tab and I select "30d", if I then navigate to the Contributors tab, the filter value should still be "90d"
- filter values should be 7d / 30d / 90d  (it's currently 3m instead of 90d on some screens)
- default value should be 30d

## Mockups
These are quick mockups so alignment might not be perfect. Just align the filter vertically to the navigation tabs, and horizontally it should align to the right with the rest of the components on the page.

Insight pages:
![image](https://github.com/open-sauced/app/assets/27322879/0618a45e-8740-4f3a-a345-291e2163ba0c)

Lists:
![image](https://github.com/open-sauced/app/assets/27322879/5545fbb8-9202-4937-9933-fd6e010d586f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by isabensusan** [comment]
@nickytonline here's some mockups for the date filter on the list page! 

It'd be great if we can also add it to insight pages to keep the consistency.

**Comment by nickytonline** [comment]
> @nickytonline here's some mockups for the date filter on the list page! 
> 
> 
> 
> It'd be great if we can also add it to insight pages to keep the consistency.

I have it in the list activity page, but I'll add it to the list pages tomorrow.

**Comment by nickytonline** [comment]
I've tackled this for the list pages.

**Comment by nickytonline** [comment]
@OgDev-01, at some point can you tackle this for the Insights pages? Thanks!
