### ISSUE TITLE
Refactor: use `ClientOnly` component on places we have encountered hydration issues before 

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/app#1821]
We now have a new `Client only component https://github.com/open-sauced/insights/blob/beta/components/atoms/ClientOnly/client-only.tsx

### List of areas where state was used
- https://github.com/open-sauced/app/blob/3f5a01333b68ded67eb4ebac84cfc491f6dc4109/pages/feed/index.tsx#L69-L70
- https://github.com/open-sauced/app/blob/3f5a01333b68ded67eb4ebac84cfc491f6dc4109/pages/hub/lists/new.tsx#L31-L32
- https://github.com/open-sauced/app/blob/3f5a01333b68ded67eb4ebac84cfc491f6dc4109/pages/pages/%5BuserOrg%5D/%5BfilterName%5D/%5BtoolName%5D.tsx#L21
- https://github.com/open-sauced/app/blob/3f5a01333b68ded67eb4ebac84cfc491f6dc4109/pages/user/%5Busername%5D/index.tsx#L72

### Suggested solution
Replace the state implementation with the `ClientOnly` component

**Comment by nickytonline** [comment]
Just a heads up on the `<ClientOnly />` component. 

it looks live the above spots should be fine to plug it in, but the general rule is we want to server render as much markup as possible, so sometimes it's only a small component within a larger component that needs to be wrapped. I'm going to create a video about this when I have some time.

**Comment by Cerchie** [comment]
I think I just experienced this in lists/new.tsx. To replicate, run locally, then run 'Edit list' -> 'Add contributor' -> 'Done' and get this error: 

<img width="1473" alt="Screenshot 2024-01-04 at 2 54 56 PM" src="https://github.com/open-sauced/app/assets/54046179/017ba95c-ac2c-4153-9f7a-d6f5460dd2a5">

**Comment by brandonroberts** [comment]
We are refactoring these as we come across them
