### ISSUE TITLE
Use first-person in blog post highlight auto-summarize

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#1826]
When you use the auto-summarize tool, the description is currently in the third-person: "The author shares insights on how to...."

To create a quicker user experience, it would be nice if the description is in first person: "I share insights into how to ..."

**Comment by diivi** [comment]
This is a backend issue, https://github.com/open-sauced/api/blob/beta/src/blogs/issue-summary.service.ts#L10 these lines need to be changed. Whoever does this, renaming the files from `issue-x` to `blog-x` would also be helpful.

**Comment by SoundaryaKoutharapu** [comment]
Hi @diivi,
can you confirm that these changes are fine.?

 private generatePrompt(language: string, maxLength: number, tone: string) {
  return [
    **`I will generate a blog summary for a blog with the specifications mentioned below`,**
    `The summary should be written in ${tone} tone in the first person`,
    `Summary language: ${language}`,
    `The summary will be a maximum of ${maxLength} characters.`,
    "Please exclude anything unnecessary, such as translation. My entire response will be used to summarize and analyze the blog.",
  ].join("\n");
}

**Comment by diivi** [comment]
I think the prompt should work fine if you just add the "first person" part. Trial and error will help here. Everything else that addresses the LLM is fine in second person.

**Comment by SoundaryaKoutharapu** [comment]
@diivi can I proceed with the pr

private generatePrompt(language: string, maxLength: number, tone: string) {
  return [
    **`I will generate a blog summary for a blog with the specifications mentioned below.`,
    `The summary should be written in the first person with a ${tone} tone.`**,
    `Summary language: ${language}`,
    `The summary will be a maximum of ${maxLength} characters.`,
    `Please exclude anything unnecessary, such as translation. My entire response will be used to summarize and analyze the blog.`,
  ].join("\n");
}
