### ISSUE TITLE
Feature: replace "Get Card" CTA for "Add to List" dropdown

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#1828]
### Type of feature

🍕 Feature

### Current behavior

These are the current CTAs in the header component on User Profile pages:
<img width="482" alt="image" src="https://github.com/open-sauced/app/assets/27322879/3e3ab9ad-3106-49b9-97e6-6c5822d5f499">

### Suggested solution

We want to replace the current "Get Card" CTA with a new "Add to list" CTA. 
- This CTA would trigger a dropdown where the user can see the lists they have and add the user to a list.
- The dropdown should be a multiselect dropdown, where the user can select more than one list

There is a new design for the "Get Card" CTA, but as we ship that, we can move the "Get Card" option to the three dot menu

<img width="519" alt="image" src="https://github.com/open-sauced/app/assets/27322879/24f53eeb-a965-40f4-bf80-44aacdc662fd">

If the user has no lists, show a "You have no lists" message in the dropdown and add a link to the "New List" page.

<img width="1111" alt="image" src="https://github.com/open-sauced/app/assets/27322879/fd231423-d740-4659-988f-d25b3b62fa73">

### Update on "Get Card" CTA
We are moving the action to a new icon button  -- see issue #1829 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
The select looks good. Maybe as it gets more popular we could add the filter option on the select like we have elsewhere (can't remember where).

**Comment by isabensusan** [comment]
@nickytonline I'm thinking we can re-use @OgDev-01 's new [multi-select component](https://design-insights.netlify.app/?path=/docs/design-system-atoms-multiselect--docs):
<img width="348" alt="image" src="https://github.com/open-sauced/app/assets/27322879/58d616f8-c68a-4bc9-b652-92640612d4d3">
