### ISSUE TITLE
Feature: New "Get card" CTA design on User Profile page

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#1829]
### Type of feature

🍕 Feature

### Current behavior

Right now, the "Get Card" CTA is shown in the header in user profile pages:
<img width="454" alt="image" src="https://github.com/open-sauced/app/assets/27322879/7dc8a520-8e09-4ecc-8101-9f752a5566fb">

### Suggested solution

Because we are shipping lists and want to incentivize usage, we want to replace the current "Get Card" CTA with a "Add to list" one, as mentioned in this issue -->  #1828 

In order to avoid hiding the "Get Card" action behind the 3 dot menu, I propose this new button design below the User Profile:

<img width="682" alt="image" src="https://github.com/open-sauced/app/assets/27322879/447d5f0f-78d3-48e1-9d74-b3ff2b916474">

Here's some more options for the icon design:
![image](https://github.com/open-sauced/app/assets/27322879/6e4916e0-1d08-4236-a45d-4a58dcacfddb)

We could also add a gradient for a fake "holographic" look 
<img width="693" alt="image" src="https://github.com/open-sauced/app/assets/27322879/692ddec4-e15f-4896-9ee9-416212bf7ebf">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by isabensusan** [comment]
@bdougie any thoughts? this is a quick idea and mock so very much open to feedback.

The rationale behind doing a fun icon is to make users curious about what that is, given that the dev cards are meant to be kind of an easter egg in a way

**Comment by bdougie** [comment]
l like it. I prefer A or B. They are both easier to decipher as a small icon. Though maybe B is preferred overall. Also the gradient is a nice touch.

**Comment by nickytonline** [comment]
I like A and also like A as a holographic icon.

**Comment by bdougie** [comment]
FWIW when I showed my 10 year old he said option A.

**Comment by isabensusan** [comment]
A it is! 🍕🍕 🍕 

Here's the SVG for the inner icon:
![pizza-id_gradient](https://github.com/open-sauced/app/assets/27322879/ba418f36-8810-4900-bf38-bbc608a15de5)
![pizza-id_white](https://github.com/open-sauced/app/assets/27322879/9658fd15-93c7-44f0-9bfb-3f454a8ce676)


CSS for the gradient: background: conic-gradient(from 180deg at 50% 50%, #FF6A06 0deg, #FF6492 120.00000357627869deg, #FFE22C 223.12500715255737deg, #FC620D 360deg, #FF7E33 360deg);

**Comment by isabensusan** [comment]
@OgDev-01 

<img width="654" alt="image" src="https://github.com/open-sauced/app/assets/27322879/b511694d-2ba2-4b9e-a5f9-ca8e59eda73a">
here's what we want for the look: 
- button should be 46px x 46px
- stroke 2px
- svg 20x26px aprox
