### ISSUE TITLE
Feature: add license section to readme.md

### ISSUE THREAD

**Issue by shelar1423** [open-sauced/app#1835]
### Type of feature

🍕 Feature

### Current behavior

No license section existing

### Suggested solution

Adding license section and linking it with LICENSE.md

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by shelar1423** [comment]
want to work on this kindly assign me this

**Comment by CBID2** [comment]
> want to work on this kindly assign me this

Hi @shelar1423! :) Thanks for your interest, but we have a license section [here](https://github.com/open-sauced/app/blob/beta/LICENSE), so I'm going to close this issue now. In the future, I suggest looking through the project thoroughly before raising an issue.
