### ISSUE TITLE
Feature[DOCS]: Add Gitpod and CodeSpaces link to README 

### ISSUE THREAD

**Issue by CBID2** [open-sauced/app#1837]
### Type of feature

🍕 Feature

### Current behavior

In my experience working with open source beginners, sometimes the directions to setting up a code environment do not always pan out, which creates a frustrating experience. Furthermore, some might not be able to afford their own computer and can only use virtual IDEs.

### Suggested solution

Adding links to [CodeSpaces](https://github.com/features/codespaces) and [Gitpod](https://www.gitpod.io/) to the Readme can make it easier for open source beginners to get started. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by heysagnik** [comment]
I would love to work on this

**Comment by CBID2** [comment]
> I would love to work on this 

Hi @heysagnik! :) This idea has been on my mind for while, so I wanted to do it.

**Comment by heysagnik** [comment]
Oh ok then

**Comment by CBID2** [comment]
> Oh ok then

Feel free to give feedback. It's #
