### ISSUE TITLE
Bug: delete list dialog input state doesn’t reset after deleting a list

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/app#1848]
### Describe the bug

The input in the delete list dialog does not reset when a list is deleted
https://github.com/open-sauced/app/assets/62995161/588d0561-2d35-43c9-9797-130e76d13c46

### Steps to reproduce

1. Visit https://beta.insights.opensauced.pizza/hub/lists
2. click on the delete icon for a list and follow the instruction to delete the list
3. try deleting another list afterward...

### Browsers

Chrome

### Additional context (Is this in dev or production?)

Clear the input state when a list is deleted succesfully

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 5hraddha** [comment]
.take
