### ISSUE TITLE
Feature: Ability to create a new list from a user profile page

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#1872]
### Type of feature

🍕 Feature

### Current behavior

You can't create a list from a user profile page, only add a user to one.

### Suggested solution

Add an option to type in a non-existent list and create it. cc: @isabensusan, would love your feedback on this potential flow.

![CleanShot 2023-10-11 at 14 42 46](https://github.com/open-sauced/app/assets/833231/8d4a5f51-afe5-4509-ad30-6b05a37304e4)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
Closing as resolved by https://github.com/open-sauced/app/pull/1843
