### ISSUE TITLE
Bug: Scrollbar appears in list header

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#1874]
### Describe the bug

A scrollbar appears in list header.

![CleanShot 2023-10-11 at 16 26 54](https://github.com/open-sauced/ai/assets/833231/9515b324-7444-46fd-a6fe-c576ff82c2ae)

### Steps to reproduce

1. Navigate to a list, e.g. https://app.opensauced.pizza/lists/04a518a0-87f7-47ad-89e9-784f4b376941/overview
2. As you start to resize a window and make it smaller, an unnecessary scrollbar appears that is not required as all the content is still viewable.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Satoshi-Sh** [comment]
Can I take this issue?

**Comment by takanome-dev** [comment]
@Satoshi-Sh sure, go ahead :+1:
