### ISSUE TITLE
Bug: Hover tooltips in repo/contributors graph should match color of repo/user block

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#1875]
### Describe the bug

The hover tooltips in repo/contributors graph should match colour of repo/user block.

### Steps to reproduce

1. Navigate to a list activity page, e.g. https://app.opensauced.pizza/lists/04a518a0-87f7-47ad-89e9-784f4b376941/activity
2. Hover over a repository in the graph.
3. Notice the little square in the hover tooltip is not the same colour as the same as the square (repo/contributor) that it's hovering over.

![CleanShot 2023-10-11 at 16 44 56](https://github.com/open-sauced/app/assets/833231/a1044b9a-4d92-403b-abb6-d67cc1da39c9)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by tarunclub** [comment]
.take
