### ISSUE TITLE
Feature: Adding contributors section to the readme.md file.

### ISSUE THREAD

**Issue by Kalyanimhala** [open-sauced/app#1879]
### Type of feature

📝 Documentation

### Current behavior

There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
 It motivates contributors, as seeing their names listed provides recognition and can encourage ongoing involvement.
Any contributions make are greatly appreciated, for that we need to add new section for contributors and adding to the readme file!

### Suggested solution

 By adding contributors section to the readme.md file.
![contributors](https://github.com/open-sauced/app/assets/147402107/44ff7cc0-5fdc-4760-8e5c-8096e46f7ce6)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Kalyanimhala** [comment]
Kindly assign me #1879 this issue, I want to work on it.

**Comment by ghoshRitesh12** [comment]
Hey I would like to work on issue #1879. Can this be assigned to me?

**Comment by bdougie** [comment]
I don't think this is ready to start working on.

## not an issue
I appreciate the willingness to work on this but no who has requested has read the readme or contributing.md

I'd rather solve that issue. Our contributing guide explains how to assign yourself.

## redundant

Automating the addition of avatars  sounds useful but it would be ideal if a solution was proposed prior to assigning. 

What is the approach?

## all contributors
Perhaps all contributors is the solution, but I question is that is needed. 

Again I appreciate the willing contributors and contributions but I'd rather provide a path to grow the contribution community and build relationships with contributors in our discord. 

## question
What prevents contributors from opening low effort pull requests only for the opportunity to appear in the remade?

How do we encourage repeat contributions?

**Comment by Kalyanimhala** [comment]
But, if we appreciate the contributors by adding their images in Readme.md file they feel more encouraging and do the open source contributions more happily! @bdougie
