### ISSUE TITLE
Bug: application slowness with API session checks

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/app#1880]
### Describe the bug

From @nickytonline 

We've been experiencing really slow initial app load times. I did a bit of superficial digging, and it looks like we're seeing about 8 seconds of time being used on two calls to the `/session` endpoint.

![image](https://github.com/open-sauced/app/assets/42211/287a0642-0109-4642-a4c2-6782e96d9764)

It looks like it has to do with Tier access.

```
TierError: org not found
    at Tier.apiGet (file:///Users/nicktaylor/dev/work/app/node_modules/tier/dist/mjs/client.js:240:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Tier.lookupLimits (file:///Users/nicktaylor/dev/work/app/node_modules/tier/dist/mjs/client.js:293:16)
    at async handler (webpack-internal:///(api)/./pages/api/session.ts:33:25)
    at async /Users/nicktaylor/dev/work/app/node_modules/@sentry/nextjs/cjs/server/wrapApiHandlerWithSentry.js:136:35 {
  path: '/v1/limits',
  requestData: { org: 'org:833231' },
  status: 400,
  code: 'org_not_found',
  responseData: { status: 400, code: 'org_not_found', message: 'org not found' },
  cause: undefined
```

Related conversation: https://opensaucedworkspace.slack.com/archives/C052YRD69JN/p1696378566630229

![image](https://github.com/open-sauced/engineering/assets/833231/7cef595f-f199-455a-ad72-eef0a77ec344)

### Steps to reproduce

We've disabled this in #1840 for now but the original check was there

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
Once we reenable Tier stuff, udpate analytics as well. See https://github.com/open-sauced/app/pull/1958#discussion_r1366031713

**Comment by brandonroberts** [comment]
Note: Talked with the `tier.run` team, they recommended we enroll everyone through their Stripe API, free accounts and all, which makes the lookup faster.

**Comment by nickytonline** [comment]
I'm going to go ahead and close this and @brandonroberts mentioned it'll be faster with the latest tier integration. Correct me if I'm wrong here Brandon.
