### ISSUE TITLE
Feature: Open links in the contributor highlights card in a separate tab

### ISSUE THREAD

**Issue by k1nho** [open-sauced/app#1891]
### Type of feature

🍕 Feature

### Current behavior

Links in the ```contributor-highlight-card``` component do not open in a new tab, which requires the user to then navigate back to the highlights.

### Suggested solution

Add ```target="_blank"``` and ```rel="noreferrer"``` attributes as it appears in many other anchor elements.

Check this file to start: [contributors-highlight-card.tsx](https://github.com/open-sauced/app/blob/c8c5ffc889eb16e8f752f7f1fda097273a7b330d/components/molecules/ContributorHighlight/contributor-highlight-card.tsx#L558C11-L558C11)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
Is rel=noreferrer needed? The think we would want to know when a profile tab is opened and where it was opened from.
