### ISSUE TITLE
Bug: The Create New List form is not having proper horizontal padding /spacing on smaller screens

### ISSUE THREAD

**Issue by 5hraddha** [open-sauced/app#1895]
### Describe the bug

The **Create New List** form at `/hub/lists/new` page is not having proper horizontal padding /spacing on smaller screens. 

https://github.com/open-sauced/app/assets/27571141/0d2a3b84-0b6a-42fc-9ae7-ba18609992bd

**Possible Solution**
The **Create New Insight Page** form at `/hub/insights/new` has proper flow to responsiveness. We can probably keep the same for the **Create New List** form.

### Steps to reproduce

1. Go to Create List page - `/hub/lists`.
2. Click the button - **Create a new List**. You're navigated to **Create New List** form at `/hub/lists/new` page.
3. Now, open DevTools and view the page in Responsive Mode.
4. Try viewing the page on smaller screen widths, you'll notice the lack of proper horizontal padding / spacing around the form. It's almost like the form touches the edges of the screen.

### Browsers

Chrome

### Additional context (Is this in dev or production?)

Saw this bug in production by navigating [here](https://app.opensauced.pizza/hub/lists/new)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 5hraddha** [comment]
I'll .take this if team is okay with the updates. Thanks!

**Comment by OgDev-01** [comment]
> I'll .take this if team is okay with the updates. Thanks!

Go for it 👍
