### ISSUE TITLE
Bug: The Three Dots at the Highlight Card Immediately Close on Click 

### ISSUE THREAD

**Issue by adiati98** [open-sauced/app#1896]
### Describe the bug

When clicking the three dots in the highlight card to open the options, it immediately close.

## Screen Recording

It's difficult to create a screen recording as it closes right away in milisecond. But hopefully the behaviour is captured well here.

![three dots highlight card opensauced](https://github.com/open-sauced/app/assets/45172775/dce28091-faaf-4721-85a1-f07e44383c53)

### Steps to reproduce

1. Go to the profile page on the insights.
2. Click the day on the left side of one of the highlights to open the card.
3. Click the three dots.
4. It will close immidiately.

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by tarunclub** [comment]
I will .take this issue
