### ISSUE TITLE
Bug: Contributions Discrepancy in Insight App card and OpenSauced Profile

### ISSUE THREAD

**Issue by dev-phantom** [open-sauced/app#1902]
### Describe the bug

I've noticed a discrepancy in the contributions displayed within the Insight app, particularly in the card section. Previously, my contributions were reflected as shown in the following screenshot:

**Previous contributions**
![1693928638130](https://github.com/open-sauced/app/assets/72051159/326f38e5-c6ba-4224-8df5-4c5eb07f0c50)

However, my current contributions in the Insight app's card are displaying differently, as shown in this screenshot:

**Current contributions**

**![Screenshot_20231014-110527](https://github.com/open-sauced/app/assets/72051159/25429819-cdde-4774-bab6-da8b9b84c550)**

This inconsistency is not limited to my contributions but is also observed in the contributions of user @bdougie , as their card previously showed 4 PRs created and 4 repositories, but now it displays 2 PRs created and 2 repositories.

Additionally, it's worth noting that these contributions have also been removed from my "Contributions" tab in my OpenSauced profile.

**Expected Behavior:**

Contributions in the Insight app, especially in the card section, should accurately reflect the user's activity and remain consistent over time. The contributions should also be reflected in the "Contributions" tab of the user's OpenSauced profile.

**Actual Behavior:**

The contributions have changed in the Insight app card, and they have been removed from the "Contributions" tab of my OpenSauced profile.

**Additional Information:**

- Device/Platform: Tecno spark 4 (mobile)
- OpenSauced Profile: [dev-phantom profile](https://app.opensauced.pizza/user/dev-phantom)

### Steps to reproduce

1. Go to [dev-phantom profile](https://app.opensauced.pizza/user/dev-phantom)
2. Click on the card icon
3. See error 

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by BekahHW** [comment]
@dev-phantom sorry for the late response on this. We have a fix in place that should be shipped soon.

**Comment by brandonroberts** [comment]
Closing as part of DevCard refresh
