### ISSUE TITLE
Bug: Remove "Add New Insight" Header When Creating a New Insight

### ISSUE THREAD

**Issue by dev-phantom** [open-sauced/app#1904]
### Describe the bug

Currently, when creating a new insight on the platform, there is an unnecessary "Add New Insight" header that appears. This header serves no functional purpose and is not consistent with the user experience. The "Create New Insight" page should start without this additional header, similar to how the "Add New List" tab functions.

**Proposed Enhancement:**

I propose removing the "Add New Insight" header when creating a new insight. The page should directly start at the "Create New Insight" section without any redundant header.

**Reason for the Proposed Approach:**

This approach offers several benefits:

1. **Simplified User Experience:** Removing the redundant header streamlines the process and eliminates unnecessary visual clutter, making it easier for users to focus on creating insights.

2. **Consistency:** Aligning the behavior with the "Add New List" tab creates a more consistent and intuitive user experience across the platform.

**Expected Behavior:**

The "Create New Insight" page should start without the "Add New Insight" header.

**Additional Information:**

- Device/Platform: Tecno spark 4 (mobile)
- Screenshots: 
This is what we have currently 
![Screenshot_20231016-200624](https://github.com/open-sauced/app/assets/72051159/71fe2670-0185-4f1c-95ce-710cb361dae2)
I think it's better like this
![Screenshot_20231016-201558](https://github.com/open-sauced/app/assets/72051159/e7bc6039-8c87-488e-8ea4-8b141d2faa55)

**Note:** I believe that implementing this enhancement will improve the user experience and make the process of creating insights more straightforward and consistent with other functionalities on the platform. Thank you for considering this improvement.

### Steps to reproduce

1. Log in to the insight app
2. Navigate to the "Create New Insight" page.
3. Click on the add insight button 
4. Observe the presence of the "Add New Insight" header.

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by dev-phantom** [comment]
I guess this ought to be a feat request

**Comment by OgDev-01** [comment]
closing this as completed in https://github.com/open-sauced/app/pull/1925
