### ISSUE TITLE
Feature: provide better social links for profiles 

### ISSUE THREAD

**Issue by andypiper** [open-sauced/app#1905]
### Type of feature

🍕 Feature

### Current behavior

Currently the project focuses on LinkedIn and Twitter as social links for user profiles. Twitter no longer exists (now called X) and many open source contributors prefer other platforms such as fediverse alternatives. 

### Suggested solution

Provide the ability to insert alternative social profile links into the Open Sauced profile.

### Additional context

GitHub itself expanded the list of options for profile links to enable developers to no longer be limited to X.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by dev-phantom** [comment]
Can you add a screenshot of the current behavior?

**Comment by nickytonline** [comment]
Thanks for opening the issue @andypiper! @dev-phantom, they're mentioning supporting more social links like GitHub, e.g. here's my GitHub profile, and here's my OpenSauced profile.

![CleanShot 2023-10-16 at 16 13 47](https://github.com/open-sauced/app/assets/833231/e0652544-986c-45ce-98bb-648299207c3a)


![CleanShot 2023-10-16 at 16 15 04](https://github.com/open-sauced/app/assets/833231/4f04513b-3fc6-444a-ad24-92b6f8c276c6)

**Comment by dev-phantom** [comment]
> Thanks for opening the issue @andypiper! @dev-phantom, they're mentioning supporting more social links like GitHub, e.g. here's my GitHub profile, and here's my OpenSauced profile.
> 
> ![CleanShot 2023-10-16 at 16 13 47](https://user-images.githubusercontent.com/833231/275639332-e0652544-986c-45ce-98bb-648299207c3a.png)
> 
> ![CleanShot 2023-10-16 at 16 15 04](https://user-images.githubusercontent.com/833231/275639456-4f04513b-3fc6-444a-ad24-92b6f8c276c6.png)

Oh nice
Thanks for the clarity
