### ISSUE TITLE
Feature: Improve Button Placement for Creating Insights When No Insights Exist

### ISSUE THREAD

**Issue by dev-phantom** [open-sauced/app#1906]
### Type of feature

🍕 Feature

### Current behavior

Currently, when there are no insights present on the platform, there are two buttons to access the "Create New Insight" page, as observed in the provided screenshot. This layout is not optimal for user experience. The issue also extends to the "List" tab, where the same problem is encountered.

**The Problem:**

The current placement of two buttons for creating new insights is problematic for the following reasons:

1. **Confusing User Experience:** Having two buttons with equal importance can confuse users, as it's not immediately clear which one they should click to create a new insight. This ambiguity can lead to user frustration.

2. **Redundancy:** The presence of two identical buttons for the same action is redundant and does not provide any additional value to the user experience.

**Steps to Reproduce:**

1. Log in to the insight app.
2. Navigate to the insight tab or list tab.
3. Observe the presence of two buttons when no insights or list exist.

**Additional Information:**

- Device/Platform: Tecno spark 4 (mobile)
- Screenshots: 
![Screenshot_20231016-202218](https://github.com/open-sauced/app/assets/72051159/147d2b32-853e-49c0-941f-b0293161a9a0)

**Note:** Implementing this enhancement will enhance the user experience by providing a more intuitive and less cluttered interface. This change should also be extended to the "List" tab to maintain consistency. Thank you for considering this improvement.

### Suggested solution

I suggest the following change:

- When there are no insights present, it should retain the button highlighted in green in the screenshot for accessing the "Create New Insight" page and remove the button circled in red.

![Screenshot_20231016-203348](https://github.com/open-sauced/app/assets/72051159/52892ddb-55e2-446b-a669-7175fb55aeaf)

- else when insight exist it should retain the one circled in green and remove the one circled in red
![Screenshot_20231016-203410](https://github.com/open-sauced/app/assets/72051159/1610c699-7a35-4c09-9b47-8dda26487971)

**Reason for the Proposed Approach:**

This approach offers several benefits:

1. **Clarity:** It provides a clear and singular path for users to create new insights, reducing confusion and streamlining the user experience.

2. **Elimination of Redundancy:** By removing one of the duplicate buttons, the interface becomes less cluttered and more user-friendly.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
We're reworking this view at the moment, so blocking this for the moment.

**Comment by dev-phantom** [comment]
> We're reworking this view at the moment, so blocking this for the moment.

Please if I may ask what does the block label means?

**Comment by OgDev-01** [comment]
> Please if I may ask what does the block label means?

Paused 👍
