### ISSUE TITLE
Bug: Menu Items appear twice for insights and lists

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#1908]
### Describe the bug

Menu Items appear twice for insights and lists

### Steps to reproduce

1.Navigate to insights or lists.
2. Notice the double navigation.

![image](https://github.com/open-sauced/app/assets/833231/877f877c-9bff-4e22-b5a5-12c4008bc32f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
Relates to #1906

**Comment by nickytonline** [comment]
See discussion in https://opensaucedworkspace.slack.com/archives/C052YRD69JN/p1697055301248459

**Comment by BekahHW** [comment]
Updated version.

![image](https://github.com/open-sauced/app/assets/34313413/5b63f9a2-d734-4f52-91b5-d4fcd42a10dd)

**Comment by brandonroberts** [comment]
Closing as resolved with move to workspaces
