### ISSUE TITLE
Feature: Reduce Padding Between Suggested Repositories and Added Repositories on Create New Insight Page

### ISSUE THREAD

**Issue by dev-phantom** [open-sauced/app#1911]
### Type of feature

🍕 Feature

### Current behavior

I would like to request an enhancement for the "Create New Insight" page. Specifically, I suggest reducing the padding between the "Suggested Repositories" and "Added Repositories" sections. This change is intended to improve the user experience.

**Reason for the Proposed Enhancement:**

1. **Optimized Screen Real Estate:** The current padding between these sections consumes valuable screen space, especially on mobile devices. By reducing the padding, users can see more content on a single screen without excessive scrolling.

2. **Enhanced User Interaction:** Reducing the distance between "Suggested Repositories" and "Added Repositories" makes it more convenient for users to quickly review and select repositories to add to their insight. This streamlined interaction improves the overall usability of the "Create New Insight" page.

**Additional Information:**

- Device/Platform: Tecno spark 4 (mobile)
- screenshot:
![Screenshot_20231016-211843](https://github.com/open-sauced/app/assets/72051159/3314e1d1-bfeb-4cc4-85fd-f7e99a07269d)

**Note:** Implementing this enhancement will improve the user experience by making the "Create New Insight" page more efficient, especially on devices with limited screen space. Thank you for considering this improvement.

### Suggested solution

Adjust the padding between the "Suggested Repositories" and "Added Repositories" sections on the "Create New Insight" page to optimize screen space and enhance user interaction.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by dev-phantom** [comment]
Please can any maintainer please add 
`Good first issue` or `easy win ` to this

**Comment by 5hraddha** [comment]
I'll .take this
