### ISSUE TITLE
Bug: Create Highlight Button Overlaps Social Icons on Small Screens (Mobile Devices) in User Profile Footer

### ISSUE THREAD

**Issue by dev-phantom** [open-sauced/app#1913]
### Describe the bug

I've noticed a user interface issue on the user profile page that particularly affects small screens or mobile devices. The "Create Highlight" button, fixed to the bottom right corner, is partially overlapping some social icons in the footer. This overlap makes it challenging for users on mobile devices to click the social icons effectively.

**Problem Description:**

The overlapping "Create Highlight" button on small screens or mobile devices poses several problems:

1. **User Interaction Difficulty:** The overlap can obscure some social icons, making it difficult for mobile users to click their desired social platform's icon. This interferes with the user's ability to connect with the profile owner on various social media channels.

2. **Visual Clutter:** The overlap creates visual clutter and disrupts the overall appearance of the user interface on small screens.

**Suggested Solution:**

To address this issue on small screens or mobile devices, I suggest the following:

- Adjust the positioning of the "Create Highlight" button or the layout of the social icons in the footer to prevent overlap. The button should not interfere with the visibility and accessibility of the social icons, specifically on small screens.

**Additional Information:**

- Device/Platform: Small screens or mobile devices
- Screenshot:

![Screenshot_20231016-213919](https://github.com/open-sauced/app/assets/72051159/83613ad6-05f8-421c-bb73-1bfa95e6d268)

**Note:** Resolving this issue will enhance the user experience on mobile devices for the user profile page, ensuring that both the "Create Highlight" button and social icons are easily accessible and not visually obstructed. Thank you for addressing this concern.

### Steps to reproduce

1. Login to your opensauced insight app
2. Navigate to your user profile
3. Scroll down

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by dev-phantom** [comment]
Please can any maintainer please add 
`Good first issue` or `easy win ` to this

**Comment by RitaDee** [comment]
Hi @dev-phantom, 
This is what it looks like on a mobile device:
<img width="464" alt="image" src="https://github.com/open-sauced/app/assets/106407013/13b9bc43-439b-4e2f-b08f-13d0548769ad">

**Comment by dev-phantom** [comment]
> Hi @dev-phantom, This is what it looks like on a mobile device: <img alt="image" width="464" src="https://user-images.githubusercontent.com/106407013/275755010-13b9bc43-439b-4e2f-b08f-13d0548769ad.png">

Take this as a [reference](https://github.com/open-sauced/landing-page/issues/139#issuecomment-1655740186) to reproduce it

**Comment by RitaDee** [comment]
> > > Hi @dev-phantom, This is what it looks like on a mobile device: <img alt="image" width="464" src="https://user-images.githubusercontent.com/106407013/275755010-13b9bc43-439b-4e2f-b08f-13d0548769ad.png">
> > 
> > 
> > Take this as a [reference](https://github.com/open-sauced/landing-page/issues/139#issuecomment-1655740186) to reproduce it
> 
> Oh, I see. What mobile device are you using? 

I am asking because this is smaller than the former screen size I referenced, and it still looks good:

<img width="1067" alt="image" src="https://github.com/open-sauced/app/assets/106407013/c5fc3b58-eb4f-4acd-9bb1-924326cfefbe">


It gets messy at this point:

<img width="761" alt="image" src="https://github.com/open-sauced/app/assets/106407013/33c3d865-2d3b-475c-9776-8d0ecacdb350">

**Comment by dev-phantom** [comment]
> > > > Hi @dev-phantom, This is what it looks like on a mobile device: <img alt="image" width="464" src="https://user-images.githubusercontent.com/106407013/275755010-13b9bc43-439b-4e2f-b08f-13d0548769ad.png">
> > > 
> > > 
> > > Take this as a [reference](https://github.com/open-sauced/landing-page/issues/139#issuecomment-1655740186) to reproduce it
> > 
> > 
> > Oh, I see. What mobile device are you using?
> 
> I am asking because this is smaller than the former screen size I referenced, and it still looks good:
> 
> <img alt="image" width="1067" src="https://user-images.githubusercontent.com/106407013/275775895-c5fc3b58-eb4f-4acd-9bb1-924326cfefbe.png">
> It gets messy at this point:
> 
> <img alt="image" width="761" src="https://user-images.githubusercontent.com/106407013/275776358-33c3d865-2d3b-475c-9776-8d0ecacdb350.png">

I'm using a Tecno spark 4 android mobile

In this [reference](https://github.com/open-sauced/landing-page/issues/139#issuecomment-1655740186) I added a screenshot of my screen width

**Comment by dev-phantom** [comment]
I can't help but notice a lot of errors in your console 🙂

**Comment by nickytonline** [comment]
There's been some discussion about a flyout button (like the Tweet button on X/Twitter that allows you to create a new Tweet, Spaces etc.)

Also, this relates to overhauling the mobile view for highlights and that button might actually disappear with those improvements.

Related to #1790.
