### ISSUE TITLE
Feature: improve UX when using dialogs on mobile with drawer like effects

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/app#1919]
### Type of feature

🍕 Feature

### Current behavior

Dialogs appear in the middle of the screen on desktop and mobile

### Desktop
![image](https://github.com/open-sauced/app/assets/62995161/51dacf2a-332f-4914-98d7-aea222c63b0b)

### Mobile
![image](https://github.com/open-sauced/app/assets/62995161/563b2e14-72c5-4048-a8c6-75a1e4c56a55)

From the above screenshot examples, the dialog pop-up looks great on the desktop but not on mobile... 
It would be more intuitive to have a bottom drawer-like behavior like the screen recorded below

https://github.com/open-sauced/app/assets/62995161/a203d465-674f-4c60-b941-7721ae454567

We've had this discussion on Zoom with @nickytonline and @isabensusan... opening this issue so we can discuss on the best ways to approach this. 

### Suggested solution

We could leverage 
- [react-bottom-drawer](https://github.com/fpellicero/react-bottom-drawer) library for this, but I can see it's no longer maintained 😢 .
- Another approach is creating a drawer from scratch with accessibility in mind

I'm open to more suggestions and approach to achieving this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
Will revisit this in the future. Closing this one for now
