### ISSUE TITLE
Enhancement: use SSR on feeds page

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/app#1920]
Currently `/feed` route uses client-side data fetching. Switching to SSR will improve load time and reduce skeleton loaders seen on first visit.

### List of resources to fetch in SSR
- logged in users data
- highlighted repos
- featured highlights
- followers highlights
- followers highlighted repos

fetching these resources in the server will help improve the page load speed on initial render

**Comment by brandonroberts** [comment]
Will revisit this in the future. Closing this one for now
