### ISSUE TITLE
Feature: Add informational nav popup to app

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#1931]
### Type of feature

🍕 Feature

### Current behavior

We currently don't have a way for users to find more information about our product, provide feedback, and get to our content. 

### Suggested solution

Let's add an informational popup to the app. We want to provide an enhanced user experience for both logged in and logged out users. 

The popup should include links to:
- docs
- feedback form
- bug reports
- blog
- community

Including these resources in the popup will allow for more user guidance about the product, help the users to understand how to make the most out of the platform, create community engagement through a feedback loop and issue reporting, and help us track user behavior to determine what to prioritize in terms of UX.

Here's an example of what I mean:
![image of popup from posthog](https://github.com/open-sauced/app/assets/34313413/1628c626-14c1-42bd-83ee-b11034ab7742)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by ATREAY** [comment]
hey @BekahHW, I would like to work on this issue.
.take

**Comment by ATREAY** [comment]
Hey @BekahHW, I have a quick question. Is it OK if I add "pop up" in the location like it's shown in the below images? 

After logging in:
![login](https://github.com/open-sauced/app/assets/66585295/18ad80b5-af90-4373-b966-d3d460f5da45)

After logging out:
![logout](https://github.com/open-sauced/app/assets/66585295/6a1cc51f-2bbd-4a94-8a73-50a8fc001e2c)

**Comment by OgDev-01** [comment]
Hey @ATREAY, thanks for your interest on this feature 👍. ATM, the core team are still traiging this and we are not yet at the point to start work on this. in the mean time, you could checkout other bug issues that does not have the `needs-triage` and `core-team-work` label to work on. 🍕

**Comment by isabensusan** [comment]
@BekahHW I love this, but I would wait until we have our docs in a better place and more related to the platform before adding a direct access on there. 

I'm adding this to our product agenda for tomorrow.

**Comment by BekahHW** [comment]
@isabensusan, with pricing turned on, it would be useful to add an "Upgrade Account" button here. There's some other interesting nav links here.

![GH menu](https://github.com/open-sauced/app/assets/34313413/1ea11eae-99af-42ff-af95-d8c9327ddd17)

**Comment by isabensusan** [comment]
fixed by #2533
