### ISSUE TITLE
Bug: Public env file

### ISSUE THREAD

**Issue by Aadarsh805** [open-sauced/app#1932]
### Describe the bug

The `.env` file is public on the repo, not sure if it's intentional

### Steps to reproduce

Go to https://github.com/open-sauced/app/blob/beta/.env

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by DimitriTsikaridze** [comment]
those variables are named PUBLIC_URL so I think it's intentional.

**Comment by nickytonline** [comment]
Thanks for checking this @Aadarsh805! This is supposed to be in the project.
