### ISSUE TITLE
Bug: Change Add to List Button text to Create List

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#1935]
### Describe the bug

When a user creates a new list, they are given an open to add new contributors. When they select a contributor, the disabled "Add to List +" button is enabled. 

When you click "Add to list," it doesn't add the contributor, it creates the list. 

https://github.com/open-sauced/app/assets/34313413/3fe99bf5-3174-421f-99b4-cc166e472168

 are prometed to 

### Steps to reproduce

 I think the simple fix here is to change the text from "Add to List" to "Create List"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 5hraddha** [comment]
I will .take this one

**Comment by nickytonline** [comment]
In [hub-contributors-header.tsx](https://github.com/open-sauced/app/blob/beta/components/molecules/HubContributorsHeader/hub-contributors-header.tsx#L98) change the following.

```diff
          <Button
            loading={loading}
            disabled={selectedContributorsIds.length === 0 || loading ? true : false}
            className={clsx(
              "bg-sauced-orange !text-white max-md:self-end order-1 md:order-2",
              selectedContributorsIds.length === 0 && "!bg-slate-300 !text-slate-100"
            )}
            variant="text"
            onClick={onAddToList}
          >
-            Add to List <FaPlus className="ml-2 text-lg" />
+            Create List <FaPlus className="ml-2 text-lg" />
          </Button>
```

**Comment by BekahHW** [comment]
Hey @5hraddha let's give someone new to this repository an opportunity to take this one. Thanks for all your contributions so far!

**Comment by 5hraddha** [comment]
Sure, @BekahHW 👍

**Comment by Satoshi-Sh** [comment]
Is that fine for me to work on this? This will be my second contribution. @BekahHW  .take

**Comment by BekahHW** [comment]
@PC-11-00  have you worked on an issue in this repo before? If not, you can assign yourself the issue. Take a look at our contributing guide if you don't know how.

**Comment by PC-11-00** [comment]
@BekahHW No i have not worked before on any issue in this repo. I will read the contribute guide thanks

**Comment by nickytonline** [comment]
@PC-11-00, @Satoshi-Sh id already assigned this issue.
