### ISSUE TITLE
Bug: Spelling error on Delete List Message

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#1937]
### Describe the bug

When you delete a list, there's a modal that let's the user know that they'll "loose access"

![image](https://github.com/open-sauced/app/assets/34313413/48eb5315-1a4f-46bd-99ef-77c617ffd42b)

## Steps
1. Go to your lists page.
2. Click the trash icon
3. Modal pops up.

## Fix
- Change "loose" to "lose"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by BekahHW** [comment]
Hey @dhruvmehtaaa check out our Contributing guide on how to self-assign the issue:https://docs.opensauced.pizza/contributing/introduction-to-contributing/

**Comment by ny-randriantsarafara** [comment]
Hi @BekahHW ! I see that there's already a commit mentioning this issue, but it's not assigned to anyone yet. Can I take it?

**Comment by codewithjazzy** [comment]
I can .take this issue

**Comment by codewithjazzy** [comment]
I can `.take` this issue

**Comment by codewithjazzy** [comment]
.take

**Comment by brainconnect93** [comment]
Can this issue be assigned to me, it is my first contribution. `.take`

**Comment by brainconnect93** [comment]
Can this issue be assigned to me, it is my first contribution. `.take`
