### ISSUE TITLE
Feature: add blocking labels to the take action

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#1947]
### Type of feature

📦 Chore

### Current behavior

Currently anyone can run `.take` and be assigned an issues, assuming no one is currently assigned.

This is great for external contributors, but it adds extra work to maintainers, when an issue needs for example triaging still.

### Suggested solution

The take action now supports blocking labels. Add the following blocking labels to the take action workflow, https://github.com/open-sauced/app/blob/beta/.github/workflows/triage.yml:

- `needs triage`
- `blocked`
- `core team work`
- `needs design`
- `duplicate`

```diff
name: "Assign issues with .take"

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  take-issue:
    name: Disable take issue
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: take an issue
        uses: bdougie/take-action@main
        with:
          issueCurrentlyAssignedMessage: Thanks for being interested in this issue. It looks like this ticket is already assigned to a contributor.
          token: ${{ secrets.GITHUB_TOKEN }}
+          blockingLabels: needs triage,blocked,core team work,needs design,duplicate
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
Does this list of labels sound good to everyone @open-sauced/staff?

**Comment by brandonroberts** [comment]
Looks good to me 👍
