### ISSUE TITLE
Feature: Add a create button to user profile

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#1967]
### Type of feature

🍕 Feature

### Current behavior

We want a user to have the opportunity to create new lists, insights, and highlights. Currently, they have to go to each individual feature to do that.

### Suggested solution

I suggest that we add a "Create" dropdown.

I think there are a couple of places we can add this. The Hitrecord community has a HUGE button in their navbar.

![image](https://github.com/open-sauced/app/assets/34313413/ddfcdb63-4cd8-4c96-ba2e-de44164a236a)

I don't recommend _that_, but I do like that when I click it, I get a variety of options.  

I think there's potential to add something similar here:
![image](https://github.com/open-sauced/app/assets/34313413/d1fa2653-ffe7-46f3-bd66-910fbaac6411)
![image](https://github.com/open-sauced/app/assets/34313413/3feab1d2-d9b7-4360-8319-7a0d324a83a7)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by a0m0rajab** [comment]
It could be added at the bottom right side of the screen I think google has a similar experience for that, but will need to check it.

**Comment by devharsh2k4** [comment]
Hey is it still open can i get assigned

**Comment by devharsh2k4** [comment]
.take

**Comment by nickytonline** [comment]
@devharsh2k4, please read the contributing guidelines.
