### ISSUE TITLE
fix: change collaborate to connect

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#1970]
We've rename collaboration to connections. 

Let's make sure the text is updated throughout the app. 

Currently, if you click the three-dot dropdown in your profile, it shows share and collaborate.

Let's make sure that gets updated and search for any other references to collaborate or collaborations and make the update.

![image](https://github.com/open-sauced/app/assets/34313413/452df15f-9be5-4af5-acf3-5e096a71a7cd)

**Comment by Shybymh** [comment]
.take

**Comment by itskish0re** [comment]
.take
