### ISSUE TITLE
Repo: add eslint rules for console.log and unused code

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/app#1972]
### Type of feature

📦 Chore

### Current behavior

In order to minimize nitpick items such as leftover console.log and commented out code, this adds those rules to the eslint config, so the build fails with an error. 

Our lint rules are here 

https://github.com/open-sauced/app/blob/beta/.eslintrc.json

It might involve cleanup of existing occurrences

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by brainconnect93** [comment]
Can you assign this to me `.take`

**Comment by brainconnect93** [comment]
@Brandon Roberts I would like to get more clarification on the task, I was able to get the console.log that is causing the build to fail with an error. So my question now is, Should I remove the console.log code or i should just comment them out?

Screenshot 👇 

![image](https://github.com/open-sauced/app/assets/78634841/acabec72-9971-4492-8e61-67ccd1319cdb)

**Comment by brandonroberts** [comment]
@brainconnect93 you can disable the eslint rule for the existing occurrences
