### ISSUE TITLE
Feature: Edit List Page

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#1977]
### Type of feature

🍕 Feature

### Current behavior

Users can't currently edit Lists

### [Figma file link](https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/Design-Lab?type=design&node-id=11428-10752&mode=design&t=N96wMixKQXsE4uUR-4)

**Parent Issue:**

### New Page - OPEN TO FEEDBACK
The idea is for users to be able to edit lists through a new "Edit list" page (we can reuse parts of the structure of the "Edit Insights Page" page).

This new page should allow users to:
- Edit the list name
- Edit page visibility
- Add new contributors
- See and remove existing contributors

![image](https://github.com/open-sauced/app/assets/27322879/1448bf2c-1d6f-43f0-b3f4-e9703c68398d)

### Removing Contributors
Users should be able to see a list of the contributors on the list, with the option to filter the list, and remove contributors.
When deleting a user, users should see a toast (reuse existing toast component) indicating that a user has been removed, and **with the option to undo the action and add the contributor back to the list (important!!)** .

Notes on usabilty:

![image](https://github.com/open-sauced/app/assets/27322879/5266d2e0-d891-4982-9926-287c24bdc98d)

### Adding contributors
The "add new contributors" button will take users to a new page, similar to the "explore contributors" page, here's the issue: #1978 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
@OgDev-01 do we have a component for the different style of pagination at the bottom?

**Comment by OgDev-01** [comment]
> do we have a component for the different style of pagination at the bottom?

Yes we do here
https://github.com/open-sauced/app/blob/3312bb6265a3818076a04a161cdcc634d1ba3e31/components/molecules/Pagination/pagination.tsx#L58-L71

We just have to tweak the conditions and it should all work 👍

**Comment by nickytonline** [comment]
@isabensusan, this doesn't block me at the moment, but for removing contributors, is there anywhere to indicate that someone has/is been removed? If not, I wonder if when we click remove from list, we remove them at that point with a little toast saying user X has been removed instead of the Save changes button up top?

![CleanShot 2023-11-01 at 15 14 39](https://github.com/open-sauced/app/assets/833231/38ccb3d7-e19c-412d-a000-b3576d3380ce)

Or if we still do it via the save button, maybe show in some way that some users are going to be removed if the user has removed some of them?

**Comment by nickytonline** [comment]
When the edited list is saved @isabensusan, e.g. in [this screen](https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/Design-Lab?type=design&node-id=11428-10029&mode=design&t=OVOLWX0sY7NaGzQP-11), do we add a toast as well, like we do for removed users (minus the undo) or was the Save changes CTA supposed to do something like a modal like when the list is first created? I'll go with toasts for now, and will adjust if needed.
