### ISSUE TITLE
Feature: add new contributors to list

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#1978]
### Type of feature

🍕 Feature

### Current behavior

N/A

### Context [(Figma File) ](https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/Design-Lab?type=design&node-id=11427-7254&mode=design&t=N96wMixKQXsE4uUR-4)
This issue is meant to elaborate on the "Add contributors" interaction from the new Edit List Page in issue #1977 

For reference, this is the start of this user flow:

<img width="2265" alt="image" src="https://github.com/open-sauced/app/assets/27322879/6aaeb3a1-d7d7-4e57-9309-8d3d7ad9fc8d">

### Default view
The idea is to reuse most of the ["Explore Contributors" page](https://app.opensauced.pizza/hub/lists/find?name=&public=false), but with some changes to the header and starting with an empty state on the table.

![image](https://github.com/open-sauced/app/assets/27322879/8e240166-8906-41cb-a2fc-d9bd70b8b236)

### User Search
Keeping the same interaction we have right now on the  ["Explore Contributors" page](https://app.opensauced.pizza/hub/lists/find?name=&public=false) table, users will be able to search for contributors, and add them to their list.
![image](https://github.com/open-sauced/app/assets/27322879/54e60874-a38d-4843-abcd-713409f44cf9)

### Success 

![CleanShot 2023-10-30 at 18 41 57](https://github.com/open-sauced/app/assets/833231/0888c9ba-2802-4fbf-abf0-6fcd68a235a8)

### Error
![image](https://github.com/open-sauced/app/assets/27322879/03f8322f-b6ee-4b94-820c-9836de1489ec)

### Search Empty State Asset 
Open in new tab to download
<img width="250" alt="image" src="https://github.com/open-sauced/app/assets/27322879/5a9eab57-cecc-4067-9a20-9c87676733db">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
@isabensusan when they go to add contribtors to the list from the grid is the flow after they've clicked add to list to redirect them back to the main edit list page?

This doesn't block me atm, so I can still work on the add users to list flow, but just want to understand the whole flow.

**Comment by nickytonline** [comment]
@isabensusan, if they want to keep adding other contributors, currently they can only go back to the list page from the success modal designs. Should another button be added, e.g. `Add More Contributors`?

Also, They come to this page from the edit list page, so shouldn't we redirect back to the edit list page instead of the list overview?

**Comment by isabensusan** [comment]
@nickytonline just saw the PR and it's looking great! To keep the conversation and answer your questions here:

To answer both:
>  when they go to add contribtors to the list from the grid is the flow after they've clicked add to list to redirect them back to the main edit list page?

and

> Also, They come to this page from the edit list page, so shouldn't we redirect back to the edit list page instead of the list overview?

That is a good point, I was working with the assumption that the most common use case would be that the user was adding contributors as a last step of their "editing" user journey, but it's true that going back to the originating context would be a better flow.

------

> Should another button be added, e.g. Add More Contributors?

I think this wouldn't hurt and would catch the edge case of someone adding contributors and realizing they missed someone. Can you add a secondary CTA with "Add more" ? Like this:

<img src="https://github.com/open-sauced/app/assets/27322879/7b10a712-70f9-42d7-a8ea-cd4e0c0dbb2f" width=400>

------

And finally, for the svg version of the empty state, here it is! 

![search-table_empty-state](https://github.com/open-sauced/app/assets/27322879/835ac5e7-f6f1-46b3-a107-4dc3ee7fc8ae)

**Comment by nickytonline** [comment]
Thanks @isabensusan!
