### ISSUE TITLE
Feature: Make user avatar on feed link to user profile

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#1981]
### Type of feature

🍕 Feature

### Current behavior

On the Highlights feed (app.opensauced.pizza/feed) on the user card only the user handle (ie @isabensusan) links to the user profile, but the expected interaction would be for the user photo to link to the profile too.

<img width="1104" alt="image" src="https://github.com/open-sauced/app/assets/27322879/7de815e0-794e-4117-8e05-9eb4e837eb1c">

### Suggested solution

Make both the handle and  the  user photo link to the user's profile.

<img width="1106" alt="image" src="https://github.com/open-sauced/app/assets/27322879/21b8f516-6d5f-4480-acf4-3ecef2417389">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by itskish0re** [comment]
.take

**Comment by itskish0re** [comment]
@brandonroberts, I am intrested to take this issue. Can you assign me this task?

**Comment by bdougie** [comment]
Please review the [CONTIBUTING.md](https://github.com/open-sauced/.github/blob/HEAD/CONTRIBUTING.md) for info on how to assign yourself to the issue.
