### ISSUE TITLE
Bug: Input background is white 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#1994]
### Describe the bug

<img width="533" alt="Screen Shot 2023-10-24 at 10 39 56 AM" src="https://github.com/open-sauced/app/assets/5713670/3ccea232-7a42-4c39-88df-3c835a861db0">

This is the user settings pages

### Steps to reproduce

Remove the background in the input. Please careful not to add regressions elsewhere. My guess is another form manually adds the background to white, maybe onboarding. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by itskish0re** [comment]
I will .take this issue.
