### ISSUE TITLE
Feature: account settings danger zone, same as insights with the a grey background

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#2027]
![image](https://github.com/open-sauced/app/assets/5713670/5bb9d1e3-69bb-42c9-aec1-d3fc3fede013)

Wanted to comment earlier before this was merged but the UI for the danger zone, same as insights with the a grey background 

![image](https://github.com/open-sauced/app/assets/5713670/4559ce73-da91-403a-a37e-99735480cbe9)

_Originally posted by @bdougie in https://github.com/open-sauced/app/pull/1990#issuecomment-1787995723_

**Comment by itskish0re** [comment]
I will .take this issue
