### ISSUE TITLE
Bug: list calculations not accurate when filtering in Activity tab

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2042]
### Describe the bug

When you look at the activity tab in lists, and then filter by new contributors, the grey description update isn't accurate. 

### Steps to reproduce

1. go to lists
2. change all contributors to new contributors
3. See changes to greyed out line

If you look at the recording below, there are two things to notice:
1. The percentage isn't possible
2. CBID2 isn't on the list of new contributors, and I would expect that line to reflect the filtered list.

https://github.com/open-sauced/app/assets/34313413/a217d209-431e-487f-b7e0-bb251846f3e1

There's one other thing I noticed, when I filter for the first time, the line is there but reads 0%. It might be worth leaving that empty until loading has completed.

![shows CBID2 with 0% while loading](https://github.com/open-sauced/app/assets/34313413/35ab41cd-f90a-47e1-b0db-8bd4f3aafc9e)

### Additional context (Is this in dev or production?)

production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 5hraddha** [comment]
Just going over the issue, realized that in `pages/lists/[listId]/activity.tsx`, the code always assigns the first element of the most active contributors data as the top contributor. It never changes with the change of filter:
```jsx
            <MostActiveContributorsCard
              data={contributorStats?.data ?? []}
              totalContributions={contributorStats?.meta.allContributionsCount ?? 0}
              topContributor={activityData.topContributor} // i.e. always equal to mostActiveData.data[0]
              setContributorType={setContributorType}
              contributorType={contributorType}
              isLoading={isLoading}
            />
```
I believe, using the `contributorStats` data from the `useMostActiveContributors()` custom hook instead (that gets updated as and when the contributor type filter changes ), should do the trick.


https://github.com/open-sauced/app/assets/27571141/a992f5fe-19e6-4a3c-be2f-4bb7a4249f16

**Comment by nickytonline** [comment]
The top person for contributions seemed to make sense for all contributors but not sure if it makes sense when you filter. 🤔 And the calculation is definitely off @BekahHW 😅 I think that's because It's the person from all contributors but then the % gets skewed as the filter changes.
