### ISSUE TITLE
Bug: style of bio section is not uniform like other input fields

### ISSUE THREAD

**Issue by itskish0re** [open-sauced/app#2046]
### Describe the bug

<b>Problem</b>
In the user's settings page i.e., <code>/user/settings</code> all input fileds have uniform styles except the <b>Bio</b> section.

<b>Expected</b>
![after](https://github.com/open-sauced/app/assets/59221338/f4feed77-129d-4223-80e0-b38b6b6b4af5)

<b>Observed</b>
![before](https://github.com/open-sauced/app/assets/59221338/0bf54d7d-8aea-41b3-913e-f6e0b97b84c2)

<b>Note</b>
The above screenshots is shown only for border property of the component. But the whole bio section has different styling.

<b>Solution</b>
The input field in the settings page is created using a component called <b>TextInput</b>. Similarly, in for the bio field Textarea component must be used. [Textarea](https://github.com/open-sauced/app/blob/beta/components/atoms/Textarea/text-area.tsx)

If the suggested solution is fine then I can work on this.
Thank you.

### Steps to reproduce

1. Go to settings page after logging in.
2. check the styling of Bio section.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by OgDev-01** [comment]
Hey @itskish0re, Would love to see you fix for this in a PR is you are in for it

**Comment by itskish0re** [comment]
Thanks @OgDev-01, I am on it. .take
