### ISSUE TITLE
Bug: styling of delete list modal is too crammed

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#2067]
### Describe the bug

The styling of delete list modal is too crammed

### Steps to reproduce

1. Go to a list by navigating to http://localhost:3000/hub/lists
2. Click the trash icon to delete the list.
3. The delete modal pops up with very crammed spacing.

![CleanShot 2023-11-07 at 13 45 31](https://github.com/open-sauced/app/assets/833231/6818532b-86b2-411d-af93-78d07a9f7cf1)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by itskish0re** [comment]
@nickytonline, unable to reproduce the issue.
![image](https://github.com/open-sauced/app/assets/59221338/87c18650-a2b0-4cf7-909e-d018311a4fac)

**Comment by nickytonline** [comment]
Hmm, weird. Maybe it's already fixed? I was checking on production.

**Comment by OgDev-01** [comment]
Did you confirm this fixed in beta @nickytonline?

**Comment by nickytonline** [comment]
> Did you confirm this fixed in beta @nickytonline?

It was happening on the beta branch as well. Here's a screenshot from the beta app today.

![CleanShot 2023-11-13 at 10 12 40](https://github.com/open-sauced/app/assets/833231/9d567fbc-97a0-4e23-a7d0-40d8f571e670)

**Comment by BekahHW** [comment]
It looks good on mobile in safari for me.

**Comment by nickytonline** [comment]
This fix has already rolled out. Just going to find the PR related to the fix.

![CleanShot 2024-01-06 at 15 25 34](https://github.com/open-sauced/app/assets/833231/3ad4ea0e-f88e-4230-ab18-3ab8d42dba38)

**Comment by nickytonline** [comment]
Looks like this is a duplicate of #2107
