### ISSUE TITLE
Feature: Add Highlights Tab to List feature

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#2069]
### Type of feature

🍕 Feature

### Current behavior

N/A

### Suggested solution

In an effort to finish building the List feature, we want to add the Highlights Tab to Lists.

### What is it?
The highlights tab is meant to display a feed of all the highlights posted by the contributors in a list. This feed should be filterable and sortable.

### Mockup - [Figma File](https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/Design-Lab?type=design&node-id=11640-8271&mode=design&t=IoH8KhB8i2KowKTy-4)
![image](https://github.com/open-sauced/app/assets/27322879/3608912f-76d0-4581-9a13-6c29f06a7ba6)

### Component Breakdown

Please use existing components when possible
- [Radio component](https://design-insights.netlify.app/?path=/docs/design-system-atoms-radio--docs)
- [Checkbox component](https://design-insights.netlify.app/?path=/docs/design-system-atoms-checkbox--docs)
- [Multi select](https://design-insights.netlify.app/?path=/docs/design-system-atoms-multiselect--docs)
- [Search](https://design-insights.netlify.app/?path=/docs/design-system-atoms-search--docs)

<img width="1725" alt="image" src="https://github.com/open-sauced/app/assets/27322879/8090db76-0164-45f3-a54f-1c631d6aa7a9">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
I removed myself @OgDev-01 as I'm working on some graphs next. Happy to pair if need be.
