### ISSUE TITLE
Feature: Add "Add Team Members" to lists feature

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2079]
### Type of feature

🍕 Feature

### Current behavior

There's no way to add a team member to the list. You can share your list, but there is no admin or edit option. 

### Suggested solution

Similar to insights, it would be great to have the ability to add team members to the list. I don't think we need the "view" option unless that's different from "Share". 

There are a number of users who would benefit from this feature:
- Project Maintainers: Allows for shared responsibilities and decentralized management.
- OSPOs: Supports the collaborative management of open source contributions at an organizational level.
- Community Managers: Empowers them to dynamically recognize contributions across various projects.
- Learning Cohorts: Facilitates group learning experiences where contribution tracking is a collective effort.

In the future, this will be a necessary feature for squads. 

![Add team member view](https://github.com/open-sauced/app/assets/34313413/c5c194b2-f265-4624-9877-9d4cc1f73942)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
moving this to the workspaces level.
