### ISSUE TITLE
Bug: Lists Activity for Most Active Contributors doesn't show All Contributors when Selected

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2092]
### Describe the bug

I currently have a list of 68 contributors. When I scroll down the activity list with "All Contributors" selected, I don't see all contributors.

https://github.com/open-sauced/app/assets/34313413/ed6b557b-ba8a-424a-8a1c-a59c69542396

I think there are two options to make this clearer:

1. Change "All Contributors" to "Top 20 contributors"
2. Show the whole list for All Contributors.

Because the title of that card is "Most Active Contributors" I would opt for the first, but we might want to consider changing the title since we do allow the user to filter for Churned Contributors. 

### Steps to reproduce

1. Go to [https://app.opensauced.pizza/lists/90109872-8c67-4c26-838b-d12c18df08c4/activity](https://app.opensauced.pizza/lists/90109872-8c67-4c26-838b-d12c18df08c4/activity)
2. Scroll down the list when all Contributors is selected.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
We appear to be returning all contributors from what I can see. It does appear to be tied to the time range though which is maybe why you don't see all of the contributors?

https://github.com/open-sauced/api/blob/06cd2f69dba35407dcda8fda23e1ba01a823c629/src/user-lists/user-list-stat.service.ts#L82-L189

**Comment by jpmcb** [comment]
Hmmm weird: definitely worth playing with this and see what's going on. if the list filter is `all` it shouldn't apply any filters from the API side:

```js
      case UserListContributorStatsTypeEnum.all:
        break;
```

I'll see if I can reproduce from the API side

**Comment by jpmcb** [comment]
Fixed by: https://github.com/open-sauced/api/pull/437

Should land in the prod API during tomorrow's release!
