### ISSUE TITLE
Change the color of Merged PRs line to purple

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2104]
On your insights dashboard, the line is currently red, which gives a negative impression. 

Let's change that line to match the dark purple of the icon. It should probably end up being something like `bg-purple-500`, which isn't currently a class, although we do have `bg-purple-200`. 

![merged icon](https://github.com/open-sauced/app/assets/34313413/bc179aab-d793-47d4-9f67-47b41bd1144d)

![merged PR tile](https://github.com/open-sauced/app/assets/34313413/a9762b7f-5e0f-4220-a5b3-b2a4db274731)

**Comment by itskish0re** [comment]
.take
