### ISSUE TITLE
Bug: Wording incorrect in Most Active Contributors graph

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#2109]
### Describe the bug

Currently the Most Active Contributors graph's contributor type filter has incorrect terminology. For the fourth item, it says `Churned Contributors`. It should be `Alumni Contributors`.

### Steps to reproduce

1. Go to any list, e.g. http://localhost:3000/lists/8b371419-6219-4448-9de1-f6293a25f98e/activity
2. Open the drop down for the contributor type filter of the Most Active Contributors graph. Notice the incorrect terminology.

![CleanShot 2023-11-10 at 13 20 01](https://github.com/open-sauced/app/assets/833231/5953c24f-06e3-437a-95db-eb0f0347cd40)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
The change can be made here, https://github.com/open-sauced/app/blob/1f7cd66f122cd39cb677e4b6552a9df90803435a/components/molecules/MostActiveContributorsCard/most-active-contributors-card.tsx#L58.

**Comment by itskish0re** [comment]
I will .take it

**Comment by nickytonline** [comment]
Thanks for the enthusiasm @itskish0re, but let's leave this one for someone who has not contributed to the project yet as you have several contributions to the project already.

**Comment by codewithjazzy** [comment]
can I take this one? @nickytonline
