### ISSUE TITLE
Move last repo contributed to under last contributed column for contributors

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2110]
## Current Issue
Currently, under the name and profile picture of the contributor, we have the name of the last repo they contributed to. 

![rachel nabors, under is aws-amplify/docs](https://github.com/open-sauced/app/assets/34313413/158bba78-4edd-4324-a7cb-4fb0c7eb9f7b)

## Solution
Let's move the repo name under the time period in the last contributed column. 
![image](https://github.com/open-sauced/app/assets/34313413/49786d61-9ab8-4ba1-923a-6ae80822c3a4)

That would require removing the second paragraph under the div with the user's name. It will look something like this: `<p class="hidden text-sm font-normal md:inline-flex text-light-slate-9">open-sauced/intro</p>`.

Next, add that paragraph under the last contributed date.

**Comment by jdwilkin4** [comment]
I would be interested to .take this 😄
