### ISSUE TITLE
Bug: app does not redirect a logged out user back to a public page

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/app#2120]
### Describe the bug

When a user is logged in and in a protected route e.g: insight page, disconnecting account should redirect the user to a public route(feeds or public dashboard filters page). But instead, we get a blank screen in the same protected route where the user was before signing out.
The below screen record is just one case... we have several protected pages that has same behaviour
https://github.com/open-sauced/app/assets/62995161/4d47c40a-d29a-4d73-9bf0-937fb64c5f16

### Pages i've confirmed to have similar behaviour
- `/hub/insights` and `/hub/lists`
- `/lists/${listId}/overview, contributors, activity` respectively

### Steps to reproduce

1. login and go to an insight or list page
2. signout

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by 5hraddha** [comment]
Hi @OgDev-01,
Are you looking to redirect the user to the public route(feeds or public dashboard filters page) just after sign out? I could work on that, if that's fine.

**Comment by OgDev-01** [comment]
> I could work on that, if that's fine.

Yes @5hraddha, happy to see your fix in a PR for this 👍

**Comment by brandonroberts** [comment]
Will revisit this in a new issue
