### ISSUE TITLE
Bug: Add Edit List button to all views on List Feature

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2123]
### Type of feature

🍕 Feature

### Current behavior

Right now, there's only an edit list button on the Overview tab.

![list dashboard](https://github.com/open-sauced/app/assets/34313413/4dc63c2c-bc52-4c61-b3cd-e22b0c484b17)

### Suggested solution

- Add Edit List button to the Activity and Contributors tab as well. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
This was initally omitted for the Product Hunt launch, but should have been added to all pages as part of #1977.
