### ISSUE TITLE
Feat: Show `insights` page for non-logged in users

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#2124]
> We should really moving away hiding links all together and start leveraging the pricing and login elements @isabensusan 

> Hiding the insights link was a solution to a short term problem.

_Originally posted by @bdougie in https://github.com/open-sauced/app/issues/1645#issuecomment-1752101690_

---

We should begin leveraging pricing and tier.run to show the insight page to users who are not logged in.

Right now, when not logged in, you don't see any indication of what's possible on the platform and there is no incentive to create an account and log in (at least from the insight page perspective):

<img width="1263" alt="Screenshot 2023-11-13 at 9 15 48 AM" src="https://user-images.githubusercontent.com/23109390/282521201-324b602a-4078-4a5e-8d8c-c7a98d3da6ee.png">

### Suggestion

Show the insight tab and if the user is not logged in, show a splash screen / demo insight page that they can view and get an idea of what's possible on the platform

**Comment by bdougie** [comment]
@OgDev-01 can you work on this today?
