### ISSUE TITLE
feature: Delete account should be danger zone button color

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#2134]
## Currently 
In the user settings we have a "Delete Account" button that does not follow existing UI and design patterns. 

![Screen Shot 2023-11-14 at 8 48 34 AM](https://github.com/open-sauced/app/assets/5713670/1beb2e6a-038e-431b-987a-0f6a13ba36d5)

## Request 

Match the UI to the danger zone found on the insight edit page

- [ ] Button color should be lighter red option

![Screen Shot 2023-11-14 at 8 48 50 AM](https://github.com/open-sauced/app/assets/5713670/1aa000ba-c612-4a3c-9172-e09570146d76)

**Comment by sital002** [comment]
I would like to work on this issue.

**Comment by sital002** [comment]
.take
