### ISSUE TITLE
Bug: Hovercards are broken 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#2138]
### Describe the bug

Noticigin in this PR's deploy preview they work, but they currently do not work in production. 

https://github.com/open-sauced/app/pull/1980

![image](https://github.com/open-sauced/app/assets/5713670/a28722b7-773e-4515-930d-9d6160ac84bc)

### Steps to reproduce

What the add does today. 

![image](https://github.com/open-sauced/app/assets/5713670/70515897-3ef0-440d-90ab-319034b1f1ed)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
Found the bad commit through a bisect. FYI @nickytonline https://github.com/open-sauced/app/commit/e1dcd5568653dc5716a24fd775f83969dd190159

**Comment by OgDev-01** [comment]
I'll pick i up from here if you don't mind @bdougie
