### ISSUE TITLE
console.logs?

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#2140]
@OgDev-01 when you get a moment. Could you confirm these console.logs are needed? I was working in the app on some low level bugs to get re-aquainted and noticed the console being populated. 

- [ ] https://github.com/open-sauced/app/blob/ec4eeab7e466ecfe166349eb1e7aa7c2ce1e254c/stories/molecules/component-date-filter.stories.tsx#L18
- [ ] https://github.com/open-sauced/app/blob/ec4eeab7e466ecfe166349eb1e7aa7c2ce1e254c/lib/utils/github.ts#L105

**Comment by nickytonline** [comment]
Not sure why eslint didn't pick that up. We have a rule for that now. 

![CleanShot 2023-11-14 at 17 30 49](https://github.com/open-sauced/app/assets/833231/52387fbf-4f10-4b12-8fd8-299f98962b15)

**Comment by nickytonline** [comment]
The Next.js build builds even with the ESLint error and it's set to error, not warn.

https://github.com/open-sauced/app/blob/5b26fb2373f4e16f713c3a5432d11d44fb1ef3e6/.eslintrc.json#L14

And the Next.js build fails if one is found, so not sure how those got in there. 🤔 

![CleanShot 2023-11-14 at 17 36 41](https://github.com/open-sauced/app/assets/833231/5d24df3a-70ce-4b93-a3fc-68c873893f53)

**Comment by OgDev-01** [comment]
This throws an error in the editor, but quite wierd how it managed to build without error
<img width="512" alt="image" src="https://github.com/open-sauced/app/assets/62995161/dc828f64-38ed-49fd-a20f-7f6320c40f20">

Maybe nextjs ignores lint warnings in storybook if it doesn’t break the build 👀

**Comment by nickytonline** [comment]
> This throws an error in the editor, but quite wierd how it managed to build without error
> 
> <img width="512" alt="image" src="https://github.com/open-sauced/app/assets/62995161/dc828f64-38ed-49fd-a20f-7f6320c40f20">
> 
> 
> 
> Maybe nextjs ignores lint warnings in storybook if it doesn’t break the build 👀

Ahh didn't realize it was in a Storybook story. That's not part of the next.js build which is why it doesn't complain most likely during a build. We can always add a pre script for building storybook for production to catch these.

The next.js build definitely runs eslint during a build.
