### ISSUE TITLE
Bug: Firefox - "Post a highlight" missing rounded corners

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#2143]
### Chrome (expected behavior)

Note the rounded corners all the way around:

![Screenshot 2023-11-14 at 5 08 45 PM](https://github.com/open-sauced/app/assets/23109390/e724cf44-f7c0-4108-ae84-cd880a6e943b)

### Firefox

Note the right side is square and not rounded like chrome:

![Screenshot 2023-11-14 at 5 07 07 PM](https://github.com/open-sauced/app/assets/23109390/e40f6b7d-3452-47fd-a464-e679db19daee)

### Steps to reproduce

1. Open Firefox
2. Log in
3. Go to `app.opensauced.pizza/feed`
4. Attempt to post a highlight: notice the right side doesn't have rounded corners and the CSS seems off

### Browsers

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
The changes will need to be made in https://github.com/open-sauced/app/blob/6536efa5845da86642eb93ef26c06ffdbddb74d2/components/molecules/HighlightInput/highlight-input-form.tsx

**Comment by maharjanraj** [comment]
Please assign this one to me.

**Comment by maharjanraj** [comment]
.take

**Comment by jpmcb** [comment]
Looks like this got fixed along the way:

<img width="1508" alt="Screenshot 2024-02-03 at 4 32 08 PM" src="https://github.com/open-sauced/app/assets/23109390/72d1494b-404c-417a-9d8c-49dcf7d37dc5">

Closing.
