### ISSUE TITLE
Bug: Checkboxes on the User Settings Page Need Focus States

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#2149]
### Describe the bug

Checkboxes on the User Settings Page Need Focus States

### Steps to reproduce

1. Go to your user settings page, https://app.opensauced.pizza/user/settings
2. Use the <kbd>TAB</kbd> key to tab through all the fields. Notice that once you hit a checkbox, you can change it's state with the keyboard, but it never receives a focus state.

![CleanShot 2023-11-14 at 22 41 55](https://github.com/open-sauced/app/assets/833231/b37e7a92-8110-4678-a39d-4a8381658dc6)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
We should add default focus states to the base styles for this @isabensusan @OgDev-01 so that the focus states become uniform throughout the site. We can then also probably remove a lot of focus state styles throughout all the components that have them.

**Comment by nickytonline** [comment]
Relates to https://github.com/open-sauced/internal-team/issues/21

**Comment by isabensusan** [comment]
@nickytonline  Yes!! I'd love to have global focus styles. I think the styling we have for the search component is ideal:

<img width="689" alt="image" src="https://github.com/open-sauced/app/assets/27322879/7ce4ebf1-c00f-4ba5-9307-e47bded538a4">

Here's the tailwind classes making this happen:
```

focus-within:ring 
focus-within:border-orange-500 
focus-within:ring-orange-100

```
