### ISSUE TITLE
Bug: ui improvement for insight edit page delete page modal

### ISSUE THREAD

**Issue by sital002** [open-sauced/app#2160]
### Describe the bug

The ```Delete``` and ```Cancel```buttons need some margin-top.
![image](https://github.com/open-sauced/app/assets/93700622/c35ac0ed-2655-4313-8f72-c0e7dd9d16fe)
margin-top

### Steps to reproduce

Go to ```http://localhost:3000/hub/insights```
Click on any repo and the click on edit the insight page.
Click on the ```Delete page ```

### Browsers

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
The fix can be the same as the fix in https://github.com/open-sauced/app/pull/2106.

**Comment by nickytonline** [comment]
This is a good first issue so if you've already contributed to the code base (thank you!), let's let someone new contribute for the first time.

**Comment by AdrianRomanski** [comment]
@nickytonline  i would like to take it :)

**Comment by nickytonline** [comment]
That's awesome! See the [contributing guide](https://docs.opensauced.pizza/contributing/introduction-to-contributing/#issues) to assign yourself.

**Comment by Anish0203** [comment]
.take

**Comment by AdrianRomanski** [comment]
@Anish0203 why you take my task?

**Comment by AdrianRomanski** [comment]
.take

**Comment by Anish0203** [comment]
@AdrianRomanski It had been around 24 hours since the last conversation and the issue was not assigned to anyone. So, I started working on it. Sorry for that, I didn't mean to hurt you. I am checking if I can assign it to you.

**Comment by AdrianRomanski** [comment]
@Anish0203 I planned to start working on it from the morning (reading [contributing guide](https://docs.opensauced.pizza/contributing/introduction-to-contributing/#issues) etc).
 That's why i wasn't assigned. I'm not hurted, just please ask next time if you see some movement in issues, 24h is not a long period.

**Comment by Anish0203** [comment]
Sure @AdrianRomanski . I am new to open source, so wasn't much sure. I'll keep that in mind.
