### ISSUE TITLE
Feature: Add Svelte in the list of available languages to filter on 

### ISSUE THREAD

**Issue by brittneypostma** [open-sauced/app#2167]
### Type of feature

🍕 Feature

### Current behavior

Svelte is not a filter provided.

### Suggested solution

Add svelte to the dropdown. I will attempt to do this myself.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
Thanks for the issue @brittneypostma! Go for it! The changes will need to be made in https://github.com/open-sauced/app/blob/1073b1d861acf01cb200323f0b1f36e2bcf86f9e/lib/utils/getInterestOptions.ts .
