### ISSUE TITLE
Refactor: Remove Netlify CLI from dev dependencies

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#2170]
The Netlify CLI shouldn't be a dev dependency in package.json.

It's typically recommended for the Netlify CLI to be installed globally, https://docs.netlify.com/cli/get-started/.

**Comment by nickytonline** [comment]
It's recommened to have the Netlify CLI installed globally. Our setup docs need to mention
installing the Netlify CLI and point to Netlify CLI, https://docs.netlify.com/cli/get-started/.

The other thing to do is to run `npm uninstall netlify-cli` and commit the package.json and npmshrinkwrap.json file.

**Comment by coder12git** [comment]
@nickytonline Hi, this is my first contribution to this community, and i would like to take this issue. It will be good if you can assign this to me.

**Comment by coder12git** [comment]
.take

**Comment by gewenyu99** [comment]
@nickytonline This looks like it can be closed 👀

**Comment by nickytonline** [comment]
Thanks @gewenyu99!
