### ISSUE TITLE
Feature:  Improve "Sync from Github" feature on lists

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#2172]
### Type of feature

🍕 Feature

### Current behavior

Users can currently sync teams from their Github organization
![image](https://github.com/open-sauced/app/assets/27322879/d77bf97a-92e5-4815-ac1d-5981dc81581b)

### Suggested solution

We've had this feedback from Jesse @ Xebia:

> At the moment I don't really see a need to sync our internal team structure, though I suppose that our Xebia cloud would probably want a version with just the cloud folks and Xebia Functional would want to showcase the scala projects and Xebia Microsoft Services would want to show azure and github contributions... For now that would be a team sync thing I suppose, though it could also be something based on repo metadata or tagging on our side. I'd love a Sync everyone​ option here:

We could reframe the Github Sync option to let users:
- Import an entire organization
- Import teams
- Import people who have contributed to specific repos on their org

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
Revamped this feature with GitHub Organization Import in workspaces
