### ISSUE TITLE
Feature: let users exclude organizations and repositories from their list

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#2173]
### Type of feature

🍕 Feature

### Current behavior

When users create a list all contribution data from all the repositories/organizations they've interacted with are taken into account for the charts.

### Suggested solution

We've gotten feedback from Jesse @ Xebia that he would like to be bale to exclude certain orgs and repos from the lists data. His specific example is that as a professor/trainer he's done thousands of contributions to one of microsoft's repositories that he doesn't care about, so whenever he adds himself to a list he breaks all the visualizations. 

We could add an "exclude" input to the Edit List page so that users can indicate organizations and repositories to ignore in the data.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
Repository filtering was added in https://github.com/open-sauced/app/pull/3355
