### ISSUE TITLE
Feature: group lists tree map by organization

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#2175]
### Type of feature

🍕 Feature

- [x] #2402

### Current behavior

Current hierarchy for the tree map drill downs is Repos > Contributors
<img width="681" alt="image" src="https://github.com/open-sauced/app/assets/27322879/d149e943-912b-4b34-9fb0-6a8818a5addf">

### Suggested solution

Can we add a higher dimension for organizations? Something like this where we have organizations on the top-level, and the user can drill down to get to repositories -> then contributors.
<img width="600" alt="image" src="https://github.com/open-sauced/app/assets/27322879/6055de5f-17e5-40ce-a76c-d83fef65cd13">

We would also want repositories belonging to the same organization to have the same color.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by getaheaddev** [comment]
I'm looking into a design that could be applied to this.
