### ISSUE TITLE
Bug: top 100 repos doesn't show 100 repos

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2177]
### Describe the bug

On the explore page, if you choose top 100 repos, it doesn't show 100 repos.

### Steps to reproduce

You can see it here: https://app.opensauced.pizza/ai/dashboard/filter/top-100-repos?range=30

<img width="583" alt="Screenshot 2023-11-17 at 4 29 40 PM" src="https://github.com/open-sauced/app/assets/34313413/31819c95-f526-4fe5-99ba-74dd6af29753">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by jdwilkin4** [comment]
Nice catch! 

I think it would be nice to show some sort of message and prevent that filter from happening. 
Maybe this message could work

<img width="872" alt="Screenshot 2023-11-18 at 12 36 39 PM" src="https://github.com/open-sauced/app/assets/67210629/d748f34a-2c60-4053-b40d-4d2efc80b034">

**Comment by a0m0rajab** [comment]
I think a message showing the number of expected repos would be cool. 
![image](https://github.com/open-sauced/app/assets/18273833/890304e8-ac4f-4689-8577-71ef6032d09b)

By the way, plus how does this filter works? Because when you check this image you can find more than 1300 repos in the AI tag.

**Comment by a0m0rajab** [comment]
In JS when you check the top 100, you can find 155 repo: 

![image](https://github.com/open-sauced/app/assets/18273833/0b3a41fb-1e73-47c9-bf96-1892bf9fc06c)

**Comment by BekahHW** [comment]
@isabensusan do you have ideas for what design should look like if there are fewer than 100? Jessica has a suggestion above.

**Comment by isabensusan** [comment]
@BekahHW sorry for the late reply! A pretty quick fix would be to change the filter copy to just "Top repos" without promising a set number of repos. That way, we can show however many repos we can (although we should still cap it at 100), and it wouldn't feel strange that smaller ecosystems have a smaller amount of top repos and bigger ecosystems have more.

A redo of this page is in the roadmap, so I wouldn't add any changes that require much effort given we have quite a few higher priority tickets.

@a0m0rajab @jdwilkin4 thank you for your input though! For what it's worth I think both options would also work to tackle the issue :)

**Comment by BekahHW** [comment]
@isabensusan I think I have a separate issue opened for this for the reports, but should it do the same?

![image](https://github.com/open-sauced/app/assets/34313413/a0cc02ca-ece9-496f-8e85-3504d7c1d1c3)

**Comment by BekahHW** [comment]
@brandonroberts to implement this fix, the `useFilterOptions` would get updated, but that means it would be replaced in both the explore filter and the reports filter. Is that ok?
