### ISSUE TITLE
Bug: Dashboard Highlight card skeleton covers hovercard details

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/app#2193]
### Describe the bug

![image](https://github.com/open-sauced/app/assets/62995161/1f6260d1-2eca-43c8-bd3c-2a71bb3079a5)

This is s z-index issue and should be a quick fix

### Steps to reproduce

1. Go to https://app.opensauced.pizza/javascript/dashboard/filter/recent?range=30
2. when the stats are still loading, try hovering on a contributor from the repositories table

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Anish0203** [comment]
.take
