### ISSUE TITLE
Bug: Svelte thumbnail missing in pills

### ISSUE THREAD

**Issue by brittneypostma** [open-sauced/app#2195]
### Describe the bug

When onboarding and selecting Svelte as an interests, the svg is missing on the pill/badge. We added the svg to the `topic-thumbnails` directory, but this needs to be added to the `img/icons/interests` directory in an interesting format. It appears to be using an svg sprite with an image data uri when I compared the react svgs. Here are the 2 file types. I would attempt this, but I'm not sure how to get the format needed for that interests svg. I assume you just need to take the Svelte svg that was added and run it through some tool, but I don't know which one.
[interests](https://github.com/open-sauced/app/blob/0e19a6b867e185d074f6f905345306de13240a1c/img/icons/interests/react.svg#L4)
[thumbnail](https://github.com/open-sauced/app/blob/0e19a6b867e185d074f6f905345306de13240a1c/img/topic-thumbnails/react.svg#L2)

### Steps to reproduce

1. Onboard or add Svelte as an interest
2. See svelte Svelte instead of the svg

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by sital002** [comment]
.take
