### ISSUE TITLE
Bug: Dev card is not in full size (cut off) on preview

### ISSUE THREAD

**Issue by adiati98** [open-sauced/app#2203]
### Describe the bug

When previewing the dev card in the [Card page](https://app.opensauced.pizza/user/adiati98/card), the dev card is cut off at the bottom so user can't see the whole card.

### Front side

**Default state**: User cannot see the text under the numbers. This can be confusing.
**Hover state**: User still cannot see the text under the numbers.

### Back side

**Default state**: User cannot see the "View Profile" button.
**Hover state**: The "View Profile" button is cut off.

### Front Side

![opensauced front page dev card 1](https://github.com/open-sauced/app/assets/45172775/a5e7a7dc-bda6-4919-b197-c82972848493)

### Back Side

![opensauced back side dev card 1](https://github.com/open-sauced/app/assets/45172775/ce82a5c3-3823-4b53-98ec-40c5fcdd74fd)

## Screen Recording

![OpenSauced Card Page](https://github.com/open-sauced/app/assets/45172775/52e63a19-68ad-4d16-8ef4-6458db7f86b2)

### Steps to reproduce

1. Go to a [user's card page](https://app.opensauced.pizza/user/adiati98/card).
2. Look at the front side of the dev card — can't see the text under the numbers.
3. Hover over — and still can't see the text under the numbers.
4. Click the card to see the back side of the dev card — can't see the "View Profile" button.
5. Hover over — can see most of the card, but the "View Profile" button is cut off. 

### Browsers

Chrome

### Additional context (Is this in dev or production?)

This issue is in production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by adiati98** [comment]
Hey @nickytonline,
I've double checked. It's cut off on 100%. It's not cut off when I zoomed out to 90%.

![dev card](https://github.com/open-sauced/app/assets/45172775/d62d4ccb-9b4a-462d-8acb-9e560b789a46)

**Comment by adiati98** [comment]
@nickytonline it's the same with Firefox.
This one is using the latest version of Firefox: 120.0 (64-bit).

 
![dev card firefox](https://github.com/open-sauced/app/assets/45172775/f52dcd0f-a64c-4e60-81fd-0e403e16fd57)

**Comment by jdwilkin4** [comment]
When I test this on mac with Chrome the full card is showing for me but the create your own dev card button only shows up when I zoom to 90%

**Comment by coder12git** [comment]
. take

**Comment by jdwilkin4** [comment]
@coder12git 

To have an issue assigned to you make sure to not have any spaces when using dot take

Hope that helps 👍

**Comment by sourabpramanik** [comment]
@coder12git are you still working on this issue? 

I can raise a PR that will fix this issue. Thanks 👍

**Comment by brandonroberts** [comment]
Closing with the DevCard being refreshed
