### ISSUE TITLE
Bug: Show more contributors isn't working

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2209]
### Describe the bug

When I'm on an insight page, and I want to expand the number of contributors that are shown, nothing happens.

https://github.com/open-sauced/app/assets/34313413/ae18df56-7a48-4ccb-b506-7a7f64334a0f

### Steps to reproduce

- Go to: https://app.opensauced.pizza/pages/BekahHW/1035/contributors?range=30&limit=50
- Only ten displays

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
I know that @OgDev-01 has been working on moving the limit from component state to the querystring. Maybe it's related?

**Comment by adiati98** [comment]
Hi @nickytonline @OgDev-01, I can't filter the number of contributors showing in a page in the "Insights" and "Explore" tab.

And I was about to create an issue until I saw this.

I see that #2227 fixes the page limit dropdown filters for repos. But will it also fix the filters for contributors as mentioned in this issue?

Below is a screen recording from the "Explore" tab. Thank you.

![contributors tab](https://github.com/open-sauced/app/assets/45172775/f5c79fcf-5d68-47eb-952c-1b4542a14aae)

**Comment by OgDev-01** [comment]
> I see that #2227 fixes the page limit dropdown filters for repos. But will it also fix the filters for contributors as mentioned in this issue?

Yes @adiati98 the fix will also apply to the contributors table.
