### ISSUE TITLE
Bug: Redirect issues happening when click tabs from a list without range or limit in the URL

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/app#2211]
### Describe the bug

When visiting a list and switching to the contributors tab, the data isn't displayed correct unless the `limit` query param is set

https://github.com/open-sauced/app/assets/42211/2599793e-f285-4a87-a69b-8b546fe90378

### Steps to reproduce

1. Navigate to a list https://app.opensauced.pizza/lists/759e58cd-2e89-4704-8def-93d911716b82/overview
2. Click on the activity tab, notice the redirect to include the `range` query param
3. Click on the contributors tab, notice the empty data for the contributors
4. Add the `limit=10` query param to the URL
5. Notice the contributors data shows up correctly.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by a0m0rajab** [comment]
hi @OgDev-01 if you are working on this I think setting the `limit` option at this lines would solve the issue: 

https://github.com/open-sauced/app/blob/37290c0487b870ed9965b71c820973ede9d06362/pages/lists/%5BlistId%5D/contributors.tsx#L65-L69
