### ISSUE TITLE
Bug: Lists Activity error when trying to load large number of contributors

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2213]
### Describe the bug

Something is causing an error when we try to load the list activity for large lists.

It seems like I can load a list of 60, but not at 94.

<img width="760" alt="image" src="https://github.com/open-sauced/app/assets/34313413/99ff0d52-7e57-43d1-afe3-f66d96c67f96">
 

### Steps to reproduce

1. Go to https://app.opensauced.pizza/lists/7eef76df-a63a-42b8-babd-237b9b213579/activity
2. See a 502

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
As mentioned in Slack, I'm going to offload all data loading for graphs to the client-side (fetch to API). Currently we're getting initial data in getServerSideProps which was fine with smaller lists, e.g. 60 and under.
