### ISSUE TITLE
Bug: the tools link does not check the available tool

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/app#2222]
### Describe the bug

When you use a different tool name for the tools we have. This makes a weird UI. 

![image](https://github.com/open-sauced/app/assets/18273833/e14fa87e-d436-4999-b566-6ea569550865)

### Suggestion 
This is related to this code:
 

https://github.com/open-sauced/app/blob/5d6b2bcfdcf9b584a0155f158808554e494fa9ee/components/organisms/ToolsDisplay/tools-display.tsx#L29C1-L41

I think having the dashboard as default would be a good fix for this. 

### Steps to reproduce

1. go to https://beta.app.opensauced.pizza/ai/tool/filter/top-100-repos?range=30
2. see the tool name as tool, 
3. visit https://beta.app.opensauced.pizza/ai/helloworld/filter/top-100-repos?range=30 again
4. the tool name is helloworld, 

### Browsers

Chrome

### Additional context (Is this in dev or production?)

Related to https://github.com/open-sauced/app/issues/2185

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by a0m0rajab** [comment]
This happens for all options in the URL example: 
https://beta.app.opensauced.pizza/hello-cat/meow/filter/top-100-kittens?range=30

![image](https://github.com/open-sauced/app/assets/18273833/a23836ff-66ee-41be-8aae-70c651daca51)
## Funny Gif
<img src="https://media0.giphy.com/media/wollgOXZPyUYvxht3V/giphy.gif"/>

**Comment by FatumaA** [comment]
I can reproduce this
