### ISSUE TITLE
Chore: CSS conflicting property in development

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/app#2228]
### Type of feature

🐛 Fix

### Current behavior

This could be a minor development but thought to address it here, when I worked on https://github.com/open-sauced/app/issues/2185 I got this warning in the console: 

```bash
Warning: Updating a style property during rerender (overflowY) when a conflicting property is set (overflow) can lead to styling bugs. To avoid this, don't mix shorthand and non-shorthand properties for the same value; instead, replace the shorthand with separate values.
```

I thought it would worth to open an issue for that and check it, this happened at this [stream](https://www.youtube.com/live/pGGV8cVsaj0?si=8CvQXgTGUy3Lefbn&t=4622)

### Additional context

Discovered in https://github.com/open-sauced/app/issues/2185

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by a0m0rajab** [comment]
@nickytonline thanks for the suggestion, I think I will keep it open and work on something else these days, might pick it up in the next few weeks if no one picked it up.

**Comment by sital002** [comment]
I am not able to reproduce the bug can you provide the URL for it.

**Comment by nickytonline** [comment]
@a0m0rajab, do you remember what page this warning was happening on?

**Comment by a0m0rajab** [comment]
It was in this URL: [app.opensauced.pizza/ai/dashboard/filter/top-100-repos?range=30](https://app.opensauced.pizza/ai/dashboard/filter/top-100-repos?range=30)

Here is the video of the error: https://www.youtube.com/live/pGGV8cVsaj0?si=m_PlWAzwxV22lJ06&t=4563

I think it appeared when I run the project in debugger in VsCode.

**Comment by nickytonline** [comment]
This might only be a development mode issue as it does not occur on that page in production.

**Comment by a0m0rajab** [comment]
I think so since the warning does not appear on production, do you think we should work on this or just ignore that?
