### ISSUE TITLE
Bug: limit selector is breaking the layout (a bit)

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/app#2231]
### Describe the bug

When you go to https://beta.app.opensauced.pizza/python/dashboard/filter/top-100-repos?range=90 and click on the number of contributors to view, the layout breaks and have an extra spaces. 

### Steps to reproduce

1. https://beta.app.opensauced.pizza/python/dashboard/filter/top-100-repos?range=90
2. click on showing 10 per page
3. you will see the header is getting resized 

### Additional context (Is this in dev or production?)

Discovered in https://github.com/open-sauced/app/issues/2185

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by Kepsondiaz** [comment]
heyy i see what you say. 
i will take it.

**Comment by takanome-dev** [comment]
Hey @Kepsondiaz, good to see you here 🙂

Here is a similar fix for this kind of behavior https://github.com/open-sauced/app/pull/1704

**Comment by a0m0rajab** [comment]
@takanome-dev and @Kepsondiaz thank you for looking into this, the issue is happening due an overflow-hidden been added to the page, I am not sure how that is being added right now, but you could notice it when you open the inspector and click on the select that you have, this will let you notice the changes in the inspector. 

Here is the extra code that is being added when you open the selector: 
![image](https://github.com/open-sauced/app/assets/18273833/fd5825c3-e4d7-4970-a386-bda00e307e7f)
