### ISSUE TITLE
Style: add to list action menu needs better design when empty

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/app#2232]
### Type of feature

🎨 Style

### Current behavior

The add-to-list action menu needs a better design: 
![image](https://github.com/open-sauced/app/assets/18273833/ba8291d5-bb33-482b-9d9d-6db158356739)

If you go to any profile page you might see it there. 

### Suggested solution

I would suggest to use a component like the one we have in the others action menu: 
![image](https://github.com/open-sauced/app/assets/18273833/24eb4d94-3ed7-47d3-9371-b04d27507b8c)

## Related code: 

https://github.com/open-sauced/app/blob/8bf71afd46f9f720595ed7dfbd97cb44c726a267/components/molecules/ContributorProfileHeader/contributor-profile-header.tsx#L447-L467

The share button code for reference: 

https://github.com/open-sauced/app/blob/6c79d5e023c828cc9b726d8285ad14c999b544cc/components/ListHeader/list-header.tsx#L57-L67

### Instruction

Adding margin and padding to the code in the contributor profile header and converting the text to div would solve the issue. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
This needs some padding and some hover styles.

**Comment by a0m0rajab** [comment]
Thanks for the suggestion, I updated the issue body and added related labels.

**Comment by Anish0203** [comment]
I would like to .take this issue and try it out. Thanks!
