### ISSUE TITLE
Bug: overflowing Most "Used Languages" in list contributors tab

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#2233]
### Describe the bug

When viewing a list and going to the contributors tab, some of the fields overlap quite alot:

![Screenshot 2023-11-29 at 8 58 51 AM](https://github.com/open-sauced/app/assets/23109390/f5f56007-ae45-46db-9276-3e1062db8b51)

This _seems_ to be the "Most Used Languages" tab but that doesn't really make sense since that seems to be the interests for @OgDev-01 - very bizzare!

### Steps to reproduce

1. Go to a list
2. Go to the contributors
3. Notice the overflow

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
That is odd. There were changes recently to show only two languages (might only be in beta still), and some languages are truncated, e.g. JavaScript becomes JS etc.

Can you confirm it's an issue on beta as well?

**Comment by a0m0rajab** [comment]
Here is a screenshot from beta: 

PC: 
![image](https://github.com/open-sauced/app/assets/18273833/120b27e7-1ee6-472f-bc20-5e496d063c9e)

Ipad mini view: 
![image](https://github.com/open-sauced/app/assets/18273833/e21fde80-c226-4875-9930-e1233040753e)

Link: https://beta.app.opensauced.pizza/lists/bc16c6cd-b4c9-469b-a1f2-1a40ba8f682d/contributors

Even if it's unrelated to the main issue, there are some responsivity issues.

**Comment by nickytonline** [comment]
> Here is a screenshot from beta: 
> 
> 
> 
> PC: 
> 
> ![image](https://github.com/open-sauced/app/assets/18273833/120b27e7-1ee6-472f-bc20-5e496d063c9e)
> 
> 
> 
> Ipad mini view: 
> 
> ![image](https://github.com/open-sauced/app/assets/18273833/e21fde80-c226-4875-9930-e1233040753e)
> 
> 
> 
> Link: https://beta.app.opensauced.pizza/lists/bc16c6cd-b4c9-469b-a1f2-1a40ba8f682d/contributors
> 
> 
> 
> Even if it's unrelated to the main issue, there are some responsivity issues. 
> 
> 

Those languages that stick out are interests and not the most used languages so not sure why those are just floating there.

For the table responsiveness, there is work underway for that.

**Comment by a0m0rajab** [comment]
> Those languages that stick out are interests and not the most used languages so not sure why those are just floating there.
do you mean the Luan and AppleScript in the PC screenshot? 

> For the table responsiveness, there is work underway for that.
looking forward for that.

**Comment by nickytonline** [comment]
> > Those languages that stick out are interests and not the most used languages so not sure why those are just floating there.
> 
> 
> 
> do you mean the Luan and AppleScript in the PC screenshot? 
> 
> 
> 
> > For the table responsiveness, there is work underway for that.
> 
> 
> 
> looking forward for that. 

No those are the two languages that should be there. I mean the ones in John's screenshot, where it's one long line with typescript etc.

![Screenshot 2023-11-29 at 8 58 51 AM](https://github.com/open-sauced/app/assets/23109390/f5f56007-ae45-46db-9276-3e1062db8b51)

**Comment by OgDev-01** [comment]
I've confirmed this is in beta also and it's only on my user. I'll dive deeper to see what the cause is 🤔

**Comment by OgDev-01** [comment]
I looked in and it turns out i have not language in my data which is wierd 🤔 
<img width="431" alt="image" src="https://github.com/open-sauced/app/assets/62995161/c07ea3bf-818d-4724-8228-daee00a06daa">

So it falls back to my interest which is not truncated in the function definition
https://github.com/open-sauced/app/blob/6c79d5e023c828cc9b726d8285ad14c999b544cc/components/molecules/ContributorListTableRow/contributor-list-table-row.tsx#L47-L58

truncating the interest fixes this

<img width="1382" alt="image" src="https://github.com/open-sauced/app/assets/62995161/814ff6d8-bd0a-46d7-aa26-848ea71fdd02">

**Comment by OgDev-01** [comment]
I'll make a PR for this shortly. but it's also weird how i don't have any language even though i've worked with typescript and javascript 🤔
