### ISSUE TITLE
Bug: After adding the repository, the "Add to page" button remains visible in the suggested bar.

### ISSUE THREAD

**Issue by Himanshuch8055** [open-sauced/app#2247]
### Describe the bug

When a user creates a new Insight on the Insight page, a suggested repo bar is displayed. When the user adds the repo to their page using the "add to page" button, the repo is properly added to their page. However, the problem arises when the repo is added to the page, as the "add to page" button still remains visible. It should either be removed or replaced with a check mark or some other indication to help the user understand that the repo has already been added to their page.

https://github.com/open-sauced/app/assets/94627200/00acd812-4351-483b-b298-a2029f43c7ef

### Steps to reproduce

1. Goto to the "Insights page"
2. Click on "New Insight"
3. Scroll down.......
4. Click on the "Add to page" button.

### Browsers

Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Himanshuch8055** [comment]
@MrCyberlord "What's the update?"

**Comment by MrCyberlord** [comment]
I am on it. Will solve the issue soon.

**Comment by Himanshuch8055** [comment]
Ok 👍

**Comment by sourabpramanik** [comment]
@MrCyberlord I will be drafting a PR which will fix this issue. If you want to and have already fixed this issue and willing to raise PR then let me know I will remove mine.

**Comment by MrCyberlord** [comment]
@sourabpramanik  No issues. Please carry on.

**Comment by sourabpramanik** [comment]
@MrCyberlord can you please assign me this issue then?

**Comment by Himanshuch8055** [comment]
"Hello, could you kindly unassign this issue from @MrCyberlord and assign it to @sourabpramanik, @nickytonline? Thank you."

**Comment by takanome-dev** [comment]
@Himanshuch8055, I think this is already resolved. Can you confirm it, please?

**Comment by Himanshuch8055** [comment]
@takanome-dev It is still there!

**Comment by sourabpramanik** [comment]
Yes it is there guys!

**Comment by Himanshuch8055** [comment]
@sourabpramanik "What about your PR? You created a PR, why is it still there?"

**Comment by sourabpramanik** [comment]
Well it's still not merged and under review
