### ISSUE TITLE
Feature: better search syntax for more granular results

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#2249]
### Type of feature

🍕 Feature

### Current behavior

Comment from jessehouwing:

> Instead of using a fuzzy search for a user's name, is therea syntax that will use the data I enter verbatim? We have a few users with very short handles and they're really hard to add:

![image](https://github.com/open-sauced/app/assets/27322879/143114c7-ee95-4f4c-8809-e706e8323522)

### Suggested solution

TBD, but we could apply something like google's quotation marks syntax for exact matches on short names

It'd be amazing to be able to search for orgs as well and add everyone on an organization to a list

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by getaheaddev** [comment]
I'm looking into how a design could be applied to this
