### ISSUE TITLE
Feature: add explanation of what users are seeing on list activity graph

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2270]
### Type of feature

🍕 Feature

### Current behavior

It's not clear what the chart is representing. 

![current activity chart](https://github.com/open-sauced/app/assets/34313413/23416b97-e3b0-4e86-839f-21b107bc8966)

### Suggested solution

1. Add subtext below like we do for the Most Active Contributors chart

![added subtext](https://github.com/open-sauced/app/assets/34313413/251780d8-6010-4048-9fd8-af77df7795fa)

You should be able to just add this below the heading:

```
<div class="text-sm text-slate-400 mb-4">Based on the number of PRs
</div>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
I wouldn't go with a tooltip for this as it's important information we should surface instead of them having to discover they have to hover over the title to find out what it is.

Does that work for you @isabensusan?

**Comment by CBID2** [comment]
> I wouldn't go with a tooltip for this as it's important information we should surface instead of them having to discover they have to hover over the title to find out what it is.
> 
> Does that work for you @isabensusan?

Yeah I agree with @nickytonline. Subtexts would make it easier for users to understand what's going on.

**Comment by manipandit** [comment]
.take

**Comment by BekahHW** [comment]
@manipandit how are things going?

**Comment by devharsh2k4** [comment]
Hey lloks like aint there any activity so can i get assigned

**Comment by manipandit** [comment]
> @manipandit how are things going?

Hey you can assign the issue to others.

**Comment by devharsh2k4** [comment]
.take

**Comment by devharsh2k4** [comment]
@BekahHW , @nickytonline  Please review my PR for this feature

**Comment by nickytonline** [comment]
> @BekahHW , @nickytonline Please review my PR for this feature

@devharsh2k4, there's no need to ask us to review your PR. We all receive notifications about activity in the repository.

**Comment by devharsh2k4** [comment]
Ok got it
