### ISSUE TITLE
Feature: Add description to URL input

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2279]
### Type of feature

🍕 Feature

### Current behavior

Currently, there's a URL field in the profile settings, but it's not clear what's expected to go in there.

<img width="309" alt="image" src="https://github.com/open-sauced/app/assets/34313413/ce628fc5-9012-4a00-bf0e-795cf8f0803a">

### Suggested solution

Let's add text to give users some ideas for what they could add there.

To do this, let's add a description in parentheses next to the URL, like this:

<img width="268" alt="image" src="https://github.com/open-sauced/app/assets/34313413/e97c1f44-83da-44a4-a827-9a0ce610b37c">

```
<p class="mb-2 text-sm text-light-slate-9">URL (personal website, portfolio, or any page that showcases your work or interests)</p>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by ItIsOHM** [comment]
Hey I'd love working on this issue

.take

**Comment by ItIsOHM** [comment]
@BekahHW I have opened a PR for this, please let me know if there's any problem :)
