### ISSUE TITLE
Bug: contributor list "Most used languages" is innacurate

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#2281]
### Describe the bug

I've seen a few instances where "Most used langauages" in the contributor lists is inaccurate.

This screenshot is off of beta:

![Screenshot 2023-12-07 at 10 07 09 AM](https://github.com/open-sauced/app/assets/23109390/e662507f-4104-45a1-8418-2032979d9c22)

For example, I haven't written CSS in forever. And "Docker" isn't really a language. I'd expect this to more closely reflect what's in my user profile (TS, and Go):

![Screenshot 2023-12-07 at 10 09 33 AM](https://github.com/open-sauced/app/assets/23109390/f7eb02d4-5732-4cd7-bbd3-985627ab8b87)

---

Another thing you'll notice: @OgDev-01 has "golang, hacktoberfest" as languages. "hacktoberfest" isn't a programming language so there's something not quite right in there.

---

This, to me, looks like an ordering problem when we get `contributor.languages`. From the API against my own user, this is what's returned:

```
  "languages": {
    "Go": 601455,
    "CSS": 1391,
    "Lua": 5058,
    "Zig": 4320,
    "HTML": 4769,
    "Just": 24,
    "Rust": 7989,
    "Shell": 5566,
    "Python": 616,
    "Makefile": 2520,
    "Dockerfile": 701,
    "JavaScript": 24295,
    "TypeScript": 1393265
  },
```

which is _not_ ordered by the weights when returned from the API. We probably need to apply ordering in this chunk to ensure we get the actual top languages, not just the random first 2:

https://github.com/open-sauced/app/blob/ae560f8b51db10e2cf7ef277538a8df40f1dd616/lib/utils/contributor-utils.ts#L1-L10

But this is just a hunch, there's something that's not quite right when getting these languages.

### Steps to reproduce

1. Go to a big user list of contributors
2. Notice the most used languages
3. Go to profiles for those users
4. Notice the difference

### Browsers

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
Ah that's true: it's just confusing. And maybe also inaccurate? For Sunday, his interests are

```
"interests": "javascript,typescript",
```

in the beta API but it shows up as `golang, hacktoberfest` which is funky: I'd expect it to surface that user's interests.

**Comment by nickytonline** [comment]
I think the assumption faith interests was they were languages.  Agree it's probably best to not have that fallback. I assumed they were languages as well, but clearly it can be anything.

**Comment by aryanas159** [comment]
Can I look into this?

**Comment by nickytonline** [comment]
> Can I look into this?

Hey @aryanas159! Thanks for the interest. This has been labelled as core team work.
