### ISSUE TITLE
Bug: When you click on the reaction button, the width of the website changes.

### ISSUE THREAD

**Issue by Himanshuch8055** [open-sauced/app#2301]
### Describe the bug

Please follow these steps to observe the navbar width change on the Highlights page:
1. Navigate to the Highlights page.
2. Click on the "Any post reaction" button.
3. Carefully observe the Navbar. You will notice that its width changes when you click on the reaction button.
4. This width change is a result of clicking on the reaction button.

https://github.com/open-sauced/app/assets/94627200/2f38f40d-c3a9-4659-8c74-bccf9479ae73

### Steps to reproduce

1. Goto "Highlights page"
2. Click on the "Any post reaction button"
3. Now "Check the Navbar carefully. The width of the navbar will change when clicking on the reaction button"

### Browsers

Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by aryanas159** [comment]
Same problem as in #2252, I can make a pull request once it's been triaged.

**Comment by jpmcb** [comment]
This still looks to be a problem in the highlights page. Something in the header bar needs fixing maybe?

**Comment by aryanas159** [comment]
.take
