### ISSUE TITLE
Feature: Add Contributors KPIs to Insight Pages' Contributors Tab

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#2307]
### Type of feature

🍕 Feature

### Current behavior

On **Insight Pages** the cotnributor's tab currently consists of just the contributor's table:
<img width="1432" alt="image" src="https://github.com/open-sauced/app/assets/27322879/f5c190f2-66e0-4d0d-a7a8-c5063a513bb0">

### Suggested solution

Adding contributor's KPIs to this page is very low hanging fruit that we should take advantage of:
<img width="993" alt="image" src="https://github.com/open-sauced/app/assets/27322879/3003fba9-502e-4d78-a29c-1e009cc5c2e2">

We should add cards for:
- Total contributors
- Active contributors
- New contributors
- Churned contributors

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by OgDev-01** [comment]
Hey @isabensusan, what determines the number below the % on the cards?
![image](https://github.com/open-sauced/app/assets/62995161/5119bbc1-272f-420c-b037-a34edf275726)

**Comment by brandonroberts** [comment]
Explore page has been paired down. Will revisit this page in a new issue
