### ISSUE TITLE
Bug:  devcard image isn't rendered properly when shared to other platforms

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#2311]
### Describe the bug

When a user shares their devcard image to other platforms, it gets cut off or doesn't get rendered properly inmost cases. Some examples:

**Sharing to Linkedin**
<img width="400" alt="image" src="https://github.com/open-sauced/app/assets/27322879/9f3911a3-29d7-493f-b1ff-c7b7ce0c06e5">
<img width="580" alt="image" src="https://github.com/open-sauced/app/assets/27322879/ecc6de10-0b9e-4edb-9ade-3c4403585453">

*Sharing to Twitter*
<img width="630" alt="image" src="https://github.com/open-sauced/app/assets/27322879/f3c45d42-f807-4182-8812-162a5d2a0e56">
<img width="597" alt="image" src="https://github.com/open-sauced/app/assets/27322879/eaa1ea3c-18a8-4781-a69a-7c53aa19d0b2">

*Sharing to dev.to*: it isn't supported either. 

We should look into creating an aspect ratio image to support all of these platforms.

### Steps to reproduce

1. Go to any dev card page
2. Click on share to linkedin or share to twitter
3. See the image render incorrectly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
DevCard has been updated
