### ISSUE TITLE
Bug: can't navigate back from user profiles to previous page

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#2313]
### Describe the bug

When navigating from any page to a user profile, if you click on the "back" button on the browser, the paltform doesn't go back to the previous page but rather reloads the user profile.

Reported by Jesse from Xebia:

> When I click a user in the contributors graph above, I'm taken to their profile, the back button won't work to go back to the list, looks like there is an additional redirect added to the history:

https://github.com/open-sauced/app/assets/27322879/bf50f22b-a552-44a9-9992-7e7806aaac3c

### Steps to reproduce

1. Go to the Highlights page 
2. Click on any user profile's link
3. Click "back" on your browser

Expected behaviour would be for the page to go back to Highlights, but it only reloads the user profile.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
I haven't looked into this yet, but I think it related to client side routing pushing to the browser history causing this odd experience.
