### ISSUE TITLE
Feature: replace Contribution distribution chart on Lists with Contributors Table

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#2315]
### Type of feature

🍕 Feature

### Current behavior

On Lists, we are currently showing the Contribution Distribution chart on the Overview tab, but the chart has brought some confusion to users, so we want to re-think it's functionality.
<img width="1426" alt="image" src="https://github.com/open-sauced/app/assets/27322879/f1d341d6-09df-4696-a973-42b1ecfa900e">

### Suggested solution

While we finish building the List Activity tab, we want to replace the Contribution Distribution chart on the Overview tab, with the Contributors table:
![image](https://github.com/open-sauced/app/assets/27322879/b312775f-b8fe-4a54-8556-f95a1701dce8)

To do this, we'll have to:
- Hide the contribution distribution chart
- Hide the Contributors tab

until we figure out better uses for both of those views.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
Love the look of this @isabensusan!

![CleanShot 2023-12-12 at 21 19 45](https://github.com/open-sauced/app/assets/833231/bb23f481-50e4-448f-b34f-e16a92316ab6)
