### ISSUE TITLE
Feature: Image test

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#2323]
### Type of feature

🍕 Feature

### Current behavior

N/A

### Suggested solution

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by isabensusan** [comment]
![arrow-right](https://github.com/open-sauced/app/assets/27322879/76a5b778-1d08-47a2-bda0-93e250acd317)

**Comment by Himanshuch8055** [comment]
Hey, @isabensusan Hope you're doing well. Can you explain the feature you need?

**Comment by isabensusan** [comment]
hey @Himanshuch8055 !! This issue was only a quick test to try out Github's image embeds on issues. I'll close it now, so pls ignore! :)

**Comment by Himanshuch8055** [comment]
ok....  :)
