### ISSUE TITLE
Bug: Complete onboarding button flashes for a second or two on smaller screens

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#2324]
### Describe the bug

Bug: Complete onboarding button flashes for a second or two on smaller screens

### Steps to reproduce

1. Navigate to any page on mobile or use the browser dev tools to select a smaller screen.
2. Log in to the app.
3. If you haven't completed the onboarding, go ahead and do that.
5. Once onboarding completes, notice that as the page loads, the Complete the onboarding button appears for a second or two.

![CleanShot 2023-12-12 at 22 38 16](https://github.com/open-sauced/app/assets/833231/a085f022-e7fd-4b6e-9e37-70a0b080446e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
Look at these two lines https://github.com/open-sauced/app/blob/146dce3fe579f31660fd39a19ef443a2b355e271/components/organisms/TopNav/top-nav.tsx#L27-L28

The check probably needs to check if there is a session as well. This logic could be cleaned up a bit more so there aren't two conditionals. All those checks could be the condition.

```diff
        {user
-          ? !onboarded && (
+          ? session && !onboarded && (
              <div className="relative">
                <OnboardingButton aria="onboarding" className="!flex !pr-1 mb-1 mr-2">
                  <Text className="text-sm !text-light-slate-12 hidden sm:block py-1 px-2">
                    Complete the onboarding
                  </Text>
                </OnboardingButton>
                <div id="onboarding" className="flex flex-col absolute right-0 sm:hidden">
                  <span className="border-x-transparent border-x-[7px] border-b-[7px] border-b-orange-500 h-0 w-0 self-end mr-[1.1rem]" />
                  <Text className="text-sm py-1 px-2 w-max rounded shadow-lg bg-light-slate-2 !text-light-orange-9 outline-[1px] outline outline-orange-500">
                    Complete the onboarding
                  </Text>
                </div>
              </div>
            )
          : null}
```

**Comment by takanome-dev** [comment]
Hey Nick, this issue is still present. Not sure why it's closed 🧐

**Comment by nickytonline** [comment]
Hmm, this shouldn't be closed as the PR is still open. I may have closed it by accident.

**Comment by artemplv** [comment]
.take
