### ISSUE TITLE
Bug: Select All doesn't clear when moving to the next page of contributors

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2328]
### Describe the bug

If I'm looking at the contributors tab of the insights page, and I select all and then move to the next page, it doesn't clear the select all checkbox. To add more contributors to my list, I have to manually click one by one.

<img width="1105" alt="image" src="https://github.com/open-sauced/app/assets/34313413/ad2e9402-6907-4ce2-be5b-76269111920d">

### Steps to reproduce

1. Go to https://app.opensauced.pizza/pages/BekahHW/01/contributors?range=30&limit=50
2. Select all
3. Got to page 2

https://github.com/open-sauced/app/assets/34313413/e4b4aa7d-e224-457f-b84f-567d6552d728

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
This should be a small fix where the comoponent state for the check all just needs to be reset.

**Comment by aryanas159** [comment]
.take

**Comment by nickytonline** [comment]
Based on https://github.com/open-sauced/app/pull/2341#issuecomment-1894197522, I'm closing this issue. We'll revisit select all in the future.
