### ISSUE TITLE
Add a new loading message to contributor list when loading a new page

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2332]
## Current

When I'm clicking to the next page when I'm searching for a new contributor, the message I see says that there are no contributors. 

https://github.com/open-sauced/app/assets/34313413/40e98481-62e2-43cb-babe-0fd0a5db7647

## Solution

If we've clicked the next button, we should either remove the message or add a message that indicates the list is loading. 

## Steps

1. Go to the lists.
2. Search for a contributor (Orta works in this case)
3. Click to see the next list.
4. see the message

**Comment by nickytonline** [comment]
This is a bug. The loading skeleton should be the only thing visible while loading paged data.

**Comment by aryanas159** [comment]
@nickytonline Can I work on this?

**Comment by nickytonline** [comment]
All yours @aryanas159!
