### ISSUE TITLE
Bug: Explore navigation link does not retain it's current(`active`) page style

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#2336]
### Describe the bug

Highlight top navigation link does not retain it's current page style

### Steps to reproduce

1. go to any page in the app.
2. Click the Explore link in the top navigation.
3. Notice it does'n get set to orange for the current page style.

![CleanShot 2023-12-13 at 18 16 10](https://github.com/open-sauced/app/assets/833231/4c75d624-9988-4fe3-8909-fc88a113719f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by a0m0rajab** [comment]
Related code: 
https://github.com/open-sauced/app/blob/e9d37b2208deea6e238aa403a52ea99b314633cb/components/organisms/TopNav/top-nav.tsx#L57-L83

**Comment by sourabpramanik** [comment]
.take
