### ISSUE TITLE
Add followers information to user profile page

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2342]
## Current

Right now to see the number of people who are following you and the number of people you follow, you have to look on the highlight feed, which isn't where any users would expect it.

<img width="250" alt="image" src="https://github.com/open-sauced/app/assets/34313413/c4036840-1076-4c5d-b452-bec92045e5c7">

## Proposed Solution

Add the follower count below the user. This is currently how GH does it and could work for us as well:

<img width="383" alt="image" src="https://github.com/open-sauced/app/assets/34313413/e0b116d3-974c-4fb0-a983-fb975a7f338d">

So it would be similar to this, but would add style and change the SVG.

<img width="305" alt="image" src="https://github.com/open-sauced/app/assets/34313413/909f84a9-0e38-4218-aef1-d7c45bb84ea7">

**Comment by isabensusan** [comment]
## Mockup
<img width="497" alt="image" src="https://github.com/open-sauced/app/assets/27322879/91cd0a1f-5b8b-40bf-9c89-83e8d4e6b976">


## Changes needed
<img width="789" alt="image" src="https://github.com/open-sauced/app/assets/27322879/3fb8bae0-aaed-41c0-9d75-df4d9d2a28c3">

## Notes on styling
<img width="869" alt="image" src="https://github.com/open-sauced/app/assets/27322879/00200832-1f4d-44ee-9b99-53b7b9b0a81b">

**Comment by isabensusan** [comment]
@brandonroberts can we also take this as an opportunity to make the text accessible by changing the text color  for these sections on the panel?

<img width="1081" alt="image" src="https://github.com/open-sauced/app/assets/27322879/20b8dfde-62ec-489c-b26a-1b549095a2ec">

**Comment by brandonroberts** [comment]
@isabensusan Yes

**Comment by diivi** [comment]
Hey! My exams are finally over and I'm back :D Can I work on this?

Also here's what it looks like for me:

![image](https://github.com/open-sauced/app/assets/41837037/cc2fa696-41ca-44e3-ab33-ff96149062bf)

Should the followers/following numbers should go below or above the gift icon?

**Comment by nickytonline** [comment]
> @brandonroberts can we also take this as an opportunity to make the text accessible by changing the text color for these sections on the panel?
> 
> <img alt="image" width="1081" src="https://private-user-images.githubusercontent.com/27322879/290876440-20b8dfde-62ec-489c-b26a-1b549095a2ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NjQ5ODIsIm5iZiI6MTcwMjY2NDY4MiwicGF0aCI6Ii8yNzMyMjg3OS8yOTA4NzY0NDAtMjBiOGRmZGUtNjJlYy00ODljLWIyNmEtMWI1NDkwOTVhMmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE4MjQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4OGVjY2NjYzYyZTc4Mzc5MzgwOWU2ZmJmMWZmNWUzYjg3NzZlY2ZkZmRlOWI1YjUwMDllOTQwMzA5ZjQ3M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vwKhGZXunxjng3hbG-XwHz2Y4WkMTcPsy0PMO-CSDAY">

I have this in a PR for the accessible text colour. I can push that up.

**Comment by isabensusan** [comment]
hey @diivi ! Hope your exams went well :)

To answer your question:
> Should the followers/following numbers go below or above the gift icon?

Here's a quick mock --
1. We want to move the birthday info (with the gift icon) and the timezone info that are currently below the avatar to the space below the "About" block with the social profiles and personal website info
2. We want to use the space below the avatar to display the followers/following info

![image](https://github.com/open-sauced/app/assets/27322879/f79b4f78-72f8-4bdf-b05b-9bdfdc780a43)

Hopefully that clears it up a bit more! Let me know if you have any more questions

**Comment by nickytonline** [comment]
Just dropping a screenshot of beta that has a bunch of colour contrast issues sorted, so this is what it's looking like atm.

![CleanShot 2023-12-18 at 17 54 40](https://github.com/open-sauced/app/assets/833231/2402a1c2-b482-49c9-af62-fd912b84dc06)

**Comment by xkrishguptaa** [comment]
hi! is this issue available to contribute? if yes do we have to fetch data from github API or the app's follower/following count?
