### ISSUE TITLE
Bug: Pagination is not working properly.

### ISSUE THREAD

**Issue by sourabpramanik** [open-sauced/app#2360]
### Describe the bug

Pagination should reset to 1 upon changing the language in Explore page.

### Steps to reproduce

1. Go to **Explore Page**
2. Select any language and scroll down to the pagination
3. Change the page number from **1** to anything in the range, lets say may be **2**
4. Scroll to the top of the page change the language and you will see that the list of repos for the newly selected language are fetched for page **1** but the page number in the pagination is not **1** it is **2** because we selected it before changing the language.
5. Now change the page number to **1** and the list of repos will not change obviously because it is already fetched for page **1**
6. But if you change the page number to **2** again, you will find the list of repos are fetched for page **2**.

> **NOTE**: I used page 2 for this example but this issue is same for any page number other than 1. This issue is also found in other pages where the pagination component is being used.

![sample](https://github.com/open-sauced/app/assets/61370770/f7d2b42f-c665-4b35-84b2-68e5db651e98)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by sourabpramanik** [comment]
@nickytonline I hope I am able describe the issue with enough details to reproduce. I would like work on it if you can assign me this, it will be my first open source contribution to move forward.

**Comment by a0m0rajab** [comment]
@sourabpramanik Feel free to assign this issue to yourself: https://docs.opensauced.pizza/contributing/introduction-to-contributing/#issues

**Comment by sourabpramanik** [comment]
.take

**Comment by sourabpramanik** [comment]
@a0m0rajab can you please review the fix?
