### ISSUE TITLE
Bug: Missing page numbers for pagination

### ISSUE THREAD

**Issue by sourabpramanik** [open-sauced/app#2362]
### Describe the bug

Missing page number and page size for pagination in 
1. Contributors organism

### Steps to reproduce

1. Go to Explore page 
2. Check the Contributors list footer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by sourabpramanik** [comment]
I have fixed it, so if anyone can assign me to it then I will raise a PR.

**Comment by sital002** [comment]
> I have fixed it, so if anyone can assign me to it then I will raise a PR.

You can self assign the isssue please the contributing guide.

**Comment by sourabpramanik** [comment]
@sital002  But the "need triage" label has to be removed first to take the issue right? I am sorry I am new to this so please help out.

**Comment by aryanas159** [comment]
> @sital002 But the "need triage" label has to be removed first to take the issue right? I am sorry I am new to this so please help out.

Yes, you can assign yourself the issue using ".take" command once one of the maintainers looks into the issue and removes the "needs triage" label.

**Comment by OgDev-01** [comment]
Assigned you @sourabpramanik 👍

**Comment by OgDev-01** [comment]
Can you add a screenshot to this issue for quicker understanding?

**Comment by sourabpramanik** [comment]
> Can you add a screenshot to this issue for quicker understanding?

Yes here it is 
<img width="958" alt="image" src="https://github.com/open-sauced/app/assets/61370770/bdbf28c9-2e64-403c-8a21-50512a6a0e7f">

**Comment by nickytonline** [comment]
I'm not sure if we want the page numbers links for these views. I believe @open-sauced/design had it set that way, so just checking in with them @sourabpramanik.

**Comment by sourabpramanik** [comment]
> I'm not sure if we want the page numbers links for these views. I believe @open-sauced/design had it set that way, so just checking in with them @sourabpramanik.

Oh I see, I was not knowing that. Thank you for mentioning that @nickytonline

**Comment by nickytonline** [comment]
We might proceed still @sourabpramanik. I just want to check with design first is all. Thanks for you other contributions btw!

**Comment by sourabpramanik** [comment]
Understood
