### ISSUE TITLE
Bug: Recommendation card in user profile routes to wrong location

### ISSUE THREAD

**Issue by sourabpramanik** [open-sauced/app#2363]
### Describe the bug

Upon clicking the recommendation card in the user profile it opens a new tab with the URL `https://app.opensauced.pizza/hot/repositories/filter/some_owner/some_repo?range=30`
And there is no repo list available unless we click on dashboard tab.

So possible fix is to replace `repositories` path from the URL and add `dashboard` path instead which will select the dashboard tab as default and the page will have list of repos.

### Steps to reproduce

1. Go to Profile page
2. Select Recommendations tab
3. If you have any recommended repo then you can click on the card and it will route you to new tab and opens a new URL

![routing bug #1](https://github.com/open-sauced/app/assets/61370770/32fe2efe-8aaa-49c7-bc0b-949f46ed816f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by sourabpramanik** [comment]
I have already fixed it so if this bug is real then I would like to raise a PR.

**Comment by BekahHW** [comment]
@sourabpramanik there's definitely a bug here. Feel free to raise a PR. Please make sure to include a gif or short video showing the fix.

**Comment by sourabpramanik** [comment]
> @sourabpramanik there's definitely a bug here. Feel free to raise a PR. Please make sure to include a gif or short video showing the fix.

Will do. Thanks @BekahHW
