### ISSUE TITLE
Bug: 'Contributors' page doesn't respect per-page setting (limit query param)

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [open-sauced/app#2404]
### Describe the bug

I want to see more than 10 contributors in my report. But no matter how I change the _Showing: * per page_ setting, nothing seems to change it?

### Steps to reproduce

Steps tried on https://app.opensauced.pizza/pages/JoshuaKGoldberg/1119/contributors?limit=40&range=90:

1. Go to a report's _Contributors_ tab
2. Change the limit to 50, either with a direct URL change or by selecting _Showing: 50 per page_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by sourabpramanik** [comment]
@JoshuaKGoldberg this issue is already fixed in this PR #2153
If you check the [beta](https://beta.app.opensauced.pizza/javascript/contributors/filter/recent?range=30&limit=40) version it is works fine.

**Comment by JoshuaKGoldberg** [comment]
Nice, thanks! Confirmed that https://beta.app.opensauced.pizza/pages/JoshuaKGoldberg/11/reports?range=50 is fixed. 🚀 

Great time to resolution 😄
