### ISSUE TITLE
Bug: Reaction icons are closing right away when clicking the smiley button on the highlight card mode

### ISSUE THREAD

**Issue by adiati98** [open-sauced/app#2408]
### Describe the bug

When I wanted to give a reaction to a highlight, the icon shuts down right away (in milliseconds) every time I click it.

Below is the screen recording. It's hard to capture the state of the icon closing right away, so you might see as if nothing happens when clicking the icon button.

![icon highlights](https://github.com/open-sauced/app/assets/45172775/5b2eb867-9d2f-44b1-9e36-1144611da708)

 

### Steps to reproduce

1. Click the bell icon on the top bar of your OpenSauced dashboard to open the notifications.
2. Click on a user's highlight. You will see the highlight's card.
3. Click the smiley button to give reaction to the highlight.
4. The icons will close immediately.

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by aryanas159** [comment]
.take

**Comment by nickytonline** [comment]
This is most likely happening due to a `<Trigger />` component or component state being wonky.
