### ISSUE TITLE
Add Delete button to Edit List Page

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2424]
Currently, to delete a list, you need to be in the list view of lists.

![image](https://github.com/open-sauced/app/assets/34313413/687c00ad-adee-462e-882f-b79632c1d51e)

In our Insights page, when you edit an insight, there's a Delete Page option at the bottom that we could add to the Edit List page.

![image](https://github.com/open-sauced/app/assets/34313413/c799d279-0aa8-4b42-9528-2ccae042a7af)

**Comment by CBID2** [comment]
.take

**Comment by sourabpramanik** [comment]
@CBID2 can I take this issue?

**Comment by CBID2** [comment]
> @CBID2 can I take this issue?
> 
> 

Let's see what @BekahHW thinks first. It's still in triage mode.

**Comment by BekahHW** [comment]
@CBID2 since you have some open issues and PRs in some of our other repositories, let's give it to @sourabpramanik while you wrap those up.

**Comment by CBID2** [comment]
> @CBID2 since you have some open issues and PRs in some of our other repositories, let's give it to @sourabpramanik while you wrap those up. 

Oh I didn't want to work on this one @BekahHW. I saw the "needs triage" label and just wanted to be sure it was ready for development.

**Comment by BekahHW** [comment]
Ah. Ok. I saw that you used the take command, so I was responding to that.

**Comment by CBID2** [comment]
> Ah. Ok. I saw that you used the take command, so I was responding to that. 

Yeah I decided to let someone else do it

**Comment by BekahHW** [comment]
@CBID2 I didn't have a needs triage label in there bc I didn't feel it needed it.
