### ISSUE TITLE
Bug:  typo when no contributors showing up

### ISSUE THREAD

**Issue by Giuliano1993** [open-sauced/app#2426]
### Describe the bug

when creating an insight page, if no contributor is found the apostrophe isn't properly encoded and result in showing the html entity as text

### Steps to reproduce

1. go to insights
2. create new insight
3. go to contributors
![Screenshot 2024-01-06 120055](https://github.com/open-sauced/app/assets/12759050/455528c7-e8c3-4ef9-a9e3-98c850f9f44e)

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
Here's the line of code that needs to be changed.

https://github.com/open-sauced/app/blob/31d12d384a257c02f1daf9a51a57064ab325447c/components/organisms/ContributorsTable/contributors-table.tsx#L22

And this is what needs to be done.

```diff
-   noContributorsMessage = "Sorry! We couldn&apos;t find any contributors.",
+   noContributorsMessage = "Sorry! We couldn't find any contributors.",
```

**Comment by nickytonline** [comment]
@arol15, would you like to work on this?

**Comment by Arol15** [comment]
.take

**Comment by Arol15** [comment]
> I know @Arol15 was interested in contributing to the app repository. Would you like to work on this? It's a good way to ease your way into the codebase.

Thank you, @nickytonline!! `.take` still feels like magic to me :D
