### ISSUE TITLE
Bug: Delete page button on edit insights page is inacessible.

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#2434]
Relates to changes I proposed for #2427's Delete list button.

              refactor (blocking): use the button's `destructive` variant.

```suggestion
                <Button onClick={() => handleOnDelete()} variant="destructive">
                  Delete list
                </Button>
```

Note: Not for this pull request, but the same will need to be done for the Delete Page button in the edit insights page. I'll create an issue for this.

_Originally posted by @nickytonline in https://github.com/open-sauced/app/pull/2427#discussion_r1444990727_

**Comment by nickytonline** [comment]
The changes to be made are in this file.

https://github.com/open-sauced/app/blob/38ce376afe8b39ce7603a48505a85791c8297e64/components/organisms/InsightPage/InsightPage.tsx#L637-L643


```diff
-                <Button
-                  onClick={() => setIsModalOpen(true)}
-                  variant="default"
-                  className="border bg-light-red-6 border-light-red-8 hover:bg-light-red-7 text-light-red-10"
-                >
-                  Delete page
-                </Button>
+                <Button onClick={() => setIsModalOpen(true)} variant="destructive">
+                  Delete page
+                </Button>

**Comment by ThePiyushAggarwal** [comment]
.take
