### ISSUE TITLE
Feature: Workspaces dashboard

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#2438]
## detailed acceptance criteria

As a user, I should be able to see insights from the data added to a created workspace. These will include but not limited to the following:

- stars, issues, prs
- contributors and repository insights

Tasks:
- [x] #2579
- [x] #2547
- [x] #2580

![CleanShot 2024-01-26 at 16 16 13](https://github.com/open-sauced/app/assets/833231/870cc292-4e96-492e-995b-0ec2ce118be5)

[Designs in Figma](https://www.figma.com/file/sqRXS7hw6E93QgRMCl3WYz/Workspaces?type=design&node-id=902-16244&mode=dev)

**Comment by bdougie** [comment]
updated the OP @nickytonline & @isabensusan. Feel free to edit or remove context.
