### ISSUE TITLE
Bug: Hydration Errors on Insight Pages

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#2441]
Looks like there are some hydration errors on insight pages. Visit https://beta.app.opensauced.pizza/pages/bdougie/43/dashboard?range=30 with the browser devtools console open.

![CleanShot 2024-01-08 at 22 34 36](https://github.com/open-sauced/app/assets/833231/92afb361-2dd1-42a6-b806-9e299d3cb062)

_Originally posted by @nickytonline in https://github.com/open-sauced/app/issues/2440#issuecomment-1882349109_

**Comment by bdougie** [comment]
Commented on the PR, but acknowledging the issue exists. Thanks for opening it.
