### ISSUE TITLE
Saved List should display list

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2446]
Currently, if you save a list, it gives you a message in the upper right corner, but the user stays on the edit page. It would be nice if once you save, it takes you to the updated list.

https://github.com/open-sauced/app/assets/34313413/1468aa57-9504-43fa-8fee-a6b521587881

**Comment by manipandit** [comment]
.take

**Comment by manipandit** [comment]
@BekahHW  I would like to work on this issue.

**Comment by manipandit** [comment]
@BekahHW this issue has needs triage label how can I work on this?

**Comment by BekahHW** [comment]
@manipandit I assigned you!
