### ISSUE TITLE
 The "Lists" tab on the hub seems broken for non-authenticated users

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/app#2457]
> The "Lists" tab on the hub seems broken in this for me: it redirects to the highlights home:

~~Are you logged in?~~

Just checked now, and it also appears broken for me... I don't think this is related to this PR, but i'll open a ticket for it

_Originally posted by @OgDev-01 in https://github.com/open-sauced/app/issues/2194#issuecomment-1885104309_
            

https://github.com/open-sauced/app/assets/62995161/07345425-4c50-4f35-a79b-46f3c455ef3e

**Comment by jpmcb** [comment]
I'm no longer able to reproduce this 😢 maybe it was a fluke: let's leave this open for abit and see if anyone else reports something similar! Otherwise we can close this

**Comment by sourabpramanik** [comment]
Yes this issue is there on beta. 
1. Logout
2. Go to lists
3. refresh and you will be redirected

**Comment by OgDev-01** [comment]
Could also reproduce this in production

**Comment by sourabpramanik** [comment]
> Could also reproduce this in production

Yes it is there in production as well

**Comment by jpmcb** [comment]
> refresh and you will be redirected

Ahhhh interesting: I was missing the redirect part of that flow - yes, I can also reproduce that

**Comment by sourabpramanik** [comment]
![bug](https://github.com/open-sauced/app/assets/61370770/4fb4b007-dedf-4de0-b6d9-7068ce7598f1)

You can find both in beta and production

**Comment by sourabpramanik** [comment]
can I work on this @OgDev-01  @jpmcb ?

**Comment by sourabpramanik** [comment]
.take

**Comment by sourabpramanik** [comment]
Yes I checked the middleware. Can we remove the /hub/:path altogether from the array?

**Comment by nickytonline** [comment]
We can't remove it as there are other paths that need to be protected.

**Comment by sourabpramanik** [comment]
Got it will make the changes like you mentioned before. Thanks for the heads up @nickytonline I was about to push with `/hub/:path*` being removed 😅
