### ISSUE TITLE
Bug: Clear input after adding a repository to insight page

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2474]
### Describe the bug

After adding a repo to an insight page, the repo remains in the search input.

https://github.com/open-sauced/app/assets/34313413/d3a278f6-93fa-4e90-9ac2-6338a599d269

### Steps to reproduce

1. Either create a new insight page or edit an existing one.
2. Add a new repo.
3. See the repo there until you manually delete it.

We probably just need to update the state in that function to reset once the Add Repository button is clicked.

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by shubhamchasing** [comment]
.take

note: this will be my first  Open Source contribution

**Comment by shubhamchasing** [comment]
Getting hydration on Create new insight page
![Screenshot from 2024-01-18 01-17-57](https://github.com/open-sauced/app/assets/106425076/5ae6d53c-a46a-4bba-821a-33caa360ab77)

I think this is an existing issue on beta
![Screenshot from 2024-01-18 01-16-43](https://github.com/open-sauced/app/assets/106425076/97e72a53-4b66-40a3-8a19-38123e5d166f)

**Comment by shubhamchasing** [comment]
@nickytonline do i need to create PR from forked repo or permissions will be granted?
and please the hydration error screanshot above

**Comment by nickytonline** [comment]
The hydration is another issue which is not related to this issue. I just noticed that as well. I'll create a separate PR for that.

I did revert my changes from the mentioned PR @BekahHW @shubhamchasing, and the issue still persists, so I think it's an existing bug and not a newly introduced one.

**Comment by nickytonline** [comment]
> @nickytonline do i need to create PR from forked repo or permissions will be granted for origianl repo? and please see the hydration error screanshot above

Issue #2498 created for this.
