### ISSUE TITLE
Bug: PRs display 0 when you're adding a repo to an insight page

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2475]
### Describe the bug

When you're adding to an existing insight page, any additions show up as 0 PRs. 

![Screenshot 2024-01-16 at 10 42 29 AM](https://github.com/open-sauced/app/assets/34313413/daa6ce91-1ff3-4dcc-a6e4-e61bf918a450)

### Steps to reproduce

1. Either edit or create a new insight page
2. Add a repo
3. See the 0

Note: Once you save the repo, the numbers are updated.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by aryanas159** [comment]
Probably an API issue
![image](https://github.com/open-sauced/app/assets/114330931/adad0c0e-ad60-4541-836f-194d4006db66)

**Comment by aryanas159** [comment]
When we add a repository the API endpoint ```{BASE_URL}/repos/{REPO_NAME}``` is hit, and this doesn't return any of the PR counts, that's why it is displaying zero.

**Comment by aryanas159** [comment]
We have to reinitiate the API request to get the repo data, I can work on this once it's been triaged.
