### ISSUE TITLE
Feature: Add again is not styled and presents a weird box

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#2485]
### Type of feature

🍕 Feature

### Current behavior

![Screen Shot 2024-01-17 at 9 59 47 AM](https://github.com/open-sauced/app/assets/5713670/702a742f-3748-475e-8272-fc044af35bd8)

### Suggested solution

Fix the stylinh

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by sourabpramanik** [comment]
.take

**Comment by sourabpramanik** [comment]
I would like to work on this.

**Comment by bdougie** [comment]
Go for it I @sourabpramanik

**Comment by sourabpramanik** [comment]
.take

**Comment by brandonroberts** [comment]
Closed by https://github.com/open-sauced/app/pull/2501
