### ISSUE TITLE
Bug: Adding already added repos show show "already added" message.

### ISSUE THREAD

**Issue by aryanas159** [open-sauced/app#2500]
### Describe the bug

On the Insight edit page when adding repos that are already added there should be an error or a toast message saying "Repo already added". When handling a large number of repositories the users may be confused if the repository is added or not, since clicking the ```Add repository``` button currently does nothing if the repo is already added.

https://github.com/open-sauced/app/assets/114330931/ee769578-f6dc-4360-a00f-d97d1b9320a9

### Steps to reproduce

1. Go to the insights edit page.
2. Add a repo that is already added to the page.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by sourabpramanik** [comment]
Hey, @aryanas159 there is a similar issue #2247 already raised before and I have also raised a PR #2407  for this. I am attaching a GIF to showcase the changes. Let me know if you like it.
![fix](https://github.com/open-sauced/app/assets/61370770/54e19231-df86-4cd9-9899-8a03763f8b3d)

**Comment by aryanas159** [comment]
@sourabpramanik Oh cool. The fix looks good, let's see what the maintainers think about this.

**Comment by BekahHW** [comment]
It looks like this issue has been resolved, so I'm going to close it. If there are still questions or you don't think it was adequately addressed, feel free to reopen the issue.
