### ISSUE TITLE
Feature: v2 API - use `v2/histogram/prs` in place of `v1/prs/insights`

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#2508]
### Type of feature

🍕 Feature

### Current behavior

Currently, `v1/prs/insights` grabs blocks of data in for `accepted_prs`, `closed_prs`, etc. based on a few time buckets (typically 30 days wide). This is _very_ close to what we can do with `v2/histogram/pull-requests` and a wider time bucket.

### Suggested solution

For example, hitting the `v2/historgram/prs` endpoint for the `open-sauced/app` repo:

```sh
curl -X 'GET' \
  'https://alpha.opensauced.pizza/v2/histogram/pull-requests?range=90&prev_days_start_date=0&width=90&repo=open-sauced%2Fapp' \
  -H 'accept: application/json'
```

Returns data that looks like:
```json
[
  {
    "bucket": "2023-11-28T00:00:00.000Z",
    "prs_count": 109,
    "accepted_prs": 75,
    "closed_prs": 14,
    "draft_prs": 9,
    "active_prs": 9,
    "spam_prs": 0,
    "pr_velocity": 3
  },
  {
    "bucket": "2023-10-14T00:00:00.000Z",
    "prs_count": 151,
    "accepted_prs": 130,
    "closed_prs": 9,
    "draft_prs": 5,
    "active_prs": 5,
    "spam_prs": 0,
    "pr_velocity": 3
  },
  {
    "bucket": "2023-08-30T00:00:00.000Z",
    "prs_count": 2,
    "accepted_prs": 0,
    "closed_prs": 1,
    "draft_prs": 0,
    "active_prs": 0,
    "spam_prs": 0,
    "pr_velocity": 0
  }
]
```

If these bucket times/widths look abit strange, it's because timescale is doing most of the heavy lifting trying to figure out where the "origin" is for the given data and the associated events. Read more on this here: https://docs.timescale.com/use-timescale/latest/time-buckets/about-time-buckets/#origin

---

Related to: 
- https://github.com/open-sauced/api/pull/470
- https://github.com/open-sauced/app/issues/2507

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
@brandonroberts - I think you were last looking at this: feel free to unassign yourself if other things have come up!

**Comment by brandonroberts** [comment]
Closed in https://github.com/open-sauced/app/pull/2516
