### ISSUE TITLE
Feature: v2 API - update contributions-evolution-by-type graph

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#2513]
### Type of feature

🍕 Feature

### Current behavior

Followup to: https://github.com/open-sauced/api/pull/485

A few things have changed with this v2 update: now uses `bucket` as the ISO time-string, has a few updated stat fields (like `commits`, etc.) See above PR for full list of changes.

### Suggested solution

- Update DTO for graph to use new datatypes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by sourabpramanik** [comment]
.take

**Comment by jpmcb** [comment]
Thanks for taking this on @sourabpramanik - I had meant to tag this as core team work, but if you're feeling up for it, go ahead! You'll want to land these changes on the `alpha` branch here and use `alpha.api.opensauced.pizza` as your API reference.

**Comment by sourabpramanik** [comment]
Oh! I will give it a shot if that works. 

Just to clarify this change has to be done on `/list/[listid]/activity` page right or somewhere else? Can you help me with where I should focus please @jpmcb?

**Comment by jpmcb** [comment]
Sine this API endpoint has changed, anywhere we grab data with this hook:

https://github.com/open-sauced/app/blob/caa511ccc079066e5a82731a44892f2b9b6945e2/lib/hooks/api/useContributionsByEvolutionType.ts#L27

**Comment by jpmcb** [comment]
Hey @sourabpramanik - We're getting really close to doing the v2 cutover: any progress here?

I may reassign this to me if you haven't started working on it yet since this was originally intended to be core team work and we're moving pretty fast on making this v1 --> v2 transition happen.

**Comment by sourabpramanik** [comment]
Hey @jpmcb I can see that yesterday the changes were already merged and there is only one place where 
` const apiEndpoint = lists/${listId}/stats/contributions-evolution-by-contributor-type?${query.toString()}` is being used. So, are there any other changes to be done here?

https://github.com/open-sauced/app/blob/8d38551610674ec6d49d9db6578a03c5eabcfd55/components/molecules/ContributionsEvolutionByTypeCard/contributions-evolution-by-type-card.tsx#L59C1-L65C1

**Comment by sourabpramanik** [comment]
I will unassign myself so that you can close this one.

**Comment by Vijaykv5** [comment]
.take

**Comment by Vijaykv5** [comment]
May I can work on it

**Comment by jpmcb** [comment]
> I can see that yesterday the changes were already merged

Ahh, good catch: I think this ended up being less granular than when I planned out this work. Thanks for the validation!

Marking this as closed since the user list graph endpoints are now migrated on `alpha`! Thanks all!
