### ISSUE TITLE
Feature: v2 API - remove `hacktoberfest`

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#2514]
### Type of feature

🍕 Feature

### Current behavior

Followup to: https://github.com/open-sauced/api/pull/481

In the above PR, `hacktoberfest` was removed as a possible topic (and the logic to only aggregate data for that given topic within Oct 1st - 31st of the configured year)

### Suggested solution

While not necessary, for consistency, we should remove hacktoberfest as a topic in the app as well.

Note to anyone who picks this up: please merge these changes to `alpha` as it should coincide with the v2 API cutover.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by OgDev-01** [comment]
I believe this has been tackled in https://github.com/open-sauced/app/pull/2371 cc: @jpmcb

**Comment by jpmcb** [comment]
Oh great!!! Thanks for the heads up @OgDev-01 ❤️ 

---

I noticed a few components still have reference to the hacktoberfest topic here:

https://github.com/open-sauced/app/blob/13d2e2847523ad221737f029a2c1519be503af6a/components/atoms/FilterCard/filterCard.stories.tsx#L24-L30

Does it make sense to remove those too?

**Comment by OgDev-01** [comment]
> Does it make sense to remove those too?

Absolutely 💯.  Those are storybook components and has no effect than for testing purposes.  Whoever works on this can switch to javascript and that will be good 👍

**Comment by HodaSalim** [comment]
.take

**Comment by sreeharsha-rav** [comment]
.take
