### ISSUE TITLE
Feature: v2 API - update most-active-contributors graph

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#2515]
### Type of feature

🍕 Feature

### Current behavior

Followup to: https://github.com/open-sauced/api/pull/476

### Suggested solution

It doesn't look like much has changed in the PR but we should validate this graph still works on `alpha` with the new `v2` endpoints 👍🏼 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
Graph still works correctly

![image](https://github.com/open-sauced/app/assets/42211/053c0140-2dfc-40aa-bb63-10e057c8a17b)

https://alpha.app.opensauced.pizza/lists/fbcc8983-a87e-4d9a-b19e-9ac89b171771/activity
