### ISSUE TITLE
Bug: Create new insights page has hydration errors

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#2520]
@shubhamchasing reported getting hydration on the create new insight page while working on #2474.

From @shubhamchasing:

![Screenshot from 2024-01-18 01-17-57](https://github.com/open-sauced/app/assets/106425076/5ae6d53c-a46a-4bba-821a-33caa360ab77)

I think this is an existing issue on beta
![Screenshot from 2024-01-18 01-16-43](https://github.com/open-sauced/app/assets/106425076/97e72a53-4b66-40a3-8a19-38123e5d166f)

_Originally posted by @shubhamchasing in https://github.com/open-sauced/app/issues/2474#issuecomment-1896676617_

**Comment by nickytonline** [comment]
To fix this, wrap the problematic component with the `<ClientOnly />` component. Note that we want to render as much markup as possible server-side, so try and narrow it down to the exact component that is causing the hydration error.

**Comment by jdwilkin4** [comment]
.take

**Comment by shubhamchasing** [comment]
@nickytonline My apologies but first I metnioned this issue in the [#2474](https://github.com/open-sauced/app/issues/2474) but then realised this is a separate isse so I created this [#2498](https://github.com/open-sauced/app/issues/2498). I think we should close any of one.
