### ISSUE TITLE
Feature: Make the app sidebar collapsible

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#2527]
As a a user, I want a collapsible side bar so that I can have the most page real estate possible.

![CleanShot 2024-01-25 at 11 57 19](https://github.com/open-sauced/app/assets/833231/f85d4d14-026c-4e8c-ac56-ec276aa3b194)

Use this icon from [HeroIcons](https://heroicons.com/) to open and close the side bar.

![CleanShot 2024-01-25 at 11 58 46](https://github.com/open-sauced/app/assets/833231/e9cd0e71-5a8d-4672-9546-b94a9af6f8f9)

**Comment by Vijaykv5** [comment]
.take

**Comment by nickytonline** [comment]
@isabensusan, I think @zeucapua could work on this, to help with the polish for workspaces.
