### ISSUE TITLE
Bug: app attempts to make too broad of API requests hitting 400

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#2539]
### Describe the bug

In https://github.com/open-sauced/api/pull/501 several `search` and `list` endpoints were changed to throw a 400 if no topic, repoIds, or other parameter was not provided. I.e., this was added to prevent extremely expensive full table scans of data.

For example, hitting the contributors search endpoint without any filter or query params:

```
https://beta.api.opensauced.pizza/v2/contributors/search?range=30&width=30
```

will throw a bad request

```
{"statusCode":400,"message":"must provide repo, repoIds, topic, filter","error":"Bad Request"}
```

---

After #2532, I noticed a few 400s being thrown in insight pages on beta:

```
https://beta.api.opensauced.pizza/v2/histogram/pull-requests?range=30&width=30
```

and

```
https://beta.api.opensauced.pizza/v2/contributors/search?page=1&limit=10&range=30
```

These latter seem to get re-called with the appropriate repoIds for the page:

```
https://beta.api.opensauced.pizza/v2/histogram/pull-requests?repoIds=77358263%2C345368765%2C279759605%2C16408992%2C583706111%2C49010787%2C145050544&range=30&width=30
```

and

```
https://beta.api.opensauced.pizza/v2/contributors/search?page=1&limit=10&repoIds=16408992%2C583706111%2C49010787%2C145050544%2C77358263%2C345368765%2C279759605&range=30
```

which return data correctly.

The page still loads fine, so maybe this is a hydration flow problem?

### Steps to reproduce

1. Open networking developer tooling and filter for `api.opensauced.pizza` to get only our API requests
2. Go to an insights page
3. Filter for 400s
4. Notice the failures

### Browsers

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
This histogram one is likely to happen if we make a request before the params are set. I'll take a look
