### ISSUE TITLE
Bug: Error serializing `.featureFlags` message shows up when trying to access insights page locally not signed in

### ISSUE THREAD

**Issue by jdwilkin4** [open-sauced/app#2542]
### Describe the bug

If you launch the application locally and try to go to `http://localhost:3000/hub/insights`, without being signed in, then you will see this message
 
<img width="950" alt="Screenshot 2024-01-26 at 10 53 48 AM" src="https://github.com/open-sauced/app/assets/67210629/035b9df5-7ab3-4ef5-a932-29a47a39f368">

On the live site, it asks you to sign in to see the insights page
<img width="1311" alt="Screenshot 2024-01-26 at 10 54 33 AM" src="https://github.com/open-sauced/app/assets/67210629/65e8749f-d32e-41a1-a02b-85cb30d6b2bf">

It would be nice to show a similar message locally, instead of have this error message

### Steps to reproduce

1. start the application locally
2. go to http://localhost:3000/hub/insights
3. see the error message describe above

### Additional context (Is this in dev or production?)

dev

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
This could be an issue with our recent alpha -> beta work in #2532 as this was working previously.

**Comment by nickytonline** [comment]
Check the history of middleware.ts to see when this stopped working.

**Comment by jdwilkin4** [comment]
It looks like the issue happened in this [commit](9cd0b9e8a46800ad2951c253c201308f751c455f) here
Here is the full PR with that changes
https://github.com/open-sauced/app/pull/2467/files

Updating the return value does get rid of the error locally, but I am not sure what ramifications that has on other parts of the application

```js
return featureFlags || null;
```
<img width="1403" alt="Screenshot 2024-01-26 at 5 12 04 PM" src="https://github.com/open-sauced/app/assets/67210629/204c547d-0bf1-44b5-896c-38239c618005">

**Comment by nickytonline** [comment]
Thanks for investigating @jdwilkin4! I'm going to assign this to myself as I worked on the PR that introduced this.

**Comment by nickytonline** [comment]
This doesn't appear to be an issue in production. If you have some bandwidth, next week @brandonroberts, could you take a peek at this? I'm still deep in workspaces feature work.

**Comment by brandonroberts** [comment]
Fixed with https://github.com/open-sauced/app/pull/2549
