### ISSUE TITLE
Bug: No clear error message/state shown when posting a highlight that is too long

### ISSUE THREAD

**Issue by FatumaA** [open-sauced/app#2560]
### Describe the bug

When posting a highlight that exceeds 500 characters, the input does not show a clear error message and the border does not show an error state. The only feedback given is the count in the corner turns red. This is not that visible and not obvious. 

Screenshot showing this: 
![Screenshot 2024-01-31 at 00 39 22](https://github.com/open-sauced/app/assets/67555014/f4b3c5c2-d72f-4772-8675-b446ac142f0b)

### Steps to reproduce

1. Click on Highlights tab
2. Click on the post a highlight input
3. Add text that exceeds the 500 limit
4. Notice the input shows no clear error except the count turns red

### Additional context (Is this in dev or production?)

localhost

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by FatumaA** [comment]
I'd love to fix this as this #2422 is blocked by this #2559 for me

**Comment by takanome-dev** [comment]
Hey @FatumaA, you can fix #2559 while fixing this issue 🙂

As for #2422, it's a backend issue. Should be moved in the api repo

**Comment by FatumaA** [comment]
Great will take it and make a PR as soon as the triage label is removed
