### ISSUE TITLE
Bug: Create Uniform Save Changes for Insight Page

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2563]
### Describe the bug

I want to save my insight page after editing, but there's no Save Changes button. 

This is what it currently looks like:

![image](https://github.com/open-sauced/app/assets/34313413/14153772-7b49-43ce-bb53-002eff4b6fd2)

Let's make it uniform with lists to make it clearer to the user:

![image](https://github.com/open-sauced/app/assets/34313413/b8eb3f1c-e329-4959-b97b-e599fc8419e8)

### Steps to reproduce

1. go to your insight page
2. edit it
3. see no "Save Changes" button

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by BekahHW** [comment]
@manipandit I was in the middle of updating the issue. I think it needs to be uniform with Lists, which has a clearer button to save the changes

**Comment by manipandit** [comment]
.take

**Comment by manipandit** [comment]
@BekahHW  Does this look right?
I have added a button similar to lists

https://github.com/open-sauced/app/assets/110151059/561a320e-152a-41e2-9e24-64b3060fe465

**Comment by bdougie** [comment]
Commented on the PR but this PR https://github.com/open-sauced/app/pull/2949 updates how insights are created, creating uniformity.
