### ISSUE TITLE
Bug: Can't navigate back in the browser from the Explore page

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#2568]
Currently a querystring parameter gets added to https://beta.app.opensauced.pizza/javascript/dashboard/filter/recent in a `useEffect`, i.e. `?range=30`. When you navigate back in the browser, it returns to https://beta.app.opensauced.pizza/javascript/dashboard/filter/recent, but the `useEffect` kicks in again and brings you back to https://beta.app.opensauced.pizza/javascript/dashboard/filter/recent?range=30 .

The default range is 30 days, so there's no need to add it on with a `useEffect`.

**Comment by joaomarcosjova** [comment]
To prevent the addition of the `?range=30` query parameter every time the component re-renders or navigates back in the browser, you can conditionally add the query parameter only if it's not present in the URL. Here's how you can modify your `useEffect` to achieve this:

```javascript
import { useEffect } from 'react';
import { useHistory, useLocation } from 'react-router-dom';

function YourComponent() {
    const history = useHistory();
    const location = useLocation();

    useEffect(() => {
        // Check if the range query parameter is already present in the URL
        const params = new URLSearchParams(location.search);
        if (!params.has('range')) {
            // Add the default range parameter if it's not already present
            params.set('range', '30');
            // Update the URL with the new query parameter
            history.replace({ search: params.toString() });
        }
    }, [history, location.search]);

    // Your component logic here
}
```

In this code:

- We use `useHistory` and `useLocation` hooks from React Router to access the history object and the current location.
- Inside the `useEffect`, we check if the `range` query parameter is already present in the URL using `URLSearchParams`.
- If the `range` parameter is not present, we add it with the default value of `30`.
- Finally, we update the URL using `history.replace()` to prevent adding a new entry to the history stack.

This way, the `?range=30` query parameter will only be added to the URL if it's not already present, avoiding unnecessary additions on navigation back.

**Comment by joaomarcosjova** [comment]
> Thanks for chiming in @joaomarcosjova, but we don't need the use effect at all. The default range is 30. We don't need to modify history or anything else. We can let the browser handle the URL when it changes.

I see, thanks for the feedback
