### ISSUE TITLE
enhancement: Unify UX for insights and lists

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2574]
### Describe the bug

Right now, lists have a different ux than insights. To maintain continuity for users, we should create a unified list and insight page view.

## Insight View

![iinsight view](https://github.com/open-sauced/app/assets/34313413/37f83a5d-d3c9-4438-929c-297924b67aa8)

## List View 

![list view](https://github.com/open-sauced/app/assets/34313413/7192cfcb-2065-4dc7-aafe-dcd9921fc74e)

## Proposed View 
Instead of having edit or delete, we should have all the options

I![image](https://github.com/open-sauced/app/assets/34313413/b47ea6cd-5827-45a6-a3a9-7f348ed0f756)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bobmakesmagics** [comment]
Hi @BekahHW,
Nice to meet you.
If you don't mind, I'd like to fix this issue now.
I would like to hear from you.
Thanks.

**Comment by bobmakesmagics** [comment]
Hi,
As you are aware, the insights page view lacked a delete button, and the lists page view didn't have an edit button. I have now added an edit button and a delete button on each page view to ensure that they will have the same set of options. This way, there is no need to implement additional logic for each newly added button when clicked?

**Comment by bobmakesmagics** [comment]
this is updated Insights page view
![image](https://github.com/open-sauced/app/assets/94222486/66dbc210-05c9-4ddf-8ba1-efb37e65871c)

and this is updated Lists page view
![image](https://github.com/open-sauced/app/assets/94222486/e0aaa9d8-8d6a-4fda-af24-f23bbcc4d999)

As you see, I have already added delete button on Insights page view.
and I added edited button on Lists page view.
and I revised small styles of arrow button on Lists page view.
I am not sure if I should add functional logic and modal of added deleted button on Insights page view.
I would like to hear from you.

**Comment by bobmakesmagics** [comment]
if I shouldn't add delete logic and modal, I will create PR for my current updated code now.

**Comment by bobmakesmagics** [comment]
Could you please review this?
https://github.com/open-sauced/app/pull/2582

**Comment by takanome-dev** [comment]
Thanks for the contribution, @bobmakesmagics 

> I am not sure if I should add functional logic and modal of added deleted button on Insights page view.

I guess so 🤔 , otherwise there wouldn't be a need to add those buttons

**Comment by bobmakesmagics** [comment]
Got it. 
I will add such functions.
Thanks.

**Comment by bobmakesmagics** [comment]
is there a endpoint to delete specific insight in the backend API?

**Comment by bobmakesmagics** [comment]
https://github.com/open-sauced/app/assets/94222486/9ff5e877-8c4e-4c6f-9ada-2399a8559414

Please review this.
