### ISSUE TITLE
Feature: Workspaces MVP: Tracking Contributors

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#2578]
As a user of workspaces, I want to be able to compile a list of contributors to track whether it be from tracked repositories or an individual contributor(s).

- [ ] #2642
- [x] #2643

![CleanShot 2024-02-02 at 18 51 54](https://github.com/open-sauced/api/assets/833231/3959f35a-7e19-4e0d-9031-e8cc21005b8f)

![CleanShot 2024-02-02 at 18 54 06](https://github.com/open-sauced/api/assets/833231/3850a222-b266-4019-bdc3-1b46f24dea54)

![CleanShot 2024-02-02 at 18 54 28](https://github.com/open-sauced/api/assets/833231/acd6b345-ae30-4bb0-9175-aac8b548de4f)

- [Design in Figma](https://www.figma.com/file/sqRXS7hw6E93QgRMCl3WYz/Workspaces?type=design&node-id=713-16465&mode=dev)
- Relates to #2437

**Comment by nickytonline** [comment]
https://github.com/open-sauced/api/issues/556 is part of this feature work.

**Comment by isabensusan** [comment]
Closing this as we've pivoted away from tracking contirbutors
