### ISSUE TITLE
Feature: Ability to filter workspaces repostitories dashboard for certain repositories

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#2581]
As a user of the workspaces repositories dashboard, I want the ability to filter the grid so that only the repositories I wish to see are filtered in the grid.

![CleanShot 2024-02-02 at 19 20 51](https://github.com/open-sauced/app/assets/833231/a126c02e-568a-4575-b8bf-4716b014d1de)

Implementation details:
- Use the multiselect component with filtering enabled
- Create a custom hook to load the tracked repositories for the given workspace.
- Use the [/v2/workspaces/{id}/repos](https://beta.api.opensauced.pizza/#/Workspace%20repos%20service/getWorkspaceReposForUser) endpoint.

Relates to #2579
[Designs in Figma](https://www.figma.com/file/sqRXS7hw6E93QgRMCl3WYz/Workspaces?type=design&node-id=902-16244&mode=dev)

**Comment by jpmcb** [comment]
There are API updates here as well: currently, I think, the workspaces activity ratio, stats, health, etc. endpoints are workspace wide. And don't filter on certain repos.

I'll come back here with some investigation details on the API side.

**Comment by jpmcb** [comment]
With https://github.com/open-sauced/api/pull/616 we can filter on a list of repo full names - this should allow us to filter all the workspace stats based on just a few of the repos in the workspace. @zeucapua, let me know if you need anything else on the API side!
