### ISSUE TITLE
Feature: Update the layout for hub pages to use the new workspaces layout

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#2585]
As a user of workspaces, I want to have a consistent layout for workspaces. Current hub pages should have the same layout as workspaces routes: `/workspaces/new`, `/workspaces/settings`, and `/workspaces/some-workspace-id/*` 

All other pages in the site should not have the workspaces layout.

- [x] #2652
- [x] #2654

**Comment by nickytonline** [comment]
The pages for those routes should be wrapped with the https://github.com/open-sauced/app/blob/beta/components/Workspaces/WorkspaceLayout.tsx component.

It may require some tweaking to the existing hub page layouts.

cc: @isabensusan

**Comment by sourabpramanik** [comment]
I would like to work on it if that's okay!!

**Comment by nickytonline** [comment]
I believe this got done from @brandonroberts work in #2648 and will be completed after #2654 is merged.

**Comment by brandonroberts** [comment]
Closing as resolved in the Workspaces MVP
