### ISSUE TITLE
Bug: List Data isn't displayed

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2596]
### Describe the bug

Lists Data isn't showing up.
<img width="1150" alt="image" src="https://github.com/open-sauced/app/assets/34313413/2cfd8024-153a-4252-bd30-e5630633358f">

### Steps to reproduce

1. Go to one of your lists.
2. See nothing.

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickaldwin** [comment]
Hi @BekahHW i'm interested to work on this issue

**Comment by nickaldwin** [comment]
.take

**Comment by bobmakesmagics** [comment]
I would like to work on this issue now.
Thanks

**Comment by nickaldwin** [comment]
> The issue you are trying to assign yourself is blocked until it can be triaged or by another label on the issue.

i understand thank you

**Comment by jpmcb** [comment]
Thanks all for jumping g in: this has already been fixed in the API and will be released to push this fix

**Comment by nickaldwin** [comment]
@jpmcb thank you so much for the update i appreciate it
