### ISSUE TITLE
Feature: pizza.new needs to be an auth protected route 

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#2599]
### Type of feature

🍕 Feature

### Current behavior

Per this [Tweet](https://x.com/saucedopen/status/1754559032013017192?s=20), I made the decision to purchase [pizza.new](https://pizza.new) and redirected it to https://app.opensauced.pizza/hub/insights/new.

When a user is not logged in, they are not redirected to do so. 

### Suggested solution

I looked through the code and @nickytonline's recent PR https://github.com/open-sauced/app/pull/2584

My guess is protected routes are managed in the Middleware, but not confident on that. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
@brandonroberts visiting https://pizza.new when not logged in, does not send you to auth.

**Comment by brandonroberts** [comment]
Ok, I'll see what it needs to go directly to the Supabase auth
