### ISSUE TITLE
Chore: Fix convoluted file routes

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#2600]
Currently we have some bizarre file routes in the application:

- pages/[userOrg]/[pageId]/[toolName].tsx
- [pageId]/[toolName].tsx

This causes several problems:
- it's confusing that there is a `pages` folder in the pages router folder
- the structure of these file base routes allow you to go to a page that should 404, but instead it results in an empty page with the title of a page that doesn't exist
- it's a source of confusion for anyone looking to work on pages that hit those confusing file-bsed routes

**Comment by nickytonline** [comment]
There should be clearer routes. So for example, if I want to go to an insights page, I'd expect the route to look like this.

For example. this is the home page for insights, https://app.opensauced.pizza/hub/insights and an individual insight currently https://app.opensauced.pizza/pages/nickytonline/1178/dashboard. It could probably be tweaked to something like this.

https://app.opensauced.pizza/hub/insights/1178/dashboard which would result in a pretty unambiguous file route.

With all the above a route for an insight would probably be better suited as `/hub/insights/[insightId]/dashboard`.

Personal workspaces are coming and there are insight pages for paying customers of workspaces, so this might be better surfaced as:

`/workspaces/[workspaceId/repository-insights/[id]/dashboard` kind of like we discussed yesterday @zeucapua.

**Comment by zeucapua** [comment]
For the insights, I'll create a `/hub/insights/[insightId]/dashboard` route for now and we can migrate it under the workspaces route once the personal workspaces are implemented and the data are migrated over.

**Comment by zeucapua** [comment]
@nickytonline and I talked 
- remove `/hub` and `/pages`
- move `/[pageId]` under new `/explore` route

**Comment by nickytonline** [comment]
so now we'd get stuff like `/explore/javascript/...` or would we want to make it more explicit like `/explore/language/javascript` or `/explore/topic/javascript` since some aren't necessarily languages, e.g. Angular, Svelte?
