### ISSUE TITLE
Bug: Can keep typing in the bio field of user settings after 255 characters

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#2612]
We currently display a message saying the bio is too long in the user settings, but we're not leveraging the native [maxLength](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/maxlength) HTML attribute to prevent someone from typing past the limit.

![CleanShot 2024-02-07 at 08 15 24](https://github.com/open-sauced/app/assets/833231/a235aecb-170b-4efc-ac58-2a942677c3a0)

As well, since `maxLength` prevents you from typing or pasting text past 255 characters, the `bio too long` message will actually never appear so it can be removed from the component.

This is what happens when `maxLength="255"` is set.

![CleanShot 2024-02-07 at 08 08 43](https://github.com/open-sauced/app/assets/833231/5e22c1cb-51f5-46d2-baf9-77f4fbff3527)

**Comment by nickytonline** [comment]
The file to change is https://github.com/open-sauced/app/blob/3d157ab69ae34353ec169f6c6cbd12744c199a98/components/organisms/UserSettingsPage/user-settings-page.tsx#L273-L298

Here's what needs to be done to fix this

```diff
            {/* Bio section */}
            <div className="flex flex-col gap-2">
              <label className="flex flex-col w-full text-sm">
                Bio
                <div className="flex-1 px-2 shadow-input border transition rounded-lg py-1 flex items-center bg-light-slate-4 disabled:cursor-not-allowed focus-within:border-light-orange-9">
                  <textarea
                    rows={4}
                    placeholder="Tell us about yourself."
                    name="bio"
                    className="w-full focus:outline-none placeholder:font-normal placeholder-slate-400 bg-inherit"
                    value={bio}
+					maxLength={255}
                    onChange={(e) => setBio(e.target.value)}
                  ></textarea>
                </div>
              </label>

-              {bio?.length > 255 ? (
-                <p aria-live="assertive" className="text-light-red-10 text-xs">
-                  Bio too long
-                </p>
-              ) : (
-                <p aria-live="polite" className="text-xs">
-                  {bio?.length}/255
-                </p>
-              )}
+              <p aria-live="polite" className="text-xs">
+                {bio?.length}/255
+              </p>
            </div>
```

**Comment by lexlucid** [comment]
.take

**Comment by Pagla-Dasu** [comment]
.take

**Comment by HodaSalim** [comment]
.take

**Comment by devharsh2k4** [comment]
is it still open?

**Comment by devharsh2k4** [comment]
@nickytonline   i have raised a pr if possible could u review

**Comment by nickytonline** [comment]
> @nickytonline i have raised a pr if possible could u review

@devharsh2k4, it's already assigned to @Pagla-Dasu and they have a PR up for this.
