### ISSUE TITLE
Bug: Can type more than 500 characters for a highlight summary resulting in a negative number in the UI

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#2613]
Currently when adding a summary for a highlight, you can type more than 500 characters for a highlight summary resulting in a negative number in the UI.

![CleanShot 2024-02-07 at 08 02 29](https://github.com/open-sauced/app/assets/833231/70d5458f-1466-4949-8e8e-f5279f7da007)

We can use the native [maxLength](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/maxlength) HTML attribute to prevent someone from typing past the limit.

**Comment by nickytonline** [comment]
To fix this, make the following change in https://github.com/open-sauced/app/blob/3d157ab69ae34353ec169f6c6cbd12744c199a98/components/molecules/HighlightInput/highlight-input-form.tsx#L550-L571

```diff
              <TypeWriterTextArea
                className={`resize-y min-h-[80px] max-h-99 font-normal placeholder:text-slate-400 text-light-slate-12 placeholder:font-normal placeholder:text-sm transition focus:outline-none rounded-lg ${
                  !isDivFocused ? "hidden" : ""
                }`}
                defaultRow={4}
                value={bodyText}
                onKeyUp={(e) => {
                  if (e.ctrlKey && e.key === "Enter") {
                    handlePostHighlight(e);
                  }
                }}
                placeholder={`Tell us about your highlight and add a link
+                maxLength={500}
              `}
                typewrite={isTyping}
                textContent={bodyText}
                onChangeText={(value) => {
                  handleTextAreaInputChange(value);
                  setCharCount(value.length);
                }}
                ref={textAreaRef}
              />
```

**Comment by tusharwebd** [comment]
Thanks for the suggestion as well @nickytonline. I've created a PR for this: https://github.com/open-sauced/app/pull/2614.
