### ISSUE TITLE
Bug: Can't open tabs on the navbar after open the profile page unless with hard refresh

### ISSUE THREAD

**Issue by adiati98** [open-sauced/app#2622]
### Describe the bug

From the profile page, clicking any of the tab on the navbar didn't bring me to the targeted page although the path changed.

### Screen Recording

![tab not open](https://github.com/open-sauced/app/assets/45172775/e67e961c-9032-4664-b355-73ae17f7f85f)

### Steps to reproduce

1. Go to a profile page, e.g.: https://app.opensauced.pizza/user/adiati98
2. Click either "Insights", "Explore", or "Highlights" tab on the navbar.
3. You will see that the path change, but it doesn't open the page.
4. Hard refresh the page by highlighting the path and click enter.
5. Now the page opens.

### Browsers

Chrome

### Additional context (Is this in dev or production?)

This happens in production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bobmakesmagics** [comment]
Hi,
I would like to fix this issue now.
thanks

**Comment by nickytonline** [comment]
Please read the contribution guidelines in the comment above yours @bobmakesmagics. Also, no need to tag core team members directly. We all get the GitHub notifications. Thanks!

**Comment by bobmakesmagics** [comment]
.take

**Comment by adiati98** [comment]
Hey @bobmakesmagics,

This issue is not yet available for grab as mentioned in the contributing guidelines in the bot message:

> If you would like to work on this issue, please wait for us to decide if it's ready. The issue will be ready to work on once we remove the "needs triage" label.

For your future reference, it would be very helpful if you first read the contributing guidelines before start exploring and contributing to a project. 😊

**Comment by bobmakesmagics** [comment]
https://github.com/open-sauced/app/assets/94222486/d78111d0-98f5-4853-b686-e26000d0df3f

I followed the steps to reproduce but I could not see the bug.
Please take a look above record video in my end.
Thanks.

**Comment by bobmakesmagics** [comment]
I worked on beta branch.

**Comment by adiati98** [comment]
@bobmakesmagics I'm not sure about the developer environment, but this happens in the production. This is a screen recording from today.

https://github.com/open-sauced/app/assets/45172775/69d99a1d-e405-40fb-a719-ce4dc53289a1

**Comment by bobmakesmagics** [comment]
could you please let me know production branch?

**Comment by bobmakesmagics** [comment]
which branch should i work to fix production?

**Comment by adiati98** [comment]
@bobmakesmagics, what I mean by production is when you sign in to OpenSauced app at https://opensauced.pizza/

**Comment by bobmakesmagics** [comment]
Of course, I have already checked this issue on the production.
by the way, I am asking which branch I will work to fix this bug.

**Comment by adiati98** [comment]
@bobmakesmagics, you need to create a new branch to work on the changes.

**Comment by bobmakesmagics** [comment]
could you please check again if the current production branch is beta ?

**Comment by adiati98** [comment]
Production branch is `main`, but everything goes to `beta` first.
If you can't find any issue in `beta`, most probably it's fixed.

@open-sauced/engineering team is the one who can confirm this.

**Comment by brandonroberts** [comment]
I'm looking into this one. Similar to https://github.com/open-sauced/app/issues/2656
