### ISSUE TITLE
fix: small screen improvements for workspaces

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#2632]
Some cleanup to the workspaces flows needs to be done for smaller screens

- [x] #2628
- [x] #2738
- [x] #2745
- [x] #2740
- [x] #2752

**Comment by takanome-dev** [comment]
@nickytonline should we go ahead and close this issue??

**Comment by nickytonline** [comment]
There's other things to do, so going to keep this open for now.

**Comment by isabensusan** [comment]
For reference -- here's a design for the sidebar on mobile
![image](https://github.com/open-sauced/app/assets/27322879/ea3f194a-7196-4f32-8687-6c7cdc1f99b6)
