### ISSUE TITLE
Feature: New workspace routes for hub lists and insights

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#2645]
As a user of workspaces, personal or not, I want to be able to access my contributor insights (previously named lists) and repository insights (previously named insights) from a link within my workspace, e.g.

 - `/workspaces/some-id/contributor-insights` (previously /hub/lists)
 - `/workspaces/some-id/contributor-insights/some-id`
 - `/workspaces/some-id/repository-insights` (previously /hub/insights)
 - `/workspaces/some-id/repository-insights/some-id`

![CleanShot 2024-02-12 at 18 24 20](https://github.com/open-sauced/app/assets/833231/da627b0e-1fd0-47af-a140-e23a16d716cc)

**Comment by nickytonline** [comment]
This isn't ready to be done yet @brandonroberts, but once personal workspaces are implemented care of @jpmcb, I might punt this to you if you have bandwidth.

**Comment by nickytonline** [comment]
Requires https://github.com/open-sauced/api/pull/558 to be merged.

**Comment by brandonroberts** [comment]
Yep, I'm good to take this one

**Comment by bdougie** [comment]
@brandonroberts this one is related. Whatever the route is to create an insight, we will need to make sure it redirects. 

https://github.com/open-sauced/app/issues/2599

**Comment by brandonroberts** [comment]
Resolved in the workspaces MVP
