### ISSUE TITLE
Feature: Support personal workspaces

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#2651]
As a user of the application, I want to have a personal workspace to house my contributor insights and contributor repository insights where the landing page is like the current insights hub.

- [x] #2652
- [x] #2653
- [x] #2654
- [x] #2655
- [x] https://github.com/open-sauced/api/issues/510
- [x] #2708

**Comment by bdougie** [comment]
@nickytonline and @isabensusan wanted to see if we can track private workspaces here too. 

As a user, I should have an option to switch my workspace to private (with paid upgrade).

![Screen Shot 2024-02-16 at 10 48 24 AM](https://github.com/open-sauced/app/assets/5713670/13086275-7d9e-43c1-91ab-0fff9f14f282)

**Comment by nickytonline** [comment]
After https://github.com/open-sauced/api/issues/575 is merged in workspaces that are public should just work. We should modify the settings page to only be in the tabs if you are an owner though and 404 on that page if someone is not the owner and the workspace is public. The API guards against this, but it'd be nice to just not allow non-owners to navigate to the settings page of a workspace.
