### ISSUE TITLE
Redirect existing lists to contributor insights

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/app#2655]
The only thing to note here is that all existing lists will be associated to a personal workspace once @jpmcb work is done. This should be fine for the redirect rule you have in place, but just wondering if there's a scenario post personal workspaces that you might not be on your personal workspace and someone hits the old link to get redirected to a route where the workspace ID isn't associated to the list.

I could be overthinking this. 😅

_Originally posted by @nickytonline in https://github.com/open-sauced/app/issues/2648#issuecomment-1943990051_

**Comment by nickytonline** [comment]
This is probably related iand needs to be removed n the middleware @brandonroberts.

```rypescript
  if (
    !pathsToMatch.some((matcher) => pathToRegexp(matcher).test(req.nextUrl.pathname)) ||
    // if the path is hub/insights or hub/lists go to the page so logged out users can see demo insights or demo lists
    req.nextUrl.pathname === "/hub/insights" ||
    req.nextUrl.pathname === "/hub/lists"
  ) {
    return res;
  }
```

**Comment by brandonroberts** [comment]
Ok cool
