### ISSUE TITLE
Bug: Tabs on user profile not working

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2656]
### Describe the bug

When you click any of the tabs on a user profile (your own or someone else's), nothing happens.

![image](https://github.com/open-sauced/app/assets/34313413/49daf0f3-8d19-4e86-beb0-27225c751ec8)

### Steps to reproduce

1. Go to https://app.opensauced.pizza/user/BekahHW
2. Click the contributions tab
3. See the error

![image](https://github.com/open-sauced/app/assets/34313413/48989f82-cd72-4a65-a765-9122023e3a5b)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
This is a regression. Not sure what's going on here. @brandonroberts, if you have some bandwidth, can you take a peek at this?
