### ISSUE TITLE
Feature: Add new topics for Android engineers

### ISSUE THREAD

**Issue by xgouchet** [open-sauced/app#2662]
### Type of feature

🍕 Feature

### Current behavior

The list of topics/interests if quite limited, and Android engineers won't have any of the existing topic be relevant

### Suggested solution

Add new topics to the list

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by xgouchet** [comment]
.take

**Comment by nickytonline** [comment]
The issue was been triaged, but it's available now @xgouchet!
