### ISSUE TITLE
Bug: workspace side to side scrolling overlaps side panel

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2669]
### Describe the bug

if you scroll side to side on a workspace page with the sidepanel, on smaller screens it scrolls too far.

https://github.com/open-sauced/app/assets/34313413/94cb81e8-9fe5-43ab-b3fb-ce1a953e1038

### Steps to reproduce

1. Go to your workspace.
2. scroll side to side 

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
This is probably related to the collapsible sidebar.

**Comment by nickytonline** [comment]
This was fixed by the sidebar work. Fixed by #2738

![CleanShot 2024-02-27 at 23 56 03](https://github.com/open-sauced/app/assets/833231/e4c87a7b-0540-48dc-a910-80d597e4dc30)
