### ISSUE TITLE
Fix: Remove workspaces feature flag

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#2677]
- [ ] #2703 
- [x] #2704 
- [x] #2711

The feature flag for workspaces needs to be removed from code:
- https://github.com/open-sauced/app/blob/beta/middleware.ts
	- any links to hub/insights should be removed in favour of a workspace URL

**Comment by nickytonline** [comment]
We'll also need to remove the feature flag for workspaces from Posthog, but only once we've deployed to production.

**Comment by isabensusan** [comment]
@nickytonline this can be closed now, right?
