### ISSUE TITLE
Bug: Sidebar does not stay collapsed when switched

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#2688]
![Rewatch GIF Recording - 2024-02-16 at 10 06 19 AM](https://github.com/open-sauced/app/assets/5713670/8cd7e143-1e86-443e-aedf-628fe3521630)

**Comment by nickytonline** [comment]
We can use the `useLocalStorage` hook so that this persists between pages. We already have the package in the repo.

See https://github.com/streamich/react-use/blob/master/docs/useLocalStorage.md
