### ISSUE TITLE
Feature: Add buttons for workspace repositories and contributors pages

### ISSUE THREAD

**Issue by zeucapua** [open-sauced/app#2690]
### Type of feature

🍕 Feature

### Current behavior

Currently, users have to go to the settings tab to add tracked repositories and contributors. There should be a button in each page that will redirect to the settings page so the user has a CTA to follow.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
Related: https://github.com/open-sauced/app/pull/2676#pullrequestreview-1885414241

**Comment by nickytonline** [comment]
I wonder if we need a settings tab at all then. Probably the edit button is enough. Thoughts @isabensusan @BekahHW?

**Comment by BekahHW** [comment]
Will settings allow you to add ppl to the workspace, give admin privileges, etc? If that's all going in the same place then I say we just need the edit button.

**Comment by zeucapua** [comment]
called out in workspace contributors page PR: https://github.com/open-sauced/app/pull/2676#pullrequestreview-1885414241

**Comment by zeucapua** [comment]
> Will settings allow you to add ppl to the workspace, give admin privileges, etc? If that's all going in the same place then I say we just need the edit button.

I'll roll this issue and #2668 in a PR then!

**Comment by nickytonline** [comment]
> Will settings allow you to add ppl to the workspace, give admin privileges, etc? If that's all going in the same place then I say we just need the edit button.

You will be able to invite people, and I haven't seen designs for it yet, but we'll definitely have something for giving people roles, like owner, viewer etc. cc: @isabensusan
