### ISSUE TITLE
Chore: Remove the feature flag for workspaces from Posthog

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#2704]
Remove the feature flag for workspaces from Posthog, **but only once we've deployed to production**.

_Originally posted by @nickytonline in https://github.com/open-sauced/app/issues/2677#issuecomment-1950243706_

**Comment by isabensusan** [comment]
Is this sth I can do from the PostHog UI?

**Comment by nickytonline** [comment]
Yep! Just remove the `workspaces` from the Feature Flag UI.

**Comment by isabensusan** [comment]
done -- disabled it, didn't completely delete it, so as to save it for reference the next time we release a big feature
