### ISSUE TITLE
Feature: Add paid upgrade banner and modal for large contributor and repository insights

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/app#2710]
### Type of feature

🍕 Feature

### Current behavior

We need a prompt for high usage accounts to upgrade. We can use this context clue as a banner for eligible insights.

![image](https://github.com/open-sauced/app/assets/42211/1c2ae2c7-e307-4cd6-851e-f80b740878dc)

And add some sort of modal to explain benefits of upgrading

![image](https://github.com/open-sauced/app/assets/42211/eae014bb-68ee-47d6-bbba-1b34d1b73fe4)

cc: @isabensusan 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by isabensusan** [comment]
Here's the design for this banner

⚠️ IMPORTANT:  we want to use the same modal for both repository and contributor insight pages that are over the limit, but changing the subtitle copy to communicate to the user the # of contributors/repositories they currently  have on the page vs the free account limit.

### For Repository Insight pages that are over the limit - [Figma link](https://www.figma.com/file/sqRXS7hw6E93QgRMCl3WYz/Workspaces?type=design&node-id=1330-55001&mode=design&t=PCaONLsn7GF27KcT-4): 

Subtitle copy: "Your Insight page has _150 repositories but the free Workspace only allows for 100 repositories tracked_. Don’t worry, your insights won’t be deleted, but if you want to continue using OpenSauced you should upgrade your Workspace to a PRO Workspace."
<img width="800" alt="image" src="https://github.com/open-sauced/app/assets/27322879/575d1799-a23e-4c5b-9f45-94c453cc48a4">

###  For Contributor Insight pages that are over the limit - [Figma link](https://www.figma.com/file/sqRXS7hw6E93QgRMCl3WYz/Workspaces?type=design&node-id=1330-55002&mode=design&t=PCaONLsn7GF27KcT-4):

Subtitle copy: "Your Insight page has _15 contributors  but the free Workspace only allows for 10 contributors tracked._ Don’t worry, your insights won’t be deleted, but if you want to continue using OpenSauced you should upgrade your Workspace to a PRO Workspace."
<img width="800" alt="image" src="https://github.com/open-sauced/app/assets/27322879/1bfd5aad-f3da-4bfa-8f92-9a96a4f780c8">

**Comment by isabensusan** [comment]
For the record -- upper limits for the pro accounts have been updated: 

I've recorded this change in this [Pricing doc ](https://docs.google.com/document/d/1VKf0lByZW2pRp7GL5zamsZ906d8RBfUtiW8m9vEsi3I/edit?usp=sharing)as well

<img width="376" alt="image" src="https://github.com/open-sauced/app/assets/27322879/0dae4b38-319f-4746-be4d-1433628c7d60">


So the copy on the modal should look like this:

<img width="1249" alt="image" src="https://github.com/open-sauced/app/assets/27322879/e5c0730d-e973-4dd9-9cd8-3ebc285e896d">
