### ISSUE TITLE
Feature: Present modal to users on first visit to workspaces feature

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/app#2724]
### Type of feature

🍕 Feature

### Current behavior

To notify users of the new workspaces feature, we want to display a modal on their first visit, talking about what the feature is, and a link to the docs.

### Suggested solution

Use localStorage to determine whether to show the modal again after the first visit

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
You can leverage the `useLocalStorage` hook for this.
