### ISSUE TITLE
Bug: Add Team Members not working on insight page

### ISSUE THREAD

**Issue by Astrodevil** [open-sauced/app#2736]
### Describe the bug

**Add Team Members** in Insight Page section throwing error after clicking the "Send Invite" while adding emails. No mails are being sent and no other options to add team members.

![image](https://github.com/open-sauced/app/assets/73425223/82fc123a-ed47-415b-959b-95fe885527bf)

### Steps to reproduce

- Go to Insights tab
- Click on the "Edit Insight Page" 
- Go to "Add Team Members" section under "Update Insight Page"
- Try entering email in "input field" and click "send invite" . It will show error popup in top right section of page.
    

### Browsers

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
Thanks @Astrodevil. We're making some updates to this page and should have this resolved soon.

**Comment by Astrodevil** [comment]
Looks like Icon is also not fetched when trying to fetch GitHub Organizations repo on insight page. Maybe there should be option to upload one.
