### ISSUE TITLE
Bug: Top navigation squished on mobile

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#2740]
Currently the top navigation gets squished on mobile.

@isabensusan suggest adding some of those links to the sidebar for mobile only.

https://files.slack.com/files-pri/T033MQB5Q0K-F06L7PPBKNY/image.png

**Comment by nickytonline** [comment]
From @isabensusan:

For reference -- here's a design for the sidebar on mobile
![image](https://github.com/open-sauced/app/assets/27322879/ea3f194a-7196-4f32-8687-6c7cdc1f99b6)

**Comment by jpmcb** [comment]
👏🏼 👏🏼 amazing!

**Comment by nickytonline** [comment]
This depends on #2758. I have a fix already, but let's get #2758 in first.
