### ISSUE TITLE
Bug: Can't add contributors from Insight to an existing List

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2742]
### Describe the bug

I created a list. I wanted to add an additional 59 contributors. I selected all of them and tried to add them to the existing list. I got the "Successfully added" message, but when I checked the list they weren't there. 

### Steps to reproduce

1. Go to an Insight Page and the Contributors Tab on the dashboard
2. Select Contributors
3. Try to add to an Existing list
4. Check the list.
5. See no new contributors

Uploading Screen Recording 2024-02-22 at 1.23.08 PM.mov…

<img width="360" alt="image" src="https://github.com/open-sauced/app/assets/34313413/b01f1782-b848-44a7-918b-415c963147e6">

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
Closing in favor of #2857
