### ISSUE TITLE
Bug: workspace repo contributors (pr search) not getting dynamic range

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#2743]
### Describe the bug

It looks like the `prs/search` is only getting the default range in the workspaces repos:

![Screenshot 2024-02-22 at 11 33 01 AM](https://github.com/open-sauced/app/assets/23109390/65c76601-19d9-4bfd-937d-6f3edbb0fcc2)

Notice that the range is 7 days but `prs/search` got called with 30 days which looks to be the default in the hook: 

https://github.com/open-sauced/app/blob/7e7c3be849b02c44987e293c4e9c0a4c26b9f534/lib/hooks/api/useRepositoryPullRequests.ts#L12

And is used to aggregate the contributors in the repo rows:

https://github.com/open-sauced/app/blob/7e7c3be849b02c44987e293c4e9c0a4c26b9f534/components/molecules/RepoRow/repo-row.tsx#L98

---

cc @BekahHW noticed this and investigated it initially as maybe an API bug. You'll notice in a workspace that the contributors do not change if you change the range.

### Steps to reproduce

1. Go to a workspace
2. Change from 7 days, to 30 days, to 90 days
3. Note that the contributors column in the repos table doesn't change

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
I can take a peek at this.
