### ISSUE TITLE
Feature: Links docs in support

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#2753]
### Type of feature

🍕 Feature

### Current behavior

Would love to have a link for docs in the support dropdown.

![Screen Shot 2024-02-23 at 10 02 37 AM](https://github.com/open-sauced/app/assets/5713670/0ef2c74b-377b-47cb-9c68-2944d64d25b1)

### Suggested solution

Link to the docs sites in the list.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
@BekahHW, what's the best link for our docs and @isabensusan, which icon would you like to use?

**Comment by BekahHW** [comment]
This is making link: https://docs.opensauced.pizza. I think that should be a good starting point. I'll add links on that page to the guides for contribs and maintainers.
