### ISSUE TITLE
Feature: Show sidebar everywhere in app

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#2780]
### Type of feature

🍕 Feature

### Current behavior

Sidebar shows up exclusively within the workspaces context.

### Suggested solution

Make the sidebar available in every other part of the platform as well, for easier access to workspaces and insights.

Namely:
- Highlights page
- Explore page
- User profiles

Excluding:
- User Settings
- Notifications

Design incoming for an empty state to show to non-logged in users

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
@zeucapua can we close this in favor of your other open issues?
