### ISSUE TITLE
Bug: `/feed` redirect breaks "Workspace" and other headers when logging in

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#2792]
### Describe the bug

When logging into prod, the top header is broken:

![sad-redirect](https://github.com/open-sauced/app/assets/23109390/e07f596a-4a40-4c5d-af9a-e462aacec71a)

This is fixed by removing the `?redirectedFrom=%2F` query param. You can see I do that in this second gif. This seems to fix the issue.

_But_, if you log out and log back in again, go to the feed, it returns to that same behavior.

### Steps to reproduce

1. Log out
2. Log in
3. Go to the feed / "Highlights"
4. Attempt to go to workspaces by clicking the top nav "Workspaces" header - unsuccessful: note the `?redirectedFrom=%2F` in the query

### Browsers

Confirmed this behavior on Firefox and Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
The issue appears to be related to a client-side redirect introduced in #2695. IT doesn't hapen in a local development environment, but it looks like the `useEffect` doesn't kick in properly in prod for some reason.

Based on this comment, https://github.com/open-sauced/app/pull/2695/files#r1492982293, it makes sense to make this a server-side redirect.
