### ISSUE TITLE
Bug: Upgrade to pro banner is displayed for pro account in Contributor Insights Page

### ISSUE THREAD

**Issue by adiati98** [open-sauced/app#2801]
### Describe the bug

Not sure if this is related to #2793 as the bug there is affecting users who are not logging in.

---

I have OpenSauced pro account and I found this bug while I logged in.

When I opened one of the page in the Contributor Insights, the banner of "Upgrade to a PRO Workspace" is displayed on the top. I notice, this bug is only affected the page that's been created by adding contributors manually through "Explore Contributor". 

**Additional info**:

- Another pages that have been created through "sync your GitHub team" and "importing GitHub following" are not affected.
- Repository Insights Pages are not affected. 

### Screenshots

![Screenshot 2024-02-28 111423](https://github.com/open-sauced/app/assets/45172775/127a1071-8bce-47bb-9996-a9836a94f5e9)

![Screenshot 2024-02-28 111439](https://github.com/open-sauced/app/assets/45172775/787b09ce-4d2f-42a3-9498-08600de55ffc)

### Steps to reproduce

1. Open the sidebar.
2. Click a page in "Contributor Insights" that's been created by adding contributors manually.
3. You will see the banner on top.

### Browsers

Chrome

### Additional context (Is this in dev or production?)

production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
Thanks for reporting this @ayu! We're looking into it.

**Comment by zeucapua** [comment]
Thank you for the issue! Is your account personally upgraded to PRO or the workspace? Because right now we are only checking if the workspace itself is upgraded. Am I missing something else? cc @nickytonline

**Comment by brandonroberts** [comment]
> Thank you for the issue! Is your account personally upgraded to PRO or the workspace? Because right now we are only checking if the workspace itself is upgraded. Am I missing something else? cc @nickytonline @brandonroberts

We have a set of previously upgraded accounts that have access to pro features. You can use the `hasReports` from the `useSession` hook to determine if they are a previously upgraded user for hiding the banner in addition to the workspace check.

**Comment by adiati98** [comment]
> Thank you for the issue! Is your account personally upgraded to PRO or the workspace? Because right now we are only checking if the workspace itself is upgraded. Am I missing something else? cc @nickytonline @brandonroberts

I think what @brandonroberts mentioned here.
I'm currently subscribed to the Pro plan as you can see on the screenshot in the issue.
