### ISSUE TITLE
Bug: Legacy Insights page links returning 404

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2807]
### Describe the bug

With the update to workspaces, the links I have for my old insights pages that I'm using in my blog posts are no longer working. 

### Steps to reproduce

 You can check these out:
 
 - https://app.opensauced.pizza/lists/bb61b5e0-eee3-4a3a-a648-bd035b5db3e7/activity
 - https://oss.fyi/oss-alts
 - https://app.opensauced.pizza/workspaces/64475ec2-cc13-4760-8a8c-5ca9995f2c62/repositories

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
Is the last link a public workspace?

**Comment by BekahHW** [comment]
@brandonroberts it should be a public repo insight page. I can't check for sure, bc it gives me the 404.

**Comment by BekahHW** [comment]
@brandonroberts the links were pulled from my blog posts. I'm trying to track down which ones I put in there.

**Comment by brandonroberts** [comment]
I found them in the URL shortener dashboard. Looking into the cause

**Comment by BekahHW** [comment]
@brandonroberts now the insight links that are in my blog posts are getting redirected to the feed.

**Comment by BekahHW** [comment]
@brandonroberts when I am logged in and click this link: [https://app.opensauced.pizza/pages/BekahHW/1189/contributors?range=30](https://app.opensauced.pizza/pages/BekahHW/1189/contributors?range=30) in my post, the url changes to this:

[https://app.opensauced.pizza/workspaces/b659d74f-bd38-4a00-a6e8-e7a9726a24c5/repositories](https://app.opensauced.pizza/workspaces/b659d74f-bd38-4a00-a6e8-e7a9726a24c5/repositories)

**Comment by brandonroberts** [comment]
I found the issue. Fix incoming
