### ISSUE TITLE
Bug: Repository insight did not add any of my repos

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#2814]
### Describe the bug

I just tried adding a bunch of terraform plugins to a repository list in my personal workspace and got a 500. When I refreshed I saw all the repos I added were not there and instead I created a list with the top starred repositories. 

Something failed, and it created an unexpected result. 

https://app.opensauced.pizza/workspaces/ddd68e1e-a326-41d8-9e7b-f31552d2d1c4/repository-insights/1241/dashboard

<img width="1691" alt="Screen Shot 2024-02-28 at 9 05 54 PM" src="https://github.com/open-sauced/app/assets/5713670/7de6f2fa-b1b7-494d-9296-2db12ac812d4">

### Steps to reproduce

1. Create an repository insight 
2. Sync the org terraform-google-modules
3. Sync a second org terraform-aws-modules
4. Add a repo cloudposse/terraform-yaml-stack-config
5. Hit save.

### Additional context (Is this in dev or production?)

I am going to test this again, but documented here first.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
Just created a second one in a workspace and it did not error. The first time I did add a lot more repos using the terraform plugin list using https://registry.terraform.io/.

https://app.opensauced.pizza/workspaces/1b814876-2007-4125-91bf-9792b93ee6d2/repository-insights/1242/dashboard

**Comment by bdougie** [comment]
I spoke too soon. I was able to get the 500 with these steps, which I think is unrelated to what repos or orgs are added, but if the 500 exceptions. 

1. Create a repository insight
2. Sync the HashiCorp org
3. Check if the 500 occurs.

<img width="1691" alt="Screen Shot 2024-02-28 at 9 10 47 PM" src="https://github.com/open-sauced/app/assets/5713670/9200b143-8702-4f84-bb0c-82e3ff5e022c">

https://app.opensauced.pizza/workspaces/e6b6f7bb-62bc-455b-86f0-a060e2fbdeea/repository-insights/1243/dashboard

I need update the insight so I can share with HashiCorp.

**Comment by bdougie** [comment]
Dang. I logged out cleared the cache and logged back in and its fine. It seems like an early adopter issue. I think I saw that come through on Slack as a solution and it worked. The 422 makes sense now. It didn't think I was suppose to view it, but everything is good. 

I will leave this issue open in case there is a discussion we should have around this.

**Comment by bdougie** [comment]
The repository insight I created had issues. It worked on the second try. 

https://app.opensauced.pizza/workspaces/e6b6f7bb-62bc-455b-86f0-a060e2fbdeea/repository-insights/1261/dashboard

**Comment by jpmcb** [comment]
Yeah, logging repo ID is a good idea, but there's a bigger problem:

The github Octokit search doesn't support finding repos by their ID, only by owner/name:

```ts
    try {
      octoResponse = await octokit.repos.get({
        owner,
        repo,
      });
```

https://github.com/open-sauced/api/blob/c3a48f0882eba00d68287294c424eafa4b6d6841/src/repo/repo.service.ts#L314-L318

So, when we are attempting to add a repo to a list by ID and it doesn't exist in our database, the API throws this error since it can't do anything with a repo ID: there's no way for it to create a stub repo based soley on the ID.

```ts
      // could not find repo being added to workspace in our database. Add it.
      if (repoId) {
        throw new BadRequestException("no repo by repo ID found: must provide repo owner/name to create stub user");
      } else if (repoOwner && repoName) {
        repo = await this.createStubRepo(repoOwner, repoName);
      }
```

https://github.com/open-sauced/api/blob/c3a48f0882eba00d68287294c424eafa4b6d6841/src/repo/repo.service.ts#L289-L294

We should refactor the App to use `owner/repo` in this case where it's pulling data from GitHub and attempting to send it to the API, otherwise the API will reject it - does that make sense @brandonroberts ?

**Comment by brandonroberts** [comment]
@jpmcb we can do that. We're already sending both the id and fullName as part of the data

https://github.com/open-sauced/app/blob/beta/components/organisms/InsightPage/InsightPage.tsx#L198

**Comment by jpmcb** [comment]
If we're sending both, we should fix this block to handle that:

```ts
      if (repoId) {
        throw new BadRequestException("no repo by repo ID found: must provide repo owner/name to create stub user");
      } 
```

Assigning myself and landing this in the API
