### ISSUE TITLE
Feature: Custom 500 error page

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#2819]
As a user of the OpenSauced application, I want to see a friendly general error page instead of a generic that isn't branded as it gives the impression the whole application is broken.

**Comment by isabensusan** [comment]
Replace with 404 page

404 --> 500
uh oh page not found --> add a dad joke, on you @nickytonline  
while you're here, you can check out some of our amazing contributors! --> keep the same


![Image](https://github.com/open-sauced/app/assets/27322879/49961741-fd84-4e75-b830-e747ddb61641)
