### ISSUE TITLE
fix: Remove Spam Reporting from Repo Insights

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2825]
Right now, the spam reporting isn't working as anticipated (ref: #2781). Let's remove it from the repository Insights. 

              We discussed this during our engineering meeting and will remove the spam metrics from repo insights for now and replace with a more relevant metric. Spam was only used more prominently during Hacktoberfest.

I would recommend opening a separate issue to remove it and closing this one.

_Originally posted by @brandonroberts in https://github.com/open-sauced/app/issues/2781#issuecomment-1971640654_

**Comment by brandonroberts** [comment]
Spam has been removed from repository insights
