### ISSUE TITLE
Bug: workspace `Explore Contributors` design issues

### ISSUE THREAD

**Issue by zeucapua** [open-sauced/app#2826]
### Describe the bug

When creating a new contributor insight with `Explore Contributors` option, the page has a lot of padding with a different background color and doubled the footer.
![Screenshot 2024-02-29 at 9 59 48 AM](https://github.com/open-sauced/app/assets/20603494/45201316-0912-4c29-b056-80ddc7d9a6ee)

### Steps to reproduce

1. Make a new Contributor Insight
2. Click the `Explore Contributors` option
3. See design issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by adiati98** [comment]
Hi @zeucapua,

I also experienced this when I want to create a new Contributor Insight page using the "+" on the sidebar.

Here are the steps to reproduce:

1. Go to workspace
2. Click "+" icon
3. Select "New Contributor Insight"
4. Scroll down until you see the footer. 

![Screenshot 2024-03-01 002645](https://github.com/open-sauced/app/assets/45172775/d237e905-0fba-4a71-bcb1-56f1e61bd0b8)

**Comment by nickytonline** [comment]
The same thing @brandonroberts did in #2805 can be done here.
