### ISSUE TITLE
Bug: Insights Show All link has a double border and double padding

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#2838]
The Show all link for an insight in the application sidebar has a double left border and double left padding.

![CleanShot 2024-03-01 at 10 19 48](https://github.com/open-sauced/app/assets/833231/1d0f25cc-ed96-40b2-96d9-d19cab8dc2c3)

**Comment by nickytonline** [comment]
This is what needs to be changed in

https://github.com/open-sauced/app/blob/b0127f21ca5e34e450be26a71c0739d2554ed077/components/shared/AppSidebar/InsightsPanel.tsx#L75

```diff
<Link
-  className="text-xs text-slate-500 pl-3 pt-2 border-l-2 hover:text-orange-600"
+  className="text-xs text-slate-500 pl-3 pt-2 hover:text-orange-600"
  title=""
  href={
    type === "list"
      ? `/workspaces/${workspaceId}/contributor-insights`
      : `/workspaces/${workspaceId}/repository-insights`
  }
>
  Show all
</Link>
```

**Comment by rishabkumar7** [comment]
Hi @nickytonline would love to work on this.

**Comment by rishabkumar7** [comment]
.take
