### ISSUE TITLE
Bug: workspace settings page 404s

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#2842]
### Describe the bug

Going to a workspace settings page 404s:

![Screenshot 2024-03-01 at 10 29 56 AM](https://github.com/open-sauced/app/assets/23109390/795fba1d-9cd8-415f-8123-80e4eaa2eabb)

This is on production and beta

### Steps to reproduce

1. Go to workspace
2. Go to settings page `/settings`
3. See 404 page

### Browsers

Chrome, Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
Hmmmm now I can't replicate it ... not sure what changed. Didn't clear my cookies, just reloaded.

**Comment by nickytonline** [comment]
I tried to reproduce this and was unable to as well.

**Comment by adiati98** [comment]
@jpmcb @nickytonline I was about to create a similar issue.

You can try this link: https://app.opensauced.pizza/workspaces/4cfd2448-e137-4e7e-8832-eb8d6100a3c0/repositories

**Comment by adiati98** [comment]
I opened #2844 just in case they're in a different case. Feel free to close it if it's a duplication. 😊

**Comment by nickytonline** [comment]
> I opened #2844 just in case they're in a different case. Feel free to close it if it's a duplication. 😊

I'm pretty sure that's a different issue. I commented on it.

**Comment by jpmcb** [comment]
This was when I was logged in. I'm no longer able to reproduce it so closing.

**Comment by jpmcb** [comment]
I think I realized what's happening:

```
    {
      "id": "4056684d-101a-424b-8ac3-74dbff461f89",
      "user_id": 23109390,
      "workspace_id": "1b814876-2007-4125-91bf-9792b93ee6d2",
      "created_at": "2024-02-14T19:47:16.188Z",
      "updated_at": "2024-02-14T19:47:16.188Z",
      "deleted_at": null,
      "role": "editor"
    },
```

I'm only an `editor` in the workspace I'm trying to modify. Which I think leads to some confusing UI/UX.

If I had an idea of what role/member status I had, that may be useful.

Probably related to: https://github.com/open-sauced/app/issues/2851
