### ISSUE TITLE
Bug: Workspace leads to 404 for logged out users

### ISSUE THREAD

**Issue by adiati98** [open-sauced/app#2844]
### Describe the bug

As per @nickytonline's explanation in a stream, workspaces are public by default. So, anyone who is not signed in to OpenSauced can look at it.

I opened a workspace link that was dropped yesterday on the stream without signing in. And it leads to 404.

### Screenshots

![Screenshot 2024-03-01 202034](https://github.com/open-sauced/app/assets/45172775/ab0eb50d-a7fc-4346-acff-a310912d3c10)

### Steps to reproduce

Without signing in:

1. Go to https://app.opensauced.pizza/workspaces/4cfd2448-e137-4e7e-8832-eb8d6100a3c0/repositories
2. You will see the 404 page.

### Browsers

Chrome

### Additional context (Is this in dev or production?)

production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
That one is a valid 404. We've updated the main page to be e.g. https://app.opensauced.pizza/workspaces/4cfd2448-e137-4e7e-8832-eb8d6100a3c0. That changed after the stream.

We won't bother updating it as we haven't done the official launch since this is still brand new or do you think it's worth putting a redirect @brandonroberts?

**Comment by nickytonline** [comment]
We can go ahead and close this unless we want to move forward with a redirect, but again, since this is super new, I don't think it's worth it, but I'll defer to the team.

**Comment by brandonroberts** [comment]
I don't think we need to add a redirect for this one

**Comment by nickytonline** [comment]
I'm going to go ahead and close this the.
