### ISSUE TITLE
Bug: Can't delete more than one contributor insight without a refresh

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#2849]
### Describe the bug

https://github.com/open-sauced/app/assets/5713670/0a0ab602-f621-46d7-a7aa-62cea57a3c81

I confirmed that this is not an issue for Repository Insights since and that only requires the word `DELETE`

## repository insight
![Screen Shot 2024-03-01 at 12 48 13 PM](https://github.com/open-sauced/app/assets/5713670/8e2c642b-0ba5-41c3-a850-09765d18ce77)

## contributor insight deletion
![Screen Shot 2024-03-01 at 12 48 34 PM](https://github.com/open-sauced/app/assets/5713670/14b829f8-7e41-49ae-a1b6-fca5f3d13d6e)

### Steps to reproduce

1. Delete a contributor insights
2. Try to delete a second one.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by arvindpndit** [comment]
.take

**Comment by nickytonline** [comment]
It's be good to standardize the deletion flow as well. Either the name of whatever is being deleted or the word DELETE. Typically what I've seen is the name of the thing to be deleted.
