### ISSUE TITLE
Feature: show who's the owner of an insight page in the UI

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#2851]
### Type of feature

🍕 Feature

### Current behavior

Workspaces are meant to be used by teams, and as team members create insight pages there's currently no way to know who created what insight page.

### Suggested solution

We should show in the UI who's the owner/creator of a particular Insight Page inside a workspace.

We could make use of some of the free real estate in the header component to indicate who the owner of an insight page is, using out avatars component
<img width="600" alt="image" src="https://github.com/open-sauced/app/assets/27322879/24cdab02-5b7c-4c8c-bab8-98729b797d02">

[Avatar Component ](https://design-insights.netlify.app/?path=/docs/design-system-atoms-avatar--docs) --> although I'd prefer it to be round

## Some examples:
Click up clearly states who's the owner of a document
<img width="400" alt="image" src="https://github.com/open-sauced/app/assets/27322879/b5a50611-67b5-4118-8759-2e62dbfdb63f">

Posthog shows owners on their dashboard table
<img width="400" alt="image" src="https://github.com/open-sauced/app/assets/27322879/f24cfd7e-a58e-4987-9136-1775ddfa099a">

cc @bdougie 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
Thanks for opening this @isabensusan. I do like the idea of showing owner & contributors on the page. Definitely helpful context.

**Comment by jpmcb** [comment]
Note: there many be many owners:

![Screenshot 2024-03-04 at 8 42 16 AM](https://github.com/open-sauced/app/assets/23109390/1efa88d6-d2cb-4e82-96c1-9deaac1f658a)

we'll probably want something that can work for many, many workspace owners.

**Comment by bdougie** [comment]
My thought is we can do something similar to the contributors in the repo list and share avatars some where near the header. Reuse exiting UI elements to display the first 5 people labeled as an owner and add `+x` for anyone else that may be listed as owner. 

![Image](https://github.com/open-sauced/app/assets/5713670/57cea87a-7d94-4106-99eb-f392f1741565)

side note: For another issue, but I think we should limit the amount owners to 1 for free and public workspaces.

**Comment by jpmcb** [comment]
A quick note:

we currently do not have membership / owner granularity for individual insight pages, only at the workspace level. So, the "owners" of an insight page will just be the owners of a workspace. I think this works for now, but we'll want to be mindful to refactor this if we introduce more auth granularity within individual insight pages.
