### ISSUE TITLE
Allow user to edit their repo page and change visibility

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2862]
- Currently, there's no way to edit a repo insight page  to change visibility. There should be an option for visibility and an option to upgrade their account

**Comment by jpmcb** [comment]
The repo and contributor insight pages being public/private has been hoisted up to the workspace level. So, if you make a workspace private via the Pro Workspace subscription, it'll make all the insight pages private.

We had talked about adding additional access granularity for individual pages but need validation on the whole workspaces product before moving forward with all that.
