### ISSUE TITLE
Feature: add option to add an icon to a button to distinguish them visually

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/app#2869]
For the sake of getting this merged before our meeting on Wednesday, LGTM. I do have concerns on how confusing these options look next to each other. I'd probably suggest exploring adding icons on the button to help distinguish they are different. 

We are getting to a point where the orange is also over used, and another option is using a different button color scheme. 

<img width="1044" alt="Screen Shot 2024-03-01 at 3 31 10 PM" src="https://github.com/open-sauced/app/assets/5713670/ae29e73c-ec5d-4db7-b537-6f039ee47218">

https://design-insights.netlify.app/?path=/docs/design-system-atoms-button--docs

_Originally posted by @bdougie in https://github.com/open-sauced/app/issues/2820#issuecomment-1974072502_

**Comment by FatumaA** [comment]
I agree, having an icon option will help enhance the overall design.

**Comment by nickytonline** [comment]
Seeing this in my feed is very timely. I'm currently writing some end to end tests and had some issues with a button with an icon.

@isabensusan, I think we can style the button with the existing variants and if an `icon` prop is added we can add the same JSX we typically use for an icon in a button, e.g. `<Icon IconImage={GitHubIcon} className="mr-2" />`

We can default the icon to the left which is where our icons typically are, but we can allow either, maybe via a prop `iconPosition` with the options `
start" | "end"`.

If at the end, we use `mr-2`, if at the beginning, we use `ml-2`.

```jsx
<Button
  variant="primary"
  className="z-1 items-center px-2.5 py-1"
  onClick={() => {
    signIn({ provider: "github", options: { redirectTo: `${host}${currentPath}` } });
  }}
>
  <Icon IconImage={GitHubIcon} className="mr-2" />
  Connect with GitHub
</Button>
```

Thoughts?

**Comment by brandonroberts** [comment]
I think this can be closed
