### ISSUE TITLE
Bug: 500s on my workspace

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#2885]
### Describe the bug

I am getting 500s on this demo workspace I created. I could use some assistance in learning how I can debug this in production.  

![image](https://github.com/open-sauced/app/assets/5713670/5a36ebe2-2586-4c21-aeb5-0d3cfb3fa3f7)

### Steps to reproduce

View this workspace. 

https://app.opensauced.pizza/workspaces/e6b6f7bb-62bc-455b-86f0-a060e2fbdeea

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
Related to: https://github.com/open-sauced/api/issues/627 - working on a fix now in https://github.com/open-sauced/api/pull/628 but validating this is the right approach

**Comment by jpmcb** [comment]
Should be fixed in prod now: https://github.com/open-sauced/api/pull/628
