### ISSUE TITLE
Bug: Cannot create a new list from a workspace

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#2886]
### Describe the bug

While exploring my repository insight, I wanted to add contributors to a list. When I select contributors and click "new user" it sends me to the workspace home. 

![Screen Shot 2024-03-06 at 8 29 35 AM](https://github.com/open-sauced/app/assets/5713670/40fb7875-597c-436d-abfe-9c064c499b35)

Adding them to an existing list works.

### Steps to reproduce

1. View a repository insight
2. Create a new list from contributors.  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
I was unable to unblock myself on this, but the issue persist. 

1. I need to create a list with 1 person in it.
2. This is wild, because I am presented an entirely new creation flow (just noting)
3. I then was able to proceed with adding the list of tigerbeetle contributors in the dropdown.

**Comment by FatumaA** [comment]
I was able to reproduce this
