### ISSUE TITLE
Feature: Add repository insight create button to the list.  

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#2887]
### Type of feature

🍕 Feature

### Current behavior

Labeling this with workspaces because this changed with that change. 

![Screen Shot 2024-03-06 at 8 14 40 AM](https://github.com/open-sauced/app/assets/5713670/0bd1b6cc-5762-4ec1-8767-0e906760290c)

The only option to add an insight is the `+` button for current users.

### Suggested solution

Can we add a button to this page?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by zeucapua** [comment]
Related to #2881
