### ISSUE TITLE
Bug: workspace Repository tab 404s

### ISSUE THREAD

**Issue by zeucapua** [open-sauced/app#2890]
### Describe the bug

Clicking the workspace tab for `Repository` leads to a 404
![image](https://github.com/open-sauced/app/assets/20603494/43cc5f45-f5b1-43f6-86d6-e117c31f9b36)

### Steps to reproduce

1. Go to a workspace
2. Click `Repository` tab
3. See 404

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
I just confirmed this is the case for me in production. 

<img width="1830" alt="Screen Shot 2024-03-06 at 3 14 08 PM" src="https://github.com/open-sauced/app/assets/5713670/d1b580ce-e643-4490-89b8-cbe4c0c08d4d">
