### ISSUE TITLE
Bug: links to insight pages take non-logged in users to highlight feed

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#2899]
### Describe the bug

Currently, if a user isn't logged in and clicks on a link to a public insight page or workspace, they are redirected to the main feed.

ref for core team: https://opensaucedworkspace.slack.com/archives/C035RQ8ANBW/p1709847745002639?thread_ts=1709847327.367359&cid=C035RQ8ANBW

### Steps to reproduce

1. Logout or use an incognito window
2. Click this link: https://app.opensauced.pizza/pages/BekahHW/1055/dashboard

Potential solution is to 404 for these pages for now.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
Hmm thought this was fixed in: https://github.com/open-sauced/app/issues/2773 - seeing the same thing. Maybe a routing regression?

**Comment by bdougie** [comment]
I moved this to planned for launch. We should also consider adding a test for this in the future.
