### ISSUE TITLE
Bug: Repository Insights are Replacing each other on creation

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#2919]
### Describe the bug

![Rewatch GIF Recording - 2024-03-11 at 10 26 16 PM](https://github.com/open-sauced/app/assets/5713670/b695b1eb-7898-4083-b777-6ba430aaf712)

### Steps to reproduce

1. Create a repository insight in a workspace
2. Note it is in the repository insight list
3. Create a Second repository insight in a workspace
4. Note that it replaces the First. 

### Additional context (Is this in dev or production?)

After some local debugging, I think it is most likely API related. I was able to confirm that this is persistent on beta. I haven't looked into the API just yet/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
Looks like this line is failing on beta currently when trying to create an insight @zeucapua 

https://github.com/open-sauced/app/blob/beta/components/organisms/InsightPage/InsightPage.tsx#L705

**Comment by jpmcb** [comment]
Doesn't seem to be API related: here's the same `PATCH /v2/workspaces/{id}/insights` I made with the same name and the same repo and they both appear.

![Screenshot 2024-03-12 at 7 34 32 AM](https://github.com/open-sauced/app/assets/23109390/329a6dcd-413b-41ff-a392-93e4ffe4084b)

**Comment by bdougie** [comment]
@brandonroberts I can confirm that this only happens when I sync an organization and not when I add repos manually.

**Comment by brandonroberts** [comment]
Confirmed on my end also

**Comment by brandonroberts** [comment]
Fixed in https://github.com/open-sauced/api/pull/642
