### ISSUE TITLE
Bug: Button that saves a repository to workspace floats to bottom of page

### ISSUE THREAD

**Issue by FatumaA** [open-sauced/app#2924]
### Describe the bug

The button floats to bottom of page when scrolling instead of staying close to the input with the lost of repositories to be added. 

As shown below:
![Screenshot 2024-03-12 at 13 35 31](https://github.com/open-sauced/app/assets/67555014/fc54ee88-441a-4017-8952-396b01dfd43e)

### Steps to reproduce

 1. Go to workspaces tab
 2. Click add a repository
 3. Follow prompts to add a repository
 4. Notice the "update workspace" button floats to the bottom of page when scrolling

### Browsers

Chrome

### Additional context (Is this in dev or production?)

localhost

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
Thanks for opening the issue @FatumaA - it doesn't look like your screenshot actually uploaded: can you try uploading it again?

**Comment by FatumaA** [comment]
> Thanks for opening the issue @FatumaA - it doesn't look like your screenshot actually uploaded: can you try uploading it again?

Hi John,
I updated the issue with the image

**Comment by isabensusan** [comment]
@FatumaA thanks for your input!

cc @nickytonline -- let's make this a fixed footer and fix the z-index
