### ISSUE TITLE
Bug: Some UI elements are shown when viewing a workspace while logged out

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/app#2929]
### Describe the bug

Some elements are displayed when logged out

- Add repositories
- Create new Insight

<img width="1264" alt="Screenshot 2024-03-12 at 10 54 31 AM" src="https://github.com/open-sauced/app/assets/42211/3175033a-3023-4f19-8558-061eedde1bfa">
<img width="1186" alt="Screenshot 2024-03-12 at 10 44 35 AM" src="https://github.com/open-sauced/app/assets/42211/8251a6df-5ba5-40c1-a371-9b72f9dbcaf4">

### Steps to reproduce

1. Visit https://app.opensauced.pizza/workspaces/b355ecef-76a5-4451-972a-281e16ccf2e4 in an incognito window
2. Note UI elements shown

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
related: https://github.com/open-sauced/app/issues/2812
