### ISSUE TITLE
Feature: Allow pasting full repository URLs as tracked repositories

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#2930]
As a user of workspaces, I want to be able to paste in a list of repository URLs so that I can track them in my workspace.

**Comment by nickytonline** [comment]
We should allow for full URLs for repos like, https://github.com/open-sauced/app but when sent to the API, it should be sent as `open-sauced/app`

**Comment by jpmcb** [comment]
> We should allow for full URLs for repos like, https://github.com/open-sauced/app but when sent to the API, it should be sent as open-sauced/app

+1 - I'd prefer if the API didn't have to do too much parsing of input from bespoke clients. If the client could do its own validation that would be 👨🏼‍🍳 👌🏼
