### ISSUE TITLE
Bug: Workspace dashboard stats show 0 on dev environment

### ISSUE THREAD

**Issue by OgDev-01** [open-sauced/app#2946]
### Describe the bug

![Screenshot 2024-03-14 at 07 10 47](https://github.com/open-sauced/app/assets/62995161/b4f26f83-559b-4f36-88b5-1f040e16f822)

### Steps to reproduce

1. Add a repository to your workspace on dev(localhost:3000)
2. Check to see that the stats are all 0

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by BekahHW** [comment]
I believe this has been fixed with API updates. Closing for now.
