### ISSUE TITLE
Bug: broken sync GitHub team on contributor insight creation

### ISSUE THREAD

**Issue by zeucapua** [open-sauced/app#2955]
### Describe the bug

Trying to add contributors by syncing GitHub teams results in an error

On Beta:
https://github.com/open-sauced/app/assets/20603494/dacc131f-f201-42b0-ae01-36c8fc235c57

### Steps to reproduce

1. Create a new contributor insight
2. Enter a name
3. Choose an organization
4. See error and no options for teams

### Additional context (Is this in dev or production?)

beta

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
Is the error telling you to logout and log back in? This is an ongoing issue with the GitHub providerToken not being refreshed in the Supbase auth

**Comment by nickytonline** [comment]
We no longer have the GH team sync in the project, so it's going to be redone in #2983.
