### ISSUE TITLE
Bug: highlight dialog, when opened in a new tab doesn't close 

### ISSUE THREAD

**Issue by monacodelisa** [open-sauced/app#2959]
### Describe the bug

The highlights dialog doesn't close on clicking the close button
when opened in a new tab from notifications, doesn't close on clicking the background either
(while if opened directly from the notifications page both options for closing work fine)

just stumbled upon this a moment ago when opening multiple notifications in new tabs

### Steps to reproduce

1. go to notifications
2. after the list of notifications loads, right click on a notification
3. select `open in a new tab`
4. navigate to the new tab and try to close the dialog

### Browsers

Chrome

### Additional context (Is this in dev or production?)

prod

![screencapture-gif](https://github.com/monacodelisa/gifs/blob/main/open-sauced-popup.gif?raw=true)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by takanome-dev** [comment]
Well spotted!

I have no idea why it's not working 😅 @nickytonline any ideas?

**Comment by monacodelisa** [comment]
@takanome-dev ty, I have not explored it in the code but it seems like a redirect is missing, just to navigate the user back to notifications, like it would happen if it was not opened in a new tab, I would like to work on it, if it goes to the next stage

**Comment by nickytonline** [comment]
I actually want to revisit the individual highlight viewing flow. It makes more sense to have it on it's own page because we are loading the entire highlights page just to show it. This causes it to load very slowly sometimes.

At @isabensusan @zeucapua, thoughts?

**Comment by isabensusan** [comment]
yeah I'd be fine with making it a new page! 

Twitter does this as well:
<img width="1307" alt="image" src="https://github.com/open-sauced/app/assets/27322879/da180ef8-0ddd-4e79-8411-2f44e0df4b29">

It could even be a good opportunity to get some extra screen real state to add more context on who the poster is.

**Comment by nickytonline** [comment]
I'm going to go ahead and close this in favour of a dedicated page for individual highlights.
