### ISSUE TITLE
Bug: cannot create contributor insight

### ISSUE THREAD

**Issue by takanome-dev** [open-sauced/app#2960]
### Describe the bug

https://github.com/open-sauced/app/assets/79809121/62e50fd9-06a4-4153-bc6c-add979485076

### Steps to reproduce

1. Go to [app.opensauced.pizza](https://app.opensauced.pizza/workspaces/)
2. Expand the sidebar and click `contributor insight`
3. Add some contributors and try creating a the page

### Browsers

Chrome

### Additional context (Is this in dev or production?)

Might be related to https://github.com/open-sauced/app/issues/2886

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
We updated the UI in a recent release @takanome-dev, can you try again and report back if this works for you.

<img width="1037" alt="Screen Shot 2024-03-27 at 3 29 52 PM" src="https://github.com/open-sauced/app/assets/5713670/9dd00b97-8b9d-431b-981c-ffe942f40d31">

**Comment by takanome-dev** [comment]
> We updated the UI in a recent release @takanome-dev, can you try again and report back if this works for you.
> 

@bdougie  I'm still getting `401 unauthorized` 🤔 Maybe my user's role is less than how much is required to be able to do the action or/and this is only for paid members (i recall receiving an email stating that all features are free for now...)

**Comment by bdougie** [comment]
Log out and log back in. Also confirm if you are still blocked when clearing the cache.
Cc @open-sauced/engineering

**Comment by takanome-dev** [comment]
> Log out and log back in. Also confirm if you are still blocked when clearing the cache. Cc @open-sauced/engineering

tried it on a new browser and it works 🥳 Maybe it was due to the cache. Thanks 👍
