### ISSUE TITLE
Bug: Auto-summarizing does not work

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#2965]
### Describe the bug

![Screen Shot 2024-03-18 at 10 48 54 AM](https://github.com/open-sauced/app/assets/5713670/7a96ce5f-6ec0-4acd-a5e9-cfcf203fdf17)

@open-sauced/triage can you confirm if this feature is broken for you. 

related #2657

### Steps to reproduce

1. Go to https://highligts.new
2. Add a github pr link
3. Click the auto-summarize button.
4. Confirm if it summarized.

### Additional context (Is this in dev or production?)

![Screen Shot 2024-03-18 at 10 56 40 AM](https://github.com/open-sauced/app/assets/5713670/196bfec6-d0c6-4061-a642-e6520ede14a3)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
This is something I have noticed too @bdougie

**Comment by takanome-dev** [comment]
Worked for me 🤔 


https://github.com/open-sauced/app/assets/79809121/825d97c2-7d37-4ec2-8c9d-ad50bcf3f87a

**Comment by nickytonline** [comment]
Can you both share your network panel outputs? I'm pretty sure we have an issue for this already where it gives a 401 @jpmcb?

**Comment by FatumaA** [comment]
works for PRs, errors for issues

the error as below:

![Screenshot 2024-03-18 at 21 39 34](https://github.com/open-sauced/app/assets/67555014/e644f439-b690-4d39-b093-2ec12d311fb0)

the console: 

![Screenshot 2024-03-18 at 21 39 51](https://github.com/open-sauced/app/assets/67555014/213842ee-b652-42c8-b7e7-e1edaa1e1227)

**Comment by nickytonline** [comment]
So there's the 401 error and as a result, no comments array.

**Comment by takanome-dev** [comment]
Disconnected and reconnected + clear cache


https://github.com/open-sauced/app/assets/79809121/4db11a32-0bf8-42eb-9e3c-68ee0ed8eead

**Comment by nickytonline** [comment]
If it happens again, we can catch the 401 potentially and ask the user to log back in. Any idea why someone might have to log back in @brandonroberts? We busted the cache recently in a release, so not sure what else it might be.

**Comment by bdougie** [comment]
> Disconnected and reconnected + clear cache

I can confirm that this is fixed for me when clearing the cache.

**Comment by jpmcb** [comment]
Here's the old issue where we identified this was a 401 issue: https://github.com/open-sauced/app/issues/1440 (and associated issues were we identified something similar)

But looks like it was closed as complete in January.

Works ok for me:

<img width="1509" alt="Screenshot 2024-03-18 at 7 32 52 PM" src="https://github.com/open-sauced/app/assets/23109390/f6d7dd0e-e279-43cb-aaf2-c66cbb9f8827">

**Comment by bdougie** [comment]
> Here's the old issue where we identified this was a 401 issue: #1440 (and associated issues were we identified something similar)
> 
> But looks like it was closed as complete in January.

Interesting. I think passing an error message via the API would clear these types of errors quicker in the future. It seems like there are a few ways this feature fails, but we are guessing every time.

1. Credits are unavailable (OpenSauced needs to pay)
2. No comments in issues
3. Auth token (this is fixed).

**Comment by nickytonline** [comment]
For credits unavailable, we could give a friendly message that the service is unavailable and log to Sentry the actual error to notify us to add credits, and for no comments we can use the Elvis operator, i.e. nullish coalescing so the array map doesn't throw.

Also, can we get notifications about low credits?

**Comment by brandonroberts** [comment]
> If it happens again, we can catch the 401 potentially and ask the user to logout and log back in, but we need to mention why. Any idea why someone might have to log back in @brandonroberts? We busted the cache recently in a release, so not sure what else it might be.

Not sure why you would need to logout and login for this as its using authentication through our API. The other issues we've had are because the GitHub session doesn't get refreshed without logging out/back in.

**Comment by jpmcb** [comment]
> Interesting. I think passing an error message via the API would clear these types of errors quicker in the future.

...

> For credits unavailable, we could give a friendly message that the service is unavailable and log to Sentry the actual error to notify us to add credits

I actually disagree: the API for many backend/back-office operations (like OpenAI credits running out) should _not_ be surfaced to clients. Otherwise, we reveal bits and pieces of the state of our infrastructure, generally increasing the attack surface area of the entire stack by threat actors.

This, in my opinion, is actually a observability and logging problem: we don't currently consume logs from the API in a way that can trigger alerts to our engineering team. While we do have this setup on Sentry, as Nick pointed out, this would be the wrong place to surface a back-office problem: instead of errors of this nature being surfaced to clients, we would want to invest in logging infrastructure and alerting mechanisms in order for our internal team to become aware of these issues (i.e., Grafana Loki consumes logs and Grafana Alerts triggers a configured alert based on a `FATAL` type log).

**Comment by bdougie** [comment]
> we would want to invest in logging infrastructure and alerting mechanisms in order for our internal team to become aware of these issues (i.e., Grafana Loki consumes logs and Grafana Alerts triggers a configured alert based on a FATAL type log).

@jpmcb I am not sure if there is a log tracking issue or if this should go into the log repo. But could we link it there and then close this. I think adding more observability to this is the move, but not a priority for now.

**Comment by jpmcb** [comment]
@bdougie yes, I have https://github.com/open-sauced/api/issues/693 which will be a good lift: our current deployment using Digital Ocean Apps doesn't have great support for log sinks that aren't DataDog or PaperTail.

We can continue to track this in that issue.
