### ISSUE TITLE
Feature: Replace click-outside-modal interaction with close icon 

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#2967]
### Type of feature

🍕 Feature

### Current behavior

<stub>

### Suggested solution

<img width="1192" alt="image" src="https://github.com/open-sauced/app/assets/27322879/bbbf019b-7b69-4143-a374-6d01ea025911">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
Thanks for mentioning this pain point when you gave workspaces a go @KevinVandy. This should be fixed in our current sprint.
