### ISSUE TITLE
Feature: Add share button to own user profile

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#2991]
### Type of feature

🍕 Feature

### Current behavior

If I visit my own user profile page, there's no option to share my profile

<img width="1512" alt="image" src="https://github.com/open-sauced/app/assets/27322879/bca02b2b-34bf-41db-bf21-5421b727f78f">

### Suggested solution

Add a CTA to the header to "Share Profile".

<img width="1132" alt="image" src="https://github.com/open-sauced/app/assets/27322879/dba7e5ac-6ebf-4c68-86a4-dcd9e0ab4206">

&nbsp;

### Expected Functionality
When the user clicks on the share button, the user profile's shortened URL should be copied to the clipboard, and we should display a toast informing the user that it's been copied to the clipboard as well.

⚠️  The url should be shortened (replicate the work done in PR #2990 )

We basically want to replicate the "Share" interacion that already exists in other user profiles

&nbsp;

![Rewatch GIF Recording - 2024-03-20 at 7 58 26 PM](https://github.com/open-sauced/app/assets/27322879/f3c7176b-be6f-4740-ab39-ce238a794ed0)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by FatumaA** [comment]
I can validate this but before removing the triage label I have a question: 
Are we going with the button design in the images above or does this need design?
