### ISSUE TITLE
Feature: Un-fix top-nav on mobile

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#2995]
### Type of feature

🎨 Style

### Current behavior

The top navbar is currently fixed to the top on mobile.
![Rewatch GIF Recording - 2024-03-21 at 12 00 02 PM](https://github.com/open-sauced/app/assets/27322879/15bfb373-5c68-4f32-b5b4-57b3560603fb)

### Suggested solution

We should make the top navbar scroll with the rest of the page instead of keeping it fixed.

Why?
- it's taking up a lot of unnecessary vertical space, which on mobile is very limited
- none of our pages have a height high enough that scrolling back to the top would be tiresome (not even when showing the max amount of rows on the table, or having them all be expanded)
- most navigation can be done through the sidebar anyways, and the lapel would still remain fixed and visible

⚠️ **Note: We want this change to only apply to mobile screens, so screens smaller than the `sm` breakpoint** ⚠️

### Intended result
![Rewatch GIF Recording - 2024-03-21 at 12 06 17 PM](https://github.com/open-sauced/app/assets/27322879/d2845282-aba8-4f9e-ba3e-405b26d45acd)

<img width="734" alt="image" src="https://github.com/open-sauced/app/assets/27322879/f680cf34-25ba-4c64-ae49-00e532cad9c6">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
Just wondering if from a UX perspective if users would mind their settings/avatar disappearing on scroll.

**Comment by arvindpndit** [comment]
.take
