### ISSUE TITLE
Feature: update 100 days of OSS banner

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#3018]
### Type of feature

🍕 Feature

### Current behavior

N/A

### Suggested solution

Update the Banner on the "Highlights" page to include information on Workspaces.

Title: **Track your project with Workspaces!**
Content: **Setup your Workspace to get you and your team access to information about PRs, Issues and contributors for all your repositories.**

Image:
![image](https://github.com/open-sauced/app/assets/27322879/e800af72-7d85-4c53-bee6-7c3052bffcb5)

<img width="292" alt="image" src="https://github.com/open-sauced/app/assets/27322879/6af42506-1c51-45dd-b1b2-0cd6cb802dc1">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
Look at what @brandonroberts did for the new workspace CTA that redirects you to log in if you aren't logged in.
