### ISSUE TITLE
Feature: Allow celebration of Releases as Highlights

### ISSUE THREAD

**Issue by Idrinth** [open-sauced/app#3022]
### Type of feature

🍕 Feature

### Current behavior

Highlights don't support releases

### Suggested solution

It would be nice to be able to celebrate a release as a highlight. It would be great if the contributors could be mentioned there - maybe that information could be retrieved from github?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
I'd love to see up add this ability. Part of the reason for highlights was trying to mirror a feature GitHub never shipped internally where you could customize your release note announcements. 

This would be great to test out with OpenSauced releases.

**Comment by brandonroberts** [comment]
Closed by https://github.com/open-sauced/app/pull/3705
