### ISSUE TITLE
Feature: Add share button to workspace

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/app#3024]
### Type of feature

🍕 Feature

### Current behavior

We currently don't have a way to share workspaces with the URL shortener. 

<img width="1391" alt="image" src="https://github.com/open-sauced/app/assets/42211/b24050ba-e749-4f51-8a41-15b12d0742dc">

### Suggested solution

Add a button to make sharing workspaces easier

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by zeucapua** [comment]
What is the link shortener it should share?

**Comment by brandonroberts** [comment]
It will use our new oss.fyi URL shortener added here https://github.com/open-sauced/app/pull/2990

There's a util here that we we use with the Share buttons https://github.com/open-sauced/app/blob/beta/lib/utils/copy-to-clipboard.ts

**Comment by brandonroberts** [comment]
There's also an example here of how we use it with contributor insights 

https://github.com/open-sauced/app/blob/beta/components/ListHeader/list-header.tsx#L77
