### ISSUE TITLE
Bug: "Contributors" tab link throws a 404 error

### ISSUE THREAD

**Issue by JoeKarow** [open-sauced/app#3027]
### Describe the bug

From the [Explore](https://app.opensauced.pizza/explore/topic/typescript/dashboard/filter/recent) page, clicking on the "Contributors" tab redirects to a 404 page not found.

### Steps to reproduce

From the [Explore](https://app.opensauced.pizza/explore/topic/typescript/dashboard/filter/recent) page, click on the "Contributors" tab. (see screenshot)

### Do you have any images or screen captures?

![image](https://github.com/open-sauced/app/assets/58997957/65be24f6-f644-4f6b-ac73-261e6b004b8e)

### Browsers

Chrome, Other (add additional context)

### Additional context (Is this in dev or production?)

Arc (chrome variant)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by JoeKarow** [comment]
I also just noticed that clicking on the "Activity" tab will also throw a 404 error.

**Comment by nickytonline** [comment]
The contributors and activity tab URL need to be prefixed with `/explore/topic/`.

**Comment by nickytonline** [comment]
I'll add some tests for this as well.
