### ISSUE TITLE
Bug: Cannot add an insight page name in create contributor insight

### ISSUE THREAD

**Issue by FatumaA** [open-sauced/app#3043]
### Describe the bug

The input for adding an insight name inorder to create the insight page does not work. 
This blocks the creation of the insight page. 

This issue is similar to #2960 but not the same.

I'd like to fix this once triaged :)

### Steps to reproduce

1. Open the workspace sidebar from the workspaces page
2. Click on create a contributor insight
3. Try naming your contributor insight
4. Notice that it does not accept any input

### Do you have any images or screen captures?

https://github.com/open-sauced/app/assets/67555014/357cf6d4-af36-4d77-a407-e9f0840b3cd1

### Browsers

Chrome

### Additional context (Is this in dev or production?)

localhost

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
I can reproduce this on prod:

![contrib-insight-no-name](https://github.com/open-sauced/app/assets/23109390/541c46b0-5ed0-43b8-be3b-99165d3706e6)

Worse yet, it seems that just the contib insight name doesn't work at all blocking creating contirb insights completely. In my gif ^ you can see me mashing the keyboard to try to enter _anything_.

**Comment by FatumaA** [comment]
Can I do the fix, i had the PR ready

**Comment by brandonroberts** [comment]
Fix is ready for review https://github.com/open-sauced/app/pull/3044

**Comment by bdougie** [comment]
Also noticed this for more inputs like this one.
<img width="540" alt="Screen Shot 2024-03-27 at 8 54 49 AM" src="https://github.com/open-sauced/app/assets/5713670/a21e4d35-dac1-4841-8ef7-1f3b52b6aba1">

**Comment by FatumaA** [comment]
> Also noticed this for more inputs like this one. <img alt="Screen Shot 2024-03-27 at 8 54 49 AM" width="540" src="https://private-user-images.githubusercontent.com/5713670/317344082-a21e4d35-dac1-4841-8ef7-1f3b52b6aba1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NTczNzgsIm5iZiI6MTcxMTU1NzA3OCwicGF0aCI6Ii81NzEzNjcwLzMxNzM0NDA4Mi1hMjFlNGQzNS1kYWMxLTQ4NDEtOGVmNy0xZjNiNTJiNmFiYTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjdUMTYzMTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjZkMDZhODA4NjFkMDZiODA2ZjY2ZGU4NjkxNWZjMmRhNDViMmUwMmVlNTBkZmU5OGRhOTI5NTViYzczMWRkYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YKbCaxgzXi4m9YA2Oy7vIol_6iY_8UJy3QpBrgoEbZI">

The inputs might need a closer look 🤔
