### ISSUE TITLE
Bug: Can't create a new workspace (400 bad request)

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#3047]
### Describe the bug

When attempting to create a new workspace (since the last release), I am unable to due to a bad request. cannot

### Steps to reproduce

1. Create a workspace
2. Click save
3. See error

### Do you have any images or screen captures?

![Rewatch GIF Recording - 2024-03-27 at 1 09 14 PM](https://github.com/open-sauced/app/assets/5713670/834258a3-8286-4aa6-ad8c-bc951f4b2a13)

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
This was related to a config misalignment in the production API: fixed via a new API deployment with the right configuration.
