### ISSUE TITLE
Bug: I can't edit and change the name of my Contributor Inisght

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#3049]
### Describe the bug

![Screen Shot 2024-03-27 at 10 42 20 PM](https://github.com/open-sauced/app/assets/5713670/73708781-24fb-4a2c-b5f8-b7b0c0e221ff)

https://app.opensauced.pizza/workspaces/b14f0da8-1c04-4066-a320-a05d30208da1/contributor-insights/ce9713e0-0d3b-4fab-bcbf-9340ee0575b8/

### Steps to reproduce

1. Click edit any contributor insight
2. Change the name
3. Hit update
4. Note the error.

### Do you have any images or screen captures?

![Screen Shot 2024-03-27 at 10 43 37 PM](https://github.com/open-sauced/app/assets/5713670/095b6ec3-5f93-4df3-97b0-b5565f6a5353)

### Additional context (Is this in dev or production?)

I notice that the Repository insights work, but it also has the old UI on page (hasn't been updated).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by FatumaA** [comment]
Gathering more context here, there is a checkbox failing but it is not there in the UI only in the `UpdateListPayload` interface. 
Was this meant to be a hidden field or is it a remnant of an old design? 
At the moment, this is the code snippet that is failing:

```
onSubmit={async (event) => {
            event.preventDefault();
            // FormData was being funky because of the way our ToggleSwitch works
            // so went this way instead.
            const form = event.target as HTMLFormElement;
            const listUpdates = {
              name: form["list_name"].value,
              is_public: form["is_public"].checked,
              contributors: [],
            } satisfies UpdateListPayload;

            const { data, error } = await updateList(listUpdates);

            if (!error) {
              toast({ description: "List updated successfully!", variant: "success" });
              router.push(`/workspaces/${workspaceId}/contributor-insights/${list.id}/overview`);
            } else {
              toast({ description: "Error updating list. Please try again", variant: "danger" });
            }
          }}
```
Changing `is_public` to true/false works

**Comment by nickytonline** [comment]
Thanks for digging in @FatumaA!

The old lists page had a toggle switch for making a contributor insight public or private.

```jsx
<ToggleSwitch
  ariaLabelledBy="make-public-explainer"
  name="is_public"
  checked={isPublic}
  handleToggle={() => setIsPublic((isPublic: boolean) => !isPublic)}
/>
```

https://github.com/open-sauced/app/blob/beta/pages/lists/%5BlistId%5D/edit.tsx#L314-L319

That component is not on the new page. In terms of visibility of a contributor insight, how are we handling this now @brandonroberts? Is it public always or private only if they make their workspace private?

**Comment by brandonroberts** [comment]
@nickytonline for sending to the API, it should just be set to public as we're handling this at the workspace level now.

**Comment by nickytonline** [comment]
@FatumaA, if you have time to fix this, let me know, if not I'll tackle it as we need it to go out in a release today.

The change is this.

```typescript
            const listUpdates = {
              name: form["list_name"].value,
-              is_public: form["is_public"].checked,
+              is_public: true, 
              contributors: [],
            } satisfies UpdateListPayload;
```

**Comment by FatumaA** [comment]
> @FatumaA, if you have time to fix this, let me know, if not I'll tackle it as we need it to go out in a release today.
> 
> The change is this.
> 
> ```diff
>             const listUpdates = {
>               name: form["list_name"].value,
> -              is_public: form["is_public"].checked,
> +              is_public: true, 
>               contributors: [],
>             } satisfies UpdateListPayload;
> ```

Sending it in now
