### ISSUE TITLE
Feature: 404 page never knows I am logged in or not

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#3064]
### Type of feature

🍕 Feature

### Current behavior

When visiting the 404 page while logged in, it should not have a "Sign Up" button.

<img width="1840" alt="Screen Shot 2024-03-29 at 8 30 07 AM" src="https://github.com/open-sauced/app/assets/5713670/6e2b8054-b6f3-4e67-b8b0-929e9eddc860">

### Suggested solution

1. Visit /404 
2. Check if user exists in the session, and do not show the button if they exist. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
I think we can remove the sign in button. It always seemed odd to me on the 404 page. And when they click on the link to take them back home, the logging button is in the top navigation.
