### ISSUE TITLE
Bug: The recommendation card in the user profile redirects to the 404 page

### ISSUE THREAD

**Issue by lmscunha** [open-sauced/app#3070]
### Describe the bug

Clicking on a recommendation card on the user profile page opens a new tab, redirecting the user to the page-not-found (404).
The redirected link is as follows:
`https://app.opensauced.pizza/repo_name/dashboard/filter/recent`

### Steps to reproduce

1. Go to the recommendation tag in the user profile;
2. Click on one of the recommendations cards;
3. It redirects to the 404 page.

### Do you have any images or screen captures?

https://github.com/open-sauced/app/assets/65237061/994cef61-bbfe-4713-8ed4-512556448c5b

### Browsers

Other (add additional context)

### Additional context (Is this in dev or production?)

production - Brave

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
Thanks for opening this is work that is in progress #3040. 

Just a heads a @zeucapua we will want to link to repo pages here in the future.

**Comment by bdougie** [comment]
Opened a PR now that the feature flag is removed for repo pages.
