### ISSUE TITLE
Bug: Share button on workspaces dashboard doesn't work on iOS Safari

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#3072]
I was looking to share a workspace on mobile, pressed the share button and the URL did not get copied. Instead it gave an error in the console.

![image](https://github.com/open-sauced/app/assets/833231/6245b7f8-3244-4ae3-98ae-d69e76a97534)

I'm in mobile atm, but I'm assuming this means no share buttons with on iOS Safari and maybe other browsers on iOS s they're all WebKit under the hood.

**Comment by nickytonline** [comment]
It would also be helpful to provide feedback that the link was copied once this is fixed.

**Comment by brandonroberts** [comment]
Tried in Safari on Desktop and got a permission denied error for using the clipboard
