### ISSUE TITLE
Bug: The flippening 2: The return of flipper 🐬 - Repo pages "Stars per day" data flips when tabbing away

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#3073]
### Describe the bug

The "Stars per day" chart data flips when tabbing away. It flips from showing the _first_ day to the right to the _last_ day to the right:

![the-flippening](https://github.com/open-sauced/app/assets/23109390/f4e8e851-f41a-4af3-965d-cf08f52a037c)

Note how it shows March 1st on the right when it flips. And then when it goes back, it shows April 1st on the right (which should be the right Y axis value for time growing to the right).

Related:
- https://github.com/open-sauced/app/pull/3063#pullrequestreview-1972051474
- https://github.com/open-sauced/app/pull/3063#issuecomment-2030668053

### Steps to reproduce

1. Go to https://app.opensauced.pizza/s/kubernetes/kubernetes
2. Click to different tab
3. Click back
4. Notice chart flip

### Browsers

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
I realized that this sometimes happens on the first opening of the page. For example, here's what I saw when I first opened a tab and went to https://beta.app.opensauced.pizza/s/containerd/containerd:

<img width="1508" alt="Screenshot 2024-04-02 at 8 59 53 AM" src="https://github.com/open-sauced/app/assets/23109390/9354b68e-daf3-4407-8e60-f88c6185f4db">

once I go to a different tab, it flips back to the correct "up and to the right" view

**Comment by isabensusan** [comment]
adding for reference: the cumulative stars chart (big line chart at the bottom) is also broken and flipping
 
![Rewatch GIF Recording - 2024-04-02 at 12 32 00 PM](https://github.com/open-sauced/app/assets/27322879/de9244b2-82bf-4258-b55a-45c6c76639dd)

**Comment by jpmcb** [comment]
I still see this consistently happening on beta with Firefox:

![the-flippening-3](https://github.com/open-sauced/app/assets/23109390/5193c7e6-46cb-42be-8f52-6f49ad619ca3)

Can't really get it to reproduce on Chrome ... but sometimes in Chrome, it starts in the wrong position and doesn't flip back:

![Screenshot 2024-04-04 at 11 00 28 AM](https://github.com/open-sauced/app/assets/23109390/015e3144-3b75-4b03-abfd-cdce0a0502ab)

Re-opening since this still seems to be a consistent problem

**Comment by nickytonline** [comment]
<img src="https://media4.giphy.com/media/IqcsXOImaOy8U/giphy.gif"/>

**Comment by nickytonline** [comment]
I'm having trouble replicating this locally with a production build, i.e. no strict mode double render.
