### ISSUE TITLE
Bug: paginate workspace repos

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#3074]
This is a followup to:

- https://github.com/open-sauced/app/pull/3019

https://github.com/open-sauced/app/blob/602a44fe7325741cf6e3d2e98f40ba2d0ba3aa53/lib/hooks/api/useGetWorkspaceRepositories.ts#L15-L16

which was a hotfix for getting paginated workspace repos to work. This will get a huge number of repos from the API to then do some client side pagination. This isn't great since query out for huge repo payloads won't scale well as people continue to adopt workspaces. Instead, we should aim to use pagination at the API hook (like we do with workspace repo insights):

https://github.com/open-sauced/app/blob/602a44fe7325741cf6e3d2e98f40ba2d0ba3aa53/lib/hooks/api/useWorkspaceRepositoryInsights.ts#L10-L18

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
This looks resolved
