### ISSUE TITLE
Feature: Create a bottom banner in sidebar for non logged in users to sign up 

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/app#3083]
I wonder if on mobile we can create a bottom banner to entice non logged in users to sign up so we don't lose that opportunity?

<img width="416" alt="image" src="https://github.com/open-sauced/app/assets/27322879/5592e87d-af24-43a0-a445-b3ce4d2997b0">

_Originally posted by @isabensusan in https://github.com/open-sauced/app/issues/2812#issuecomment-2012528403_

**Comment by nickytonline** [comment]
There's a `footer` prop (psuedo-slot) in the WorkspaceLayout that you can use for this.
