### ISSUE TITLE
Feature: add a loading state to repo pages

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#3087]
### Type of feature

🍕 Feature

### Current behavior

Currently, if I open a repo page, there's a few seconds while the data is loading where the screen looks like this:
<img width="1219" alt="image" src="https://github.com/open-sauced/app/assets/27322879/006ed78f-52c0-4f36-823f-d38ad789f0eb">

### Suggested solution

Can we add a loading state while the data loads?
<img width="1339" alt="image" src="https://github.com/open-sauced/app/assets/27322879/b34095f0-9949-4b5f-bc3c-62466e9535bd">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
@zeu, we have a skeleton component for this you can use. See https://design-insights.netlify.app/?path=/story/design-system-atoms-skeleton-wrapper--double-wrappers
