### ISSUE TITLE
Bug: Logos on the page are smaller in some cases - i.e. microsoft/garnet

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#3096]
### Describe the bug

<img width="1210" alt="Screen Shot 2024-04-02 at 3 16 22 PM" src="https://github.com/open-sauced/app/assets/5713670/d2e23ce9-6aae-49fb-a437-8099972cccae">

Noticing that the microsoft logo renders smaller on Beta. 

I also noticed it is smaller on production as well. My suggestion is that we add a min height. 

<img width="445" alt="Screen Shot 2024-04-02 at 3 18 03 PM" src="https://github.com/open-sauced/app/assets/5713670/dc878133-deac-41ff-9204-aac52cbcff01">

The open-sauced log is much bigger, also looks better 🥂 

<img width="528" alt="Screen Shot 2024-04-02 at 3 19 47 PM" src="https://github.com/open-sauced/app/assets/5713670/87c4349f-ba86-4edc-9493-7619491e07da">

### Steps to reproduce

1. Visit https://beta.app.opensauced.pizza/s/microsoft/garnet

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by isabensusan** [comment]
Fixed!
<img width="1114" alt="image" src="https://github.com/open-sauced/app/assets/27322879/342a64d8-d7ce-4773-ba24-6627861eca4e">
