### ISSUE TITLE
Bug: repo pages 500 on certain repos

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#3097]
### Describe the bug

Noticed this bug where a 500 is hit on certain repo pages:

![Screenshot 2024-04-02 at 6 10 28 PM](https://github.com/open-sauced/app/assets/23109390/2160aba7-4a6e-47f8-93c6-10c707edb99a)

And I thought that maybe it's because "Netflix" has a capital N in it:

https://github.com/Netflix/bpftop

which shouldn't matter: all org/repo names are case insensitive. But their other repos work fine:

![Screenshot 2024-04-02 at 6 12 39 PM](https://github.com/open-sauced/app/assets/23109390/05b42ce9-28c6-48d1-ab5f-f46c979fdd29)

![Screenshot 2024-04-02 at 6 13 01 PM](https://github.com/open-sauced/app/assets/23109390/170156c0-df0f-4c0c-af0d-09e906fc0196)

So I have no idea what it could be. Trying to find other repos this happens on without much luck

### Steps to reproduce

1. Go to https://beta.app.opensauced.pizza/s/Netflix/bpftop
2. Notice 500

### Browsers

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by BekahHW** [comment]
@jpmcb I'm not getting a 500. Do you think this is resolved?

**Comment by brandonroberts** [comment]
Looks to be resolved
