### ISSUE TITLE
Bug: Edit insight page button style

### ISSUE THREAD

**Issue by sourabpramanik** [open-sauced/app#3099]
### Describe the bug

There is a styling issue with the Sync GitHub org. section button
![image](https://github.com/open-sauced/app/assets/61370770/50243c54-9683-45e9-a82e-f200be5de49a)
Selecting the button content shows the label
![image](https://github.com/open-sauced/app/assets/61370770/ccce53e0-68fd-4428-8e3a-7efab183efa3)

### Steps to reproduce

1. Go to the edit insight page
2. Scroll to GitHub org. section

### Do you have any images or screen captures?

![image](https://github.com/open-sauced/app/assets/61370770/50243c54-9683-45e9-a82e-f200be5de49a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
This is already fixed on beta and will go live in the next release https://github.com/open-sauced/app/pull/3142#issuecomment-2040611118
