### ISSUE TITLE
Bug: overflow on mobile views

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#3114]
Looking at [kubernetes](https://app.opensauced.pizza/s/kubernetes/kubernetes) with.  

![image](https://github.com/open-sauced/app/assets/5713670/55fdf101-1b00-46ba-8a03-128547ffb169)

**Comment by nickytonline** [comment]
It's definitely data related, but regardless we should obviously contain it.

I didn't notice this when I was cleaning up the mobile views as our app repo has less data to display.

![image](https://github.com/open-sauced/app/assets/833231/154457fe-06b0-4837-81f2-27f0fd9f7feb)
