### ISSUE TITLE
Feature: Include Releases as a Highlight Option

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#3121]
### Type of feature

🍕 Feature

### Current behavior

Today releases only work for Issues and PRs. Adding releases should be straightforward. This would open up the path for more maintainers to engage with the feature.

![image](https://github.com/open-sauced/app/assets/5713670/5d31e0a8-5ff7-4e2e-a245-2aa58261cb4d)

### Suggested solution

Add option for isValidReleaseURL

https://github.com/open-sauced/app/blob/beta/components/molecules/HighlightInput/highlight-input-form.tsx#L435

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
Closing as a duplicate
