### ISSUE TITLE
Feature: Add GitHub link to repo pages

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/app#3153]
### Type of feature

🍕 Feature

### Current behavior

Currently repo pages don't have an external link to their corresponding GitHub Repo URL

### Suggested solution

Link the name of the repository in the header on the repo page to GitHub

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
This relates to this convo, https://github.com/open-sauced/app/issues/3154#issuecomment-2046149433
