### ISSUE TITLE
Feature: Link repositories to their repo page

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/app#3154]
### Type of feature

🍕 Feature

### Current behavior

Places where we link a repository to GitHub should navigate to the new Repo Pages

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
I was chatting with @isabensusan about this as it came up during our chat about the PRs table, and we talking about an external link to the actual PR and another link to the repo page. One of how GitHub does it on mobile when you click on a repo link and it gives you a choice to go to the user/org or repo. e.g.

![image](https://github.com/open-sauced/app/assets/833231/02a01f2c-9236-4a29-9ea9-06b50ed4be54)
