### ISSUE TITLE
Feature: update metric cards on repo pages

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#3165]
### Current behavior

We have duplicate information in the forks/stars mini charts and the charts below
<img width="1249" alt="image" src="https://github.com/open-sauced/app/assets/27322879/8b21592e-18a3-4a3c-9297-6bfe4f7a085f">

### Suggested solution

Add PR / Issue info to Repo pages using the current cards
<img width="450" alt="image" src="https://github.com/open-sauced/app/assets/27322879/5f4943af-152b-43cc-b6dd-c1edd80929f1">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
FWIW these smaller star and fork card elements would make for great hover card context.
