### ISSUE TITLE
Feature: Make workspaces dropdown searchable

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#3167]
As a user of many workspaces, I want the workspaces dropdown in the sidebar to be searchable, so that I can drill down to a specific workspace quicker.

**Comment by nickytonline** [comment]
Also, as the list of workspaces gets longer, it doesn't make sense to list all workspaces. Perhaps recent and pinned ones (see #3075) and then from there, you just type to find your workspace.

**Comment by BekahHW** [comment]
This would be great. I too am in the situation where it's unwieldy, but I also think it's a power user issue rn. But once users have a long list, being able to search will make for a more useable experience.
