### ISSUE TITLE
Bug: Some OSS fyi links don't work

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#3175]
### Describe the bug

Going to my oss.fyi link (oss.fyi/jpmcb) doesn't work:

![oss-fyi-broken](https://github.com/open-sauced/app/assets/23109390/ec5a0348-7af6-4655-ac16-0cf76fb2e5dc)

_but_, so do work (like oss.fyi/bdougie)

### Steps to reproduce

1. Go to oss.fyi/jpmcb
2. notice forward to marketing page
3. go to oss.fyi/bdougie
4. notice it works

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by isabensusan** [comment]
can confirm, oss.fyi/isabensusan doesn't work either

**Comment by jpmcb** [comment]
Doesn't look this is a bug, just some confusion on what "oss.fyi" can do: we'd need to go into dub.co and create those short links. Some additional context: I think I was getting confused on what "oss.fyi" could do from some of our marketing communication.

We could definitly get it on the roadmap to auto generate those links but probably would want to limit the auto generation to user profiles.

**Comment by brandonroberts** [comment]
Will handle this in the API for shortening contributor profile URLs to use the handle

**Comment by brandonroberts** [comment]
These are setup in dub.co on oss.fyi for our team, and URLs shortened from user profiles will be handled by the API automatically
