### ISSUE TITLE
Bug: No feedback while saving workspace changes 

### ISSUE THREAD

**Issue by FatumaA** [open-sauced/app#3181]
### Describe the bug

When saving changes in a workspace there is no indicator that anything is happening until it is done saving.

Perhaps a loading/disabled state can be added to the button? Or a message indicating that something is happening?

### Steps to reproduce

1. Go to workspaces
2. Create a new workspace
3. Give it some details
4. Make some changes to it
5. Click "update workspace"
6. Notice it takes a minute before any feedback is received 

### Do you have any images or screen captures?

https://github.com/open-sauced/app/assets/67555014/c857cbb6-9dc4-4cb5-a13e-2edcd2724b88

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
We can probably add a processing overlay screen @isabensusan. This wasn't an issue initially as all our tests were with small datasets. Now that you can import an orgs repositories, it really looks likes nothing happening for a bit.

**Comment by nickytonline** [comment]
For now, @isabensusan, I opted for a button loading state instead. We can revisit a saving overlay.
