### ISSUE TITLE
Bug: Cannot delete a couple of Contributor Insight Pages in a row

### ISSUE THREAD

**Issue by adiati98** [open-sauced/app#3188]
### Describe the bug

When I wanted to delete a couple of Contributor Insight Pages in a row, I couldn't do it without refreshing the page.

Here is what I did:

- After deleting a page, I wanted to delete another page.
- I typed the page name that I want to delete, but clicking the "Delete" button didn't do anything.
- Clicking the "x" icon to clear the name also didn't work.
- Only the "Cancel" button worked.
- I tried one more time with the same result.
- This finally worked after I refreshed the page.

### Steps to reproduce

1. In the sidebar, click the "Show all" option for Contributor Insights.
2. Click "bin" icon and delete a page.
3. Click "bin" icon to delete another page.
4. Type the page name and click the "Delete" button. You will see that nothing happen.
5. Click the "x" icon next to the name to clear the input. Nothing happens.
6. Click the "Cancel" button. It will take you back to the list.
7. Repeat step 3 - 6. Nothing will happen.
8. Refresh the page and repeat step 3 - 4.
9. Now it deletes the page as it should. 

### Do you have any images or screen captures?

https://github.com/open-sauced/app/assets/45172775/0c49a0f1-3e64-4646-a8bb-06be92edb13a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by Lalithkumarponnambalam** [comment]
.take

**Comment by Lalithkumarponnambalam** [comment]
.take
