### ISSUE TITLE
bug: z-index is off for search on the Workspaces page (mobile)

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#3190]
![image](https://github.com/open-sauced/app/assets/5713670/498c7603-aa3e-414f-ab20-1e4844655436)

Logged in and searching from the workspaces page. Unable to click out of the search due to z-index

**Comment by nickytonline** [comment]
We probably don't need to mess with z-indices, and can leverage Radix's hover card component so it gets inserted at the end of `document.body` (default hover card component container).

**Comment by bdougie** [comment]
> We probably don't need to mess with z-indices, and can leverage Radix's hover card component so it gets inserted at the end of `document.body` (default hover card component container).

Agreed. Messing with z-index is usually a smell.

**Comment by bdougie** [comment]
This was fixed in a recent release.
