### ISSUE TITLE
Feature: better loading state

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#3203]
### Current behavior

We don't have a loading state right now, and when the info comes in, it just replicates the stream flow from the API.

### Suggested solution

It'd be great to have a nicer animation for the loading state and prompt reply creation.

### Inspiration
![Rewatch GIF Recording - 2024-04-17 at 11 19 18 AM](https://github.com/open-sauced/app/assets/27322879/3b995aa4-1f7b-4687-ad9a-30befbe62b9b)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
This would be nice for launch. When asking multiple questions. The chat falls below the fold and there is no context for what is happening. It is not a great experience for chatting more than once.

![Ryan Cavanaugh](https://github.com/open-sauced/app/assets/5713670/324d5b86-a461-47e5-8691-2ca97ef3819d)

**Comment by nickytonline** [comment]
@isabensusan had some ideas, but nothing concrete for the loading state. This is an easy lift once we have the asset.

**Comment by isabensusan** [comment]
@nickytonline  We can definitely come up with a better loading state, but for the time being, can we add the 3 dot animation?

![Image](https://github.com/open-sauced/app/assets/27322879/0b7fdfb3-d4c7-4f48-b121-446d38b1df7e)

### Specs
- 3 dots, 8x8px each, separated by 4px 
- color --> open-sauced orange at 50% opacity


For reference -- we can make this with tailwind:
https://tailwindflex.com/@anonymous/loading-dots
