### ISSUE TITLE
Feature: Waitlist

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#3207]
### Current behavior

<stub>

### Suggested solution

<stub>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nickytonline** [comment]
See designs in Figma, https://www.figma.com/file/38v1mNMKSlbIhaAvcm9az0/Star-Search?type=design&node-id=207-2977&mode=design&t=kRsm9Ccp0EpKnHKD-0
