### ISSUE TITLE
Bug: Delete Contributor Insight uses wrong copy

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#3213]
### Describe the bug

1.  The Delete section uses Workspace instead of Contributor Insight

### Steps to reproduce

1. Go [here](https://app.opensauced.pizza/workspaces/70809527-03ce-41ec-a159-fc664651afdb/contributor-insights/05d267d4-d5e3-4877-8e54-306e6bb35519/edit) or to any edit contrib insight page.

## Fix

Copy should be updated to:

Delete Contributor Insight

Once you delete a Contributor Insight, you're past the point of no return.

### Do you have any images or screen captures?

<img width="806" alt="image" src="https://github.com/open-sauced/app/assets/34313413/3c182fb4-128a-46c8-80c4-4181272caf88">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Lalithkumarponnambalam** [comment]
Hello @BekahHW, I would like to suggest the following changes be made to the "Delete Repository Insight" as well. what do you think ?


![Screenshot from 2024-04-18 15-34-01](https://github.com/open-sauced/app/assets/139358124/7baf6969-9f25-44cb-bfcf-6f1dd6a547cd)

**Comment by BekahHW** [comment]
@Lalithkumarponnambalam, I think that sounds right. We should be consistent.

**Comment by Lalithkumarponnambalam** [comment]
@BekahHW Could you please assign this task to me ?

**Comment by nickytonline** [comment]
@Lalithkumarponnambalam, just read the [contributing guidelines](https://docs.opensauced.pizza/contributing/introduction-to-contributing/).

**Comment by Lalithkumarponnambalam** [comment]
.take
