### ISSUE TITLE
Feature: clear input after submitting question to StarSearch

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#3225]
### Current behavior

Right now, if I make a question to StarSearch, the prompt input box keeps the prompt:

<img width="1048" alt="image" src="https://github.com/open-sauced/app/assets/27322879/8aa2f938-e699-46db-9b7e-44094a196504">

### Suggested solution

Expected behaviour would be for the input box to clear out after the user presses the enter key.

<img width="1130" alt="image" src="https://github.com/open-sauced/app/assets/27322879/1a6f4240-0a07-40f7-a0f4-e057b0ac556e">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by shobhit8797** [comment]
Where can i find this page? @isabensusan 
i am not able th=o find the chat option in the application

**Comment by isabensusan** [comment]
Hi @shobhit8797 ! This is actually feature flagged while we test it, we'll let you know when it's open to everyone!
