### ISSUE TITLE
Bug: Filtering by repos on the workspace activity page no longer works

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#3230]
When the feature for the pull requests table got merged, a table available from the workspace activity page, you were able to filter by one or more repositories. This no longer seems to be the case.

I came across this after I had created a Netlify workspace, https://app.opensauced.pizza/workspaces/8b856470-d615-45f0-b001-ebedaae29bed.

![CleanShot 2024-04-22 at 22 00 06](https://github.com/open-sauced/app/assets/833231/c6ceb07a-76c7-4c0a-87eb-54b6b1770d5c)

**Comment by brandonroberts** [comment]
I've tested this in prod with the provided link and beta and the issue seems to be resolved.
