### ISSUE TITLE
Follow up style fixes for StarSearch suggestion boxes

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/app#3232]
I'm still getting some weird behaviours with things overlapping , but I think overall this is good to merge -- we can do follow up PRs for styling

<img width="1334" alt="image" src="https://github.com/open-sauced/app/assets/27322879/c097b2b6-ec57-401a-9b19-5a6d74a69c00">

<img width="1503" alt="image" src="https://github.com/open-sauced/star-search/assets/27322879/da17c445-4449-4657-a019-6be65b291102">

_Originally posted by @isabensusan in https://github.com/open-sauced/app/pull/3176#pullrequestreview-2015786692_

**Comment by zeucapua** [comment]
Fixed and replaced with a carousel #3431
