### ISSUE TITLE
Replace Readme logo

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#3250]
The logo in this repo's README is the old one, we should replace it with the new one.

<img width="739" alt="image" src="https://github.com/open-sauced/app/assets/34313413/f6fad9ab-665f-4b38-99d9-a7c9df236bf5">

Replacement:

https://github.com/open-sauced/assets/blob/main/logos/logo-on-dark.png

**Comment by Lalithkumarponnambalam** [comment]
.take
