### ISSUE TITLE
Bug: Multiple Emoji description does not appear in the repo page

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#3314]
### Describe the bug

Looking at https://app.opensauced.pizza/s/qrev-ai/qrev and noticing their description does not show

#### open-sauced
![Screenshot 2024-05-03 at 8 03 23 AM](https://github.com/open-sauced/app/assets/5713670/df9df887-c4c2-4405-8a9c-c491fdc38235)

#### github
![Screenshot 2024-05-03 at 8 03 28 AM](https://github.com/open-sauced/app/assets/5713670/102606b7-0f38-4fb7-8086-76651f954c09)

### Steps to reproduce

1. Note https://app.opensauced.pizza/s/qrev-ai/qrev
2. Confirm description exists https://github.com/qrev-ai/qrev

I'm not sure if this is a timing thing and they may not have had a description before we indexed it or if it is the triple emoji thing. open-sauced-app shows up fine. Pandas also shows fine too.

![Screenshot 2024-05-03 at 8 06 34 AM](https://github.com/open-sauced/app/assets/5713670/3e742ef5-501e-4a3c-9e12-86e371c1ede9)

![Screenshot 2024-05-03 at 8 06 44 AM](https://github.com/open-sauced/app/assets/5713670/c0203399-20ed-4128-9ad5-968a315856f7)

**Comment by nickytonline** [comment]
If they updated it today after you visited the page, the page will be cached for two hours. Check a bit later to see if it's still an issue.

**Comment by nikkhielseath** [comment]
I just wanted to mention that the issue still exists. The page still doesn't show the description.

<details>
 <summary>Screenshot</summary>
 
![Screenshot 2024-05-06 at 5 26 56 AM](https://github.com/open-sauced/app/assets/51415616/3b7968ba-7880-4d58-9976-8659df809ecb)

</details>

<details>
 <summary>Network Request</summary>
 
![Screenshot 2024-05-06 at 5 30 08 AM](https://github.com/open-sauced/app/assets/51415616/ae473372-e899-48e9-b7ec-e9af822f0195)

</details>

**Comment by bdougie** [comment]
Checking a new repo today and noticed the missing description - https://oss.fyi/middlewarehq/middleware

<img width="595" alt="Screenshot 2024-05-15 at 6 41 28 AM" src="https://github.com/open-sauced/app/assets/5713670/f5392c64-ad77-447b-89ff-10d5596e7401">

**Comment by nickytonline** [comment]
Hmm, if it has a description it should render in the OG image. I'll take a peek at this once some Lunch week stuff settles down.

**Comment by bdougie** [comment]
Seems like any new repo index doesn't show a description. react-compiler open sourced yesterday.

<img width="577" alt="Screenshot 2024-05-16 at 5 51 26 AM" src="https://github.com/open-sauced/app/assets/5713670/8d912766-17bf-4a38-b2ab-9799a0be7a4a">

**Comment by nickytonline** [comment]
Debugging this, and the API returns an empty string for the description.

![CleanShot 2024-05-17 at 17 33 12](https://github.com/open-sauced/app/assets/833231/c3f139b5-dca4-46e7-9e7e-532e085ef67c)

**Comment by nickytonline** [comment]
Looking at the repo though (should have done this first 😅 ), there is no description.

![CleanShot 2024-05-17 at 17 34 18](https://github.com/open-sauced/app/assets/833231/0ec16364-d34c-49b3-8a2f-e71ae4c2c626)

**Comment by nickytonline** [comment]
Hmmm, debugging and MiddlewareHQ/middleware's description appears. Maybe there was a bug fix for this?

![CleanShot 2024-05-17 at 17 37 05](https://github.com/open-sauced/app/assets/833231/698ee30f-e059-42a9-9e9c-7e988f028f56)

**Comment by nickytonline** [comment]
On beta it's all good.

![CleanShot 2024-05-17 at 17 38 37](https://github.com/open-sauced/app/assets/833231/5218b518-7a80-4d7e-98b6-9e7e8806ee9c)

On production it's missing.

![CleanShot 2024-05-17 at 17 39 23](https://github.com/open-sauced/app/assets/833231/ebfe38af-c556-40ad-b935-489e26175cc5)

Any bug fixes related to description for repo pages this past week @open-sauced/engineering?

**Comment by nickytonline** [comment]
Closing for now. If this is still happening after the Tuesday release, please reopen.
