### ISSUE TITLE
Bug:   ReferenceError: window is not defined 

### ISSUE THREAD

**Issue by devharsh2k4** [open-sauced/app#3327]
### Describe the bug

This error happened while generating the page. Any console logs will be displayed in the terminal window while testing locally

whenever am using the app locally and navigate to some other pages inside the app my browser is showing up this error

![Screenshot from 2024-05-07 13-54-53](https://github.com/open-sauced/app/assets/103301856/0d76014f-11ca-4fe0-861f-1d4c95d3aafc)

### Steps to reproduce

Navigating to other pages

**Comment by nickytonline** [comment]
Thanks for the issue @devharsh2k4. Which page(s) is this happening on? We have some end to end tests and locally I have yet to encounter this issue.

**Comment by devharsh2k4** [comment]
Actually its mostly happening while locating to other profiles,repos and others pages its totally random can't say its only limited to those pages first of all i thought that it might be an issues with my browser as am using Brave browser so i also tried with chrome but still the same issue was happening 
My OS :- Linux (Debian 12)

**Comment by devharsh2k4** [comment]
unable to replicate this via this link looks like a local environment issue

**Comment by devharsh2k4** [comment]
![Screenshot from 2024-05-07 23-04-35](https://github.com/open-sauced/app/assets/103301856/f3af61d7-3792-4d95-8f00-9a35f204c205)
getting this error in compiler

**Comment by nickytonline** [comment]
Since it's not happening on beta, I'm going to go ahead and close this. If you're having trouble getting set up, first go through the installation instructions.
