### ISSUE TITLE
Bug: Placeholder to paste URL when creating a Highlight is still mentioning DEV.to blog post only 

### ISSUE THREAD

**Issue by adiati98** [open-sauced/app#3331]
### Describe the bug

Recently, there is an update where users can highlight blog posts that they published outside Dev.to.
However, the placeholder is still mentioning to paste Dev.to URL only for blog post highlight.

Current placeholder:

  
![placeholder to paste URL at OpenSauced app](https://github.com/open-sauced/app/assets/45172775/1f405fd5-5931-4cb8-916a-af65126c0765)

We might want to update this placeholder to make users aware that they can now create highlight for blog posts that they published outside Dev.to.

### Steps to reproduce

1. Post a highlight.
2. You can see at the placeholder that says: "Paste the URL to your PR, Issue, or Dev.to blog post".

**Comment by FatumaA** [comment]
I can confirm this is still the case

Do you think this is a good first issue?

**Comment by nickytonline** [comment]
This is the line of code to change.

https://github.com/open-sauced/app/blob/cc8d7344824478a86d0c14ecdcaa8026e4ecb222/components/molecules/HighlightInput/highlight-input-form.tsx#L671

```diff
-                   placeholder="Paste the URL to your PR, Issue, or Dev.to blog post."
+                   placeholder="Paste the URL to your PR, Issue, or blog post." 
```

**Comment by nickytonline** [comment]
> I can confirm this is still the case
> 
> Do you think this is a good first issue?

@FatumaA, I think this would be a great first issue.

**Comment by Asin-Junior-Honore** [comment]
.take
