### ISSUE TITLE
Bug: Star-Search markdown rendering isn't displaying rendered react-markdown HTML properly

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#3337]
### Describe the bug

There appears to be something wrong with how the react-markdown gets rendered in the chat box for Star-Search. Primarily, the renderd HTML doesn't seem to be correctly displayed. For example, here's an H3 (that is properly rendered from a "###" in markdown) that doesn't get bolded or highlighted or anything:

<img width="1509" alt="Screenshot 2024-05-07 at 3 53 29 PM" src="https://github.com/open-sauced/app/assets/23109390/128541d7-0858-41af-bc7c-0d2a3c8c17ba">

### Steps to reproduce

1. Ask Star-Search a question
2. Inspect the HTML
3. See that the markdown was rendered but notice that it's HTML elements aren't observed correctly

**Comment by nickytonline** [comment]
@jpmcb, the reason this happens is because tailwind by default removes default browser stylings. We can add some for the markdown rendered.

**Comment by nickytonline** [comment]
I have a PR I will put up that fixes all this, e.g.
![CleanShot 2024-05-07 at 21 04 58](https://github.com/open-sauced/app/assets/833231/97879c27-a81b-4f0d-9aa0-025e5d63850f)
