### ISSUE TITLE
Repo pages show closed PRs, but they should be Merged

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#3338]
<img width="1286" alt="Screenshot 2024-05-07 at 4 24 52 PM" src="https://github.com/open-sauced/app/assets/5713670/39b08d26-b354-4482-ac0e-5ad187be1227">

Looking at these charts. Issues closed should be a red line. PRs closed should be "merged."

cc @zeucapua & @isabensusan perhaps this is a quick fix?

**Comment by isabensusan** [comment]
@bdougie agree on the "merged" wording for PRs, but for issues, GitHub consistently uses purple to represent "closed" issues,  not red (I think the only place they showed it that way was on org insights). Might be missing something though, so let me know!

<img width="129" alt="image" src="https://github.com/open-sauced/app/assets/27322879/fae526ef-b3a3-4e5e-810b-a11e1eea36ec">

**Comment by bdougie** [comment]
>  GitHub consistently uses purple to represent "closed" issues, not red (I think the only place they showed it that way was on org insights). Might be missing something though, so let me know!

We can go with github on closed issues. Related, I think "low activity" should be grey instead of red. Red sends the wrong signal.

**Comment by nickytonline** [comment]
That's a good point about low @bdougie. We should also update OG images in regards to low activity as well.
