### ISSUE TITLE
Feature: Lottery Factor Chart

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#3341]
## Overview
We want to build a lottery factor chart for our repo pages, so that users can see who the most active contributors are (based on commits) and the % of their contributions over the total.

<img width="400" src="https://github.com/open-sauced/app/assets/27322879/4a9569a8-1327-4147-bfe1-1855077d342d">

<img width="400" src="https://github.com/open-sauced/app/assets/27322879/31ca83a3-7a13-4397-9567-ef55a73dca8e">

## Endpoint
We have an existing `/v2/repos/lotto` endpoint that returns a list of lottery factor contributors that can be used to populate this chart

```
{
  "all_contribs": [
    {
      "contributor": "nickytonline",
      "count": 34,
      "percent_of_total": 0.3269230769230769,
      "lotto_factor": "high"
    },
    {
      "contributor": "brandonroberts",
      "count": 29,
      "percent_of_total": 0.27884615384615385,
      "lotto_factor": "high"
    },
    ...
  ],
  "all_lotto_factor": "high"
}
```

## The Barchart
The goal is for users to put in perspective the contributions of the lottery factor contributors vs the rest of the community.
To achieve this, the metric for the barchart should be the `percentage_of_total` field on the endpoint, and the chart should:
- Show the contributors that make up to 80% of the contributions, and then the rest of the community grouped

BUT, if there's more than 5 contributors that have made 80% of the contributions:
- Show only the top 5 contributors + the rest of the community grouped

The reason behind this is to avoid crowding the chart too much. 

Two examples of what the bar chart would look like for two different repositories (see color code in next section):
<img width="739" alt="image" src="https://github.com/open-sauced/app/assets/27322879/ea0d4633-2a9e-4e9d-b8e0-cc652a42c15e">

### Color Code
![image](https://github.com/open-sauced/app/assets/27322879/a8782251-8671-453e-8799-1ceacb1e4f45)

## The insight subtitle

<img width="800" alt="image" src="https://github.com/open-sauced/app/assets/27322879/b6b84a01-0d8f-4370-83e8-49a792d03714">

**Comment by bdougie** [comment]
This looking real nice

![shaq](https://github.com/open-sauced/app/assets/5713670/6fcce6ca-e9eb-4161-876d-e13c15f6a9b3)

**Comment by nickytonline** [comment]
For the bar chart you can pull code from the languages chart I built a while back. https://design-insights.netlify.app/?path=/docs/components-graphs-most-used-languages-graph--docs

![CleanShot 2024-05-08 at 13 04 50](https://github.com/open-sauced/app/assets/833231/423fd296-9661-4036-b95b-e3166c8c65a2)

**Comment by jpmcb** [comment]
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExa2VjYmZkODhjNjhpeXFhNzBzbXJqOTV6d2tiM2k5ODJtNjR2OTlrMSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3WCNY2RhcmnwGbKbCi/giphy.gif)
