### ISSUE TITLE
Update card for Lunch Week

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#3344]
Once we have the lunch week page up, we should update this card to preview and link to the page.

## Current 
<img width="223" alt="image" src="https://github.com/open-sauced/app/assets/34313413/a62128f6-085e-403f-996d-f091ad0237a5">

## Suggestion

We just need the image for this (@isabensusan) 

<img width="253" alt="image" src="https://github.com/open-sauced/app/assets/34313413/7d1a93f4-6c85-48cd-91da-cef999307d04">

**Comment by nickytonline** [comment]
This will require updating the end to end test again.

https://github.com/open-sauced/app/blob/a854c90514dc55bd03c8a1a1a016767381275914/e2e/homepage.spec.ts#L15

```diff
-  await expect(page.getByRole("complementary", { name: "Introducing Star Search!", exact: true })).toBeVisible();
+  await expect(page.getByRole("complementary", { name: "Join Our Lunch Week!", exact: true })).toBeVisible();
```

**Comment by BekahHW** [comment]
I remember 😁On May 8, 2024, at 4:44 PM, Nick Taylor ***@***.***> wrote:﻿
This will require updating the end to end test again.
https://github.com/open-sauced/app/blob/a854c90514dc55bd03c8a1a1a016767381275914/e2e/homepage.spec.ts#L15
-  await expect(page.getByRole("complementary", { name: "Introducing Star Search!", exact: true })).toBeVisible();
+  await expect(page.getByRole("complementary", { name: "Join Our Lunch Week!", exact: true })).toBeVisible();
