### ISSUE TITLE
Feature: change "low" activity badge to gray instead of red

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#3345]
### Suggested solution

Change the "Low Activity" badge from red to gray. 

Low activity isn't necessarily always a bad thing, it could be a sign that contributors are just taking a break, and that's ok too! 

A gray badge can help signal inactivity without the negative connotation of red.

We can use the color palette that we use for the "public badge"
https://design-insights.netlify.app/?path=/docs/design-system-atoms-insightsbadge--docs

## Places where we are using the Activity badge

**Workspaces Metrics**
<img width="447" alt="image" src="https://github.com/open-sauced/app/assets/27322879/ced12828-54b8-46fd-93a4-2f380b8f9eb5">

**Repositories Table**
<img width="399" alt="image" src="https://github.com/open-sauced/app/assets/27322879/901d623e-bc25-44c2-8557-6b556933a79b">

**Comment by nickytonline** [comment]
We'll also need to update this image that is used for workspace OG images. Can you provide a new one @isabensusan when you have a chance?

https://github.com/open-sauced/app/blob/c6e0514bc2c2dfa9d20be9f18d50662e1593c351/public/assets/og-images/workspaces/low-activity.png

![CleanShot 2024-05-08 at 17 53 48](https://github.com/open-sauced/app/assets/833231/611d0703-9e4a-4982-8e73-a232a9be8bba)
