### ISSUE TITLE
Bug: Suggestions on Initial Load of StarSearch should be a carousel

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#3369]
Suggestions on initial load of starSearch should be a carousel, in fact they should always be a carousel.

![IMG_3E9750D38BE5-1](https://github.com/open-sauced/app/assets/833231/bc1505f1-338e-490a-a9df-bbe772887374)

**Comment by zeucapua** [comment]
On mobile view, these are now in a drawer always. Should we close this issue?

**Comment by brandonroberts** [comment]
Closing as resolved, we can reopen it if necessary
