### ISSUE TITLE
Feature: style Repo pages layout

### ISSUE THREAD

**Issue by zeucapua** [open-sauced/app#3370]
### Suggested solution

![image](https://github.com/open-sauced/app/assets/20603494/b8f37650-c184-4ea6-b5b1-125ba40e6168)

Notes from @isabensusan:
```
overall, the lottery chart needs to be smaller:
- for text -- make subtitle, names, and everything text-sm
- padding is significantly smaller, p-4
the contributors chart needs to be taller as well
the metrics and the title on the contributor chart should be vertically aligned to the top
```

**Comment by nickytonline** [comment]
I like the look of this for larger screens. Thoughts @isabensusan?

**Comment by isabensusan** [comment]
@nickytonline yes! that's the mock I gave zeu :)

**Comment by bdougie** [comment]
I am recording a video for @chhristopher later today and hit some noob level CSS things, but brute forced this to work for an recording. If this happens to make it on a deploy preview before end of day, that would be amazing. 
                                             
For some reason, I could not get the lotto chart and echart to match heights, so I instead just added overflow hidden 😓   
                                                                   
<img width="1474" alt="Screenshot 2024-05-13 at 12 32 10 PM" src="https://github.com/open-sauced/app/assets/5713670/ba4b19f2-9366-4990-b9af-c0831d4a27be">
