### ISSUE TITLE
Feature: Enriched Star Search Responses

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#3372]
As a user of StarSearch I want an enriched UI response that is more than standard HTML links, lists, etc. so that I can have more context in responses to my prompt.

**Comment by nickytonline** [comment]
Relates to:

- https://github.com/open-sauced/app/issues/3353
- https://github.com/open-sauced/app/pull/3367
- https://github.com/open-sauced/api/pull/787
- https://opensauced.rewatch.com/video/j21qyw8rc6nv43e8-enriched-ui-for-starsearch

**Comment by bdougie** [comment]
We had something for this that @isabensusan made. Not related to Lottery factor but there is a quick [example with profiles in Figma](https://www.figma.com/design/38v1mNMKSlbIhaAvcm9az0/Star-Search?node-id=88-36&t=S3AqXLtPXFq97Ces-0).

![Screenshot 2024-05-13 at 11 50 43 AM](https://github.com/open-sauced/app/assets/5713670/27adb2d2-5144-43b4-95af-259d0884a19b)

**Comment by jpmcb** [comment]
FYI - the tool calls hinting has landed in beta:

![Screenshot 2024-05-13 at 4 07 48 PM](https://github.com/open-sauced/app/assets/23109390/da488cb3-a39c-477c-8a76-c2756b506658)

so, for this one, when you ask about the lottery factor, it should know to call the "renderLotteryFactor" tool which will send that in the SSE. If we want to also try one for user cards, let me know!
