### ISSUE TITLE
Bug: Cannot find some repositories in the process of creating a new workspace

### ISSUE THREAD

**Issue by adiati98** [open-sauced/app#3382]
### Describe the bug

I wanted to create a new workspace. But when I wanted to find a repository using "Search for repositories", it doesn't search the repository at all. Clicking enter also didn't do anything. I'm not sure if this happens to random repositories.

### Screen Recording

https://github.com/open-sauced/app/assets/45172775/f23a2e2e-c346-4137-9a5b-9edae6de4aca

### Steps to reproduce

1. Create a new workspace.
2. Click "Add repositories" button.
3. Try to search "open-sauced/docs" or "open-sauced/intro".
4. The repo doesn't show as a suggestion and it doesn't search it, too.

**Comment by FatumaA** [comment]
Yap, can reproduce this. Even when adding new repos to an existing wotkspace

**Comment by adiati98** [comment]
Additionally, this happens whenever we want to search a repository in general.

I tried to search the repository from the search bar and got the same result as screen recording below:

https://github.com/open-sauced/app/assets/45172775/be02e83d-328e-45ee-9d84-20db99f0bb3d

**Comment by nickytonline** [comment]
There's some wonkiness in that search component. I think part of it might be throttling from GitHub, but I do think there is a genuine bug in there.

**Comment by brandonroberts** [comment]
We switched this to use our api first, then fallback to GitHub
