### ISSUE TITLE
Bug: Share buttons do not work on mobile

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#3385]
Trying to click the share buttons and get no interaction on mobile.

Profile

![image](https://github.com/open-sauced/app/assets/5713670/4197ed41-6a14-45a3-a62c-5968b741f10c)

Repo

![image](https://github.com/open-sauced/app/assets/5713670/4f7dc351-2bae-4267-8632-40c738523e88)

Repo Insights

![image](https://github.com/open-sauced/app/assets/5713670/e4aefeb5-edbc-47ce-97be-884e33699ead)

**Comment by sourabpramanik** [comment]
Can't reproduce this on my end. Tested on Android, IOS, and web mobile view as well.

**Comment by bdougie** [comment]
It does work, just confirmed. However I think it his is still missing something visual letting the user.

I don't currently see a toast message when copied on mobile.
