### ISSUE TITLE
Chore: Remove unused components from the project

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#3399]
While working on the waitlist for StarSearch, I noticed some existing components that were in the project that have never been used.

They should be removed from the project. If we ever do need them, git history to the rescue.

The are the files the files and folders to be deleted.

https://github.com/open-sauced/app/blob/e2c8b3b0d624416d105f86efb8e8d38a615dc17b/components/organisms/Waitlist/waitlist.tsx

https://github.com/open-sauced/app/blob/e2c8b3b0d624416d105f86efb8e8d38a615dc17b/components/organisms/Waitlist/waitlist.stories.tsx

https://github.com/open-sauced/app/blob/e2c8b3b0d624416d105f86efb8e8d38a615dc17b/components/molecules/WaitlistButton/waitlist-button.tsx

https://github.com/open-sauced/app/blob/e2c8b3b0d624416d105f86efb8e8d38a615dc17b/components/molecules/WaitlistButton/wailtlist-button.stories.tsx

**Comment by nickaldwin** [comment]
Hi @nickytonline i would like to work on this issue .take
