### ISSUE TITLE
Bug: Only show one not found message

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#3411]
When a user and a repository is not found,for the given search term, we display two warning messages.

![CleanShot 2024-05-16 at 18 28 53](https://github.com/open-sauced/app/assets/833231/770d84ef-6a37-444c-8921-2c11fe57a943)

It should consolidate into one in a scenario like this.

`We couldn't find any users or repositories with that name`

**Comment by BekahHW** [comment]
I agree!

**Comment by sourabpramanik** [comment]
.take
