### ISSUE TITLE
Bug: lottery factor loading state overflows

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#3466]
### Describe the bug

When loading a repo page, the lottery factor loading animation overflows outside of the chart.

<img width="479" alt="image" src="https://github.com/open-sauced/app/assets/27322879/21a2c4ac-4f56-4a28-beed-1b04d393df98">

https://github.com/open-sauced/app/assets/27322879/be607207-c4b1-4982-8816-1ffd4fff704f

### Steps to reproduce

1. Go to any repo page ie. https://app.opensauced.pizza/s/laravel/laravel
2. See loading state

**Comment by nickytonline** [comment]
It looks like the loading state is intertwined with the error/no contributors view.
