### ISSUE TITLE
Bug: 500 when clicking on workspaces while logged in.

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#3475]
### Describe the bug

A new user has shared that when they log in  and click workspaces, they get a 500.

 
![image](https://github.com/open-sauced/app/assets/34313413/cc211de9-4579-439b-93a1-539579d88135)

### Steps to reproduce

I haven't been able to replicate, but the flow is:

1. log in
2. click workspaces
3. see 500

**Comment by a0m0rajab** [comment]
I could not reproduce this!

**Comment by nickytonline** [comment]
I'm having trouble reproducing this as well. Anyone else in @open-sauced/engineering able to reproduce this? It's definitely an issue as two new signups have encountered it.

**Comment by brandonroberts** [comment]
Is this only after onboarding? I'll check also

**Comment by nickytonline** [comment]
> Is this only after onboarding? I'll check also

I imagine it is. I reset onboarding to test it.

**Comment by a0m0rajab** [comment]
@brandonroberts did we solve this issue? 
I faced it today with one of my friends when he tried the app for the first time. 

Here is the case we got from it: 

https://app.opensauced.pizza/workspaces/null

I believe that the issue would be that the app was not able to get the first workspace if it's not generated, and it's not waiting to generate it.
