### ISSUE TITLE
Bug: AI hallucination

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/app#3479]
### Describe the bug

I tried to find a contributor who used 3 different technologies, StarSearch has provided me some data about the contributors, yet one of them have not been active on GitHub for the last few years.. 

![image](https://github.com/open-sauced/app/assets/18273833/f1e1e7b9-caa1-4f57-9e04-226e9566e238)

https://github.com/ojkwon

### Steps to reproduce

1. go to star search
2. use the next prompt: `give me three contributors who worked on all of TailwindCSS, NextJS and TRPC`

**Comment by nickytonline** [comment]
Hallucinations do happen and we have a disclaimer about this at the bottom of the StarSearch page. I'm going to close this for now as there's the disclaimer.

![image](https://github.com/open-sauced/app/assets/833231/0d78dd7f-b270-49d5-a34f-20e6e8243348)

**Comment by a0m0rajab** [comment]
Thanks for the fast feedback!

**Comment by bdougie** [comment]
@a0m0rajab did you use the feedback widget after getting the response?

That is helpful for us to flag prompts for improvement.

Also would not consider this a hallucination, but an ungrounded result. The question broad, so the result is prone to an ungrounded result.

**Comment by a0m0rajab** [comment]
@bdougie if you mean the thumb up/down, then no i did not use it. Will be careful next time and use that. 
![image](https://github.com/open-sauced/app/assets/18273833/32756148-0e77-4712-a53e-648a43cbe050)

**Comment by bdougie** [comment]
No worries. Just pointing out that exists and is very helpful for training the model.

**Comment by a0m0rajab** [comment]
Thanks for pointing that out! will use it next time.

**Comment by jpmcb** [comment]
Thanks for surfacing this: very helpful information as we continue to improve this. Abit more context on what's going on behind the scenes:

A question like `give me three contributors who worked on all of TailwindCSS, NextJS and TRPC` essentially has 3 subjects to search across: Tailwind, next, and trpc. We could do 3 vector searches for those 3 technologies but that wouldn't necessarily return the same individuals. So, you'd end up having to do a huge search where there is overlap across all 3 vector spaces for the same users which would take awhile.

It looks like what the model decides to do is one big vector search for any context that includes all 3 of those. And it popped up someone who isn't currently active resulting in an ungrounded answer.

It's possible it decided to use Bing search too which can pop up some ungrounded results. I'll dig more into this to see if there's a path forward for unraveling a better result.

**Comment by a0m0rajab** [comment]
Thanks for the explanation, based on that would not the model be able to alert/tell the user that it would not be able to search the three results?

A simple check would be to have a prompt manager that can see the number of topic wthat searched for and tell the user it exceeds the maximum number (there is a paper from Microsoft about this I will try to find it when I am on pc (hopefully I won't forget that 😅))

Another approach that would be helpful to use is to show the user what the model actually doing (something like Devin and open Devin). It shows the planning and thinking process to the user.

As for the users of these technologies, If you are using vectors multiplying the vectors would help to find the target user.

Something like dot multiple.

Sent from mobile device


________________________________

**Comment by a0m0rajab** [comment]
Note: I though about this question based on the T3 stack and decided to choose three technologies from it.

Sent from mobile device


________________________________
