### ISSUE TITLE
Bug: highlights feed is too close to the footer 

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/app#3482]
### Describe the bug

The highlight feeds is to close to the footer. adding `py` padding would solve the issue: 

![image](https://github.com/open-sauced/app/assets/18273833/61a6a885-60f4-43f7-969b-08345062cc7f)

Related code: 
https://github.com/open-sauced/app/blob/06b73aff03fb95771ac1811ee15bd997e21651bd/pages/feed/index.tsx#L178-L181

### Steps to reproduce

1. go to the main page
2. scroll till the end of the page

**Comment by nickytonline** [comment]
Thanks for reporting @a0m0rajab! This appears to only be an issue on the highlights page. If you'd like to work on this, feel free to, or we can open it up as a potentially good first issue. I'd suggest `pb-14` (3.5 rem/56px) which is what it appears to be on the explore page.

![CleanShot 2024-05-26 at 15 57 13](https://github.com/open-sauced/app/assets/833231/5b65f8fd-4e9f-4197-ba9a-cb33b7febf8c)

**Comment by a0m0rajab** [comment]
I think it would be better to have it as `good-first-issue`, since the code that needs to be changed is already mentioned in the issue. 

 As for the padding, I checked the filter page and noticed that it's using `py-8` there, do you think we could use it for this case? 

Here is the code, here is the search results for that code: 

https://github.com/search?q=repo%3Aopen-sauced%2Fapp%20flex%20w-full%20flex-1%20flex-col%20items-center%20%20py-8%20bg-light-slate-2&type=code

**Comment by nickaldwin** [comment]
HI @nickytonline and @a0m0rajab can i work on this issue? .take
