### ISSUE TITLE
Feature: share `LotteryFactorChart` as image

### ISSUE THREAD

**Issue by zeucapua** [open-sauced/app#3502]
### Suggested solution

Instead of users having to screenshot each individual card on the site, they can press a "share chart" button to have an image copied to the clipboard. This should be made by an edge function so it is copiable, as well as fetchable via URL.

**Comment by isabensusan** [comment]
@zeucapua on your design request for a shareable image:
 
I think when sharing, the chart should look exactly the same as it does in the page. The logic is that if someone sees an image for the lotto factor chart on twitter or social media and click through to the repo page they should be able to instantly recognize the chart in the page.

My question here is: do you know what's the best format/size to export the image so it looks good pasted on different places?

Ideally we'd prioritize twitter, slack and linkedin as surfaces where we'd want these to show up, but I'm not sure if there is a size that works for all of them.

## Possible Directions
From what I've seen there's two directions we could go:

1. Share only the chart as a card (ie. PostHog does this):
<img width="400" alt="image" src="https://github.com/open-sauced/app/assets/27322879/25a77924-6387-4854-8836-4ec87bb58979">



2. Share the chart with a nice background (allows us to resize it to better fit socials?):
<img width="600" alt="image" src="https://github.com/open-sauced/app/assets/27322879/b57156e1-fa64-4c88-9fe7-27591852843a">


Would love to hear your thoughts on what could be the best direction based on what you've seen so far!

**Comment by isabensusan** [comment]
@zeucapua udpated the designs with more eye catching colors

**Comment by zeucapua** [comment]
I like the second one with the full background. I think if we add a border/shadow to differentiate the card from the background, and also make the grid more pronounced, it'll be perfect. Also agree on the possible resizing for different socials in the future.

**Comment by bdougie** [comment]
Linking context that the original dev card has embedded as a feature already.

devcard onboarding and embedding.

https://devcard2.netlify.app/
https://github.com/open-sauced/devcard

We should consider this when approaching this experience.

**Comment by nickytonline** [comment]
The suggestions above were more OG image like, but I think we can just go with copying the lottery factor chart via the CopyContainer component. https://github.com/open-sauced/app/pull/3975
