### ISSUE TITLE
Feature: StarSearch in Workspaces UI Component

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#3508]
## StarSearch in Workspaces UI Component

We want to turn StarSearch into an embedabble chat component that can be used throughout different parts of the platform, using the context surrounding it.

This issue represents the first iteration of this UI Component.

### Use Cases
Some use cases that come to mind when thinking of 

**Get a better understanding of your contributors**
- What languages do my contributors use the most?
- Where are my contributors from? Where do they work? --> *if we get better location/company info
- Who have been the most active contributors?

**Find experts in a contributor base**
- Are there any contributors in my Workspace that have used Rust before?
- Who has worked with React components the most in x repository?

**Identify trends**
- What repository has been getting the most stars lately?
- Are any repositories getting higher activity than usual?

**Uncover potential risks**
- Is there a high lottery factor in any of my repositories?
- Have any repositories been loosing a lot of contributors?

**Understand your repositories**
- What is the average issue velocity on my repositories?
- What's the repository with the highest contributor confidence score?

Open to more suggestions!

Tasks:

- [x] #3587
- [x] #3588
- [x] #3589

## Mock ups

[FIGMA FILE](https://www.figma.com/design/38v1mNMKSlbIhaAvcm9az0/Star-Search?node-id=437-857&t=z6X89LiBLqdKlyp7-4)

### Entry Point

Users will be able to trigger StarSearch by clicking on a floating button fixed to the bottom of the screen. We can make it more attention grabbing by introducing some slight animation as well.

<img width="1390" alt="image" src="https://github.com/open-sauced/app/assets/27322879/862dd282-8be3-48eb-99eb-f4f9660919a4">

&nbsp;

With a tooltip on hover
<img width="311" alt="image" src="https://github.com/open-sauced/app/assets/27322879/4241a9a2-033b-425e-85b4-864bcdce4e39">

&nbsp;

### Initial Screen
The initial screen will include suggestions on things to search for, based on the mentioned use cases:
![image](https://github.com/open-sauced/app/assets/27322879/251464b1-accf-44a2-a3de-3acd0a59a9de)

&nbsp;

Once the user asks a question, they'll be taken to the chat interface
![image](https://github.com/open-sauced/app/assets/27322879/467a5f29-10bf-4ea0-a6f3-e4e94c9ebbd1)

&nbsp;
### Header actions
<img width="600" alt="image" src="https://github.com/open-sauced/app/assets/27322879/aa7bd3d2-d56d-40f9-95e0-ff74c873c4cc">

&nbsp;

### Chat History
<img width="1121" alt="image" src="https://github.com/open-sauced/app/assets/27322879/3a39cfa5-a8dc-4ccb-92ae-7bb2499d8f02">

**Comment by isabensusan** [comment]
## Open Question
mentioned by @nickytonline -- in conjunction with [api #853](https://github.com/open-sauced/api/issues/853), when we add chat history, how is that going to play with this simplified embeddable component?

**Comment by isabensusan** [comment]
Updated issue with mocks and more implementation details

cc - @bdougie @nickytonline @jpmcb  for visibility

this is the basic UI component  -- I'll be opening more tickets for other interactions like:
- Advanced actions to entice users to transform the result of their prompts into contributor insights
- Enriched objects/charts in response
- etc.

**Comment by nickytonline** [comment]
> ## Open Question
> mentioned by @nickytonline -- in conjunction with [api #853](https://github.com/open-sauced/api/issues/853), when we add chat history, how is that going to play with this simplified embeddable component?

I liked your idea of the history loading in the StarSearch panel when you click on history in the header to avoid the double panel issue.
