### ISSUE TITLE
Bug:  notifications and user settings pages 404

### ISSUE THREAD

**Issue by Haimantika** [open-sauced/app#3522]
### Describe the bug

<img width="1512" alt="Screenshot 2024-06-05 at 12 52 04 PM" src="https://github.com/open-sauced/app/assets/32809211/28f6324a-7510-4e94-9453-2deb4d68a6d0">
The notification tab is throwing a 404 error, as shown in the screenshot.

### Steps to reproduce

1. Go to your OpenSauced profile
2. Click on the bell icon
3. You see a 404 error

**Comment by nickytonline** [comment]
I’m guessing this is related to the new route path for users, e.g. `/user` is now ‘/u`

**Comment by nickytonline** [comment]
Thanks for reporting @Haimantika! I’ve rolled back the app to the previous deploy while we investigate.

**Comment by Haimantika** [comment]
> Thanks for reporting @Haimantika! I’ve rolled back the app to the previous deploy while we investigate.

After rolling it back to the previous deploy it is working. Thanks for taking a quick look and I hope the path issue gets solved soon. :)

**Comment by nickytonline** [comment]
I confirmed with the latest of the beta branch that this is an issue for user settings as well.

**Comment by Haimantika** [comment]
> I confirmed with the latest of the beta branch that this is an issue for user settings as well.
> 
> The routes for those pages is still `/user`, but all `/user` routes go to `/u` now.
> 
> ![CleanShot 2024-06-05 at 06 56 03](https://private-user-images.githubusercontent.com/833231/336807716-7cc33f15-b942-4c9c-a05c-222622b0ab79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1ODcxNTYsIm5iZiI6MTcxNzU4Njg1NiwicGF0aCI6Ii84MzMyMzEvMzM2ODA3NzE2LTdjYzMzZjE1LWI5NDItNGM5Yy1hMDVjLTIyMjYyMmIwYWI3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQxMTI3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNWRhN2IxYTk5NDY4MTViZWYwZGNkYzc4MzFmNjQ2NmRhNTczNzlhMzNmMGNlMmMyMDcyNjc4NGVmNWQ2ZDM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x-_8E07mRtNhQCTz5sEEDlGOlOFw5UN31bi6dxaeoLs)
> 
> If we want to keep these separate, we'll need to adjust the redirect rules. If we want to have them under e.g. `/u/settings`, we'll need to move the page files.

Oh. Was there a reason to redirect to `/u`?

**Comment by jpmcb** [comment]
> Oh. Was there a reason to redirect to /u?

This was done as part of feature work to align some of our other short routes (for example, repo pages exist under the `/s` route)

https://github.com/open-sauced/app/pull/3486
