### ISSUE TITLE
Feature: initial ROSS index implementation for Repo Pages

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#3548]
### Suggested solution

Now that we have "Contributor Confidence" in https://github.com/open-sauced/app/pull/3545 coming to repo pages, an excellent decoration to that would be the ROSS index.

## What is the ROSS index?

The Rate Of Self Selection (ROSS) is an index invented by @bdougie and @jpmcb that looks at the overall rate of internal vs. external individuals that land contributions in repos over a period of time.

Ultimately, it's a rate of how often a project "self selects" for internal members. An extremely low score means there are essentially _only_ internal contributions. A higher score means there's a healthy mix of internal and new. A very very high score would be harder to find but would basically mean there's a solo dev who's taking alot of new / recurring external contributions but the internal team isn't doing anything.

**_TLDR_**: it's a way to see if there's a healthy balance of external contributors to your open source project (or possibly, non at all!) over time.

This is important to have an understanding of if internal members to an org suddenly drop off, if there's a steady decline of new contributors coming in (who ultimately need to feed the maintainer pipeline), etc. etc.

## What's the payload look like?

Initial work is being done in the API to bring this to individual repos. This index already exists for workspaces under `v2/workspaces/{id}/ross`. See the following:

- https://github.com/open-sauced/app/issues/3317
- https://github.com/open-sauced/app/issues/3318

So, this new API endpoint for individual repos will exist under `v2/repos/{org}/{name}/ross` and will look nearly identical to how it works for workspaces today. As an example, this is what the data would look like for a repo over a 30 day period:

```json5
{
  // The actual index across buckets: each bucket is a 7 day period
  // where the rate of self selection is a percentage over each 7 day time range.
  "ross": [
    {
      "bucket": "2024-02-19T00:00:00.000Z",
      "index": 0.012658227848101266
    },
    {
      "bucket": "2024-02-05T00:00:00.000Z",
      "index": 0.051470588235294115
    },
    {
      "bucket": "2024-01-29T00:00:00.000Z",
      "index": 0.0028735632183908046
    },
    {
      "bucket": "2024-01-22T00:00:00.000Z",
      "index": 0.04950495049504951
    }
  ],

  // In each 7 day time bucket, we can dive into how many new / recurring / internal
  // contributors there were over that period of time.
  // "new" are external contributors who have not made a contribution before
  // "recurring" are external contributors who have made a contribution before
  // "internal" are org members / repo owners
  "contributors": [
    {
      "bucket": "2024-02-19T00:00:00.000Z",
      "new": 1,
      "recurring": 9,
      "internal": 9
    },
    {
      "bucket": "2024-02-05T00:00:00.000Z",
      "new": 7,
      "recurring": 17,
      "internal": 21
    },
    {
      "bucket": "2024-01-29T00:00:00.000Z",
      "new": 1,
      "recurring": 9,
      "internal": 15
    },
    {
      "bucket": "2024-01-22T00:00:00.000Z",
      "new": 5,
      "recurring": 12,
      "internal": 16
    }
  ]
}
```

### Skunkworks design

An idea to get this data in would be to have a histogram superimposed with the index percentage:

![Screenshot 2024-06-11 at 7 35 13 AM](https://github.com/open-sauced/app/assets/23109390/098cc0d5-7a4d-43fc-8488-d64f80ae5e06)

Each of the 4 sections are the 4 buckets that represent the 7 day chunks over a period of 30 days. The green histogram bar is "new" contributors, brown is "recurring", and red is "internal". You'll also notice a time series that displays the ross percentage over time (maybe we can have a toggle that turns off the ross time series or the contributor histograms to make it easier to visualize).

I think it'll be important to get _something_ in since this is relatively unproven data and we need to start experimenting to find the rough edges in the ROSS algorithm we've derived. We can also choose to put this behind a feature flag if we don't want this initial, skunkworks design.

**Comment by isabensusan** [comment]
![Image](https://github.com/open-sauced/app/assets/27322879/7be3f8a4-24aa-437e-a5f9-4030ca5944fe)

**Comment by jpmcb** [comment]
These changes have merged in the API: https://github.com/open-sauced/api/pull/868 - let me know if there are questions on the payload or anything else!
