### ISSUE TITLE
Bug: the input is not reset after deleting a contributor insight page

### ISSUE THREAD

**Issue by takanome-dev** [open-sauced/app#3553]
### Describe the bug

https://github.com/open-sauced/app/assets/79809121/dba2ca23-8ccf-4bda-ac43-2feb9205bb99

### Steps to reproduce

1. Go to your workspaces
2. delete one of them
3. try deleting another 
4. notice that the input is not cleared

**Comment by nickytonline** [comment]
Did you want to work on this @takanome-dev?

**Comment by shubhamchasing** [comment]
@nickytonline can I take this?

**Comment by shubhamchasing** [comment]
.take

**Comment by takanome-dev** [comment]
> Did you want to work on this @takanome-dev?

Oh didn't see this, yeah I was planning to then forgot about it 😅 
Will pick another one 👍
