### ISSUE TITLE
Bug: Repository page throws a hydration error on smaller screens

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#3557]
here's some hydration errors with smaller screens sizes.

![CleanShot 2024-06-12 at 16 17 17](https://github.com/open-sauced/app/assets/833231/91da3b4e-fe4b-4aca-9b88-5244b5412a70)

**Comment by brandonroberts** [comment]
This seems to be causing some of the flakiness in E2E tests also. Looking into it as part of #3946
