### ISSUE TITLE
Update gauge text styling in contributor confidence

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/app#3558]
@zeucapua  styling wise, I'd love to see the number inside the gauge be bigger and placed higher. Could be a follow up PR too :)

<img width="1112" alt="image" src="https://github.com/open-sauced/app/assets/27322879/541fbb79-bbc5-47ca-81fb-ea97c75b52bd">

_Originally posted by @isabensusan in https://github.com/open-sauced/app/issues/3545#issuecomment-2161368933_

**Comment by nickytonline** [comment]
a custom label can be applied for the text size changes @isabensusan requested. https://recharts.org/en-US/examples/PieChartWithCustomizedLabel
