### ISSUE TITLE
Bug: Workspaces layout missing top padding

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#3562]
### Describe the bug

Padding at the top of the Workspaces layout is off:
<img width="1719" alt="image" src="https://github.com/open-sauced/app/assets/27322879/1e714217-1902-452f-82ec-ec26acfe47f3">

By adding a `pt-8` class to the top, It should look something like this:

<img width="1508" alt="image" src="https://github.com/open-sauced/app/assets/27322879/17b1e39c-1ceb-47d5-aa92-5e071ba7b3a8">

### Steps to reproduce

1. Go to any workspace and you'll see it

**Comment by zeucapua** [comment]
This is fixed with the merging of #3537 (example of the workspace home page):
https://github.com/open-sauced/app/blob/a5578b0b0a7471192853280cdc120bb2271d555e/pages/workspaces/%5BworkspaceId%5D/index.tsx#L142
