### ISSUE TITLE
Bug: Header on Contributor Insights looks broken

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#3595]
### Describe the bug

If you navigate to any contributor insight, you will find that the header's width is bigger than it should be and it looks off:
<img width="1511" alt="image" src="https://github.com/open-sauced/app/assets/27322879/15917799-87bb-48e6-9f24-74abb1a99528">

If you click on the Activity tab, the header looks normal
<img width="1511" alt="image" src="https://github.com/open-sauced/app/assets/27322879/9c323689-beb9-415e-a494-13099bd5ef5b">

### Steps to reproduce

1. Go to any contributor insight's overview tab

**Comment by jpmcb** [comment]
+1 - also just ran into this. Let's tackle this soon since we'll be shipping new features to Contributor Insights soon.

<img width="1508" alt="Screenshot 2024-06-24 at 8 23 30 AM" src="https://github.com/open-sauced/app/assets/23109390/38edabf8-c225-44b3-817a-22e8487f7522">
