### ISSUE TITLE
Bug: Cannot scroll on workspaces

### ISSUE THREAD

**Issue by zeucapua** [open-sauced/app#3609]
### Describe the bug

Workspaces that have a big enough repository table that the page is too long on the screen cannot be scrolled through.

### Steps to reproduce

1. Go to any workspaces with a large repository list
2. Attempt and fail to scroll

**Comment by nickytonline** [comment]
This currently only affects the core team that are behind the feature flag for StarSearch for workspaces.

I’ll look into this when I’m back as I’m still working on some of the functionality of the desktop view of StarSearch for workspaces.

**Comment by zeucapua** [comment]
Fixed with #3619
