### ISSUE TITLE
Bug: 404 on Shivshankar-Reddy user

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#3610]
### Describe the bug

When viewing [valkey](https://app.opensauced.pizza/s/valkey-io/valkey?range=360) I clicked on the number one lotto factor person, [Shivshankar-Reddy](https://app.opensauced.pizza/u/Shivshankar-Reddy), and get a 404 on their profile. 

![Screenshot 2024-06-21 at 8 56 07 AM](https://github.com/open-sauced/app/assets/5713670/243339bf-e800-495c-a3e5-9cf5e6a01ade)

Perhaps this is an edge case or something specific with their profile. I am on the hunt to find similar profiles 

### Steps to reproduce

View [valkey](https://app.opensauced.pizza/s/valkey-io/valkey?range=360) and visit the first profile.

**Comment by bdougie** [comment]
Found a second on https://app.opensauced.pizza/u/zwayth from https://oss.fyi/EddieHubCommunity/awesome-github-profiles

**Comment by brandonroberts** [comment]
I think we need to add our fallback to the users endpoint in the API. Currently if they aren't in our data, they need to connect their account, or we add the fallback to proactively add them on demand.

cc @jpmcb

**Comment by chriskthomas** [comment]
My account is connected, but my profile also gives 404: https://app.opensauced.pizza/u/chriskthomas
