### ISSUE TITLE
Bug: the share button does not close when clicked outside it

### ISSUE THREAD

**Issue by a0m0rajab** [open-sauced/app#3616]
### Describe the bug

Clicking outside the share chat does not close the dialog 

https://github.com/open-sauced/app/assets/18273833/fbf610eb-288d-4c10-90a1-4a31cd6a8d74

### Steps to reproduce

1. go to star search
2. click on the share button 
3. try to click outside it, it would not close

**Comment by a0m0rajab** [comment]
Related Component: https://github.com/open-sauced/app/blob/50c5d1111775d3aafd989fb48478dac304b553a0/components/StarSearch/ShareChatMenu.tsx#L53 

Related code: 

https://github.com/open-sauced/app/blob/50c5d1111775d3aafd989fb48478dac304b553a0/components/StarSearch/StarSearchChat.tsx#L81-L92

A function to check the outside click here and set the sharing enabled to false would be enough.

**Comment by AshutoshNanaware** [comment]
.take
