### ISSUE TITLE
Feature: refactor Contributors table to TanStack

### ISSUE THREAD

**Issue by zeucapua** [open-sauced/app#3624]
### Suggested solution

Similar to `WorkspaceIssueTable`, the Contributors table, as seen on contributor insights, should be sortable by columns like name and the future feature "ranking".

**Comment by isabensusan** [comment]
<img width="1633" alt="image" src="https://github.com/open-sauced/app/assets/27322879/fe37e194-a868-42b2-8f7d-21b1eade3d74">

**Comment by bdougie** [comment]
@zeucapua is this still blocked? What is needed to move it forward?

**Comment by zeucapua** [comment]
@jpmcb Proposed API schema for a contributor lists to be used for this table (possibly for `/repos/<org>/<repo>/contributors` & `/workspaces/<workspaceId>/userLists/<listId>/contributors`):

```ts
type DbContributorRow = {                                                                                                                                                                                                              
   "data": [
     // per user
     {
       // user info
       id: string;
       user_id: number;
       username: string;
       login: string;
       avatar_url: string;
      
       // properties for table
       oscr: number;
       repositories: { name: string; full_name: string; }[]; // top repos
       tags: string[]; // YOLO, internal, outsider, recurring, Lottery (?)
       company: string;
       location: string;
       contributions: number; // total = PRs, issues, commits, etc.
       last_contributed: string; // date time string
     }
   ],
   "meta": {
     // pagination, etc.
   }
}
```

**Comment by isabensusan** [comment]
@zeucapua on responsiveness: 

I'd love to keep the same experience we have today were each row turns into a collapsible component. 

When the row is collapsed I'd keep the same info:
- Avatar
- Name
- Last contributed

<img width="552" alt="image" src="https://github.com/user-attachments/assets/0f947d9f-ae03-4df4-b916-5ab75988d272">
