### ISSUE TITLE
Bug: after deleting an account it's almost impossible to use OpenSauced again

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#3647]
### Describe the bug

While doing some onboarding tests, I tried deleting my account to be able to re-connect and re-do the onboarding process, but noticed that after deleting my account the platform is virtually inaccessible.

Immediately after deleting my account, the following URLs all throw the same error:

- Feed and Explore page --> https://app.opensauced.pizza/feed
- User Profiles --> https://app.opensauced.pizza/u/bdougie
- Repo Pages --> https://app.opensauced.pizza/s/meta-llama/llama3
etc.

<img width="800" alt="image" src="https://github.com/open-sauced/app/assets/27322879/823f83fe-251f-4d7e-873f-7d4cf0fa193d">

### After deleting site cookies
I was able to at least use the public pages (see URLs above), but as soon as I tried clicking on "Connect with GitHub", the application would break again without letting me reconnect

### Why is this a problem?
If a churned user ever wanted to come back to use OpenSauced, we are making it impossible for them to do so. Ideally, they should still be able to navigate the page as a non-logged in user, and if they wanted to -- connect their github accounts again.

### Steps to reproduce

1. Go to User Settings
2. Click on "delete account"
3. After confirmation, try to navigate to https://app.opensauced.pizza/feed or any other public URL
4. See error message
5. Delete cookies
6. You should be able to navigate the site as usual
7. Try clicking on "Connect with Github"
8. Get error screen again

**Comment by brandonroberts** [comment]
Thanks @vivitt. We'll take care of deleting your account manually so you can reconnect, and look further into this issue.

What trouble were you having to need to delete your account?

**Comment by vivitt** [comment]
Hi @brandonroberts, sounds good, thanks!
I couldn't see my profile picture and my GitHub activity, and navigating to my user page throws a 404 error. As I didn't have previous activity on my account, I tried deleting it to see if it would solve the issue.

**Comment by brandonroberts** [comment]
@vivitt I removed your user account, so you can connect again and see if its resolved
