### ISSUE TITLE
Bug: Contributor Insights are still called lists on the Repository Insight page

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#3671]
### Describe the bug

<img width="1576" alt="Screenshot 2024-07-02 at 5 15 13 PM" src="https://github.com/open-sauced/app/assets/5713670/5b969f68-9870-42ed-b6a2-30539c4b0808">

### Steps to reproduce

1. Create a repository insight
2. View the contributors tab
3. Note the "Add to list" button

**Comment by shubhamchasing** [comment]
Instead of `Add to list` what should be the button's text, please share what changes need to be made.

I would like to work on it please assign me when you will remove the "needs triage" label
