### ISSUE TITLE
Bug: Type error in feed/index.tsx

### ISSUE THREAD

**Issue by DhairyaMajmudar** [open-sauced/app#3696]
### Describe the bug

There's a type error noticed in feed/index.tsx file 

**Screenshot**

![image](https://github.com/open-sauced/app/assets/124715224/9e0492db-9861-4584-9ad8-8116afda846a)
 

### Steps to reproduce

1. Navigate to feed/index.tsx file
2. View the type error in VS code problems tab

**Comment by DhairyaMajmudar** [comment]
This bug can be fixed if we add type boolean with `open` variable:

`onOpenChange={(open: boolean) => {`

**Comment by nickytonline** [comment]
Hi @DhairyaMajmudar. I have the latest of our beta branch, and the open parameter is inferred correctly as a boolean and things build fine.

![CleanShot 2024-07-08 at 21 14 36](https://github.com/open-sauced/app/assets/833231/f822ba9a-5af7-43c4-91ad-b7e9cd5d5fe2)

I'm going to go ahead and close this as there is no issue.

**Comment by DhairyaMajmudar** [comment]
> Hi @DhairyaMajmudar. I have the latest of our beta branch, and the open parameter is inferred correctly as a boolean and things build fine.
> 
> ![CleanShot 2024-07-08 at 21 14 36](https://private-user-images.githubusercontent.com/833231/346764677-f822ba9a-5af7-43c4-91ad-b7e9cd5d5fe2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MDI1ODMsIm5iZiI6MTcyMDUwMjI4MywicGF0aCI6Ii84MzMyMzEvMzQ2NzY0Njc3LWY4MjJiYTlhLTVhZjctNDNjNC05MWFkLWI3ZTljZDVkNWZlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQwNTE4MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNWYwNTI5OGMyMGJjYjg5M2E5MzkyNDQzYmY5MjQ4NzVkZmVjOGZiZWEwMzlkMDFiOWI2ZWViOWI5ZjZlOTAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8q3TRpBOL5aGL6MihrqPocYs4ZSIGRrsTqLFCMxwgRE)
> 
> I'm going to go ahead and close this as there is no issue.

Seems like issue is resolved in the recent commits.
