### ISSUE TITLE
Feature: Metadata for Repo Pages

### ISSUE THREAD

**Issue by zeucapua** [open-sauced/app#3706]
### Suggested solution

Implement more metadata for repo pages
- License
- Language
- Last updated

Suggested design:
![image](https://github.com/open-sauced/app/assets/20603494/beda324c-a422-48fa-a6f5-9aa80f524f6f)

**Comment by bdougie** [comment]
I think all of these make sense and linking to the explore page from here would make sense.

My concern is drawing a line between rebuilding GitHub and providing something useful for users.

**Comment by isabensusan** [comment]
@bdougie I think it's an understandable concern, but I think metadata like this helps give context to the data we are showing. 

I can also see some potential use cases:
- Org users who are deciding whether to use a repo in their project or not  / verify that a project is compliant with their company's OSS protocols --> licence info is valuable
- Users who are trying to understand whether a project is still alive or not --> they can see the "last updated at" info at a glance

IMO this is information that adds to the picture we are trying to paint
