### ISSUE TITLE
Bug: OpenSauced not CamelCased on User Profile

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#3719]
### Describe the bug

Currently, OpenSauced is all lowercase on the "Invite to OpenSauced" button on the user profile.

<img width="467" alt="image" src="https://github.com/user-attachments/assets/9499ba11-d448-4410-8cf7-423d5773555a">

### Steps to reproduce

1. Go to https://app.opensauced.pizza/u/AlonsoGuevara
2. See it twice on the page of a user not part of OpenSauced.

<img width="1060" alt="image" src="https://github.com/user-attachments/assets/e9ad7ca4-9460-4da2-aa2f-7497b61297ef">

**Comment by shubhamchasing** [comment]
Please assign me

**Comment by shubham-singh-748** [comment]
is this issue still open?

**Comment by shubhamchasing** [comment]
@shubham-singh-748  Yes I am working on it

**Comment by shubhamchasing** [comment]
@BekahHW 
I think you mean PascelCase.
https://miro.medium.com/v2/resize:fit:1400/1*PSDlLqeuDgeqClF-LLqPPw.png
