### ISSUE TITLE
Bug: query for starsearch workspaces persists across workspaces

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#3755]
### Describe the bug

1. When I ask a question in one workspace and then change workspaces, I see the same questions.
2. I would expect that each workspace has it's own history.

### Steps to reproduce

1. go to one of your workspaces and ask starsearch a question
2. got to another workspace and open starsearch. 
3. see the question from the previous workspace.

https://github.com/user-attachments/assets/d080a171-27c2-4933-8bda-61bdbe6a3c9c

**Comment by nickytonline** [comment]
The 404 in the logs there is an issue, but not related to this. I'm not sure what that is yet, but it doesn't appear to be affecting anything, yet. 😅
