### ISSUE TITLE
Feature: Create an OG Image for dev cards

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#3760]
### Suggested solution

Currently, Dev Cards aren't shareable. We want to be able to share the DevCards on social media with the OSCR rating on them. 

Here's an example from daily.dev: https://app.daily.dev/devcard

They have both vertical and horizontal, but I think we should start with horizontal since we already have things set up that way and we can display both the OSCR and the front and the back info bc there's more real estate. If we find that people are sharing these, we can consider adding the vertical. The challenge there is that we don't get all the info on the front and the back of the card. 

Ref: [discussion](https://github.com/open-sauced/api/discussions/894#discussioncomment-9883463)

![image](https://github.com/user-attachments/assets/e20b64a8-39b0-4038-b392-2d64b9d20de7)

cc: @isabensusan if you have design ideas.

**Comment by nickytonline** [comment]
Moving this to the app as we're using Edge functions for newer OG images.

**Comment by isabensusan** [comment]
@nickytonline sorry this took so long! but here's a quick approach to the OG image (all files are in better res in [this drive folder](https://drive.google.com/drive/folders/1c3m8KSLTDd8kzZDZcSGtZuehMYtxe-4k?usp=sharing) too)

Wasn't sure what was the best way to create the images, so I made two different approaches to the same design, and you can pick the one that's better!

### Approach 1: entire image as template
![Image](https://github.com/user-attachments/assets/0f2f3496-6b16-4c23-9e43-b5be6aaf1fdb)


### Approach 2: devcard image and background as separate images
![Image](https://github.com/user-attachments/assets/a61e621d-ea8b-45eb-97a7-01bb79787e44)
![Image](https://github.com/user-attachments/assets/ea8973cc-2535-4dfd-9f19-ed40537176d6)

**Comment by nickytonline** [comment]
> @nickytonline sorry this took so long! but here's a quick approach to the OG image (all files are in better res in [this drive folder](https://drive.google.com/drive/folders/1c3m8KSLTDd8kzZDZcSGtZuehMYtxe-4k?usp=sharing) too)
> 
> ### Example of OG Image
> ![Image](https://private-user-images.githubusercontent.com/27322879/356047993-9664da7f-e4fc-4b5c-9a79-a1b7dc5d72ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODQyNDksIm5iZiI6MTcyMzA4Mzk0OSwicGF0aCI6Ii8yNzMyMjg3OS8zNTYwNDc5OTMtOTY2NGRhN2YtZTRmYy00YjVjLTlhNzktYTFiN2RjNWQ3MmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDAyMjU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMjYwMGY2NWMyMTVkOGJiODZiNzYxZjYwM2M3MjBmODI0N2YwNTk1NWM1YWQxNWQ1ODM1OWEyZjY4MjQ4ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VkfdHC7kGtoJOxzH90AEX4vgK0EeFMWCQ-v8MxvYAcs)
> 
> Wasn't sure what was the best way to create the images, so I made two different approaches to the same design, and you can pick the one that's better!
> 
> ### Approach 1: entire image as template
> ![Image](https://private-user-images.githubusercontent.com/27322879/356047103-0f2f3496-6b16-4c23-9e43-b5be6aaf1fdb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODQyNDksIm5iZiI6MTcyMzA4Mzk0OSwicGF0aCI6Ii8yNzMyMjg3OS8zNTYwNDcxMDMtMGYyZjM0OTYtNmIxNi00YzIzLTllNDMtYjViZTZhYWYxZmRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDAyMjU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3NTY1N2MyYTdjYzQ5MDY4OGQ4NDQ3ZmNlYTQyYjZhZmIyYzBiMTZjZTQyMjZkNTY0OTlhNjEyYThjN2VkYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8-Fm25cMxtb7RxwtLkIEzpc0mfCkqlplK1mr3AXFO04)
> 
> ### Approach 2: devcard image and background as separate images
> ![Image](https://private-user-images.githubusercontent.com/27322879/356047101-a61e621d-ea8b-45eb-97a7-01bb79787e44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODQyNDksIm5iZiI6MTcyMzA4Mzk0OSwicGF0aCI6Ii8yNzMyMjg3OS8zNTYwNDcxMDEtYTYxZTYyMWQtZWE4Yi00NWViLTk3YTctMDFiYjc5Nzg3ZTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDAyMjU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5MDhiMDk5NjNlNTRjNzY3MGI3MzEzZjg4ODYyNjExNjE2Yjg3MTk0MDk5NTQ1NzExYWFjYzQ4YjU1ZWVlOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OII08Vx4jiEWnEe6ofVfkKSXkItJRJomgST0SGsIMz0) ![Image](https://private-user-images.githubusercontent.com/27322879/356047102-ea8973cc-2535-4dfd-9f19-ed40537176d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODQyNDksIm5iZiI6MTcyMzA4Mzk0OSwicGF0aCI6Ii8yNzMyMjg3OS8zNTYwNDcxMDItZWE4OTczY2MtMjUzNS00ZGZkLTlmMTktZWQ0MDUzNzE3NmQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDAyMjU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1M2E2NGMzNTYyZjRkY2U1YjQ2Mzk1Yjk3MzFjOWM5NGY2ZDI0NWY4YTU0YjUwZDNkOGQzOWU1Yjk4ODNhYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WhLsuXomWjWrdVQN0Jo6JL-TvOAiEZgVlEVq3E2Ntvk)

No worries @isabensusan! Looks great! I'll start working on this tomorrow.
