### ISSUE TITLE
Bug: multiple `DayRange` in mobile Activity page

### ISSUE THREAD

**Issue by zeucapua** [open-sauced/app#3762]
### Describe the bug

<img width="385" alt="Screenshot 2024-07-22 at 15 25 07" src="https://github.com/user-attachments/assets/88cdc35f-8302-49c4-a78f-449d0db11ba5">

### Steps to reproduce

1. Go to a workspace and click the Activity tab
2. In mobile view, observed the multiple day range selects

**Comment by shubhamchasing** [comment]
Please assign me, when the `triage` label will be removed

I believe the _Pull Requests_ tab UI should be like the _Issues_ tab 
![Screenshot from 2024-07-23 15-23-52](https://github.com/user-attachments/assets/e79ee7d0-91c4-4ea2-a13f-587f1d73f55a)

**Comment by shubhamchasing** [comment]
.take

**Comment by nickytonline** [comment]
I took this out of triage @shubhamchasing. All yours!
