### ISSUE TITLE
Feature: MVP `OssfChart` component

### ISSUE THREAD

**Issue by zeucapua** [open-sauced/app#3765]
### Suggested solution

Implement an MVP of component and storybook for #3742 with mock data. This will be added to the repository pages once it is [integrated in the API](https://github.com/open-sauced/api/issues/962). 

Design from #3742 
![image](https://github.com/user-attachments/assets/af5b9fb8-5e0b-4ddd-bf2d-e1ac02011f8d)

**Comment by isabensusan** [comment]
Some more details:

### Layout
![Image](https://github.com/user-attachments/assets/74e8272a-3ab0-49e0-a98c-74816dbe80d3)

**Comment by isabensusan** [comment]
@zeucapua 

### Anything > 8 
"This project is safe to use" 
"It passes almost all checks in the OpenSSF software security checklist with a high score. You can run the full test here."

### Any score between 6 and 7 
"This project is safe to use" 
"It passes almost all checks in the OpenSSF software security checklist. You can run the full test here."

### Any score < 5
"This project might not be safe to use" 
"It might not pass all checks in the OpenSSF software security checklist. You can run the full test here."


### Links
In all cases, the "You can run the full test here" text should be a link redirecting to: 
https://github.com/ossf/scorecard?tab=readme-ov-file#view-a-projects-score

And the "Learn more" should link to an entry on our own docs (doc pending). We can leave it hidden for now until we create the doc entry.
