### ISSUE TITLE
Feature: feedback - make the "create workspace" option more obvious

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#3774]
### Suggested solution

Sometimes I find myself confused how to make a new workspace:

![Screenshot 2024-07-25 at 7 39 22 AM](https://github.com/user-attachments/assets/8d9e2b17-2663-4a66-862f-9f57f59ed9cd)

The "Create new workspace" option _looks just like_ the rest of my workspaces.

Can me make it more obvious that it's a special option or a button? It's abit confusing how you actually create a new workspace.

**Comment by Anish0203** [comment]
Hi @jpmcb I would like to .take up this issue

**Comment by nickytonline** [comment]
We can change the styling for the Create Workspace... option in the list to make it stand out.

**Comment by Anish0203** [comment]
Design 1:
<img width="607" alt="image" src="https://github.com/user-attachments/assets/dce3879d-e3c8-4f93-a91f-823577aeeea9">

Design 2:
<img width="596" alt="image" src="https://github.com/user-attachments/assets/75d6ba79-a038-4b0b-acae-735b1637bf48">

Hi @jpmcb and @nickytonline , I would like to know your opinions on these 2 design options. Should we keep the plus icon or/and make the text italics? Also, any other styling that would prefer? Thanks.

**Comment by nickytonline** [comment]
The first design looks better. The icon already distinguishes it, so the italics really isn't necessary.

**Comment by Anish0203** [comment]
Got it. Thank you @nickytonline for the suggestion. I've a created a PR for the same
