### ISSUE TITLE
Bug: Other workspace starSearch history viewable on current workspace

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#3776]
### Describe the bug

For example, this is a netflix only workspace, but you can see that it's showing a query and chat from a different workspace.

<img width="1258" alt="image" src="https://github.com/user-attachments/assets/afb36453-6527-4bc5-9678-a2571d7310f1">

### Steps to reproduce

1. Open your workspace and ask a couple of questions.
2. Go to another workspace and open StarSearch history.
3. See chat from previous workspace.

**Comment by BekahHW** [comment]
Here are related issues. I can add individual issues for them, but I think if we fix the above it will take care of both of these as well. Adding them him so we can test it out:

## Deleting history from other workspace fails

It seems like if you have a history show up from a different workspace (let's call this x), but then try to delete it in Y, it fails to delete.

https://github.com/user-attachments/assets/b0a9be84-07eb-4af0-8dae-13d2ccd5033b

## Accessing history from other workspace shows blank ui

 If your history shows for a different workspace and you click it, the UI is blank:

https://github.com/user-attachments/assets/8500d73b-f84c-4ded-818d-ad77a07878dd

**Comment by nickytonline** [comment]
This should have already been sorted out. Is this in production or beta?

**Comment by nickytonline** [comment]
I can replicate the issue. A page refresh shows the correct history. Most likely the change in workspace is not updating the history for the workspace you changed to. Taking a peek.
