### ISSUE TITLE
Bug: Duplicate StarSearch history entries

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#3777]
### Describe the bug

I think it might be duplicating history. When you delete it in the chat, it doesn't show up immediately in the UI. But you can see from the video that all conversations suddenly disappear. It's worth noting that when this happens, that history disappears from the other workspaces as well.

https://github.com/user-attachments/assets/4ecedc3a-423e-4040-9227-30e54bdf2797

### Steps to reproduce

1. Go to a workspace.
2. Add a bunch of queries.
3. Leave the workspace, add some queries in a different workspace
4. Go back to original workspace.
5. try deleting conversations

**Comment by nickytonline** [comment]
I'm going to go ahead and close this @BekahHW as I can't replicate the issue since #3780 got merged. Feel free to reopen if you exhibit the behviour
