### ISSUE TITLE
Bug: Newsletter Signup Validation Fails for Valid Email Addresses

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#3795]
While investigating a separate issue, I discovered that the Newsletter sign up in the app's feed page fails for valid email address, e.g. my own, `nick at nickyt dot co`.

![image](https://github.com/user-attachments/assets/d726c6f3-35e9-41a9-b243-ff8d01831ebf)'

This regex appears to be the cause, https://github.com/open-sauced/app/blob/b266d15c71c57eb8488f578e86ae5eee57e0b81a/lib/utils/validate-email.ts

I'd recommend using Valibot instead since we already have it in the project. You can use their [email schema](https://valibot.dev/api/email/), as well as `type="email"` on the input.

https://github.com/open-sauced/app/blob/b266d15c71c57eb8488f578e86ae5eee57e0b81a/components/molecules/NewsletterForm/newsletter-form.tsx#L96-L104

**Comment by jpmcb** [comment]
Originally reported in: https://github.com/open-sauced/app/issues/3271

Attempted fix in: https://github.com/open-sauced/app/pull/3273
