### ISSUE TITLE
Bug: Newsletter sign up no longer collects a user's email

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#3796]
While investigating a build error `@netlify/plugin-nextjs@5 requires migration steps to support Netlify Forms. Refer to https://ntl.fyi/next-runtime-forms-migration for migration example.` I discovered that our newsletter signup no longer collects emails.

The last one collected appears to have been in March, but a couple tests I did does not collect the emails.

We're using the pages router, but it appears we may need to do the same fix as suggested in the Netlify docs to be able to use [Netlify Forms](https://www.netlify.com/platform/core/forms/) with Next.js. Not sure when this broke.

The fix is detailed at https://docs.netlify.com/frameworks/next-js/overview/#breaking-changes.

- [x] #3798
- [ ] #3799

**Comment by BekahHW** [comment]
@jpmcb here's the signup link: https://news.opensauced.pizza/#/portal/signup

**Comment by jpmcb** [comment]
Re-opening since we'll want to tackle the bigger lift of getting the form for newsletter signups to work and re-factor out my quickfix:

https://github.com/open-sauced/app/blob/b550a8c79ceb64e1b7c1c3e4c8a2ee483539c4ff/components/molecules/NewsletterForm/newsletter-form.tsx#L10-L18

**Comment by nickytonline** [comment]
Once that is complete, we'll want to tackle #3799
