### ISSUE TITLE
Bug: Custom oss.fyi/reponame does not work

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#3824]
### Describe the bug

At one point, when clicking the share button on a repo page it would use the repo name and org in the URL. That is no longer the case.

### Steps to reproduce

1. Visit https://beta.app.opensauced.pizza/s/swiftlang/swift
2. Click the share button
3. Note the link is not oss.fyi/swiftlang/swift

**Comment by jpmcb** [comment]
cc @brandonroberts - I believe you had the most context on the Dub.co short linking functionality
