### ISSUE TITLE
Bug: Bot accounts in contributor grids give a 404 when clicking on them.

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#3833]
Bot accounts in contributor grids give a 404 when clicking on them.

![CleanShot 2024-08-02 at 09 45 26](https://github.com/user-attachments/assets/bc420958-916e-4ec9-8268-1eb231508b5d)

We should consider checking for ` [bot]` at the end of the username and generate a generic avatar (current one broken) and provide no link to an OpenSauced user profile page as they don't exist for bot accounts.

**Comment by jpmcb** [comment]
Hmmmm the `[bot]` accounts definitely exist in our users table and are fetchable by the API:

![Screenshot 2024-08-02 at 8 11 39 AM](https://github.com/user-attachments/assets/94d76d09-5491-4e88-b9fb-9190f92db79c)

Could it be that the `[` and `]` are not getting properly escaped?
