### ISSUE TITLE
Bug: Contributors grid on repository contributors page is missing OSCRs

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#3834]
The contributors grid on the repository contributors page is missing OSCRs

![CleanShot 2024-08-02 at 09 55 11](https://github.com/user-attachments/assets/e1d6a483-24f0-4a1f-a185-1e80b9fe2dd6)

The ContributorCard component which is mapped over to create the grid already has the logic to show the OSCR. The problem is the contributor data in this view does not contain OSCR properties.

The reason for the discrepancy is the Contributors grid uses a different hook. It uses

https://github.com/open-sauced/app/blob/87824de461a3d24c7a06f4c12ad9d1f180a22a33/components/Tables/ContributorsGrid.tsx#L16

where as the contributors repo page loads the data via 

https://github.com/open-sauced/app/blob/87824de461a3d24c7a06f4c12ad9d1f180a22a33/pages/s/%5Borg%5D/%5Brepo%5D/contributors.tsx#L95-L106

and passes it as a prop to the contributors table

https://github.com/open-sauced/app/blob/87824de461a3d24c7a06f4c12ad9d1f180a22a33/pages/s/%5Borg%5D/%5Brepo%5D/contributors.tsx#L225-L232

**Comment by SURAJ-SHARMA27** [comment]
Hi @nickytonline, I would be happy to work on this issue. However, I'm unable to reproduce the issue on the repository-contributors page in grid view; OSCRs are showing as expected. Has this already been fixed, or is this behavior specific to an edge case?

![image](https://github.com/user-attachments/assets/612e6859-6b75-4dac-85ff-c95edfa1fdf8)

**Comment by nickytonline** [comment]
Duplicate of #3883
