### ISSUE TITLE
Feature: replace "Spam" column in Repo Workspaces with "OSSF Scorecard"

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/app#3841]
### Suggested solution

Instead of the "Spam" column in the Workspace Repos:

![image](https://github.com/user-attachments/assets/89e963b0-e1db-449d-ac8c-16ef40b89c56)

We should add an OSSF Scorecard column that tracks the repos security posture. This will require a small API change to include the OSSF Scorecard result in the `v2/repo/:owner/:name/search` endpoint.

---

This ticket is related to: https://github.com/open-sauced/app/pull/3838 which removes the "Spam" column.

**Comment by jpmcb** [comment]
Ah - looks like it's already included in the endpoint.

Example:

```
https://beta.api.opensauced.pizza/v2/repos/search?page=1&limit=10&range=30&repoIds=599731589%2C831881376%2C754357181%2C758580752%2C611397346
```

gets called for one of my workspaces (note the list of Repo IDs from the workspace). This payload looks like:

```
{
	"data": [
		{
			"full_name": "ublue-os/cosmic",
			"ossf_scorecard_total_score": null,
			"ossf_scorecard_dependency_update_score": null,
			"ossf_scorecard_fuzzing_score": null,
			"ossf_scorecard_maintained_score": null,
			"ossf_scorecard_updated_at": "1970-01-01T00:00:00.000Z",

                        // etc. etc. other fields for the repo
		},
	        
                // etc. etc., other repos in the workspace
	],
	"meta": {
		"page": 1,
		"limit": 10,
		"itemCount": 5,
		"pageCount": 1,
		"hasPreviousPage": false,
		"hasNextPage": false
	}
}
```

**Comment by brandonroberts** [comment]
Yep, got it
