### ISSUE TITLE
Feature: Update devcard with new design

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#3872]
### Suggested solution

We have a slightly updated Devcard design to implement
<img width="736" alt="image" src="https://github.com/user-attachments/assets/35b4b1b8-d211-4f6a-b139-4146627954ab">

### Assets
![image](https://github.com/user-attachments/assets/105d8b12-6ed3-4890-9501-33d97fb416a2)

<img width="1273" alt="image" src="https://github.com/user-attachments/assets/872af36a-8694-4253-8aba-c37f859a4fc3">

Priority order:
1. Oscr title in orange
2. Add the ’top X%’ badge
3. replace bg chart with gradient
4. update table in the back

Nice to haves:
- repo badges

![Rectangle 211](https://github.com/user-attachments/assets/81b841c5-d87e-4639-ab1d-bfbfce33c7bd)

**Comment by BekahHW** [comment]
Can we also add score/300?

**Comment by jpmcb** [comment]
Did abit of data analytics on the ~400,000+ contributors we've crunched the OSCR on:

![image](https://github.com/user-attachments/assets/4ac73a28-91d9-49d0-bcbe-301a0b181654)

Maybe not surprising, there's a huge weight near 0. My hypothesis is that most people are not actively contributing to an open source project or participating in conversation. Anyone above 250 is a true unicorn and in the 1%. The spread from 1% to 5% looks pretty even. What I suggest is the following:

250+ is top 1%
235+ is top 2%
225+ is top 3%
215+ is top 4%
200+ is top 5%
100+ is top 10%
