### ISSUE TITLE
Bug: onboarding page keep showing up each time I authenticate

### ISSUE THREAD

**Issue by Dun-sin** [open-sauced/app#3885]
### Describe the bug

Whenever I authenticate the application, I keep getting asked to add in my interests or basically the onboarding system doesn't go away

![image](https://github.com/user-attachments/assets/382ee400-0f85-41f4-978c-3fcd1aa5ac51)

Technically it's because the user data is loading in the background, but we should use a loading page instead of the onboarding system as the default

### Steps to reproduce

1. Go to `https://opensauced.pizza/`
2. Click on `Connect your GitHub`

**Comment by brandonroberts** [comment]
@Dun-sin I reset your onboarding status checks, will you try and connect again?

**Comment by Dun-sin** [comment]
> @Dun-sin I reset your onboarding status checks, will you try and connect again?

Didn't change

**Comment by brandonroberts** [comment]
@Dun-sin we've made some changes to onboarding. Try it again with the browser devtools open and let us know if you see any errors in the console when trying to complete it.

**Comment by Dun-sin** [comment]
> @Dun-sin we've made some changes to onboarding. Try it again with the browser devtools open and let us know if you see any errors in the console when trying to complete it.

i'm still getting asked the time but the interests no longer show

**Comment by Dun-sin** [comment]
this happens when i click go to profile tho, think it should be a single loading indication, not sure if this should be a seperate issue

![image](https://github.com/user-attachments/assets/882ccddd-7261-4b16-9b9d-7bc649894d2f)

**Comment by brandonroberts** [comment]
Are you getting any errors in the browser console?

**Comment by Dun-sin** [comment]
> Are you getting any errors in the browser console?

just to be clear it still works just the weird double loading indicator for both options on the last step

**Comment by brandonroberts** [comment]
Got it. I'm referring to errors in the browser console or network requests when clicking the button(s)

**Comment by Dun-sin** [comment]
> Got it. I'm referring to errors in the browser console or network requests when clicking the button(s)

there was no error

**Comment by brandonroberts** [comment]
Will you record/post a video of you going through the process with the browser devtools open? There should be a call to `/v2/auth/onboarding` when you finish the timezone part

**Comment by Dun-sin** [comment]
> Will you record/post a video of you going through the process with the browser devtools open? There should be a call to `/v2/auth/onboarding` when you finish the timezone part


https://github.com/user-attachments/assets/4d3b28be-9ddb-4a4c-b0df-23551157a4b4

**Comment by brandonroberts** [comment]
Ok. I see you're onboarded now. Now you should just be able to go to https://app.opensauced.pizza without having to go through onboarding again.

Anytime you go to https://app.opensauced.pizza/start, it will prompt you first unless you're already onboarded.
