### ISSUE TITLE
Bug: outline cut off for dashboard tab when it receives focus

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#3889]
@nickytonline not a blocker, but the dashboard outline gets cut off (I'm on chrome)

<img width="160" alt="image" src="https://github.com/user-attachments/assets/dd106d01-a35e-464e-a5ee-801820d7f136">

That's not related to the fix, but we can address that in a separate issue. Probably a good first issue for a11y for someone.

_Originally posted by @BekahHW in https://github.com/open-sauced/app/issues/3888#issuecomment-2276088006_

The page in question is https://beta.app.opensauced.pizza/explore/topic/typescript?redirectedFrom=%2F, but I imagine it happens anywhere that the tab component is used.

**Comment by Dun-sin** [comment]
.take

want to give this a try

**Comment by Dun-sin** [comment]
@nickytonline seems that happens in a lot of places

https://github.com/user-attachments/assets/2106b19c-b7c6-4cf9-a294-b9f34aa4f655
