### ISSUE TITLE
Bug: Creating or updating a contributor insight provides no feedback to user making it look broken.

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#3909]
The Create Insight and Update Insight buttons provide no feedback that they're updating or creating a contributor insight. It's not as noticeable with a few people being added, but if there are more than a dozen, it's noticeable.

![CleanShot 2024-08-09 at 18 10 21](https://github.com/user-attachments/assets/6d39f101-5a0d-4238-8248-7a5f1cb7e230)

It needs the loading spinner to provide feedback like when we create or update a workspace.

https://github.com/open-sauced/app/blob/b1e1e203dd880054007853a9c1be75095f8e0862/pages/workspaces/new.tsx#L118-L126

https://github.com/open-sauced/app/blob/b1e1e203dd880054007853a9c1be75095f8e0862/pages/workspaces/%5BworkspaceId%5D/settings.tsx#L225-L233

**Comment by Dun-sin** [comment]
.take
