### ISSUE TITLE
Bug:  Profile card are  not displayed correctly on all resolution 

### ISSUE THREAD

**Issue by Kampouse** [open-sauced/app#3923]
### Describe the bug

Social  buttons  on MBA firefox  are hidden   resolution of :1470 x 755  
<img width="786" alt="image" src="https://github.com/user-attachments/assets/2c4d9ffd-0749-4bbc-bd04-2b9516f5c325">

### Steps to reproduce

go to  https://app.opensauced.pizza/u/<name>/card 
 test with different screen high / width 
 on the screeshot  ex: 1470 x 755

**Comment by nickytonline** [comment]
Thanks for reporting this @Kampouse!
