### ISSUE TITLE
Bug: Dev card back and front overlap when flipped

### ISSUE THREAD

**Issue by Kampouse** [open-sauced/app#3927]
### Describe the bug

<img width="302" alt="image" src="https://github.com/user-attachments/assets/6c595c61-078f-44ac-92ae-13e094ef2298">

### Steps to reproduce

  https://app.opensauced.pizza/u/Kampouse/card 
flip a  card (firefox,safari,mobile)

**Comment by nickytonline** [comment]
Did a quick test and can confirm it is indeed an issue on Firefox and Safari.

**Safari**

![CleanShot 2024-08-12 at 18 33 31](https://github.com/user-attachments/assets/b1422c57-d1af-40bc-9214-8656d06d81d8)

**Firefox**

![CleanShot 2024-08-12 at 18 32 19](https://github.com/user-attachments/assets/7203943e-bf16-4cb3-80fe-25bb28a7aa9b)
