### ISSUE TITLE
Feature: show where to find the contributors' insight page

### ISSUE THREAD

**Issue by Dun-sin** [open-sauced/app#3948]
### Suggested solution

While looking at the project, I didn't know you could create a contributors' insight from workspaces, so I'm proposing we add that to the home page for workspace somewhere here rather than the side nav bar that's hidden:

![image](https://github.com/user-attachments/assets/6d0dab66-7116-448c-a08a-169bdf812dd5)

or the side nav should be open by default on desktop

**Comment by FatumaA** [comment]
Agreed on this

**Comment by Mandeep56Singh** [comment]
@Dun-sin @FatumaA  would it be helpful changing the color to orange ? 
In this way it will visible .
