### ISSUE TITLE
Bug: Search fields redirects to  404 error page

### ISSUE THREAD

**Issue by Mandeep56Singh** [open-sauced/app#3949]
### Describe the bug

https://github.com/user-attachments/assets/b050d140-4542-4733-b42e-74cec89fe998

### Steps to reproduce

1. Go to Explore
2. Search any repositories 
3. You will be directed to error page

**Comment by adamgonzo** [comment]
.take

**Comment by Mandeep56Singh** [comment]
@adamgonzo have you checked in your system ? do you get the same issue ?

**Comment by Mandeep56Singh** [comment]
@adamgonzo  I find it kinda weird that search suggest any repo in search repositories field, I should only suggest repos based on seleted topic. 
Like I seleted typescript then It should only suggest repos based on it. Otherwise there is no use of it. We also have search field at top which can also be used for the same.

**Comment by Mandeep56Singh** [comment]
@adamgonzo  yeah, because repositories are shown based on selected topic and we are using search filed so to find the repo under that topic fast.

**Comment by brandonroberts** [comment]
Thanks @Mandeep56Singh @adamgonzo. The URL path should begin with `/explore/topic/{topic}/...` instead of `/{topic}/...`.

**Comment by Mandeep56Singh** [comment]
hey I was also intrested in solving this  issue too 😅
but no worries

**Comment by Mandeep56Singh** [comment]
@brandonroberts  @adamgonzo  I have resolved this issue 

https://github.com/user-attachments/assets/3951bcc8-0012-4071-a00c-47bbb68da203

should I create a pr ?

**Comment by brandonroberts** [comment]
@Mandeep56Singh if @adamgonzo wants to defer to you, that's fine. They did try to pick it up initially

**Comment by Mandeep56Singh** [comment]
@adamgonzo  in case of empty search we can display error message to user to ask him to fill the field, some kind of validation with valibot.

**Comment by Mandeep56Singh** [comment]
@adamgonzo also happen when clicking cross icon.

**Comment by Mandeep56Singh** [comment]
@brandonroberts It seems that in handleOnSearch within repositories.tsx, the following code is responsible for the issue:
` const handleOnSearch = (search?: string) => {
    if (selectedFilter && !search) {
      return router.push(`${topic}/${toolName}`);
    }
    if (search && /^[a-zA-Z0-9\-\.]+\/[a-zA-Z0-9\-\.]+$/.test(search)) {
      return router.push(`/explore/topic/${topic}/${toolName}/filter/${search}`);
    }
  };`
The first if condition is causing the problem when the search query is empty, directing the user to a weird page. This could be fixed by updating the route as we did in the second condition. But then when user enter the empty query the page direct to 
current page and all filter get cleared.
My question is when search field is empty why we need to use router , there is no need for first if ?

**Comment by brandonroberts** [comment]
@Mandeep56Singh yes, the path in the first condition should match. We support that way also so you can clear the search box after filtering for a specific repository

**Comment by Mandeep56Singh** [comment]
@brandonroberts 
It is also affecting the clear button.
When a user selects a filter and unintentionally inputs the wrong text, clicking the 'clear' button currently clears all fields, including the selected filters. This could lead to a poor user experience, as the user may lose their filters and have to reselect them. It might be better to only clear the text field, preserving the filters.

**Comment by brandonroberts** [comment]
Maybe. I think we should fix the 404 navigation first, then revisit the UX separately.
