### ISSUE TITLE
Bug: Registration  flow is non-peristent 

### ISSUE THREAD

**Issue by Kampouse** [open-sauced/app#3950]
### Describe the bug

Was wondering if this a bug or was intended behaviour but feels like a bug to me:
user will always be  prompted for interests every time he  login with => https://opensauced.pizza/ 
![image](https://github.com/user-attachments/assets/abeeea7c-4d9a-494c-a544-b306aa077782)

### Steps to reproduce

make sure your are logged out of the application
navigate to  https://opensauced.pizza/ 
login you will get prompted the above pic!

**Comment by nickytonline** [comment]
This step has been removed in #3951. I'm going to go ahead and close this.

**Comment by bdougie** [comment]
Assuming is because the "connect with GitHub" link from the landing take the user to /start. I think we could address with better logic that doesn't show the onboarding for users that have existing accounts with us.
