### ISSUE TITLE
Bug: Searching for a user/repository name throws error and crashes page

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#3978]
It looks like in certain cases we need to check if data is defined or not.

![CleanShot 2024-08-16 at 16 48 16](https://github.com/user-attachments/assets/58e4b3ca-873b-42a5-b871-2c4bd99f4a79)

**Comment by SURAJ-SHARMA27** [comment]
Hi @nickytonline,

I would like to work on the issue. I have actually resolved it on my local environment. The issue occurs when the API inside `searchOpenSaucedAPI`  promise returns an empty response, and userData.data is undefined. To solve this, I added a null check and initialized `userData.data ` as an empty array if it is undefined. Should I proceed for PR?

Before:

[screen-capture (25).webm](https://github.com/user-attachments/assets/2d28f107-bc40-42fe-baea-8feac84b3308)

After:
 
[screen-capture (24).webm](https://github.com/user-attachments/assets/75fa55b1-70f5-4a1f-9ad6-19c715f6124c)

**Comment by nickytonline** [comment]
Hi @SURAJ-SHARMA27. Please read the contributing guidelines to get assigned to this issue.

**Comment by SURAJ-SHARMA27** [comment]
.take

**Comment by SURAJ-SHARMA27** [comment]
@nickytonline  , I have submitted the PR. Could you please review it?
