### ISSUE TITLE
Bug: Unauthorized Error (401) When Creating Insight via POST /v2/workspaces/{id}/insights

### ISSUE THREAD

**Issue by SURAJ-SHARMA27** [open-sauced/app#3985]
### Describe the bug

When a user selects repositories from the workspace and clicks "Add to Insight" followed by "Create Insight," the page freezes for an extended period. Eventually, the site crashes and throws an error:

![image](https://github.com/user-attachments/assets/d8d5616c-b1ad-4927-9287-8cf51aa602ea)

I tested the endpoint using Swagger with a valid payload, and it returned a 401 Unauthorized error.

Proposed Solution:

a fallback function to handle cases where the API fails to return the desired response, preventing the site from crashing.

### Steps to reproduce

1. Go to workspace
2. Select some repositories
3. Click on add to insight button
4. Click on create insight.

**Comment by jpmcb** [comment]
I'm not able to reproduce this: can you give us abit more information?

1. Generally, geographically, where are you located?
2. You mention that "the API fails to return the desired response": can you look in the network tab to give us which API endpoint is failing? Is it timing out?
3. Is this consistently reproducible?

**Comment by SURAJ-SHARMA27** [comment]
Yes i have attached the video for your reference:

[screen-capture (28).webm](https://github.com/user-attachments/assets/3df75b89-f03d-4f03-8bd5-4f13c691e94b)

**Comment by BekahHW** [comment]
@jpmcb it seems to be an issue just on beta.

**Comment by jpmcb** [comment]
I believe this is an API issue where the `POST v2/workspaces/:workspace-id/insights` is timing out. I believe I have a solution and this should start working on beta when we get it in.

**Comment by SURAJ-SHARMA27** [comment]
Just out of curiosity, is the backend of OpenSauced not open source? 🙂

**Comment by jpmcb** [comment]
> Just asking out of curiosity, is the backend of OpenSauced not open source?

Good question! Not currently: we closed sourced it earlier this year as we were working on some more special proprietary bits.

This has been fixed in the beta API and will land in prod soon!

**Comment by SURAJ-SHARMA27** [comment]
> > Just asking out of curiosity, is the backend of OpenSauced not open source?
> 
> Good question! Not currently: we closed sourced it earlier this year as we were working on some more special proprietary bits.
> 
> This has been fixed in the beta API and will land in prod soon!

No problem, @jpmc. Actually, I have worked with backend development as well and was looking to learn from here by contributing. That's why I asked.
