### ISSUE TITLE
Bug: unable to delete repo from workspace

### ISSUE THREAD

**Issue by Mandeep56Singh** [open-sauced/app#3990]
### Describe the bug

When attempting to delete a repository from the workspace section, the interface indicates that the repository has been successfully deleted. However, after refreshing the page or navigating away and returning to the workspace, the repository reappears.

video
https://github.com/user-attachments/assets/e7ed41c0-b7bd-43be-bfd8-0b17b9aaeea9

### Steps to reproduce

1. Go to workspace 
2. Click on edit 
3. delete the repository
4. refresh or go back to workspace 
5. you will see that same repository

**Comment by SURAJ-SHARMA27** [comment]
Hi @Mandeep56Singh, after deleting the repo, you should click on 'Update Workspace' for the changes to be reflected in the workspace.

**Comment by Mandeep56Singh** [comment]
@SURAJ-SHARMA27 I didn't knew about that 😅
thanks 👍
