### ISSUE TITLE
Bug: Contributors tab error on repo pages when time is 6mo or 1 yr

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/app#3992]
### Describe the bug

There's an error when selecting 6mo or 1 yr on the contributor tab of repo pages.
![image](https://github.com/user-attachments/assets/8fc0a346-8e45-419c-ade2-ad5e5b36f51b)

![image](https://github.com/user-attachments/assets/4e19bbaa-99b3-445c-854c-6e10f7840bf0)

### Steps to reproduce

1. Go here https://app.opensauced.pizza/s/microsoft/TypeScript/contributors?range=180&display=grid

**Comment by zeucapua** [comment]
The endpoint used for the page is `/repo/<org>/<repo>/contributors`; does this endpoint not support longer time ranges? @jpmcb

**Comment by jpmcb** [comment]
This was an arbitrary limitation we placed on the API to prevent problems with calculating alot of data across droves of contributors past 90 days.

I'll investigate if it'd be tenable to expand this to work with 6 months and 1 year: there may be some optimizations that make this "just work ™️ "
