### ISSUE TITLE
Feature: Add lottery factor to the repository table

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#4007]
### Suggested solution

We want to make sure the new devstats we've developed are available on other parts of the site. In this case, we want to make sure we display the Lottery Factor in every instance of the repositories table.

<img width="1849" alt="image" src="https://github.com/user-attachments/assets/184ce78f-f645-452e-bbab-ead0eff1eb10">

**Comment by zeucapua** [comment]
It's getting crowded; is there a column we should change into the lottery factor (PR velocity maybe?) cc @isabensusan

**Comment by isabensusan** [comment]
@zeucapua I'd say let's keep the actual value for PR velocity, but remove the purple pill (shows variation vs previous time period but isn't really clear right now). That should open up some space for lottery factor.

<img width="1877" alt="image" src="https://github.com/user-attachments/assets/88f444e4-55f6-45a6-828a-c96ff5438020">
