### ISSUE TITLE
Feature: add contributor confidence to the repository table

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/app#4008]
### Suggested solution

We want to update the repository tables to include the Contributor Confidence score for each repository in a workspace or repository insight 
<img width="1427" alt="image" src="https://github.com/user-attachments/assets/6dca1a2b-3c25-41f3-9ef0-a5456be864e0">

**Comment by Pratik-Mahajan257** [comment]
Hi @isabensusan , can you please let me know if this is done triaging or not? I would love to take this issue and the lottery factor one, Thanks!!
