### ISSUE TITLE
Bug: user apparently is undefined

### ISSUE THREAD

**Issue by tutkli** [open-sauced/app#4029]
### Describe the bug

Hi, I can login to the app with my github user just fine, but can't really do anything.

When I go to workspaces, it requests `https://app.opensauced.pizza/workspaces/undefined`
![image](https://github.com/user-attachments/assets/e157e4e0-a22a-4915-a6df-7b82d82a5cea)

If I go to edit profile, all fields contain undefined. Trying to edit the profile also fails.
![image](https://github.com/user-attachments/assets/b2637c9c-2045-40d3-ba32-f0ed0e336738)

I tried to delete my account, but I can't
![image](https://github.com/user-attachments/assets/82ed8fad-fba3-4429-9b0d-92e1a22a1c34)

### Steps to reproduce

I don't really know. I created my account long ago, but it has been like this from the begining.

**Comment by brandonroberts** [comment]
Thanks @tutkli. We have an issue looking into account deletion. Try logging in again

**Comment by tutkli** [comment]
Thanks @brandonroberts ! I'm able to use the app now :)
