### ISSUE TITLE
Bug: width problem in AppSideBar CSS causing layout issues

### ISSUE THREAD

**Issue by mouad-dadda** [open-sauced/app#4031]
### Description:

There is an issue with the `AppSideBar `component where the width is incorrectly set in the CSS, leading to layout problems. 

![Screenshot_25-8-2024_131842_app opensauced pizza](https://github.com/user-attachments/assets/f9346e2f-a14c-493e-8110-e53072ff12bb)

### Suggested Fix:

I have corrected this issue in a pull request. The CSS width properties in  `AppSideBar.js` have been adjusted to match the intended design specifications.

**Comment by brandonroberts** [comment]
Thanks @mouad-dadda. Please follow the contributing guidelines and do not submit a PR until the issue has been triaged and assigned.

**Comment by nickytonline** [comment]
It looks like the styling regressed as it's no longer the same color. Resizing the app sidebar is not the fix.

**Comment by BekahHW** [comment]
@mouad-dadda I removed the needs triage label. As Nick said, it's a styling regression. If you do want to make the update, go ahead and assign yourself the issue.

**Comment by mouad-dadda** [comment]
.take

**Comment by nickytonline** [comment]
@mouad-dadda if you look back a few release or do a [git bisect](https://git-scm.com/docs/git-bisect), you should be able to figure out when the styling broke and put it back to what it was.

**Comment by mouad-dadda** [comment]
> @mouad-dadda if you look back a few release or do a [git bisect](https://git-scm.com/docs/git-bisect), you should be able to figure out when the styling broke and put it back to what it was.

**Thank you,** @nickytonline, for the guidance. I’ll review previous releases and perform a `git bisect` to identify when the styling regression occurred .
