### ISSUE TITLE
Bug: OSCR pill not aligned with username in contributor grid views 

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#4034]
The OSCR pill not aligned with username in contributor grid views. When this was implemented originally it lined up correctly.

![CleanShot 2024-08-26 at 11 49 23](https://github.com/user-attachments/assets/647a1ac3-8cb9-4984-aedb-e5929809fec7)

"Should be an easy styling fix"

**Comment by shubhamchasing** [comment]
.take

**Comment by shubhamchasing** [comment]
@nickytonline Currently, the OSCR pill is excluded, should I let it be like that?

and current changes will not affect other places where the OSCR pill has been used.

Is it fine?
![Screenshot from 2024-08-27 20-36-26](https://github.com/user-attachments/assets/9b9b184c-1bdc-4058-8c68-1842be9ef581)

**Comment by nickytonline** [comment]
> @nickytonline Currently, the OSCR pill is excluded, should I let it be like that?
> 
> and current changes will not affect other places where the OSCR pill has been used.
> 
> Is it fine? ![Screenshot from 2024-08-27 20-36-26](https://private-user-images.githubusercontent.com/106425076/361864238-9b9b184c-1bdc-4058-8c68-1842be9ef581.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3ODA3NjIsIm5iZiI6MTcyNDc4MDQ2MiwicGF0aCI6Ii8xMDY0MjUwNzYvMzYxODY0MjM4LTliOWIxODRjLTFiZGMtNDA1OC04YzY4LTE4NDJiZTllZjU4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QxNzQxMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzQ3NjFjYWZjYjBiM2Y5YzQ3ZjRkMDM5OWI1NjU1NzE0OTdiMzkxNjhkYzQxYjM1ODkxZmZkMWUwZDI0ZmQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZU98bM4CS6cUDYtyO-aGHA9kjtk634JLXSNmiiVR5kE)

I'm not sure what you mean by it's excluded as I see it in the image and in the original issue.

**Comment by shubhamchasing** [comment]
> I'm not sure what you mean by it's excluded as I see it in the image and in the original issue.
In the latest code OSCR is excluded please refer #3901

**Comment by nickytonline** [comment]
Ahh, I see. Don't change where it's currently excluded. The fix is just aligning the OSCR pill component.
