### ISSUE TITLE
Bug: Remove unnecessary z-index on OpenSSF score card I want this now button

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#4055]
Remove the z-index from the `<OssfChart />` components "I want this now!" button JSX and move the JSX below the `<ResponsiveContainer />` component.

```diff
            <div className="relative w-full !max-w-[14rem] lg:max-w-full lg:mx-auto h-full lg:max-h-24 xl:h-full">
-              {isError && (
-                <div className="absolute inset-0 z-50 flex items-center justify-center">
-                  <Button variant="primary" onClick={onRequestClick} className="!text-xs">
-                    I want this now!
-                  </Button>
-                </div>
-              )}
              <ResponsiveContainer width="100%" height={150} className={`${isError && "blur-[2.5px]"}`}>...
              </ResponsiveContainer>
+              {isError && (
+                <div className="absolute inset-0 flex items-center justify-center">
+                  <Button variant="primary" onClick={onRequestClick} className="!text-xs">
+                    I want this now!
+                  </Button>
+                </div>
+              )}
            </div>
```

The file where the changes should be made is https://github.com/open-sauced/app/blob/beta/components/Repositories/OssfChart.tsx

https://github.com/user-attachments/assets/5ba00455-0976-4d2b-a628-1f0ce0b94ca4

Some additional reading for those interested:
* [Stacking Contexts](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index/Stacking_context)
* [z-index](https://developer.mozilla.org/en-US/docs/Web/CSS/z-index)

**Comment by ryandotfurrer** [comment]
Feel free to assign this to me, I'll get it done tonight or tomorrow night.

**Comment by ryandotfurrer** [comment]
.take
