### ISSUE TITLE
Bug: Workspace dropdown in Add to workspace modal it too big

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#4063]
The workspace dropdown in the Add to workspace modal it too big. The arrow is in the middle of the dropdown.

![CleanShot 2024-08-28 at 18 06 37](https://github.com/user-attachments/assets/95f1ab1e-0b15-43d9-81e7-3c615ae023b2)

**Comment by ryandotfurrer** [comment]
.take

**Comment by ryandotfurrer** [comment]
I am looking to login on my branch so I can see the changes I'm making to the dropdown, however, I am getting a 404 upon running `npm run dev`. Any ideas how I can fix this so I can see what I am working on?

The same thing occurs when I try to go to `/home`

![CleanShot CleanShot-000191](https://github.com/user-attachments/assets/447d01b5-35e0-437c-b522-30601cd0a347)

**Comment by nickytonline** [comment]
Hmm not sure what’s up. We don’t have a `/login` route.

Can you run `git clean -dfx` to remove any files that are in git and then run `npm install`. There are no environment variables to set. From there running `npm run dev` and going  to http://localhost:3000 should load up the site.

and to log in just click on the connect with GitHub button at the top right of the site.

**Comment by nickytonline** [comment]
> Thanks, @nickytonline! I forgot this is a known issue from working on [Gridiron Survivor](https://github.com/LetsGetTechnical/gridiron-survivor) (GIS). Any time I spin up another Next.JS app it tries to use the redirect in GIS's next.config, which redirects to `/login`. I imagine this has something to do with caching but none of us know the solution.
> 
> I didn't think about this yesterday but was going crazy as I did not see a `/login` route.
> 
> Either way, I've got this running now. Thanks for teaching me about `git clean -dfx` too.

You probably have a [ServiceWorker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) in GridIron survivor causing the issue. Just clearing all application data in dev tools fixes it or unregistering the service worker.

![CleanShot 2024-09-02 at 11 10 40](https://github.com/user-attachments/assets/cc1a6eff-f514-45f6-9cd2-f561e25ec3c3)

**Comment by ryandotfurrer** [comment]
> > Thanks, @nickytonline! I forgot this is a known issue from working on [Gridiron Survivor](https://github.com/LetsGetTechnical/gridiron-survivor) (GIS). Any time I spin up another Next.JS app it tries to use the redirect in GIS's next.config, which redirects to `/login`. I imagine this has something to do with caching but none of us know the solution.
> > I didn't think about this yesterday but was going crazy as I did not see a `/login` route.
> > Either way, I've got this running now. Thanks for teaching me about `git clean -dfx` too.
> 
> You probably have a [ServiceWorker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) in GridIron survivor causing the issue. Just clearing all application data in dev tools fixes it or unregistering the service worker.

Thanks for this man, I'll have a look! You may have solved our headache 😅
