### ISSUE TITLE
Bug: Wrong copy on contributor insights page

### ISSUE THREAD

**Issue by FatumaA** [open-sauced/app#4089]
### Describe the bug

When you click the "Contributor insights" button on the workspaces page and have no insights yet, you are taken to a page that says, "You have no repository insights.". It should be "You have no contributor insights." instead.

![Screenshot 2024-09-09 at 22 34 31](https://github.com/user-attachments/assets/6423dbe4-2847-41ed-897f-1a7282f51132)

### Steps to reproduce

1. Go to workspaces
2. Click on the "Contributor insights" button in the top right side
3. You will be taken to the page with the wrong copy

**Comment by shubhamchasing** [comment]
I would like to work on it, please assign me

**Comment by nickytonline** [comment]
Feel free to grab it @shubhamchasing. I just removed the needs triage label.

**Comment by shubhamchasing** [comment]
.take
