### ISSUE TITLE
Bug: loading dev card page from the user profile crashes

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/app#4108]
Going to the dev card page directly works, but if you click on the dev card button near the avatar on the user profile page, it crashes.

![CleanShot 2024-09-18 at 08 17 58](https://github.com/user-attachments/assets/9146d8a9-3949-4a81-987c-e00957047826)

![CleanShot 2024-09-18 at 08 20 19](https://github.com/user-attachments/assets/5245419d-a56c-4413-8aba-5513561aec89)

The `user` is `null` causing the crash.

**Comment by nickytonline** [comment]
This is still an issue, but it appears to only occur when running locally in dev mode. Beta and Prod are fine.

**Comment by Dun-sin** [comment]
@nickytonline what do you want to do with this? should this still be debugged?

**Comment by nickytonline** [comment]
It's, most likely related to React's [strict mode](https://react.dev/reference/react/StrictMode) which is on by default in Next.js. Feel free to dig into this.

**Comment by Dun-sin** [comment]
> It's, most likely related to React's [strict mode](https://react.dev/reference/react/StrictMode) which is on by default in Next.js. Feel free to dig into this.

Got it💪🏽

**Comment by Bashamega** [comment]
Can I work on this?

**Comment by nickytonline** [comment]
Please read the contributing guidelines if you'd like to work on this.

**Comment by Bashamega** [comment]
.take

**Comment by Bashamega** [comment]
> > For full info on how to contribute, please check out our [contributors guide](https://docs.opensauced.pizza/contributing/introduction-to-contributing/).
> 
> Please read the contributing guidelines if you'd like to work on this.

Thanks

**Comment by Bashamega** [comment]
Hello @nickytonline 
I have tried to run it locally, and i have followed the steps but i get this error:
![image](https://github.com/user-attachments/assets/1e44629b-5dc4-4397-b6ee-c029df2c4481)

Console:
![image](https://github.com/user-attachments/assets/e3d88116-b1dc-4f47-b9b5-dcfa2160d554)

**Comment by nickytonline** [comment]
@Bashamega, ensure you have latest of the beta branch. I just pulled down all the latest changes and I do not get the error you get, I get the original error still.

![CleanShot 2024-10-01 at 13 24 10@2x](https://github.com/user-attachments/assets/75065e8d-a3bb-44b9-8f73-b998ec71783f)

**Comment by Bashamega** [comment]
@nickytonline on my side the profile page is not loading, so i can't click on the badge.

**Comment by nickytonline** [comment]
Please ensure that you have the latest of the beta branch and that you've followed the steps in our README to get up and running locally. It definitely works locally (with the error mentioned in the issue) and it's working in our beta and production environment, so my guess is there is something not right in your local environment.

**Comment by Bashamega** [comment]
> Please ensure that you have the latest of the beta branch and that you've followed the steps in our README to get up and running locally. It definitely works locally (with the error mentioned in the issue) and it's working in our beta and production environment, so my guess is there is something not right in your local environment.

I have followed the steps in the readme.
I have ran:
```
npm ci
npm run dev
```

**Comment by nickytonline** [comment]
I'm not sure what the issue is. Can you open the project in GitHub CodeSpaces, and run the setup? I have a feeling it's something with your local environment, but I have no idea what at the moment.

**Comment by Bashamega** [comment]
sure

**Comment by Bashamega** [comment]
Thanks @nickytonline ,
It worked, i fix the issue now

**Comment by Bashamega** [comment]
The problem is with the Link tag, the link tag doesn't make it a full reload, causing the `getServerSideProps` to not run. There are 2 options to fix this issue:
1. Remove the Link tag and replace with `window.location.href`.
2. Remove the `getServerSideProps` and write it in a useEffect.

**Comment by Bashamega** [comment]
The issue with `getServerSideProps` not working locally when using the `<Link />` tag but functioning in production is a known issue that has surfaced in various Next.js deployments. This typically happens because when navigating using the `<Link />` component, Next.js fetches JSON data through the `_next/data` endpoint to re-render the page without a full reload. If the data is missing or the fetch fails, the page props might not be populated correctly, leading to issues.

Locally, this could be caused by differences in how environments handle data prefetching and cache control, or it might relate to how Next.js manages client-side navigation. In production, server configurations and CDN setups might handle these differently, which is why it works there but not locally.

**Comment by Bashamega** [comment]
> Glad things work for your environment now.
> 
> We want to keep the getServerSideProps, but I'm not sure a window.location.href is the best option as this only happens in development mode. Put up a pull request and we can continue the conversation there.

sure
