### ISSUE TITLE
feature: Shareable link (URL shortner)

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#522]
### Type of feature

Select the type of feature request, the lowercase should also be the PR prefix.

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

### Current behavior

Is your feature request related to a problem? Please describe.

As a user, I should be able to copy a shortened URL by clicking the share button on the insights. My recommendation is that this URL is shortened, which will require us to use our own custom URL shortener. 

We could potential use this [path outline by Netlify](https://www.netlify.com/blog/2018/03/19/create-your-own-url-shortener-with-netlifys-forms-and-functions/). Open to suggestions

![image](https://user-images.githubusercontent.com/5713670/195218856-2400c254-29a3-4375-8c0d-a4095de192ee.png)

### Suggested solution

URL shortener URL options.

- oss.fyi
- that's it 😅

### Code of Conduct

By submitting this issue, you agree to follow our [Code of Conduct](https://docs.opensauced.pizza/contributing/code-of-conduct/).

- [ ] I agree to follow this project's Code of Conduct

### Contributing Docs

If you plan on contributing code please read - [Contribution Guide](https://docs.opensauced.pizza/contributing/introduction-to-contributing/)

- [ ]  I agree to follow this project's Contribution Docs

**Comment by babblebey** [comment]
I'd seriously like to see this work

**Comment by bdougie** [comment]
This is actually blocked until [dub.sh](https://github.com/steven-tey/dub) ships their API integration, expected this fall. WE could potentially self-hosted, but I would rather prioritize that since we have some other pressing things that need to ship.

Checkout the new URL though https://oss.fy/bdougie
