### ISSUE TITLE
test: Add unit testing for all lib files 

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/app#546]
### Type of feature

Select the type of feature request, the lowercase should also be the PR prefix.

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [x] ✅ Test
- [ ] 🤖 Build
- [x] 🔁 CI
- [] 📦 Chore (Release)
- [ ] ⏩ Revert

### Current behavior

Is your feature request related to a problem? Please describe.

### Suggested solution

Describe the solution you'd like.

This effort:
- Sets up Vitest dependencies (https://vitest.dev)
- Adds initial setup to run units tests against the Design System atoms
- Sets up structure for future testing efforts
- Documents running unit test setup and practices
- Add unit testing to CI pipeline

Additional considerations
- @testing-library/react - https://github.com/testing-library/react-testing-library
- MSW - https://mswjs.io/

### Code of Conduct

By submitting this issue, you agree to follow our [Code of Conduct](https://docs.opensauced.pizza/contributing/code-of-conduct/).

- [x] I agree to follow this project's Code of Conduct

### Contributing Docs

If you plan on contributing code please read - [Contribution Guide](https://docs.opensauced.pizza/contributing/introduction-to-contributing/)

- [x]  I agree to follow this project's Contribution Docs

**Comment by TAKANOME-DEV** [comment]
.take

**Comment by TAKANOME-DEV** [comment]
Hum, the `take` action is not working, cc @brandonroberts @bdougie,  can I take this one?

**Comment by bdougie** [comment]
For this project, we have a clear roadmap and are happy to take contributions. To avoid folks assigning issues and blocking work we would like you to communicate with us in the discord. 

Aside: My suggestion for this is to test files in the `lib` folder to ensure the scope of this stays focused.
