### ISSUE TITLE
feature: introduce feature flag management system

### ISSUE THREAD

**Issue by brandonroberts** [open-sauced/app#640]
### Type of feature

Select the type of feature request, the lowercase should also be the PR prefix.

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

### Current behavior

Is your feature request related to a problem? Please describe.

### Suggested solution

Describe the solution you'd like.

We'd have a way to toggle features on/off on demand to a deployed application, where we can continue to add features that aren't fully finished yet instead of long lived feature/alpha branches.

- Look at some options for libraries/services
- Pick one that has good support for Next.JS/React
- Spike/Test/Evaluate/Implement

### Code of Conduct

By submitting this issue, you agree to follow our [Code of Conduct](https://docs.opensauced.pizza/contributing/code-of-conduct/).

- [ ] I agree to follow this project's Code of Conduct

### Contributing Docs

If you plan on contributing code please read - [Contribution Guide](https://docs.opensauced.pizza/contributing/introduction-to-contributing/)

- [ ]  I agree to follow this project's Contribution Docs

**Comment by a0m0rajab** [comment]
Post hog is already enabled in the app, what it's needed for this is to use it: 

Related docs from posthog: https://posthog.com/docs/feature-flags/manual

@brandonroberts is this still relevant and how can we use it?

**Comment by a0m0rajab** [comment]
Side note: it would be great to have feature flags for disabling onboards and middleware for test purposes like this PR: https://github.com/open-sauced/insights/pull/1488

This would let the QA move faster during the test and we can revert the flag to it's previous state when the PR approved.

**Comment by isabensusan** [comment]
Closing this issue -- We've already figured out the PostHog feature flag integration and will be opening individual tickets in the feature for feature flags related to specific feature work.
