### ISSUE TITLE
feature: Mobile settings for toggles

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#739]
For now, we can hide this toggle on mobile. We can focus on designing a better option for filters on mobile. This section will get unruly, and we will need to have drawer or menu option for these. 

![image](https://user-images.githubusercontent.com/5713670/209564319-758e9ecb-abdd-4469-b8d8-897c07989f03.png)

examples

https://dribbble.com/tags/mobile_settings

cc @pixelsbyeryc - I will open this as an issue.

_Originally posted by @bdougie in https://github.com/open-sauced/insights/issues/736#issuecomment-1365254427_

**Comment by chhristopher** [comment]
Is there a way to find out how frequently the Show Bots toggle is being used in general, if at all? I am curious.

**Comment by bdougie** [comment]
This is an answer we can get through posthog. I might explore that next week.

**Comment by takanome-dev** [comment]
Fixed but couldn't find the pr :sweat:
