### ISSUE TITLE
Feature: Connect posthog link events

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#740]
### Type of feature

🍕 Feature

### Current behavior

We are leveraging [Posthog](https://posthog.com/) in the app and have no insight on what features are being leveraged. 

### Suggested solution

https://posthog.com/docs/integrate/ingest-live-data

## Links to posthog
Events are needed for the following.
- Bots filter, PR filter (future) - https://github.com/open-sauced/insights/issues/739#issuecomment-1365391711
- Insights pages
- Link to repo pages
- Link to user pages (external and internal)
- All other links 

## Future links
There are instances where users are clicking places that are not clickable. It might be worth capturing that. For example, the title on the repo table and icons in the contributor cards. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by OgDev-01** [comment]
Hey @bdougie, do we still need this?

**Comment by bdougie** [comment]
I think we have context in posthog now and don't need custom events, but they trivial add if needed.


 cc @isabensusan.
