### ISSUE TITLE
Refractor: change Table Repository Name prop naming & related data to match Favorite Repo Card naming

### ISSUE THREAD

**Issue by Deadreyo** [open-sauced/app#750]
### Type of feature

🧑‍💻 Refactor

### Current behavior

In table-repository-name.tsx, the prop naming are as follows:
```ts
interface TableRepositoryNameProps {
  avatarURL?: string | StaticImageData;
  name?: string;
  handle?: string;
  isLoading?: boolean;
  topic?: string;
  user?: string | string[];
}
```
1- Prop names are unclear, specifically `handle` & `user`.
2- `isLoading` has no use.
3- Correct usage for `user` is to be only `string`. string array doesn't have a meaning in the usage and shouldn't exist
4- Many of those props are supposed to be required. Wouldn't make sense to use them without giving those data.

### Suggested solution

Follow the prop structure for the Favorite Repo Card props in #744 
1- Rename `handle` to `owner`, `user` to `userPage`
2- Remove `isLoading`
3- Follow the Favorite Repo Card props structure for props that should be required or optional.
4- Adjust the type of `user`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by GaganSingh5** [comment]
Hi, Can I pick this task?

**Comment by a0m0rajab** [comment]
@GaganSingh5 if you are still interested, feel free to take it. 

https://docs.opensauced.pizza/contributing/introduction-to-contributing/#issues

**Comment by SoundaryaKoutharapu** [comment]
.take

**Comment by SoundaryaKoutharapu** [comment]
Hi @OgDev-01,

currently the code looks as follows
There is no `handle` attribute and name as `fullname`

 ```
interface TableRepositoryNameProps {
  avatarURL?: string | StaticImageData;
  fullName: string;
  isLoading?: boolean;
  topic?: string;
  user?: string | string[];
} 
```

I've renamed `user` to `userPage` , removed `isLoading` and adjusted the type of `user`

```
interface TableRepositoryNameProps {
  avatarURL?: string | StaticImageData;
  fullName: string;
  topic?: string;
  userPage?: string;
} 
```
Can I proceed to make a PR?

**Comment by takanome-dev** [comment]
> Can I proceed to make a PR?

Yes :slightly_smiling_face:

**Comment by SoundaryaKoutharapu** [comment]
Thanks @takanome-dev!
I've submitted a pr.
