### ISSUE TITLE
feat: Design for an empty list or no results found 

### ISSUE THREAD

**Issue by SimranjitKaurMaan** [open-sauced/app#782]
### Type of feature

🍕 Feature

### Current behavior

Design is required for an empty list or no results found. It's related to issue #778. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by OgDev-01** [comment]
cc: @getaheaddev

**Comment by OgDev-01** [comment]
Hey @isabensusan, Would it be ok to use something similar to what we have here
<img width="755" alt="image" src="https://github.com/open-sauced/app/assets/62995161/b1d24265-839e-4c6a-8dc5-c6aa74da43c0">

and update the copy for both repositories and contributors table to also fix https://github.com/open-sauced/app/issues/1280
