### ISSUE TITLE
Feature: Email onboarding

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#803]
### Type of feature

🍕 Feature

### Current behavior

Today users can only connect their GitHub to log in. There are use cases where users don't have a GitHub that we will need to account for. 

### Suggested solution

We need the following. 

1. Onboarding needs to include email sign-up link.
2. Move connect github link to settings page and replace with Login and Sign up buttons
3. Add Linkedin option to the settings page 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by 0-vortex** [comment]
Marked as blocked for now, pending the OPS thread! 🍕

**Comment by a0m0rajab** [comment]
@0-vortex is there anything changed for this?

**Comment by OgDev-01** [comment]
@bdougie do we still have plans for this?

**Comment by bdougie** [comment]
No. We would be better off adding a SSO. But we can open a separate issue for that.
