### ISSUE TITLE
Feature: Tag a repo to a highlight

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#868]
### Type of feature

🍕 Feature

### Current behavior

This feature (https://github.com/open-sauced/insights/pull/843) does not work unless we tag a highlight to a repo. We need a solution designed

### Suggested solution

When submitting we can add the tag automatically, but if the user has a different repo to tag. We should add it to the dropdown. Here is the example from Campsite

<img width="236" alt="Screen Shot 2023-02-11 at 7 46 44 AM" src="https://user-images.githubusercontent.com/5713670/218267505-9af8ac41-410a-4e98-8f6f-e710a355bc69.png">
<img width="664" alt="Screen Shot 2023-02-11 at 7 46 50 AM" src="https://user-images.githubusercontent.com/5713670/218267507-10b3e898-8731-4077-a5c6-95667f57ab31.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by getaheaddev** [comment]
Is this going to work more like tags @bdougie or should it have a new function?

**Comment by getaheaddev** [comment]
Tag's have now been designed!

[[Figma file](https://www.figma.com/file/768ifqOGWrsRN29Igkc4ip/User-Flows?node-id=176%3A526&t=IggKgB5nBNUMShqz-1)]

**Comment by bdougie** [comment]
We have a design

![image](https://github.com/open-sauced/insights/assets/5713670/28a3ef92-d1e5-4f72-b8df-185cbb31ed72)

**Comment by diivi** [comment]
![image](https://github.com/open-sauced/insights/assets/41837037/43f4091d-ae45-468c-aa30-92ce8049194d)
What's the difference between the tag icon button and the "Add a repo" button? I'm adding this for now:

![image](https://github.com/open-sauced/insights/assets/41837037/4d14b8d3-6498-4c7a-979b-7d69ef2b35da)

**Comment by bdougie** [comment]
> ![image](https://user-images.githubusercontent.com/41837037/260832163-43f4091d-ae45-468c-aa30-92ce8049194d.png) What's the difference between the tag icon button and the "Add a repo" button? I'm adding this below the highlight text for now:
> 
> ![image](https://user-images.githubusercontent.com/41837037/260832727-4d14b8d3-6498-4c7a-979b-7d69ef2b35da.png)

That is a good question. @isabensusan can you clarify the workflow for this feature. I assume use would be able to paste a url or repo when clicked, but not sure how it would look.

**Comment by diivi** [comment]
![Peek 2023-08-16 03-09](https://github.com/open-sauced/insights/assets/41837037/c26f529a-1231-4ab4-bae9-7f473c4c6715)
This is what I made for now (for tagging and adding blogs).

We can take these components and refactor when we change the highlight creation form.

Quick Question - How many repos can you add to a highlight? https://github.com/diivi/insights/blob/ffde102394bea0e4f857e5deaf38385c27a552c5/components/molecules/CardRepoList/card-repo-list.tsx#L73 Code seems to support an infinite number of repos.

**Comment by bdougie** [comment]
This works, we can improve this in the next iteration. 

> Quick Question - How many repos can you add to a highlight?

We can limit it 3 for now, but for most use cases one is the norm.
