### ISSUE TITLE
Feature: Highlight suggestions

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#943]
### Type of feature

🍕 Feature

### Current behavior

We need to provide things for the user to highlight. 

### Suggested solution

Can we design the follow
1. button on the contribution list that suggests creating a highlight
2. Pull Request suggestions in a list next to the feed suggesting a highlight. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

![Image](https://user-images.githubusercontent.com/122071536/234135040-946e1db7-cd96-4276-b7c7-d1e41f41fa8a.png)

**Comment by getaheaddev** [comment]
@bdougie I think I need more details on this.

[[Figma File](https://www.figma.com/file/768ifqOGWrsRN29Igkc4ip/User-Flows?node-id=301%3A1597&t=IggKgB5nBNUMShqz-1)]

**Comment by bdougie** [comment]
Moved this back to the backlog. Need a better solution for suggesting highlights.

**Comment by diivi** [comment]
> button on the contribution list that suggests creating a highlight

This part means switching the tab to "Highlights" and focusing on the input so it expands. 

> Pull Request suggestions in a list next to the feed suggesting a highlight.

How do we get the pull requests that the user created recently? Was this implemented in the backend?

**Comment by bdougie** [comment]
There is a new UI for this. The API for fetching recent PRs is not implemented.

![Screen Shot 2023-08-04 at 11 34 26 AM](https://github.com/open-sauced/insights/assets/5713670/6c8e5cd3-a830-4610-8d74-5484244876f4) 

[[Figma](https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/Design-Lab?type=design&node-id=6180-7075&mode=design&t=vGqtZDvZPrA5H063-0)] 

## API

This will need its own tracking issue in the API, but we should be able to grab the most recent PRs (10) and display the ones that do not already have existing highlights associated with them. For now suggestions will be PRs, but we can add issues and milestones in future iterations. 

suggested endpoint: `/v1/user/highlights/suggestions`

**Comment by bdougie** [comment]
@diivi when you approach this, could you add the new modal as the way to create highlights. 

![image](https://github.com/open-sauced/app/assets/5713670/59f4d847-60ac-40ea-a444-8480d7629149)

@isa, can you confirm if this [[figma](https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/Design-Lab?type=design&node-id=9002-16522&mode=design&t=fS8W1WIR0adIPLWd-0)] is ready to approach.

**Comment by diivi** [comment]
Fine by me.

**Comment by diivi** [comment]
Maybe we should fetch the recent PRs and issues on the frontend itself instead of making an extra endpoint that calls github apis anyway? We call the api for validations in the frontend already.

**Comment by bdougie** [comment]
> Maybe we should fetch the recent PRs and issues on the frontend itself instead of making an extra endpoint that calls github apis anyway? We call the api for validations in the frontend already.

We are using the GitHub api for some of social card generation. 

I think that would be fine, we just want to make sure we are checking if the pr or issue is  not already highlighted.

**Comment by bdougie** [comment]
@OgDev-01 just assigned this to you. If you are able to approach it this week, that would be appreciated. 

We will need an endpoint to check the suers recently authored PRs and Issues. Suggesting only PRs and Issues that are not already linked to an existing highlight by the user.

**Comment by bdougie** [comment]
> @OgDev-01 just assigned this to you. If you are able to approach it this week, that would be appreciated.
> 
> We will need an endpoint to check the suers recently authored PRs and Issues. Suggesting only PRs and Issues that are not already linked to an existing highlight by the user.

Actually. Per slack, @diivi has bandwidth. Let us know if this is possible to be PR'd before Friday.

**Comment by diivi** [comment]
![image](https://github.com/open-sauced/app/assets/41837037/c4757689-c9ec-474d-b8bc-5bfd8e19b82e)
This is what it looks like with just the elements that we have now.

Once I add the suggested things to highlight, it'll be even longer (maybe making them collapsible can help). Views?

**Comment by diivi** [comment]
Another point to consider - Modals are the topmost elements in Radix UI (I might be wrong though), so all toasts appear below them (and blurred). So the way we show errors also will have to be changed.

**Comment by diivi** [comment]
Did some research, I can bring the toast to the top. But to make it interactable I'll have to set `modal={false}` on the Dialog, which will make it loose the background blur, and it looks bad like that.

The alternate solution that I went for is just remove the close icon from the toast for the toasts resulting from this form. The toasts will disappear after a few seconds anyway. Here's what it looks like that way:

![image](https://github.com/open-sauced/app/assets/41837037/2276e3c4-2f7c-4b53-8676-a37fa19ca95f)

**Comment by OgDev-01** [comment]
Can you take a look at the edit blog error message handling and follow that same pattern for thus I'd we have any error message to be displayed to users?. 

The toast can remain for only success messages which mostly comes after successful request and dialog is closed

**Comment by diivi** [comment]
![image](https://github.com/open-sauced/app/assets/41837037/53c07e02-017c-4cc9-9cd0-c33ac8b83778)
I can't duplicate this effect even after going through a lot of Radix UI docs. Has this been done somewhere already? Or an alternative that I can try?

**Comment by isabensusan** [comment]
I think we can do all the same modal then, and just have a good amount of padding between the two sections

**Comment by diivi** [comment]
When the modal becomes too big:
![image](https://github.com/open-sauced/app/assets/41837037/94ae0cbd-7b74-4902-8714-53a05af1fc56)

I could make it scrollable (don't know how yet), but even then it'll look like this (cut off).

What should I do?

**Comment by diivi** [comment]
Option 2:

![image](https://github.com/open-sauced/app/assets/41837037/7928c7a2-f09c-4587-a94a-8e56d68c2485)
![image](https://github.com/open-sauced/app/assets/41837037/085760ea-8330-48bc-8620-492f611833e0)
