### ISSUE TITLE
Feature: User generated interest

### ISSUE THREAD

**Issue by bdougie** [open-sauced/app#956]
### Type of feature

🍕 Feature

### Current behavior

This would need planning, but a user should be able to search or suggest interests. The challenge will be associating it to one of the existing topics 900k topics on GitHub.

<img width="422" alt="Screen Shot 2023-03-06 at 5 38 25 AM" src="https://user-images.githubusercontent.com/5713670/223127079-cd36837f-b19f-4c6b-ab1f-f69d2013cec1.png">

### Suggested solution

1. Let's get the top 100 topics on GitHub per our data. 
2. Allow suggestions either via the GitHub Discussions or Zendesk. 
3. Add new topics based on demand. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by a0m0rajab** [comment]
Blocked due to API updates need.

**Comment by brandonroberts** [comment]
Closing as not planned, custom topics can still be added through the URL manually, and we'll add additional ones as needed
